    .set cur_map_group, -1

    new_map_group
    map_group Map0_0                              @ 0.0
    map_group Map0_1                              @ 0.1
    map_group Map0_2                              @ 0.2
    map_group Map0_3                              @ 0.3
    map_group Map0_4                              @ 0.4

    new_map_group
    map_group ViridianForest                      @ 1.0
    map_group Map1_1                              @ 1.1
    map_group Map1_2                              @ 1.2
    map_group Map1_3                              @ 1.3
    map_group Map1_4                              @ 1.4
    map_group Map1_5                              @ 1.5
    map_group Map1_6                              @ 1.6
    map_group Map1_7                              @ 1.7
    map_group Map1_8                              @ 1.8
    map_group Map1_9                              @ 1.9
    map_group Map1_10                             @ 1.10
    map_group Map1_11                             @ 1.11
    map_group Map1_12                             @ 1.12
    map_group Map1_13                             @ 1.13
    map_group Map1_14                             @ 1.14
    map_group Map1_15                             @ 1.15
    map_group Map1_16                             @ 1.16
    map_group Map1_17                             @ 1.17
    map_group Map1_18                             @ 1.18
    map_group Map1_19                             @ 1.19
    map_group Map1_20                             @ 1.20
    map_group Map1_21                             @ 1.21
    map_group Map1_22                             @ 1.22
    map_group Map1_23                             @ 1.23
    map_group Map1_24                             @ 1.24
    map_group Map1_25                             @ 1.25
    map_group Map1_26                             @ 1.26
    map_group Map1_27                             @ 1.27
    map_group Map1_28                             @ 1.28
    map_group Map1_29                             @ 1.29
    map_group Map1_30                             @ 1.30
    map_group Map1_31                             @ 1.31
    map_group Map1_32                             @ 1.32
    map_group Map1_33                             @ 1.33
    map_group Map1_34                             @ 1.34
    map_group Map1_35                             @ 1.35
    map_group Map1_36                             @ 1.36
    map_group Map1_37                             @ 1.37
    map_group Map1_38                             @ 1.38
    map_group VictoryRoad_1F                      @ 1.39
    map_group VictoryRoad_2F                      @ 1.40
    map_group VictoryRoad_3F                      @ 1.41
    map_group Map1_42                             @ 1.42
    map_group Map1_43                             @ 1.43
    map_group Map1_44                             @ 1.44
    map_group Map1_45                             @ 1.45
    map_group Map1_46                             @ 1.46
    map_group Map1_47                             @ 1.47
    map_group Map1_48                             @ 1.48
    map_group Map1_49                             @ 1.49
    map_group Map1_50                             @ 1.50
    map_group Map1_51                             @ 1.51
    map_group Map1_52                             @ 1.52
    map_group Map1_53                             @ 1.53
    map_group Map1_54                             @ 1.54
    map_group Map1_55                             @ 1.55
    map_group Map1_56                             @ 1.56
    map_group Map1_57                             @ 1.57
    map_group Map1_58                             @ 1.58
    map_group Map1_59                             @ 1.59
    map_group Map1_60                             @ 1.60
    map_group Map1_61                             @ 1.61
    map_group Map1_62                             @ 1.62
    map_group Map1_63                             @ 1.63
    map_group Map1_64                             @ 1.64
    map_group Map1_65                             @ 1.65
    map_group Map1_66                             @ 1.66
    map_group Map1_67                             @ 1.67
    map_group Map1_68                             @ 1.68
    map_group Map1_69                             @ 1.69
    map_group Map1_70                             @ 1.70
    map_group Map1_71                             @ 1.71
    map_group CeruleanCave_1F                     @ 1.72
    map_group CeruleanCave_2F                     @ 1.73
    map_group CeruleanCave_B1F                    @ 1.74
    map_group Map1_75                             @ 1.75
    map_group Map1_76                             @ 1.76
    map_group Map1_77                             @ 1.77
    map_group Map1_78                             @ 1.78
    map_group Map1_79                             @ 1.79
    map_group Map1_80                             @ 1.80
    map_group Map1_81                             @ 1.81
    map_group Map1_82                             @ 1.82
    map_group SeafomIslands_1F                    @ 1.83
    map_group SeafomIslands_B1F                   @ 1.84
    map_group SeafomIslands_B2F                   @ 1.85
    map_group SeafomIslands_B3F                   @ 1.86
    map_group SeafomIslands_B4F                   @ 1.87
    map_group Map1_88                             @ 1.88
    map_group Map1_89                             @ 1.89
    map_group Map1_90                             @ 1.90
    map_group Map1_91                             @ 1.91
    map_group Map1_92                             @ 1.92
    map_group Map1_93                             @ 1.93
    map_group Map1_94                             @ 1.94
    map_group PowerPlant                          @ 1.95
    map_group Map1_96                             @ 1.96
    map_group Map1_97                             @ 1.97
    map_group Map1_98                             @ 1.98
    map_group Map1_99                             @ 1.99
    map_group Map1_100                            @ 1.100
    map_group Map1_101                            @ 1.101
    map_group Map1_102                            @ 1.102
    map_group Map1_103                            @ 1.103
    map_group Map1_104                            @ 1.104
    map_group Map1_105                            @ 1.105
    map_group Map1_106                            @ 1.106
    map_group Map1_107                            @ 1.107
    map_group Map1_108                            @ 1.108
    map_group Map1_109                            @ 1.109
    map_group Map1_110                            @ 1.110
    map_group Map1_111                            @ 1.111
    map_group Map1_112                            @ 1.112
    map_group Map1_113                            @ 1.113
    map_group Map1_114                            @ 1.114
    map_group Map1_115                            @ 1.115
    map_group Map1_116                            @ 1.116
    map_group Map1_117                            @ 1.117
    map_group Map1_118                            @ 1.118
    map_group Map1_119                            @ 1.119
    map_group Map1_120                            @ 1.120
    map_group Map1_121                            @ 1.121
    map_group Map1_122                            @ 1.122

    new_map_group
    map_group Map2_0                              @ 2.0
    map_group Map2_1                              @ 2.1
    map_group Map2_2                              @ 2.2
    map_group Map2_3                              @ 2.3
    map_group Map2_4                              @ 2.4
    map_group Map2_5                              @ 2.5
    map_group Map2_6                              @ 2.6
    map_group Map2_7                              @ 2.7
    map_group Map2_8                              @ 2.8
    map_group Map2_9                              @ 2.9
    map_group Map2_10                             @ 2.10
    map_group Map2_11                             @ 2.11
    map_group Map2_12                             @ 2.12
    map_group Map2_13                             @ 2.13
    map_group Map2_14                             @ 2.14
    map_group Map2_15                             @ 2.15
    map_group Map2_16                             @ 2.16
    map_group Map2_17                             @ 2.17
    map_group Map2_18                             @ 2.18
    map_group Map2_19                             @ 2.19
    map_group Map2_20                             @ 2.20
    map_group Map2_21                             @ 2.21
    map_group Map2_22                             @ 2.22
    map_group Map2_23                             @ 2.23
    map_group Map2_24                             @ 2.24
    map_group Map2_25                             @ 2.25
    map_group Map2_26                             @ 2.26
    map_group Map2_27                             @ 2.27
    map_group Map2_28                             @ 2.28
    map_group Map2_29                             @ 2.29
    map_group Map2_30                             @ 2.30
    map_group Map2_31                             @ 2.31
    map_group Map2_32                             @ 2.32
    map_group Map2_33                             @ 2.33
    map_group Map2_34                             @ 2.34
    map_group Map2_35                             @ 2.35
    map_group Map2_36                             @ 2.36
    map_group Map2_37                             @ 2.37
    map_group Map2_38                             @ 2.38
    map_group Map2_39                             @ 2.39
    map_group Map2_40                             @ 2.40
    map_group Map2_41                             @ 2.41
    map_group Map2_42                             @ 2.42
    map_group Map2_43                             @ 2.43
    map_group Map2_44                             @ 2.44
    map_group Map2_45                             @ 2.45
    map_group Map2_46                             @ 2.46
    map_group Map2_47                             @ 2.47
    map_group Map2_48                             @ 2.48
    map_group Map2_49                             @ 2.49
    map_group Map2_50                             @ 2.50
    map_group Map2_51                             @ 2.51
    map_group Map2_52                             @ 2.52
    map_group Map2_53                             @ 2.53
    map_group Map2_54                             @ 2.54
    map_group Map2_55                             @ 2.55
    map_group Map2_56                             @ 2.56
    map_group Map2_57                             @ 2.57
    map_group Map2_58                             @ 2.58
    map_group Map2_59                             @ 2.59

    new_map_group
    map_group PalletTown                          @ 3.0
    map_group ViridianCity                        @ 3.1
    map_group PewterCity                          @ 3.2
    map_group CeruleanCity                        @ 3.3
    map_group LavenderTown                        @ 3.4
    map_group VermillionCity                      @ 3.5
    map_group CeladonCity                         @ 3.6
    map_group FuchsiaCity                         @ 3.7
    map_group CinnabarIsland                      @ 3.8
    map_group IndigoPlateau                       @ 3.9
    map_group SaffronCity                         @ 3.10
    map_group SaffronCity2                        @ 3.11
    map_group OneIsland                           @ 3.12
    map_group TwoIsland                           @ 3.13
    map_group ThreeIsland                         @ 3.14
    map_group FourIsland                          @ 3.15
    map_group FiveIsland                          @ 3.16
    map_group SevenIsland                         @ 3.17
    map_group SixIsland                           @ 3.18
    map_group Route1                              @ 3.19
    map_group Route2                              @ 3.20
    map_group Route3                              @ 3.21
    map_group Route4                              @ 3.22
    map_group Route5                              @ 3.23
    map_group Route6                              @ 3.24
    map_group Route7                              @ 3.25
    map_group Route8                              @ 3.26
    map_group Route9                              @ 3.27
    map_group Route10                             @ 3.28
    map_group Route11                             @ 3.29
    map_group Route12                             @ 3.30
    map_group Route13                             @ 3.31
    map_group Route14                             @ 3.32
    map_group Route15                             @ 3.33
    map_group Route16                             @ 3.34
    map_group Route17                             @ 3.35
    map_group Route18                             @ 3.36
    map_group Route19                             @ 3.37
    map_group Route20                             @ 3.38
    map_group Route21                             @ 3.39
    map_group Route21b                            @ 3.40
    map_group Route22                             @ 3.41
    map_group Route23                             @ 3.42
    map_group Route24                             @ 3.43
    map_group Route25                             @ 3.44
    map_group OneIsland_KindleRoad                @ 3.45
    map_group OneIsland_TreasureBeach             @ 3.46
    map_group TwoIsland_CapeBrink                 @ 3.47
    map_group ThreeIsland_BondBridge              @ 3.48
    map_group ThreeIsland_Port                    @ 3.49
    map_group SeviiIsle6                          @ 3.50
    map_group SeviiIsle7                          @ 3.51
    map_group SeviiIsle8                          @ 3.52
    map_group SeviiIsle9                          @ 3.53
    map_group FiveIsland_ResortGorgeous           @ 3.54
    map_group FiveIsland_WaterLabyrinth           @ 3.55
    map_group FiveIsland_Meadow                   @ 3.56
    map_group FiveIsland_MemorialPillar           @ 3.57
    map_group SixIsland_OutcastIsland             @ 3.58
    map_group SixIsland_GreenPath                 @ 3.59
    map_group SixIsland_WaterPath                 @ 3.60
    map_group SixIsland_RuinValley                @ 3.61
    map_group SevenIsland_TrainerTower            @ 3.62
    map_group SevenIsland_CanyonEntrance          @ 3.63
    map_group SevenIsland_SevaultCanyon           @ 3.64
    map_group SevenIsland_TanobyRuins             @ 3.65

    new_map_group
    map_group PalletTown_PlayersHouse_1F          @ 4.0
    map_group PalletTown_PlayersHouse_2F          @ 4.1
    map_group PalletTown_RivalsHouse              @ 4.2
    map_group PalletTown_ProfessorOaksLab         @ 4.3

    new_map_group
    map_group ViridianCity_0                      @ 5.0
    map_group ViridianCity_1                      @ 5.1
    map_group ViridianCity_2                      @ 5.2
    map_group ViridianCity_PokeMart               @ 5.3
    map_group ViridianCity_PokemonCenter_1F       @ 5.4
    map_group ViridianCity_PokemonCenter_2F       @ 5.5

    new_map_group
    map_group PewterCity_0                        @ 6.0
    map_group PewterCity_1                        @ 6.1
    map_group PewterCity_2                        @ 6.2
    map_group PewterCity_PokeMart                 @ 6.3
    map_group PewterCity_4                        @ 6.4
    map_group PewterCity_PokemonCenter_1F         @ 6.5
    map_group PewterCity_PokemonCenter_2F         @ 6.6
    map_group PewterCity_7                        @ 6.7

    new_map_group
    map_group CeruleanCity_0                      @ 7.0
    map_group CeruleanCity_1                      @ 7.1
    map_group CeruleanCity_2                      @ 7.2
    map_group CeruleanCity_PokemonCenter_1F       @ 7.3
    map_group CeruleanCity_PokemonCenter_2F       @ 7.4
    map_group CeruleanCity_5                      @ 7.5
    map_group CeruleanCity_6                      @ 7.6
    map_group CeruleanCity_PokeMart               @ 7.7
    map_group CeruleanCity_8                      @ 7.8
    map_group CeruleanCity_9                      @ 7.9

    new_map_group
    map_group LavenderTown_PokemonCenter_1F       @ 8.0
    map_group LavenderTown_PokemonCenter_2F       @ 8.1
    map_group LavenderTown_2                      @ 8.2
    map_group LavenderTown_3                      @ 8.3
    map_group LavenderTown_4                      @ 8.4
    map_group LavenderTown_PokeMart               @ 8.5

    new_map_group
    map_group VermillionCity_0                    @ 9.0
    map_group VermillionCity_PokemonCenter_1F     @ 9.1
    map_group VermillionCity_PokemonCenter_2F     @ 9.2
    map_group VermillionCity_3                    @ 9.3
    map_group VermillionCity_4                    @ 9.4
    map_group VermillionCity_PokeMart             @ 9.5
    map_group VermillionCity_6                    @ 9.6
    map_group VermillionCity_7                    @ 9.7

    new_map_group
    map_group CeladonCity_0                       @ 10.0
    map_group CeladonCity_1                       @ 10.1
    map_group CeladonCity_2                       @ 10.2
    map_group CeladonCity_3                       @ 10.3
    map_group CeladonCity_4                       @ 10.4
    map_group CeladonCity_5                       @ 10.5
    map_group CeladonCity_6                       @ 10.6
    map_group CeladonCity_7                       @ 10.7
    map_group CeladonCity_8                       @ 10.8
    map_group CeladonCity_9                       @ 10.9
    map_group CeladonCity_10                      @ 10.10
    map_group CeladonCity_11                      @ 10.11
    map_group CeladonCity_PokemonCenter_1F        @ 10.12
    map_group CeladonCity_PokemonCenter_2F        @ 10.13
    map_group CeladonCity_14                      @ 10.14
    map_group CeladonCity_15                      @ 10.15
    map_group CeladonCity_16                      @ 10.16
    map_group CeladonCity_17                      @ 10.17
    map_group CeladonCity_18                      @ 10.18
    map_group CeladonCity_19                      @ 10.19

    new_map_group
    map_group FuchsiaCity_0                       @ 11.0
    map_group FuchsiaCity_PokeMart                @ 11.1
    map_group FuchsiaCity_2                       @ 11.2
    map_group FuchsiaCity_3                       @ 11.3
    map_group FuchsiaCity_4                       @ 11.4
    map_group FuchsiaCity_PokemonCenter_1F        @ 11.5
    map_group FuchsiaCity_PokemonCenter_2F        @ 11.6
    map_group FuchsiaCity_7                       @ 11.7
    map_group FuchsiaCity_8                       @ 11.8
    map_group FuchsiaCity_9                       @ 11.9

    new_map_group
    map_group CinnabarIsland_0                    @ 12.0
    map_group CinnabarIsland_1                    @ 12.1
    map_group CinnabarIsland_2                    @ 12.2
    map_group CinnabarIsland_3                    @ 12.3
    map_group CinnabarIsland_4                    @ 12.4
    map_group CinnabarIsland_PokemonCenter_1F     @ 12.5
    map_group CinnabarIsland_PokemonCenter_2F     @ 12.6
    map_group CinnabarIsland_PokeMart             @ 12.7

    new_map_group
    map_group IndigoPlateau_0                     @ 13.0
    map_group IndigoPlateau_PokemonCenter_2F      @ 13.1

    new_map_group
    map_group SaffronCity_0                       @ 14.0
    map_group SaffronCity_1                       @ 14.1
    map_group SaffronCity_2                       @ 14.2
    map_group SaffronCity_3                       @ 14.3
    map_group SaffronCity_4                       @ 14.4
    map_group SaffronCity_PokeMart                @ 14.5
    map_group SaffronCity_PokemonCenter_1F        @ 14.6
    map_group SaffronCity_PokemonCenter_2F        @ 14.7
    map_group SaffronCity_8                       @ 14.8
    map_group SaffronCity_9                       @ 14.9

    new_map_group
    map_group Route2_0                            @ 15.0
    map_group Route2_1                            @ 15.1
    map_group Route2_2                            @ 15.2
    map_group Route2_3                            @ 15.3

    new_map_group
    map_group Route4_PokemonCenter_1F             @ 16.0
    map_group Route4_PokemonCenter_2F             @ 16.1

    new_map_group
    map_group Route5_0                            @ 17.0
    map_group Route5_1                            @ 17.1

    new_map_group
    map_group Route6_0                            @ 18.0
    map_group Route6_1                            @ 18.1

    new_map_group
    map_group Route7_0                            @ 19.0

    new_map_group
    map_group Route8_0                            @ 20.0

    new_map_group
    map_group Route10_PokemonCenter_1F            @ 21.0
    map_group Route10_PokemonCenter_2F            @ 21.1

    new_map_group
    map_group Route11_0                           @ 22.0
    map_group Route11_1                           @ 22.1

    new_map_group
    map_group Route12_0                           @ 23.0
    map_group Route12_1                           @ 23.1
    map_group Route12_2                           @ 23.2

    new_map_group
    map_group Route15_0                           @ 24.0
    map_group Route15_1                           @ 24.1

    new_map_group
    map_group Route16_0                           @ 25.0
    map_group Route16_1                           @ 25.1
    map_group Route16_2                           @ 25.2

    new_map_group
    map_group Route18_0                           @ 26.0
    map_group Route18_1                           @ 26.1

    new_map_group
    map_group Route19_0                           @ 27.0

    new_map_group
    map_group Route22_0                           @ 28.0

    new_map_group
    map_group Route23_0                           @ 29.0

    new_map_group
    map_group Route25_0                           @ 30.0

    new_map_group
    map_group SevenIsland_0                       @ 31.0
    map_group SevenIsland_1                       @ 31.1
    map_group SevenIsland_PokeMart                @ 31.2
    map_group SevenIsland_PokemonCenter_1F        @ 31.3
    map_group SevenIsland_PokemonCenter_2F        @ 31.4
    map_group SevenIsland_5                       @ 31.5
    map_group SevenIsland_6                       @ 31.6

    new_map_group
    map_group OneIsland_0                         @ 32.0
    map_group OneIsland_1                         @ 32.1
    map_group OneIsland_2                         @ 32.2
    map_group OneIsland_3                         @ 32.3
    map_group OneIsland_4                         @ 32.4

    new_map_group
    map_group TwoIsland_0                         @ 33.0
    map_group TwoIsland_1                         @ 33.1
    map_group TwoIsland_PokemonCenter_1F          @ 33.2
    map_group TwoIsland_PokemonCenter_2F          @ 33.3
    map_group TwoIsland_4                         @ 33.4

    new_map_group
    map_group ThreeIsland_0                       @ 34.0
    map_group ThreeIsland_PokemonCenter_1F        @ 34.1
    map_group ThreeIsland_PokemonCenter_2F        @ 34.2
    map_group ThreeIsland_PokeMart                @ 34.3
    map_group ThreeIsland_4                       @ 34.4
    map_group ThreeIsland_5                       @ 34.5
    map_group ThreeIsland_6                       @ 34.6
    map_group ThreeIsland_7                       @ 34.7

    new_map_group
    map_group FourIsland_0                        @ 35.0
    map_group FourIsland_PokemonCenter_1F         @ 35.1
    map_group FourIsland_PokemonCenter_2F         @ 35.2
    map_group FourIsland_3                        @ 35.3
    map_group FourIsland_4                        @ 35.4
    map_group FourIsland_5                        @ 35.5
    map_group FourIsland_6                        @ 35.6
    map_group FourIsland_PokeMart                 @ 35.7

    new_map_group
    map_group FiveIsland_PokemonCenter_1F         @ 36.0
    map_group FiveIsland_PokemonCenter_2F         @ 36.1
    map_group FiveIsland_2                        @ 36.2
    map_group FiveIsland_3                        @ 36.3
    map_group FiveIsland_4                        @ 36.4

    new_map_group
    map_group SixIsland_PokemonCenter_1F          @ 37.0
    map_group SixIsland_PokemonCenter_2F          @ 37.1
    map_group SixIsland_2                         @ 37.2
    map_group SixIsland_3                         @ 37.3
    map_group SixIsland_PokeMart                  @ 37.4

    new_map_group
    map_group Map38_0                             @ 38.0

    new_map_group
    map_group Map39_0                             @ 39.0

    new_map_group
    map_group Map40_0                             @ 40.0

    new_map_group
    map_group Map41_0                             @ 41.0
    map_group Map41_1                             @ 41.1

    new_map_group
    map_group Map42_0                             @ 42.0
