Text_8444C35:: @ 8444C35
    .string "This is a newly discovered POKéMON. It is\n"
    .string "currently under investigation. No detailed\n"
    .string "information is available at this time.$"

Text_8444CB1:: @ 8444CB1
    .string "$"

Text_8444CB2:: @ 8444CB2
    .string "There is a plant seed on its back right\n"
    .string "from the day this POKéMON is born.\n"
    .string "The seed slowly grows larger.$"

Text_8444D1B:: @ 8444D1B
    .string "$"

Text_8444D1C:: @ 8444D1C
    .string "There is a plant bulb on its back.\n"
    .string "When it absorbs nutrients, the bulb is said\n"
    .string "to blossom into a large flower.$"

Text_8444D8B:: @ 8444D8B
    .string "$"

Text_8444D8C:: @ 8444D8C
    .string "A bewitching aroma wafts from its flower.\n"
    .string "The fragrance becalms those engaged in\n"
    .string "a battle.$"

Text_8444DE7:: @ 8444DE7
    .string "$"

Text_8444DE8:: @ 8444DE8
    .string "From the time it is born, a flame burns\n"
    .string "at the tip of its tail. Its life would end\n"
    .string "if the flame were to go out.$"

Text_8444E58:: @ 8444E58
    .string "$"

Text_8444E59:: @ 8444E59
    .string "It lashes about with its tail to knock\n"
    .string "down its foe. It then tears up the fallen\n"
    .string "opponent with sharp claws.$"

Text_8444EC5:: @ 8444EC5
    .string "$"

Text_8444EC6:: @ 8444EC6
    .string "Its wings can carry this POKéMON close to\n"
    .string "an altitude of 4,600 feet. It blows out\n"
    .string "fire at very high temperatures.$"

Text_8444F38:: @ 8444F38
    .string "$"

Text_8444F39:: @ 8444F39
    .string "When it retracts its long neck into its\n"
    .string "shell, it squirts out water with vigorous\n"
    .string "force.$"

Text_8444F92:: @ 8444F92
    .string "$"

Text_8444F93:: @ 8444F93
    .string "This POKéMON is very popular as a pet.\n"
    .string "Its fur-covered tail is a symbol of its\n"
    .string "longevity.$"

Text_8444FED:: @ 8444FED
    .string "$"

Text_8444FEE:: @ 8444FEE
    .string "It crushes its foe under its heavy body\n"
    .string "to cause fainting. In a pinch, it will\n"
    .string "withdraw inside its shell.$"

Text_8445058:: @ 8445058
    .string "$"

Text_8445059:: @ 8445059
    .string "It is covered with a green skin. When it\n"
    .string "grows, it sheds the skin, covers itself\n"
    .string "with silk, and becomes a cocoon.$"

Text_84450CB:: @ 84450CB
    .string "$"

Text_84450CC:: @ 84450CC
    .string "Even though it is encased in a sturdy\n"
    .string "shell, the body inside is tender.\n"
    .string "It can’t withstand a harsh attack.$"

Text_8445137:: @ 8445137
    .string "$"

Text_8445138:: @ 8445138
    .string "The wings are protected by rain-repellent\n"
    .string "dust. As a result, this POKéMON can fly\n"
    .string "about even in rain.$"

Text_844519E:: @ 844519E
    .string "$"

Text_844519F:: @ 844519F
    .string "Often found in forests and grasslands.\n"
    .string "It has a sharp, toxic barb of around two\n"
    .string "inches on top of its head.$"

Text_844520A:: @ 844520A
    .string "$"

Text_844520B:: @ 844520B
    .string "This POKéMON is in a temporary stage\n"
    .string "while making its body. It is almost\n"
    .string "completely unable to move on its own.$"

Text_844527A:: @ 844527A
    .string "$"

Text_844527B:: @ 844527B
    .string "May appear in a swarm. Flies at violent\n"
    .string "speeds, all the while stabbing with the\n"
    .string "toxic stinger on its rear.$"

Text_84452E6:: @ 84452E6
    .string "$"

Text_84452E7:: @ 84452E7
    .string "Does not like to fight. It hides in\n"
    .string "tall grass and so on, foraging for food\n"
    .string "such as small bugs.$"

Text_8445347:: @ 8445347
    .string "$"

Text_8445348:: @ 8445348
    .string "The claws on its feet are well developed.\n"
    .string "It can carry prey such as an EXEGGCUTE\n"
    .string "to its nest over 60 miles away.$"

Text_84453B9:: @ 84453B9
    .string "$"

Text_84453BA:: @ 84453BA
    .string "It spreads its gorgeous wings widely to\n"
    .string "intimidate enemies. It races through the\n"
    .string "skies at Mach-2 speed.$"

Text_8445422:: @ 8445422
    .string "$"

Text_8445423:: @ 8445423
    .string "Its fangs are long and very sharp.\n"
    .string "They grow continuously, so it gnaws on\n"
    .string "hard things to whittle them down.$"

Text_844548F:: @ 844548F
    .string "$"

Text_8445490:: @ 8445490
    .string "Its rear feet have three toes each.\n"
    .string "They are webbed, enabling it to swim\n"
    .string "across rivers.$"

Text_84454E8:: @ 84454E8
    .string "$"

Text_84454E9:: @ 84454E9
    .string "It busily flits around here and there.\n"
    .string "Even if it is frail, it can be a tough\n"
    .string "foe that uses MIRROR MOVE.$"

Text_8445552:: @ 8445552
    .string "$"

Text_8445553:: @ 8445553
    .string "Its huge and magnificent wings can keep it\n"
    .string "aloft in the sky. It can remain flying a\n"
    .string "whole day without landing.$"

Text_84455C2:: @ 84455C2
    .string "$"

Text_84455C3:: @ 84455C3
    .string "A very common sight in grassland, etc.\n"
    .string "It flicks its tongue in and out to sense\n"
    .string "danger in its surroundings.$"

Text_844562F:: @ 844562F
    .string "$"

Text_8445630:: @ 8445630
    .string "The pattern on its belly appears to be a\n"
    .string "frightening face. Weak foes will flee just\n"
    .string "at the sight of the pattern.$"

Text_84456A1:: @ 84456A1
    .string "$"

Text_84456A2:: @ 84456A2
    .string "It has small electric sacs on both its\n"
    .string "cheeks. If threatened, it looses electric\n"
    .string "charges from the sacs.$"

Text_844570A:: @ 844570A
    .string "$"

Text_844570B:: @ 844570B
    .string "Its electric charges can reach even\n"
    .string "100,000 volts. Careless contact can cause\n"
    .string "even an Indian elephant to faint.$"

Text_844577B:: @ 844577B
    .string "$"

Text_844577C:: @ 844577C
    .string "It burrows and lives underground.\n"
    .string "If threatened, it curls itself up into a\n"
    .string "ball for protection.$"

Text_84457DC:: @ 84457DC
    .string "$"

Text_84457DD:: @ 84457DD
    .string "It is adept at attacking with the spines\n"
    .string "on its back and its sharp claws while\n"
    .string "quickly scurrying about.$"

Text_8445845:: @ 8445845
    .string "$"

Text_8445846:: @ 8445846
    .string "Though small, it must be treated with\n"
    .string "caution because of its powerfully toxic\n"
    .string "barbs. The female has smaller horns.$"

Text_84458B9:: @ 84458B9
    .string "$"

Text_84458BA:: @ 84458BA
    .string "The female has a gentle temperament.\n"
    .string "It emits ultrasonic cries that have the\n"
    .string "power to befuddle foes.$"

Text_844591F:: @ 844591F
    .string "$"

Text_8445920:: @ 8445920
    .string "The body is covered by stiff, needle-\n"
    .string "like scales. If it becomes excited,\n"
    .string "the needles bristle outwards.$"

Text_8445988:: @ 8445988
    .string "$"

Text_8445989:: @ 8445989
    .string "Its large ears are flapped like wings\n"
    .string "when it is listening to distant sounds.\n"
    .string "It extends toxic barbs when angered.$"

Text_84459FC:: @ 84459FC
    .string "$"

Text_84459FD:: @ 84459FD
    .string "It is easily angered. By swinging its well-\n"
    .string "developed horn wildly, it can even punch\n"
    .string "through diamond.$"

Text_8445A63:: @ 8445A63
    .string "$"

Text_8445A64:: @ 8445A64
    .string "It is recognized by its rock-hard hide\n"
    .string "and its extended horn. Be careful with\n"
    .string "the horn as it contains venom.$"

Text_8445AD1:: @ 8445AD1
    .string "$"

Text_8445AD2:: @ 8445AD2
    .string "Its adorable appearance makes it popular\n"
    .string "as a pet. However, it is rare and\n"
    .string "difficult to find.$"

Text_8445B30:: @ 8445B30
    .string "$"

Text_8445B31:: @ 8445B31
    .string "It has an acute sense of hearing. It can\n"
    .string "easily hear a pin being dropped nearly\n"
    .string "1,100 yards away.$"

Text_8445B93:: @ 8445B93
    .string "$"

Text_8445B94:: @ 8445B94
    .string "While young, it has six gorgeous tails.\n"
    .string "When it grows, several new tails are\n"
    .string "sprouted.$"

Text_8445BEB:: @ 8445BEB
    .string "$"

Text_8445BEC:: @ 8445BEC
    .string "It has nine long tails and fur that \n"
    .string "gleams gold. It is said to live for \n"
    .string "1,000 years.$"

Text_8445C43:: @ 8445C43
    .string "$"

Text_8445C44:: @ 8445C44
    .string "It captivates foes with its huge, round\n"
    .string "eyes, then lulls them to sleep by singing\n"
    .string "a soothing melody.$"

Text_8445CA9:: @ 8445CA9
    .string "$"

Text_8445CAA:: @ 8445CAA
    .string "Its fur is extremely fine, dense, and\n"
    .string "supple. The exquisitely pleasant fur\n"
    .string "conveys an image of luxury.$"

Text_8445D11:: @ 8445D11
    .string "$"

Text_8445D12:: @ 8445D12
    .string "It has no eyes. Instead, it relies on\n"
    .string "its ultrasonic cries for echo location to\n"
    .string "flit about in darkness.$"

Text_8445D7A:: @ 8445D7A
    .string "$"

Text_8445D7B:: @ 8445D7B
    .string "It clamps down on its prey with needle-\n"
    .string "sharp fangs and drains over 10 ounces of\n"
    .string "blood in one gulp.$"

Text_8445DDF:: @ 8445DDF
    .string "$"

Text_8445DE0:: @ 8445DE0
    .string "Its scientific name is “Oddium Wanderus.”\n"
    .string "At night, it is said to walk nearly 1,000\n"
    .string "feet on its two roots.$"

Text_8445E4B:: @ 8445E4B
    .string "$"

Text_8445E4C:: @ 8445E4C
    .string "Its pistils exude an incredibly foul odor.\n"
    .string "The horrid stench can cause fainting at a\n"
    .string "distance of 1.25 miles.$"

Text_8445EB9:: @ 8445EB9
    .string "$"

Text_8445EBA:: @ 8445EBA
    .string "Its petals are the largest in the world.\n"
    .string "It fiendishly scatters allergy-causing\n"
    .string "pollen from its petals.$"

Text_8445F22:: @ 8445F22
    .string "$"

Text_8445F23:: @ 8445F23
    .string "Growing out of the bug’s back are\n"
    .string "mushrooms called tochukaso. The mushrooms\n"
    .string "grow with the bug host.$"

Text_8445F87:: @ 8445F87
    .string "$"

Text_8445F88:: @ 8445F88
    .string "It scatters toxic spores from the\n"
    .string "mushroom cap. In China, the spores are\n"
    .string "used as herbal medicine.$"

Text_8445FEA:: @ 8445FEA
    .string "$"

Text_8445FEB:: @ 8445FEB
    .string "Its eyes act as radar, enabling it to be\n"
    .string "active in darkness. The eyes can also\n"
    .string "shoot powerful beams.$"

Text_8446050:: @ 8446050
    .string "$"

Text_8446051:: @ 8446051
    .string "The wings are covered with dustlike\n"
    .string "scales. Every time it flaps its wings, it\n"
    .string "looses highly toxic dust.$"

Text_84460B9:: @ 84460B9
    .string "$"

Text_84460BA:: @ 84460BA
    .string "It burrows through the ground at a\n"
    .string "shallow depth. It leaves raised earth in\n"
    .string "its wake, making it easy to spot.$"

Text_8446128:: @ 8446128
    .string "$"

Text_8446129:: @ 8446129
    .string "In battle, it digs through the ground and\n"
    .string "strikes the unsuspecting foe from an\n"
    .string "unexpected direction.$"

Text_844618E:: @ 844618E
    .string "$"

Text_844618F:: @ 844618F
    .string "All it does is sleep during the daytime.\n"
    .string "At night, it patrols its territory with its\n"
    .string "eyes aglow.$"

Text_84461F0:: @ 84461F0
    .string "$"

Text_84461F1:: @ 84461F1
    .string "Has a vicious temperament. Beware if it\n"
    .string "raises its tail straight up. It is a signal\n"
    .string "that it is about to pounce and bite.$"

Text_844626A:: @ 844626A
    .string "$"

Text_844626B:: @ 844626B
    .string "It is constantly wracked by a headache.\n"
    .string "When the headache turns intense, it begins\n"
    .string "using mysterious powers.$"

Text_84462D7:: @ 84462D7
    .string "$"

Text_84462D8:: @ 84462D8
    .string "The forelegs are webbed, helping to make\n"
    .string "it an adept swimmer. It can be seen\n"
    .string "swimming elegantly in lakes, etc.$"

Text_8446347:: @ 8446347
    .string "$"

Text_8446348:: @ 8446348
    .string "Light and agile on its feet, and ferocious\n"
    .string "in temperament. When angered, it flies into\n"
    .string "an uncontrollable frenzy.$"

Text_84463B9:: @ 84463B9
    .string "$"

Text_84463BA:: @ 84463BA
    .string "It is always outrageously furious. If it\n"
    .string "gives chase, it will tenaciously track the\n"
    .string "target no matter how far.$"

Text_8446428:: @ 8446428
    .string "$"

Text_8446429:: @ 8446429
    .string "Very friendly and faithful to people.\n"
    .string "It will try to repel enemies by barking\n"
    .string "and biting.$"

Text_8446483:: @ 8446483
    .string "$"

Text_8446484:: @ 8446484
    .string "A POKéMON that is described in Chinese\n"
    .string "legends. It is said to race at an\n"
    .string "unbelievable speed.$"

Text_84464E1:: @ 84464E1
    .string "$"

Text_84464E2:: @ 84464E2
    .string "Its slick black skin is thin and damp.\n"
    .string "A part of its internal organs can be seen\n"
    .string "through the skin as a spiral pattern.$"

Text_8446559:: @ 8446559
    .string "$"

Text_844655A:: @ 844655A
    .string "Its two legs are well developed.\n"
    .string "Even though it can live on the ground,\n"
    .string "it prefers living in water.$"

Text_84465BE:: @ 84465BE
    .string "$"

Text_84465BF:: @ 84465BF
    .string "An adept swimmer, it knows the front\n"
    .string "crawl, butterfly, and more. It is faster\n"
    .string "than the best human swimmers.$"

Text_844662B:: @ 844662B
    .string "$"

Text_844662C:: @ 844662C
    .string "It sleeps for 18 hours a day. It uses a\n"
    .string "variety of extrasensory powers even\n"
    .string "while asleep.$"

Text_8446686:: @ 8446686
    .string "$"

Text_8446687:: @ 8446687
    .string "It happened one morning - a boy with\n"
    .string "extrasensory powers awoke in bed\n"
    .string "transformed into KADABRA.$"

Text_84466E7:: @ 84466E7
    .string "$"

Text_84466E8:: @ 84466E8
    .string "It does not like physical attacks very \n"
    .string "much. Instead, it freely uses extra-\n"
    .string "sensory powers to defeat foes.$"

Text_8446754:: @ 8446754
    .string "$"

Text_8446755:: @ 8446755
    .string "Its whole body is composed of muscles.\n"
    .string "Even though it’s the size of a human\n"
    .string "child, it can hurl 100 grown-ups.$"

Text_84467C3:: @ 84467C3
    .string "$"

Text_84467C4:: @ 84467C4
    .string "Its formidable body never gets tired.\n"
    .string "It helps people by doing work such as\n"
    .string "the moving of heavy goods.$"

Text_844682B:: @ 844682B
    .string "$"

Text_844682C:: @ 844682C
    .string "Its four ruggedly developed arms can\n"
    .string "launch a flurry of 1,000 punches in just\n"
    .string "two seconds.$"

Text_8446887:: @ 8446887
    .string "$"

Text_8446888:: @ 8446888
    .string "Its bud looks like a human face. Because\n"
    .string "of the bud, it is rumored to be a type of\n"
    .string "legendary mandrake plant.$"

Text_84468F5:: @ 84468F5
    .string "$"

Text_84468F6:: @ 84468F6
    .string "The leafy parts act as cutters for\n"
    .string "slashing foes. It spits a fluid that\n"
    .string "dissolves everything.$"

Text_8446954:: @ 8446954
    .string "$"

Text_8446955:: @ 8446955
    .string "Lures prey into its mouth with a honeylike\n"
    .string "aroma. The helpless prey is melted with\n"
    .string "a dissolving fluid.$"

Text_84469BC:: @ 84469BC
    .string "$"

Text_84469BD:: @ 84469BD
    .string "Its eyes are as transparent as crystals.\n"
    .string "From them, it shoots mysterious\n"
    .string "beams of light.$"

Text_8446A16:: @ 8446A16
    .string "$"

Text_8446A17:: @ 8446A17
    .string "It has 80 tentacles that move about\n"
    .string "freely. They can sting, causing poisoning\n"
    .string "and sharp, stabbing pain.$"

Text_8446A7F:: @ 8446A7F
    .string "$"

Text_8446A80:: @ 8446A80
    .string "Its round form makes it easy to pick up.\n"
    .string "Some people have used them to hurl\n"
    .string "at each other in a snowball fight.$"

Text_8446AEF:: @ 8446AEF
    .string "$"

Text_8446AF0:: @ 8446AF0
    .string "Be careful while hiking on mountain trails.\n"
    .string "GRAVELER may come rolling down the path\n"
    .string "without slowing.$"

Text_8446B55:: @ 8446B55
    .string "$"

Text_8446B56:: @ 8446B56
    .string "It is enclosed in a hard shell that is as\n"
    .string "rugged as slabs of rock. It sheds skin\n"
    .string "once a year to grow larger.$"

Text_8446BC3:: @ 8446BC3
    .string "$"

Text_8446BC4:: @ 8446BC4
    .string "Its body is light, and its legs are\n"
    .string "incredibly powerful. It can clear\n"
    .string "Ayers Rock in one leap.$"

Text_8446C22:: @ 8446C22
    .string "$"

Text_8446C23:: @ 8446C23
    .string "It can gallop at a top speed of 150\n"
    .string "miles per hour. It can race as fast as a\n"
    .string "bullet train while ablaze.$"

Text_8446C8B:: @ 8446C8B
    .string "$"

Text_8446C8C:: @ 8446C8C
    .string "It is always vacantly lost in thought, but\n"
    .string "no one knows what it is thinking about.\n"
    .string "It is good at fishing with its tail.$"

Text_8446D04:: @ 8446D04
    .string "$"

Text_8446D05:: @ 8446D05
    .string "When a SLOWPOKE went hunting in the sea,\n"
    .string "its tail was bitten by a SHELLDER. That\n"
    .string "made it evolve into SLOWBRO.$"

Text_8446D73:: @ 8446D73
    .string "$"

Text_8446D74:: @ 8446D74
    .string "It moves while constantly hovering.\n"
    .string "It discharges THUNDER WAVE and so on\n"
    .string "from the units at its sides.$"

Text_8446DDA:: @ 8446DDA
    .string "$"

Text_8446DDB:: @ 8446DDB
    .string "A linked cluster formed of several\n"
    .string "MAGNEMITE. It discharges powerful\n"
    .string "magnetic waves at high voltage.$"

Text_8446E40:: @ 8446E40
    .string "$"

Text_8446E41:: @ 8446E41
    .string "It always walks about with a plant stalk\n"
    .string "clamped in its beak. The stalk is used for\n"
    .string "building its nest.$"

Text_8446EA8:: @ 8446EA8
    .string "$"

Text_8446EA9:: @ 8446EA9
    .string "A two-headed POKéMON that was discovered\n"
    .string "as a sudden mutation. It runs at a pace\n"
    .string "of over 60 miles per hour.$"

Text_8446F15:: @ 8446F15
    .string "$"

Text_8446F16:: @ 8446F16
    .string "An odd species that is rarely found.\n"
    .string "The three heads respectively represent\n"
    .string "joy, sadness, and anger.$"

Text_8446F7B:: @ 8446F7B
    .string "$"

Text_8446F7C:: @ 8446F7C
    .string "Covered with light blue fur, its hide is\n"
    .string "thick and tough. It is active in bitter\n"
    .string "cold of minus 40 degrees Fahrenheit.$"

Text_8446FF2:: @ 8446FF2
    .string "$"

Text_8446FF3:: @ 8446FF3
    .string "Its body is covered with a pure white\n"
    .string "fur. The colder the weather, the more\n"
    .string "active it becomes.$"

Text_8447052:: @ 8447052
    .string "$"

Text_8447053:: @ 8447053
    .string "Sludge exposed to X rays from the moon\n"
    .string "transformed into GRIMER. It loves feeding\n"
    .string "on filthy things.$"

Text_84470B6:: @ 84470B6
    .string "$"

Text_84470B7:: @ 84470B7
    .string "It is usually undetectable because it\n"
    .string "blends in with the ground. Touching it can\n"
    .string "cause terrible poisoning.$"

Text_8447122:: @ 8447122
    .string "$"

Text_8447123:: @ 8447123
    .string "It is encased in a shell that is harder\n"
    .string "than diamond. Inside, however, it is\n"
    .string "surprisingly tender.$"

Text_8447185:: @ 8447185
    .string "$"

Text_8447186:: @ 8447186
    .string "Its shell is extremely hard. It cannot be\n"
    .string "shattered, even with a bomb. The shell\n"
    .string "opens only when it is attacking.$"

Text_84471F8:: @ 84471F8
    .string "$"

Text_84471F9:: @ 84471F9
    .string "A being that exists as a thin gas. It can\n"
    .string "topple an Indian elephant by enveloping\n"
    .string "the prey in two seconds.$"

Text_8447264:: @ 8447264
    .string "$"

Text_8447265:: @ 8447265
    .string "If you get the feeling of being watched\n"
    .string "in darkness when nobody is around,\n"
    .string "HAUNTER is there.$"

Text_84472C2:: @ 84472C2
    .string "$"

Text_84472C3:: @ 84472C3
    .string "It is said to emerge from darkness to\n"
    .string "steal the lives of those who become lost\n"
    .string "in mountains.$"

Text_8447320:: @ 8447320
    .string "$"

Text_8447321:: @ 8447321
    .string "It usually lives underground. It searches\n"
    .string "for food while boring its way through the\n"
    .string "ground at 50 miles per hour.$"

Text_8447392:: @ 8447392
    .string "$"

Text_8447393:: @ 8447393
    .string "A descendent of the legendary animal\n"
    .string "baku, which is said to eat dreams. It is\n"
    .string "skilled at hypnotism.$"

Text_84473F7:: @ 84473F7
    .string "$"

Text_84473F8:: @ 84473F8
    .string "It carries a pendulum-like device. There\n"
    .string "once was an incident in which it took \n"
    .string "away a child it hypnotized.$"

Text_8447464:: @ 8447464
    .string "$"

Text_8447465:: @ 8447465
    .string "It can be found near the sea. The large\n"
    .string "pincers grow back if they are torn out of\n"
    .string "their sockets.$"

Text_84474C6:: @ 84474C6
    .string "$"

Text_84474C7:: @ 84474C7
    .string "Its large and hard pincer has 10,000-\n"
    .string "horsepower strength. However, being so\n"
    .string "big, it is unwieldy to move.$"

Text_8447531:: @ 8447531
    .string "$"

Text_8447532:: @ 8447532
    .string "A life-form whose identity is unknown.\n"
    .string "It is said to SCREECH or suddenly\n"
    .string "SELFDESTRUCT.$"

Text_8447589:: @ 8447589
    .string "$"

Text_844758A:: @ 844758A
    .string "It explodes in response to even minor\n"
    .string "stimuli. It is feared, with the nickname\n"
    .string "of “The Bomb Ball.”$"

Text_84475ED:: @ 84475ED
    .string "$"

Text_84475EE:: @ 84475EE
    .string "Even though it appears to be eggs of\n"
    .string "some sort, it was discovered to be a life-\n"
    .string "form more like plant seeds.$"

Text_844765A:: @ 844765A
    .string "$"

Text_844765B:: @ 844765B
    .string "It is called “The Walking Tropical\n"
    .string "Rainforest.” Each of the nuts has\n"
    .string "a face and a will of its own.$"

Text_84476BE:: @ 84476BE
    .string "$"

Text_84476BF:: @ 84476BF
    .string "It wears the skull of its dead mother on\n"
    .string "its head. When it becomes lonesome, it is\n"
    .string "said to cry loudly.$"

Text_8447726:: @ 8447726
    .string "$"

Text_8447727:: @ 8447727
    .string "It is small and was originally very weak.\n"
    .string "Its temperament turned ferocious when it\n"
    .string "began using bones.$"

Text_844778D:: @ 844778D
    .string "$"

Text_844778E:: @ 844778E
    .string "The legs freely contract and stretch.\n"
    .string "The stretchy legs allow it to hit a\n"
    .string "distant foe with a rising kick.$"

Text_84477F8:: @ 84477F8
    .string "$"

Text_84477F9:: @ 84477F9
    .string "The spirit of a pro boxer has infused this\n"
    .string "POKéMON. It throws punches that are\n"
    .string "faster than a bullet train.$"

Text_8447864:: @ 8447864
    .string "$"

Text_8447865:: @ 8447865
    .string "Its tongue is twice the length of its\n"
    .string "body. It can be moved like an arm for\n"
    .string "grabbing food and attacking.$"

Text_84478CE:: @ 84478CE
    .string "$"

Text_84478CF:: @ 84478CF
    .string "Its thin, balloon-like body is inflated by\n"
    .string "horribly toxic gases. It reeks when it is\n"
    .string "nearby.$"

Text_844792C:: @ 844792C
    .string "$"

Text_844792D:: @ 844792D
    .string "Very rarely, a sudden mutation can result\n"
    .string "in two small KOFFING twins becoming\n"
    .string "conjoined as a WEEZING.$"

Text_8447993:: @ 8447993
    .string "$"

Text_8447994:: @ 8447994
    .string "Strong, but not too bright, this POKéMON\n"
    .string "can shatter even a skyscraper with its\n"
    .string "charging TACKLES.$"

Text_84479F6:: @ 84479F6
    .string "$"

Text_84479F7:: @ 84479F7
    .string "It begins walking on its hind legs after\n"
    .string "evolution. It can punch holes through\n"
    .string "boulders with its horn.$"

Text_8447A5E:: @ 8447A5E
    .string "$"

Text_8447A5F:: @ 8447A5F
    .string "It lays several eggs a day. The eggs are\n"
    .string "apparently rich in nutrients and extremely\n"
    .string "delicious.$"

Text_8447ABE:: @ 8447ABE
    .string "$"

Text_8447ABF:: @ 8447ABF
    .string "Blue plant vines cloak the POKéMON’s\n"
    .string "identity in a tangled mass. It entangles\n"
    .string "anything that gets close.$"

Text_8447B27:: @ 8447B27
    .string "$"

Text_8447B28:: @ 8447B28
    .string "The female raises its offspring in a pouch\n"
    .string "on its belly. It is skilled at attacking\n"
    .string "using COMET PUNCH.$"

Text_8447B8F:: @ 8447B8F
    .string "$"

Text_8447B90:: @ 8447B90
    .string "It maintains balance using its tail, which\n"
    .string "is wound up like a coil. It may spray ink\n"
    .string "from its mouth.$"

Text_8447BF5:: @ 8447BF5
    .string "$"

Text_8447BF6:: @ 8447BF6
    .string "Its body bristles with sharp spikes.\n"
    .string "Carelessly trying to touch it could cause\n"
    .string "fainting from the spikes.$"

Text_8447C5F:: @ 8447C5F
    .string "$"

Text_8447C60:: @ 8447C60
    .string "Its dorsal and pectoral fins are strongly\n"
    .string "developed like muscles. It can swim at a\n"
    .string "speed of five knots.$"

Text_8447CC8:: @ 8447CC8
    .string "$"

Text_8447CC9:: @ 8447CC9
    .string "The horn on its head is sharp like a\n"
    .string "drill. It bores a hole in a boulder to\n"
    .string "make its nest.$"

Text_8447D24:: @ 8447D24
    .string "$"

Text_8447D25:: @ 8447D25
    .string "It appears in large numbers by seashores.\n"
    .string "At night, its central core flashes with a\n"
    .string "red light.$"

Text_8447D84:: @ 8447D84
    .string "$"

Text_8447D85:: @ 8447D85
    .string "This POKéMON has a geometric body.\n"
    .string "Because of its body, the locals suspect\n"
    .string "that it is an alien creature.$"

Text_8447DEE:: @ 8447DEE
    .string "$"

Text_8447DEF:: @ 8447DEF
    .string "It is adept at conning people. It is said\n"
    .string "to be able to create walls out of thin\n"
    .string "air by miming.$"

Text_8447E4F:: @ 8447E4F
    .string "$"

Text_8447E50:: @ 8447E50
    .string "It tears and shreds prey with its wickedly\n"
    .string "sharp scythes. It very rarely spreads its\n"
    .string "wings to fly.$"

Text_8447EB3:: @ 8447EB3
    .string "$"

Text_8447EB4:: @ 8447EB4
    .string "It speaks using a language that sounds\n"
    .string "human. Research is under way to determine\n"
    .string "what is being said.$"

Text_8447F19:: @ 8447F19
    .string "$"

Text_8447F1A:: @ 8447F1A
    .string "It loves to feed on strong electricity.\n"
    .string "It occasionally appears around large\n"
    .string "power plants and so on.$"

Text_8447F7F:: @ 8447F7F
    .string "$"

Text_8447F80:: @ 8447F80
    .string "Found near the mouth of a volcano.\n"
    .string "This fire-breather’s body temperature is\n"
    .string "nearly 2,200 degrees Fahrenheit.$"

Text_8447FED:: @ 8447FED
    .string "$"

Text_8447FEE:: @ 8447FEE
    .string "Its two long pincer horns are powerful.\n"
    .string "Once they grip an enemy, they won’t\n"
    .string "release until the foe is torn.$"

Text_8448059:: @ 8448059
    .string "$"

Text_844805A:: @ 844805A
    .string "When it is about to TACKLE, it whips\n"
    .string "its body repeatedly with its three\n"
    .string "long tails.$"

Text_84480AE:: @ 84480AE
    .string "$"

Text_84480AF:: @ 84480AF
    .string "It is virtually worthless in terms of both\n"
    .string "power and speed. It is the most weak and\n"
    .string "pathetic POKéMON in the world.$"

Text_8448122:: @ 8448122
    .string "$"

Text_8448123:: @ 8448123
    .string "It has an extremely aggressive nature.\n"
    .string "The HYPER BEAM it shoots from its mouth\n"
    .string "totally incinerates all targets.$"

Text_8448193:: @ 8448193
    .string "$"

Text_8448194:: @ 8448194
    .string "Its high intelligence enables it to\n"
    .string "understand human speech. It likes to ferry\n"
    .string "people on its back.$"

Text_84481F7:: @ 84481F7
    .string "$"

Text_84481F8:: @ 84481F8
    .string "It can freely recombine its own cellular\n"
    .string "structure to transform into other life-\n"
    .string "forms.$"

Text_8448250:: @ 8448250
    .string "$"

Text_8448251:: @ 8448251
    .string "An extremely rare POKéMON that may\n"
    .string "evolve in a number of different ways\n"
    .string "depending on stimuli.$"

Text_84482AF:: @ 84482AF
    .string "$"

Text_84482B0:: @ 84482B0
    .string "Its body’s cellular structure is similar to\n"
    .string "the molecular composition of water.\n"
    .string "It can melt invisibly in water.$"

Text_8448320:: @ 8448320
    .string "$"

Text_8448321:: @ 8448321
    .string "If it is angered or startled, the fur all\n"
    .string "over its body bristles like sharp needles\n"
    .string "that pierce foes.$"

Text_8448387:: @ 8448387
    .string "$"

Text_8448388:: @ 8448388
    .string "It has a flame bag inside its body. After\n"
    .string "inhaling deeply, it blows out flames of\n"
    .string "nearly 3,100 degrees Fahrenheit.$"

Text_84483FB:: @ 84483FB
    .string "$"

Text_84483FC:: @ 84483FC
    .string "Using the most advanced technologies,\n"
    .string "scientists finally succeeded in making the\n"
    .string "first artificial POKéMON.$"

Text_8448467:: @ 8448467
    .string "$"

Text_8448468:: @ 8448468
    .string "A prehistoric POKéMON that lived in the\n"
    .string "primordial sea, it swims by twisting its\n"
    .string "10 tentacles about.$"

Text_84484CD:: @ 84484CD
    .string "$"

Text_84484CE:: @ 84484CE
    .string "Its tentacles are highly developed as if\n"
    .string "they are hands and feet. As soon as it\n"
    .string "ensnares prey, it bites.$"

Text_8448537:: @ 8448537
    .string "$"

Text_8448538:: @ 8448538
    .string "This POKéMON was regenerated from the\n"
    .string "fossil of an ancient creature. It protects\n"
    .string "itself with a hard shell.$"

Text_84485A3:: @ 84485A3
    .string "$"

Text_84485A4:: @ 84485A4
    .string "It swims freely through water. It catches\n"
    .string "prey with its scythe-like arms and drains\n"
    .string "the victim’s fluids.$"

Text_844860D:: @ 844860D
    .string "$"

Text_844860E:: @ 844860E
    .string "It was regenerated from a dinosaur’s\n"
    .string "genetic matter that was found in amber.\n"
    .string "It flies with high-pitched cries.$"

Text_844867D:: @ 844867D
    .string "$"

Text_844867E:: @ 844867E
    .string "It is not satisfied unless it eats over 880\n"
    .string "pounds of food every day. When it is done\n"
    .string "eating, it goes promptly to sleep.$"

Text_84486F7:: @ 84486F7
    .string "$"

Text_84486F8:: @ 84486F8
    .string "One of the legendary bird POKéMON.\n"
    .string "With its long tail trailing behind, its\n"
    .string "flying form is magnificent.$"

Text_844875F:: @ 844875F
    .string "$"

Text_8448760:: @ 8448760
    .string "One of the legendary bird POKéMON.\n"
    .string "While it is flying, it makes crackling and\n"
    .string "snapping sounds.$"

Text_84487BF:: @ 84487BF
    .string "$"

Text_84487C0:: @ 84487C0
    .string "One of the legendary bird POKéMON.\n"
    .string "Those seeing it are overwhelmed by its\n"
    .string "orange wings that seem to be on fire.$"

Text_8448830:: @ 8448830
    .string "$"

Text_8448831:: @ 8448831
    .string "Even the young can exceed 6.5 feet in\n"
    .string "length. It grows larger by repeatedly\n"
    .string "shedding skin.$"

Text_844888C:: @ 844888C
    .string "$"

Text_844888D:: @ 844888D
    .string "It is said to live in seas and lakes.\n"
    .string "Even though it has no wings, it has been\n"
    .string "seen flying occasionally.$"

Text_84488F6:: @ 84488F6
    .string "$"

Text_84488F7:: @ 84488F7
    .string "It can fly in spite of its big and bulky\n"
    .string "physique. It circles the globe in just\n"
    .string "16 hours.$"

Text_8448951:: @ 8448951
    .string "$"

Text_8448952:: @ 8448952
    .string "A POKéMON whose genetic code was\n"
    .string "repeatedly recombined for research.\n"
    .string "It turned vicious as a result.$"

Text_84489B6:: @ 84489B6
    .string "$"

Text_84489B7:: @ 84489B7
    .string "A POKéMON of South America that was\n"
    .string "thought to have been extinct. It is very\n"
    .string "intelligent and learns any move.$"

Text_8448A25:: @ 8448A25
    .string "$"

Text_8448A26:: @ 8448A26
.ifeq (REVISION - 0)
    .string "Its pleasantly aromatic leaves have the\n"
.else
    .string "Its pleasantly aromatic leaf has the\n"
.endif
    .string "ability to check the humidity and\n"
    .string "temperature.$"

Text_8448A7D:: @ 8448A7D
    .string "$"

Text_8448A7E:: @ 8448A7E
    .string "A spicy aroma emanates from around its\n"
    .string "neck. The aroma acts as a stimulant to\n"
    .string "restore health.$"

Text_8448ADC:: @ 8448ADC
    .string "$"

Text_8448ADD:: @ 8448ADD
    .string "MEGANIUM’s breath has the power to revive\n"
    .string "dead grass and plants. It can make them\n"
    .string "healthy again.$"

Text_8448B3E:: @ 8448B3E
    .string "$"

Text_8448B3F:: @ 8448B3F
    .string "It usually stays hunched over. If it is\n"
    .string "angry or surprised, it shoots flames out\n"
    .string "of its back.$"

Text_8448B9D:: @ 8448B9D
    .string "$"

Text_8448B9E:: @ 8448B9E
    .string "This POKéMON is fully covered by\n"
    .string "nonflammable fur. It can withstand any\n"
    .string "kind of fire attack.$"

Text_8448BFB:: @ 8448BFB
    .string "$"

Text_8448BFC:: @ 8448BFC
    .string "It has a secret, devastating move. It\n"
    .string "rubs its blazing fur together to cause\n"
    .string "huge explosions.$"

Text_8448C5A:: @ 8448C5A
    .string "$"

Text_8448C5B:: @ 8448C5B
    .string "It is small but rough and tough. It won’t\n"
    .string "hesitate to take a bite out of anything\n"
    .string "that moves.$"

Text_8448CB9:: @ 8448CB9
    .string "$"

Text_8448CBA:: @ 8448CBA
    .string "It opens its huge jaws wide when\n"
    .string "attacking. If it loses any fangs while\n"
    .string "biting, they grow back in.$"

Text_8448D1D:: @ 8448D1D
    .string "$"

Text_8448D1E:: @ 8448D1E
    .string "It is hard for it to support its own\n"
    .string "weight out of water, so it gets down on\n"
    .string "all fours. But it moves fast.$"

Text_8448D89:: @ 8448D89
    .string "$"

Text_8448D8A:: @ 8448D8A
    .string "It stands on its tail so it can see a long\n"
    .string "way. If it spots an enemy, it cries loudly\n"
    .string "to warn its kind.$"

Text_8448DF2:: @ 8448DF2
    .string "$"

Text_8448DF3:: @ 8448DF3
    .string "There is no telling where its tail begins.\n"
    .string "Despite its short legs, it is quick at\n"
    .string "hunting RATTATA.$"

Text_8448E56:: @ 8448E56
    .string "$"

Text_8448E57:: @ 8448E57
    .string "It has a perfect sense of time. Whatever\n"
    .string "happens, it keeps rhythm by precisely\n"
    .string "tilting its head in time.$"

Text_8448EC0:: @ 8448EC0
    .string "$"

Text_8448EC1:: @ 8448EC1
    .string "When it needs to think, it rotates its head\n"
    .string "180 degrees to sharpen its intellectual\n"
    .string "power.$"

Text_8448F1C:: @ 8448F1C
    .string "$"

Text_8448F1D:: @ 8448F1D
    .string "When the weather turns cold, numerous\n"
    .string "LEDYBA gather from everywhere to cluster\n"
    .string "and keep each other warm.$"

Text_8448F86:: @ 8448F86
    .string "$"

Text_8448F87:: @ 8448F87
    .string "The star patterns on its back grow larger\n"
    .string "or smaller depending on the number of\n"
    .string "stars in the night sky.$"

Text_8448FEF:: @ 8448FEF
    .string "$"

Text_8448FF0:: @ 8448FF0
    .string "It spins a web using fine--but durable--\n"
    .string "thread. It then waits patiently for prey\n"
    .string "to be trapped.$"

Text_8449051:: @ 8449051
    .string "$"

Text_8449052:: @ 8449052
    .string "A single strand of a special string is\n"
    .string "endlessly spun out of its rear. The string\n"
    .string "leads back to its nest.$"

Text_84490BC:: @ 84490BC
    .string "$"

Text_84490BD:: @ 84490BD
    .string "The development of wings on its legs\n"
    .string "enables it to fly fast but also makes it\n"
    .string "tough to stop and rest.$"

Text_8449123:: @ 8449123
    .string "$"

Text_8449124:: @ 8449124
    .string "On the dark ocean floor, its only means\n"
    .string "of communication is its constantly\n"
    .string "flashing lights.$"

Text_8449180:: @ 8449180
    .string "$"

Text_8449181:: @ 8449181
    .string "It blinds prey with an intense burst of\n"
    .string "light, then swallows the immobilized prey\n"
    .string "in a single gulp.$"

Text_84491E5:: @ 84491E5
    .string "$"

Text_84491E6:: @ 84491E6
    .string "Despite its small size, it can zap even\n"
    .string "adult humans. However, if it does so, it\n"
    .string "also surprises itself.$"

Text_844924E:: @ 844924E
    .string "$"

Text_844924F:: @ 844924F
    .string "When numerous meteors illuminate the\n"
    .string "night sky, sightings of CLEFFA strangely\n"
    .string "increase.$"

Text_84492A7:: @ 84492A7
    .string "$"

Text_84492A8:: @ 84492A8
    .string "Its extremely flexible and elastic body\n"
    .string "makes it bounce continuously--anytime,\n"
    .string "anywhere.$"

Text_8449301:: @ 8449301
    .string "$"

Text_8449302:: @ 8449302
    .string "A proverb claims that happiness will come\n"
    .string "to anyone who can make a sleeping TOGEPI\n"
    .string "stand up.$"

Text_844935F:: @ 844935F
    .string "$"

Text_8449360:: @ 8449360
    .string "It grows dispirited if it is not with kind\n"
    .string "people. It can float in midair without\n"
    .string "moving its wings.$"

Text_84493C4:: @ 84493C4
    .string "$"

Text_84493C5:: @ 84493C5
    .string "It usually forages for food on the ground\n"
    .string "but may, on rare occasions, hop onto\n"
    .string "branches to peck at shoots.$"

Text_8449430:: @ 8449430
    .string "$"

Text_8449431:: @ 8449431
    .string "In South America, it is said that its right\n"
    .string "eye sees the future and its left eye\n"
    .string "views the past.$"

Text_8449492:: @ 8449492
    .string "$"

Text_8449493:: @ 8449493
    .string "Its fleece grows continually. In the\n"
    .string "summer, the fleece is fully shed, but it\n"
    .string "grows back in a week.$"

Text_84494F7:: @ 84494F7
    .string "$"

Text_84494F8:: @ 84494F8
    .string "Its fluffy fleece easily stores\n"
    .string "electricity. Its rubbery hide keeps it\n"
    .string "from being electrocuted.$"

Text_8449558:: @ 8449558
    .string "$"

Text_8449559:: @ 8449559
    .string "The bright light on its tail can be seen\n"
    .string "far away. It has been treasured since\n"
    .string "ancient times as a beacon.$"

Text_84495C3:: @ 84495C3
    .string "$"

Text_84495C4:: @ 84495C4
    .string "Plentiful in the tropics. When it dances,\n"
    .string "its petals rub together and make a\n"
    .string "pleasant ringing sound.$"

Text_8449629:: @ 8449629
    .string "$"

Text_844962A:: @ 844962A
    .string "The end of its tail serves as a buoy that\n"
    .string "keeps it from drowning, even in a vicious\n"
    .string "current.$"

Text_8449687:: @ 8449687
    .string "$"

Text_8449688:: @ 8449688
    .string "When it plays in water, it rolls up its\n"
    .string "elongated ears to prevent their insides\n"
    .string "from getting wet.$"

Text_84496EA:: @ 84496EA
    .string "$"

Text_84496EB:: @ 84496EB
    .string "It disguises itself as a tree to avoid\n"
    .string "attack. It hates water, so it will\n"
    .string "disappear if it starts raining.$"

Text_8449755:: @ 8449755
    .string "$"

Text_8449756:: @ 8449756
    .string "Whenever three or more of these get\n"
    .string "together, they sing in a loud voice that\n"
    .string "sounds like bellowing.$"

Text_84497BA:: @ 84497BA
    .string "$"

Text_84497BB:: @ 84497BB
    .string "Its body is so light, it must grip the\n"
    .string "ground firmly with its feet to keep from\n"
    .string "being blown away.$"

Text_844981D:: @ 844981D
    .string "$"

Text_844981E:: @ 844981E
    .string "It spreads its petals to absorb sunlight.\n"
    .string "It also floats in the air to get closer to\n"
    .string "the sun.$"

Text_844987C:: @ 844987C
    .string "$"

Text_844987D:: @ 844987D
    .string "It drifts on seasonal winds and spreads\n"
    .string "its cotton-like spores all over the world \n"
    .string "to make more offspring.$"

Text_84498E8:: @ 84498E8
    .string "$"

Text_84498E9:: @ 84498E9
    .string "It lives atop tall trees. When leaping\n"
    .string "from branch to branch, it deftly uses its\n"
    .string "tail for balance.$"

Text_844994C:: @ 844994C
    .string "$"

Text_844994D:: @ 844994D
    .string "It lives by drinking only dewdrops from\n"
    .string "under the leaves of plants. It is said\n"
    .string "that it eats nothing else.$"

Text_84499B7:: @ 84499B7
    .string "$"

Text_84499B8:: @ 84499B8
    .string "In the daytime, it rushes about in a\n"
    .string "hectic manner, but it comes to a complete\n"
    .string "stop when the sun sets.$"

Text_8449A1F:: @ 8449A1F
    .string "$"

Text_8449A20:: @ 8449A20
    .string "Its large eyes can scan 360 degrees.\n"
    .string "It looks in all directions to seek out\n"
    .string "insects as its prey.$"

Text_8449A81:: @ 8449A81
    .string "$"

Text_8449A82:: @ 8449A82
    .string "When it walks around on the ground,\n"
    .string "it coats its body with a slimy, poisonous\n"
    .string "film.$"

Text_8449AD6:: @ 8449AD6
    .string "$"

Text_8449AD7:: @ 8449AD7
    .string "Due to its relaxed and carefree attitude,\n"
    .string "it often bumps its head on boulders and\n"
    .string "boat hulls as it swims.$"

Text_8449B41:: @ 8449B41
    .string "$"

Text_8449B42:: @ 8449B42
    .string "By reading air currents, it can predict\n"
    .string "things such as the weather or its foe’s\n"
    .string "next move.$"

Text_8449B9D:: @ 8449B9D
    .string "$"

Text_8449B9E:: @ 8449B9E
    .string "When darkness falls, the rings on its body\n"
    .string "begin to glow, striking fear in the hearts\n"
    .string "of anyone nearby.$"

Text_8449C06:: @ 8449C06
    .string "$"

Text_8449C07:: @ 8449C07
    .string "It is said that when chased, it lures its\n"
    .string "attacker onto dark mountain trails where\n"
    .string "the foe will get lost.$"

Text_8449C71:: @ 8449C71
    .string "$"

Text_8449C72:: @ 8449C72
    .string "When its head was bitten, toxins entered\n"
    .string "SLOWPOKE’s head and unlocked an\n"
    .string "extraordinary power.$"

Text_8449CD0:: @ 8449CD0
    .string "$"

Text_8449CD1:: @ 8449CD1
    .string "It loves to bite and yank people’s hair\n"
    .string "from behind without warning, just to see\n"
    .string "their shocked reactions.$"

Text_8449D3B:: @ 8449D3B
    .string "$"

Text_8449D3C:: @ 8449D3C
    .string "Its flat, thin body is always stuck on\n"
    .string "walls. Its shape appears to have some\n"
    .string "meaning.$"

Text_8449D92:: @ 8449D92
    .string "$"

Text_8449D93:: @ 8449D93
    .string "To keep its pitch-black tail hidden, it\n"
    .string "lives quietly in the darkness. It is never\n"
    .string "first to attack.$"

Text_8449DF7:: @ 8449DF7
    .string "$"

Text_8449DF8:: @ 8449DF8
    .string "Its tail, which also contains a small\n"
    .string "brain, may bite on its own if it notices an\n"
    .string "alluring smell.$"

Text_8449E5A:: @ 8449E5A
    .string "$"

Text_8449E5B:: @ 8449E5B
    .string "It hangs and waits for flying-insect prey\n"
    .string "to come near. It does not move about\n"
    .string "much on its own.$"

Text_8449EBB:: @ 8449EBB
    .string "$"

Text_8449EBC:: @ 8449EBC
    .string "It remains immovably rooted to its tree.\n"
    .string "It scatters pieces of its hard shell to\n"
    .string "drive its enemies away.$"

Text_8449F25:: @ 8449F25
    .string "$"

Text_8449F26:: @ 8449F26
    .string "If spotted, it escapes by burrowing with\n"
    .string "its tail. It can hover just slightly using\n"
    .string "its wings.$"

Text_8449F85:: @ 8449F85
    .string "$"

Text_8449F86:: @ 8449F86
    .string "It usually clings to cliffs. When it spots\n"
    .string "its prey, it spreads its wings and glides\n"
    .string "down to attack.$"

Text_8449FEB:: @ 8449FEB
    .string "$"

Text_8449FEC:: @ 8449FEC
    .string "It is said that if an ONIX lives for over\n"
    .string "100 years, its composition changes to\n"
    .string "become diamond-like.$"

Text_844A051:: @ 844A051
    .string "$"

Text_844A052:: @ 844A052
    .string "It has an active, playful nature. Many\n"
    .string "women like to frolic with it because of\n"
    .string "its affectionate ways.$"

Text_844A0B8:: @ 844A0B8
    .string "$"

Text_844A0B9:: @ 844A0B9
    .string "Because its fangs are too heavy, it\n"
    .string "always keeps its head tilted down.\n"
    .string "However, its BITE is powerful.$"

Text_844A11F:: @ 844A11F
    .string "$"

Text_844A120:: @ 844A120
    .string "The small spikes covering its body\n"
    .string "developed from scales. They inject a\n"
    .string "toxin that causes fainting.$"

Text_844A184:: @ 844A184
    .string "$"

Text_844A185:: @ 844A185
    .string "Its wings are not used for flying.\n"
    .string "They are flapped at high speed to adjust\n"
    .string "its body temperature.$"

Text_844A1E7:: @ 844A1E7
    .string "$"

Text_844A1E8:: @ 844A1E8
    .string "It stores BERRIES inside its shell.\n"
    .string "To avoid attacks, it hides beneath rocks\n"
    .string "and remains completely still.$"

Text_844A253:: @ 844A253
    .string "$"

Text_844A254:: @ 844A254
    .string "Usually docile, but if disturbed while\n"
    .string "sipping honey, it chases off the intruder\n"
    .string "with its horn.$"

Text_844A2B4:: @ 844A2B4
    .string "$"

Text_844A2B5:: @ 844A2B5
    .string "Vicious in nature, it drives PIDGEY from\n"
    .string "their nests and feasts on the eggs that\n"
    .string "are left behind.$"

Text_844A317:: @ 844A317
    .string "$"

Text_844A318:: @ 844A318
    .string "Before food becomes scarce in wintertime,\n"
    .string "its habit is to hoard food in many hidden\n"
    .string "locations.$"

Text_844A377:: @ 844A377
    .string "$"

Text_844A378:: @ 844A378
    .string "With its ability to distinguish any smell,\n"
    .string "it unfailingly finds all food buried deep\n"
    .string "underground.$"

Text_844A3DA:: @ 844A3DA
    .string "$"

Text_844A3DB:: @ 844A3DB
    .string "A common sight in volcanic areas, it\n"
    .string "slowly slithers around in a constant\n"
    .string "search for warm places.$"

Text_844A43D:: @ 844A43D
    .string "$"

Text_844A43E:: @ 844A43E
    .string "Its brittle shell occasionally spouts\n"
    .string "intense flames that circulate throughout\n"
    .string "its body.$"

Text_844A497:: @ 844A497
    .string "$"

Text_844A498:: @ 844A498
    .string "If it smells something enticing, it dashes\n"
    .string "off headlong to find the source of the\n"
    .string "aroma.$"

Text_844A4F1:: @ 844A4F1
    .string "$"

Text_844A4F2:: @ 844A4F2
    .string "If it charges at an enemy, the hairs on\n"
    .string "its back stand up straight. It is very\n"
    .string "sensitive to sound.$"

Text_844A555:: @ 844A555
    .string "$"

Text_844A556:: @ 844A556
    .string "In a south sea nation, the people live in\n"
    .string "communities that are built on groups of\n"
    .string "these POKéMON.$"

Text_844A5B7:: @ 844A5B7
    .string "$"

Text_844A5B8:: @ 844A5B8
    .string "Using its dorsal fin as a suction pad, it\n"
    .string "clings to a MANTINE’s underside to\n"
    .string "scavenge for leftovers.$"

Text_844A61D:: @ 844A61D
    .string "$"

Text_844A61E:: @ 844A61E
    .string "It instinctively sneaks into rocky holes.\n"
    .string "If it gets sleepy, it steals the nest of a\n"
    .string "fellow OCTILLERY.$"

Text_844A685:: @ 844A685
    .string "$"

Text_844A686:: @ 844A686
    .string "It nests at the edge of sharp cliffs.\n"
    .string "It spends all day carrying food to its\n"
    .string "awaiting chicks.$"

Text_844A6E4:: @ 844A6E4
    .string "$"

Text_844A6E5:: @ 844A6E5
    .string "Swimming freely in open seas, it may fly\n"
    .string "out of the water and over the waves if it\n"
    .string "builds up enough speed.$"

Text_844A750:: @ 844A750
    .string "$"

Text_844A751:: @ 844A751
    .string "After nesting in bramble bushes, the wings\n"
    .string "of its chicks grow hard from scratches by\n"
    .string "thorns.$"

Text_844A7AE:: @ 844A7AE
    .string "$"

Text_844A7AF:: @ 844A7AF
    .string "To corner prey, they check each other’s\n"
    .string "location using barks that only they can\n"
    .string "understand.$"

Text_844A80B:: @ 844A80B
    .string "$"

Text_844A80C:: @ 844A80C
    .string "Upon hearing its eerie howls, other\n"
    .string "POKéMON get the shivers and head straight\n"
    .string "back to their nests.$"

Text_844A86F:: @ 844A86F
    .string "$"

Text_844A870:: @ 844A870
    .string "It sleeps deep on the ocean floor to\n"
    .string "build its energy. It is said to cause\n"
    .string "tornadoes as it wakes.$"

Text_844A8D2:: @ 844A8D2
    .string "$"

Text_844A8D3:: @ 844A8D3
    .string "As a sign of affection, it bumps with its\n"
    .string "snout. However, it is so strong, it may\n"
    .string "send you flying.$"

Text_844A936:: @ 844A936
    .string "$"

Text_844A937:: @ 844A937
    .string "The longer and bigger its tusks, the\n"
    .string "higher its rank in its herd. The tusks take\n"
    .string "a long time to grow.$"

Text_844A99D:: @ 844A99D
    .string "$"

Text_844A99E:: @ 844A99E
    .string "Further research enhanced its abilities.\n"
    .string "Sometimes, it may exhibit motions that\n"
    .string "were not programmed.$"

Text_844AA03:: @ 844AA03
    .string "$"

Text_844AA04:: @ 844AA04
    .string "Those who stare at its antlers will\n"
    .string "gradually lose control of their senses\n"
    .string "and be unable to stand.$"

Text_844AA67:: @ 844AA67
    .string "$"

Text_844AA68:: @ 844AA68
    .string "Once it becomes an adult, it has a\n"
    .string "tendency to let its comrades plant\n"
    .string "footprints on its back.$"

Text_844AAC6:: @ 844AAC6
    .string "$"

Text_844AAC7:: @ 844AAC7
    .string "Even though it is small, it can’t be\n"
    .string "ignored because it will slug any handy\n"
    .string "target without warning.$"

Text_844AB2B:: @ 844AB2B
    .string "$"

Text_844AB2C:: @ 844AB2C
    .string "It launches kicks while spinning. If it\n"
    .string "spins at high speed, it may bore its way\n"
    .string "into the ground.$"

Text_844AB8E:: @ 844AB8E
    .string "$"

Text_844AB8F:: @ 844AB8F
    .string "It always rocks its head slowly backwards\n"
    .string "and forwards as if it is trying to kiss\n"
    .string "someone.$"

Text_844ABEA:: @ 844ABEA
    .string "$"

Text_844ABEB:: @ 844ABEB
    .string "Even in the most vicious storm, this\n"
    .string "POKéMON plays happily if thunder rumbles\n"
    .string "in the sky.$"

Text_844AC45:: @ 844AC45
    .string "$"

Text_844AC46:: @ 844AC46
    .string "It is found in volcanic craters. Its body\n"
    .string "heat exceeds 1,100 degrees Fahrenheit,\n"
    .string "so don’t underestimate it.$"

Text_844ACB2:: @ 844ACB2
    .string "$"

Text_844ACB3:: @ 844ACB3
    .string "If it has just had a baby, the milk it\n"
    .string "produces contains much more nutrition than\n"
    .string "usual.$"

Text_844AD0C:: @ 844AD0C
    .string "$"

Text_844AD0D:: @ 844AD0D
    .string "It has a very compassionate nature. If it\n"
    .string "sees a sick POKéMON, it will nurse the\n"
    .string "sufferer back to health.$"

Text_844AD77:: @ 844AD77
    .string "$"

Text_844AD78:: @ 844AD78
    .string "This POKéMON races across the\n"
    .string "land while barking a cry that sounds\n"
    .string "like crashing thunder.$"

Text_844ADD2:: @ 844ADD2
    .string "$"

Text_844ADD3:: @ 844ADD3
    .string "A POKéMON that races across the land.\n"
    .string "It is said that one is born every time a\n"
    .string "new volcano appears.$"

Text_844AE37:: @ 844AE37
    .string "$"

Text_844AE38:: @ 844AE38
    .string "This POKéMON races across the land.\n"
    .string "It is said that north winds will somehow\n"
    .string "blow whenever it appears.$"

Text_844AE9F:: @ 844AE9F
    .string "$"

Text_844AEA0:: @ 844AEA0
    .string "It is born deep underground. It can’t\n"
    .string "emerge until it has entirely consumed the\n"
    .string "soil around it.$"

Text_844AF00:: @ 844AF00
    .string "$"

Text_844AF01:: @ 844AF01
    .string "Even sealed in its shell, it can move\n"
    .string "freely. Hard and fast, it has outstanding\n"
    .string "destructive power.$"

Text_844AF64:: @ 844AF64
    .string "$"

Text_844AF65:: @ 844AF65
.ifeq (REVISION - 0)
    .string "Its body can’t be harmed by any sort of\n"
    .string "attack, so it is very eager to make\n"
    .string "challenges against enemies.$"
.else
    .string "It has an impudent nature. Having great\n"
    .string "strength, it can even change surrounding\n"
    .string "landforms.$"
.endif

Text_844AFCD:: @ 844AFCD
    .string "$"

Text_844AFCE:: @ 844AFCE
    .string "It is said to be the guardian of the seas.\n"
    .string "It is rumored to have been seen on the\n"
    .string "night of a storm.$"

Text_844B032:: @ 844B032
    .string "$"

Text_844B033:: @ 844B033
    .string "A legend says that its body glows in\n"
    .string "seven colors. A rainbow is said to form\n"
    .string "behind it when it flies.$"

Text_844B099:: @ 844B099
    .string "$"

Text_844B09A:: @ 844B09A
    .string "When CELEBI disappears deep in a forest,\n"
    .string "it is said to leave behind an egg it\n"
    .string "brought from the future.$"

Text_844B101:: @ 844B101
    .string "$"

Text_844B102:: @ 844B102
    .string "It quickly scales even vertical walls.\n"
    .string "It senses humidity with its tail to predict\n"
    .string "the next day’s weather.$"

Text_844B16D:: @ 844B16D
    .string "$"

Text_844B16E:: @ 844B16E
    .string "Its strongly developed thigh muscles\n"
    .string "give it astounding agility and jumping\n"
    .string "performance.$"

Text_844B1C7:: @ 844B1C7
    .string "$"

Text_844B1C8:: @ 844B1C8
    .string "The leaves on its forelegs are as sharp\n"
    .string "as swords. It agilely leaps about the\n"
    .string "branches of trees to strike.$"

Text_844B233:: @ 844B233
    .string "$"

Text_844B234:: @ 844B234
    .string "It has a flame sac inside its belly that\n"
    .string "perpetually burns. It feels warm if it is\n"
    .string "hugged.$"

Text_844B28F:: @ 844B28F
    .string "$"

Text_844B290:: @ 844B290
    .string "It boosts its concentration by emitting\n"
    .string "harsh cries. Its kicks have outstanding\n"
    .string "destructive power.$"

Text_844B2F3:: @ 844B2F3
    .string "$"

Text_844B2F4:: @ 844B2F4
    .string "When facing a tough foe, it looses flames\n"
    .string "from its wrists. Its powerful legs let it\n"
    .string "jump clear over buildings.$"

Text_844B363:: @ 844B363
    .string "$"

Text_844B364:: @ 844B364
    .string "Its large tail fin propels it through\n"
    .string "water with powerful acceleration. It is\n"
    .string "strong in spite of its size.$"

Text_844B3CF:: @ 844B3CF
    .string "$"

Text_844B3D0:: @ 844B3D0
    .string "It is at its best when on muddy ground\n"
    .string "with poor footing. It quickly overwhelms\n"
    .string "foes struggling in mud.$"

Text_844B438:: @ 844B438
    .string "$"

Text_844B439:: @ 844B439
    .string "Its arms are rock-hard. With one swing,\n"
    .string "they can batter down its foe. It makes its\n"
    .string "nest on beautiful beaches.$"

Text_844B4A7:: @ 844B4A7
    .string "$"

Text_844B4A8:: @ 844B4A8
    .string "It has a very tenacious nature. Its acute\n"
    .string "sense of smell lets it chase a chosen\n"
    .string "prey without ever losing track.$"

Text_844B518:: @ 844B518
    .string "$"

Text_844B519:: @ 844B519
    .string "It will always obey the commands of a\n"
    .string "skilled TRAINER. Its behavior arises from\n"
    .string "its living in packs in ancient times.$"

Text_844B58F:: @ 844B58F
    .string "$"

Text_844B590:: @ 844B590
    .string "A POKéMON with abundant curiosity.\n"
    .string "It shows an interest in everything, so it\n"
    .string "always zigs and zags.$"

Text_844B5F3:: @ 844B5F3
    .string "$"

Text_844B5F4:: @ 844B5F4
    .string "When running in a straight line, it can top\n"
    .string "60 miles per hour. However, it has a\n"
    .string "tough time with curved roads.$"

Text_844B663:: @ 844B663
    .string "$"

Text_844B664:: @ 844B664
    .string "It lives amidst tall grass and in forests.\n"
    .string "When attacked, it resists by pointing its\n"
    .string "venomous spikes at the foe.$"

Text_844B6D5:: @ 844B6D5
    .string "$"

Text_844B6D6:: @ 844B6D6
    .string "It conserves its energy by moving as\n"
    .string "little as possible. It awaits evolution\n"
    .string "while drinking only a little rainwater.$"

Text_844B74B:: @ 844B74B
    .string "$"

Text_844B74C:: @ 844B74C
    .string "Despite its appearance, it has an\n"
    .string "aggressive nature. It attacks by jabbing\n"
    .string "with its long, thin mouth.$"

Text_844B7B2:: @ 844B7B2
    .string "$"

Text_844B7B3:: @ 844B7B3
    .string "Its body, which is made of soft silk,\n"
    .string "hardens over time. When cracks appear,\n"
    .string "evolution is near.$"

Text_844B813:: @ 844B813
    .string "$"

Text_844B814:: @ 844B814
    .string "It scatters horribly toxic dust when it\n"
    .string "senses danger. They tend to gather in the\n"
    .string "glow of streetlamps at night.$"

Text_844B884:: @ 844B884
    .string "$"

Text_844B885:: @ 844B885
    .string "It searches about for clean water. If it\n"
    .string "does not drink water for too long, the\n"
    .string "leaf on its head wilts.$"

Text_844B8ED:: @ 844B8ED
    .string "$"

Text_844B8EE:: @ 844B8EE
    .string "It lives at the water’s edge where it is\n"
    .string "sunny. It sleeps on a bed of water grass\n"
    .string "by day and becomes active at night.$"

Text_844B964:: @ 844B964
    .string "$"

Text_844B965:: @ 844B965
    .string "The rhythm of bright, festive music\n"
    .string "activates LUDICOLO’s cells, making it more\n"
    .string "powerful.$"

Text_844B9BE:: @ 844B9BE
    .string "$"

Text_844B9BF:: @ 844B9BF
    .string "If it remains still, it becomes impossible\n"
    .string "to distinguish from real nuts. It delights\n"
    .string "in surprising foraging PIDGEY.$"

Text_844BA34:: @ 844BA34
    .string "$"

Text_844BA35:: @ 844BA35
    .string "They live in holes bored in large trees.\n"
    .string "The sound of NUZLEAF’s grass flute fills\n"
    .string "listeners with dread.$"

Text_844BA9D:: @ 844BA9D
    .string "$"

Text_844BA9E:: @ 844BA9E
    .string "A POKéMON that was feared as a forest\n"
    .string "guardian. It can read the foe’s mind and\n"
    .string "take preemptive action.$"

Text_844BB05:: @ 844BB05
    .string "$"

Text_844BB06:: @ 844BB06
    .string "It dislikes cold seasons. They migrate to\n"
    .string "other lands in search of warmth, flying\n"
    .string "over 180 miles a day.$"

Text_844BB6E:: @ 844BB6E
    .string "$"

Text_844BB6F:: @ 844BB6F
    .string "If its two tail feathers are standing at\n"
    .string "attention, it is proof of good health.\n"
    .string "It soars elegantly in the sky.$"

Text_844BBDE:: @ 844BBDE
    .string "$"

Text_844BBDF:: @ 844BBDF
    .string "It rides upon ocean winds as if it were\n"
    .string "a glider. In the winter, it hides food\n"
    .string "around its nest.$"

Text_844BC3F:: @ 844BC3F
    .string "$"

Text_844BC40:: @ 844BC40
    .string "It is a flying transporter that carries\n"
    .string "small POKéMON in its beak. It bobs on the\n"
    .string "waves to rest its wings.$"

Text_844BCAB:: @ 844BCAB
    .string "$"

Text_844BCAC:: @ 844BCAC
    .string "It is highly attuned to the emotions of\n"
    .string "people and POKéMON. It hides if it senses\n"
    .string "hostility.$"

Text_844BD09:: @ 844BD09
    .string "$"

Text_844BD0A:: @ 844BD0A
    .string "The cheerful spirit of its TRAINER gives\n"
    .string "it energy for its psychokinetic power.\n"
    .string "It spins and dances when happy.$"

Text_844BD7A:: @ 844BD7A
    .string "$"

Text_844BD7B:: @ 844BD7B
    .string "It has the power to predict the future.\n"
    .string "Its power peaks when it is protecting its\n"
    .string "TRAINER.$"

Text_844BDD6:: @ 844BDD6
    .string "$"

Text_844BDD7:: @ 844BDD7
    .string "They usually live on ponds, but after an\n"
    .string "evening shower, they may appear on\n"
    .string "puddles in towns.$"

Text_844BE35:: @ 844BE35
    .string "$"

Text_844BE36:: @ 844BE36
    .string "The antennae have distinctive patterns\n"
    .string "that look like eyes. When it rains, they\n"
    .string "grow heavy, making flight impossible.$"

Text_844BEAC:: @ 844BEAC
    .string "$"

Text_844BEAD:: @ 844BEAD
    .string "It prefers damp places. By day it remains\n"
    .string "still in the forest shade. It releases\n"
    .string "toxic powder from its head.$"

Text_844BF1A:: @ 844BF1A
    .string "$"

Text_844BF1B:: @ 844BF1B
    .string "The seeds on its tail are made of toxic\n"
    .string "spores. It knocks out foes with quick,\n"
    .string "virtually invisible punches.$"

Text_844BF87:: @ 844BF87
    .string "$"

Text_844BF88:: @ 844BF88
    .string "It sleeps for 20 hours every day. Making\n"
    .string "drowsy those that see it is one of\n"
    .string "its abilities.$"

Text_844BFE3:: @ 844BFE3
    .string "$"

Text_844BFE4:: @ 844BFE4
    .string "It is always hungry because it won’t stop\n"
    .string "rampaging. Even while it is eating, it\n"
    .string "can’t keep still.$"

Text_844C047:: @ 844C047
    .string "$"

Text_844C048:: @ 844C048
    .string "It is the world’s most slothful POKéMON.\n"
    .string "However, it can exert horrifying power by\n"
    .string "releasing pent-up energy all at once.$"

Text_844C0C1:: @ 844C0C1
    .string "$"

Text_844C0C2:: @ 844C0C2
    .string "Because it lived almost entirely\n"
    .string "underground, it is nearly blind.\n"
    .string "It uses its antennae instead.$"

Text_844C122:: @ 844C122
    .string "$"

Text_844C123:: @ 844C123
    .string "This POKéMON is so quick, it is said to\n"
    .string "be able to avoid any attack. It loves to\n"
    .string "feed on tree sap.$"

Text_844C186:: @ 844C186
    .string "$"

Text_844C187:: @ 844C187
    .string "A most peculiar POKéMON that somehow\n"
    .string "appears in a POKé BALL when a NINCADA\n"
    .string "evolves.$"

Text_844C1DB:: @ 844C1DB
    .string "$"

Text_844C1DC:: @ 844C1DC
    .string "It usually murmurs, but starts crying\n"
    .string "loudly if it senses danger. It stops when\n"
    .string "its ear covers are shut.$"

Text_844C245:: @ 844C245
    .string "$"

Text_844C246:: @ 844C246
    .string "When it stamps its feet and bellows, it\n"
    .string "generates ultrasonic waves that can blow\n"
    .string "apart a house.$"

Text_844C2A6:: @ 844C2A6
    .string "$"

Text_844C2A7:: @ 844C2A7
    .string "It emits a variety of sounds from the \n"
    .string "holes all over its body. Its loud cries\n"
    .string "can be heard from over six miles away.$"

Text_844C31D:: @ 844C31D
    .string "$"

Text_844C31E:: @ 844C31E
    .string "It grows stronger by enduring harsh\n"
    .string "training. It is a gutsy POKéMON that can\n"
    .string "withstand any attack.$"

Text_844C381:: @ 844C381
    .string "$"

Text_844C382:: @ 844C382
    .string "It stomps on the ground to build power.\n"
    .string "It can send a 10-ton truck flying with a\n"
    .string "straight-arm punch.$"

Text_844C3E7:: @ 844C3E7
    .string "$"

Text_844C3E8:: @ 844C3E8
    .string "It battles by flinging around its tail,\n"
    .string "which is bigger than its body. The\n"
    .string "tail is a flotation device in water.$"

Text_844C458:: @ 844C458
    .string "$"

Text_844C459:: @ 844C459
    .string "Its magnetic nose consistently faces\n"
    .string "north. Travelers check NOSEPASS to get\n"
    .string "their bearings.$"

Text_844C4B5:: @ 844C4B5
    .string "$"

Text_844C4B6:: @ 844C4B6
    .string "It is said to be difficult to earn its\n"
    .string "trust. However, it is extremely popular\n"
    .string "for its cute looks and behavior.$"

Text_844C526:: @ 844C526
    .string "$"

Text_844C527:: @ 844C527
    .string "The favorite of trend-conscious\n"
    .string "female TRAINERS, they are used in\n"
    .string "competition for their style and fur.$"

Text_844C58E:: @ 844C58E
    .string "$"

Text_844C58F:: @ 844C58F
    .string "It feeds on gemstone crystals.\n"
    .string "In darkness, its eyes sparkle with the\n"
    .string "glitter of jewels.$"

Text_844C5E8:: @ 844C5E8
    .string "$"

Text_844C5E9:: @ 844C5E9
    .string "It uses its docile-looking face to lull\n"
    .string "foes into complacency, then bites with its\n"
    .string "huge, relentless jaws.$"

Text_844C653:: @ 844C653
    .string "$"

Text_844C654:: @ 844C654
    .string "It eats iron to build its steel body.\n"
    .string "It is a pest that descends from mountains\n"
    .string "to eat bridges and train tracks.$"

Text_844C6C5:: @ 844C6C5
    .string "$"

Text_844C6C6:: @ 844C6C6
    .string "It habitually shows off its strength with\n"
    .string "the size of sparks it creates by ramming\n"
    .string "its steel body into boulders.$"

Text_844C737:: @ 844C737
    .string "$"

Text_844C738:: @ 844C738
    .string "It claims a large mountain as its sole\n"
    .string "territory. It mercilessly thrashes those\n"
    .string "that violate its space.$"

Text_844C7A0:: @ 844C7A0
    .string "$"

Text_844C7A1:: @ 844C7A1
    .string "It never skips its daily yoga training.\n"
    .string "It heightens its inner strength through\n"
    .string "meditation.$"

Text_844C7FD:: @ 844C7FD
    .string "$"

Text_844C7FE:: @ 844C7FE
    .string "It elegantly avoids attacks with dance-\n"
    .string "like steps, then launches a devastating\n"
    .string "blow in the same motion.$"

Text_844C867:: @ 844C867
    .string "$"

Text_844C868:: @ 844C868
    .string "It stores static electricity in its fur\n"
    .string "for discharging. It gives off sparks if a\n"
    .string "storm approaches.$"

Text_844C8CC:: @ 844C8CC
    .string "$"

Text_844C8CD:: @ 844C8CD
    .string "It rarely appears before people.\n"
    .string "It is said to nest where lightning has\n"
    .string "fallen.$"

Text_844C91D:: @ 844C91D
    .string "$"

Text_844C91E:: @ 844C91E
    .string "It cheers on partners while scattering\n"
    .string "sparks from its body. It climbs telephone\n"
    .string "poles to absorb electricity.$"

Text_844C98C:: @ 844C98C
    .string "$"

Text_844C98D:: @ 844C98D
    .string "Its dislike of water makes it take shelter\n"
    .string "under the eaves of houses in rain. It uses\n"
    .string "pom-poms made of sparks for cheering.$"

Text_844CA09:: @ 844CA09
    .string "$"

Text_844CA0A:: @ 844CA0A
    .string "It lives around clean ponds. At night,\n"
    .string "its rear lights up. It converses with\n"
    .string "others by flashing its light.$"

Text_844CA75:: @ 844CA75
    .string "$"

Text_844CA76:: @ 844CA76
    .string "It guides VOLBEAT to draw signs in night\n"
    .string "skies. There are scientists that study the\n"
    .string "patterns it creates.$"

Text_844CADF:: @ 844CADF
    .string "$"

Text_844CAE0:: @ 844CAE0
    .string "Its flowers give off a relaxing fragrance.\n"
    .string "The stronger its aroma, the healthier\n"
    .string "the ROSELIA is.$"

Text_844CB41:: @ 844CB41
    .string "$"

Text_844CB42:: @ 844CB42
    .string "There is nothing its stomach can’t digest.\n"
    .string "While it is digesting, vile, overpowering\n"
    .string "gases are expelled.$"

Text_844CBAB:: @ 844CBAB
    .string "$"

Text_844CBAC:: @ 844CBAC
    .string "It can swallow a tire whole in one gulp.\n"
    .string "It secretes a horribly toxic fluid from\n"
    .string "the pores on its body.$"

Text_844CC14:: @ 844CC14
    .string "$"

Text_844CC15:: @ 844CC15
    .string "It lives in massive rivers that course\n"
    .string "through jungles. It swarms prey that\n"
    .string "enter its territory.$"

Text_844CC76:: @ 844CC76
    .string "$"

Text_844CC77:: @ 844CC77
    .string "The ruffian of the seas, it has fangs that\n"
    .string "crunch through iron. It swims by jetting\n"
    .string "water from its rear.$"

Text_844CCE0:: @ 844CCE0
    .string "$"

Text_844CCE1:: @ 844CCE1
    .string "When it sucks in a large volume of\n"
    .string "seawater, it becomes like a big, bouncy\n"
    .string "ball. It eats a ton of food daily.$"

Text_844CD4F:: @ 844CD4F
    .string "$"

Text_844CD50:: @ 844CD50
    .string "It is among the largest of all POKéMON.\n"
    .string "It herds prey in a pack then swallows the\n"
    .string "massed prey in one gulp.$"

Text_844CDBB:: @ 844CDBB
    .string "$"

Text_844CDBC:: @ 844CDBC
    .string "Magma of almost 2,200 degrees Fahrenheit\n"
    .string "courses through its body. When it grows\n"
    .string "cold, the magma hardens and slows it.$"

Text_844CE33:: @ 844CE33
    .string "$"

Text_844CE34:: @ 844CE34
    .string "If angered, the humps on its back erupt\n"
    .string "in a shower of molten lava. It lives in\n"
    .string "the craters of volcanoes.$"

Text_844CE9E:: @ 844CE9E
    .string "$"

Text_844CE9F:: @ 844CE9F
    .string "It burns coal inside its shell. If it is\n"
    .string "attacked, it belches thick, black smoke\n"
    .string "and flees.$"

Text_844CEFB:: @ 844CEFB
    .string "$"

Text_844CEFC:: @ 844CEFC
    .string "It apparently dies if it stops bouncing\n"
    .string "about. It carries a pearl from CLAMPERL\n"
    .string "on its head.$"

Text_844CF59:: @ 844CF59
    .string "$"

Text_844CF5A:: @ 844CF5A
    .string "It can gain control over foes by doing\n"
    .string "odd dance steps. The black pearls on its\n"
    .string "forehead are precious gems.$"

Text_844CFC6:: @ 844CFC6
    .string "$"

Text_844CFC7:: @ 844CFC7
    .string "No two SPINDA are said to have identical\n"
    .string "patterns. It confuses foes with its\n"
    .string "stumbling motions.$"

Text_844D027:: @ 844D027
    .string "$"

Text_844D028:: @ 844D028
    .string "It lives in arid deserts. It makes a\n"
    .string "sloping pit trap in sand where it\n"
    .string "patiently awaits prey.$"

Text_844D086:: @ 844D086
    .string "$"

Text_844D087:: @ 844D087
    .string "It generates ultrasonic waves by violently\n"
    .string "flapping its wings. After making its prey\n"
    .string "faint, it melts the prey with acid.$"

Text_844D100:: @ 844D100
    .string "$"

Text_844D101:: @ 844D101
    .string "It hides itself by kicking up desert sand\n"
    .string "with its wings. Red covers shield its eyes\n"
    .string "from sand.$"

Text_844D161:: @ 844D161
    .string "$"

Text_844D162:: @ 844D162
    .string "It prefers harsh environments such as\n"
    .string "deserts. It can survive for 30 days on\n"
    .string "water stored in its body.$"

Text_844D1C9:: @ 844D1C9
    .string "$"

Text_844D1CA:: @ 844D1CA
    .string "It lives in deserts. It becomes active at\n"
    .string "night when it hunts for prey exhausted\n"
    .string "from the desert’s heat.$"

Text_844D233:: @ 844D233
    .string "$"

Text_844D234:: @ 844D234
    .string "It constantly grooms its cotton-like\n"
    .string "wings. It takes a shower to clean\n"
    .string "itself if it becomes dirty.$"

Text_844D297:: @ 844D297
    .string "$"

Text_844D298:: @ 844D298
    .string "If you hear a beautiful melody trilling\n"
    .string "deep among mountains far from people,\n"
    .string "it is ALTARIA’s humming.$"

Text_844D2FF:: @ 844D2FF
    .string "$"

Text_844D300:: @ 844D300
    .string "If it comes across a SEVIPER, its fur\n"
    .string "bristles and it assumes its battle pose.\n"
    .string "Its sharp claws are its best weapon.$"

Text_844D374:: @ 844D374
    .string "$"

Text_844D375:: @ 844D375
    .string "It sharpens its swordlike tail on hard\n"
    .string "rocks. It hides in tall grass and strikes\n"
    .string "unwary prey with venomous fangs.$"

Text_844D3E7:: @ 844D3E7
    .string "$"

Text_844D3E8:: @ 844D3E8
    .string "Its health ebbs and flows with the lunar\n"
    .string "cycle. It brims with power when exposed\n"
    .string "to the light of the full moon.$"

Text_844D458:: @ 844D458
    .string "$"

Text_844D459:: @ 844D459
    .string "It absorbs solar energy during the day.\n"
    .string "Always expressionless, it can sense what\n"
    .string "its foe is thinking.$"

Text_844D4BF:: @ 844D4BF
    .string "$"

Text_844D4C0:: @ 844D4C0
    .string "It probes muddy riverbeds with its two\n"
    .string "long whiskers. A slimy film protects its\n"
    .string "body.$"

Text_844D516:: @ 844D516
    .string "$"

Text_844D517:: @ 844D517
    .string "It makes its nest at the bottom of \n"
    .string "swamps. It will eat anything - if it is\n"
    .string "alive, WHISCASH will eat it.$"

Text_844D580:: @ 844D580
    .string "$"

Text_844D581:: @ 844D581
    .string "It came from overseas. It is a very hardy\n"
    .string "creature that will quickly proliferate,\n"
    .string "even in polluted streams.$"

Text_844D5ED:: @ 844D5ED
    .string "$"

Text_844D5EE:: @ 844D5EE
    .string "A rough customer that wildly flails its\n"
    .string "giant claws. It is said to be extremely\n"
    .string "hard to raise.$"

Text_844D64D:: @ 844D64D
    .string "$"

Text_844D64E:: @ 844D64E
    .string "It was discovered in ancient ruins.\n"
    .string "While moving, it constantly spins. It\n"
    .string "stands on one foot even when asleep.$"

Text_844D6BD:: @ 844D6BD
    .string "$"

Text_844D6BE:: @ 844D6BE
    .string "It appears to have been born from clay\n"
    .string "dolls made by ancient people. It uses\n"
    .string "telekinesis to float and move.$"

Text_844D72A:: @ 844D72A
    .string "$"

Text_844D72B:: @ 844D72B
    .string "It became extinct roughly 100 million\n"
    .string "years ago. It was regenerated from a\n"
    .string "fossil using advanced techniques.$"

Text_844D798:: @ 844D798
    .string "$"

Text_844D799:: @ 844D799
    .string "It ensnares prey with its eight tentacles.\n"
    .string "It then melts the prey with a strong acid\n"
    .string "before feeding.$"

Text_844D7FE:: @ 844D7FE
    .string "$"

Text_844D7FF:: @ 844D7FF
    .string "It is a kind of POKéMON progenitor.\n"
    .string "It uses its extending claws to catch prey\n"
    .string "hiding among rocks on the seafloor.$"

Text_844D871:: @ 844D871
    .string "$"

Text_844D872:: @ 844D872
    .string "Protected by a hard shell, its body is\n"
    .string "very sturdy. It skewers prey with its\n"
    .string "claws to feed.$"

Text_844D8CE:: @ 844D8CE
    .string "$"

Text_844D8CF:: @ 844D8CF
    .string "Ridiculed for its shabby appearance,\n"
    .string "it is ignored by researchers. It lives in\n"
    .string "ponds choked with weeds.$"

Text_844D937:: @ 844D937
    .string "$"

Text_844D938:: @ 844D938
    .string "MILOTIC is breathtakingly beautiful.\n"
    .string "Those that see it are said to forget their\n"
    .string "combative spirits.$"

Text_844D99B:: @ 844D99B
    .string "$"

Text_844D99C:: @ 844D99C
    .string "It has the ability to change its form into\n"
    .string "the sun, the rain, or a snow cloud, \n"
    .string "depending on the weather.$"

Text_844DA06:: @ 844DA06
    .string "$"

Text_844DA07:: @ 844DA07
    .string "It changes body color to blend in with\n"
    .string "its surroundings. It also changes color if\n"
    .string "it is happy or sad.$"

Text_844DA6D:: @ 844DA6D
    .string "$"

Text_844DA6E:: @ 844DA6E
    .string "It loves to feed on feelings like envy and\n"
    .string "malice. Its upright horn catches the\n"
    .string "emotions of people.$"

Text_844DAD2:: @ 844DAD2
    .string "$"

Text_844DAD3:: @ 844DAD3
    .string "Strong feelings of hatred turned a puppet\n"
    .string "into a POKéMON. If it opens its mouth,\n"
    .string "its cursed energy escapes.$"

Text_844DB3F:: @ 844DB3F
    .string "$"

Text_844DB40:: @ 844DB40
    .string "Making itself invisible, it silently sneaks\n"
    .string "up to prey. It has the ability to slip\n"
    .string "through thick walls.$"

Text_844DBA8:: @ 844DBA8
    .string "$"

Text_844DBA9:: @ 844DBA9
    .string "Its body is entirely hollow. When it opens\n"
    .string "its mouth, it sucks everything in as if it\n"
    .string "were a black hole.$"

Text_844DC12:: @ 844DC12
    .string "$"

Text_844DC13:: @ 844DC13
    .string "It lives in tropical jungles. The bunch of\n"
    .string "fruit around its neck is delicious.\n"
    .string "The fruit grows twice a year.$"

Text_844DC80:: @ 844DC80
    .string "$"

Text_844DC81:: @ 844DC81
    .string "It travels by riding on winds. It cleverly\n"
    .string "uses its long tail to pluck nuts and\n"
    .string "berries, which it loves to eat.$"

Text_844DCF1:: @ 844DCF1
    .string "$"

Text_844DCF2:: @ 844DCF2
    .string "It appears when it senses an impending\n"
    .string "natural disaster. As a result, it was\n"
    .string "mistaken as a doom-bringer.$"

Text_844DD5B:: @ 844DD5B
    .string "$"

Text_844DD5C:: @ 844DD5C
    .string "It tends to move in a pack with others.\n"
    .string "They cluster in a tight group to sleep in\n"
    .string "a cave.$"

Text_844DDB6:: @ 844DDB6
    .string "$"

Text_844DDB7:: @ 844DDB7
    .string "It is said that a home visited by a\n"
    .string "SNORUNT will prosper. It can withstand\n"
    .string "cold of minus 150 degrees Fahrenheit.$"

Text_844DE28:: @ 844DE28
    .string "$"

Text_844DE29:: @ 844DE29
    .string "It has a body of ice that won’t melt,\n"
    .string "even with fire. It can instantly freeze\n"
    .string "moisture in the atmosphere.$"

Text_844DE93:: @ 844DE93
    .string "$"

Text_844DE94:: @ 844DE94
    .string "Its body is covered in fluffy fur. The\n"
    .string "fur keeps it from feeling cold while\n"
    .string "it is rolling on ice.$"

Text_844DEF6:: @ 844DEF6
    .string "$"

Text_844DEF7:: @ 844DEF7
    .string "It touches new things with its nose to\n"
    .string "test for smell and feel. It plays by\n"
    .string "spinning SPHEAL on its nose.$"

Text_844DF60:: @ 844DF60
    .string "$"

Text_844DF61:: @ 844DF61
    .string "It swims through icy seas while shattering\n"
    .string "ice floes with its large tusks. It is\n"
    .string "protected by its thick blubber.$"

Text_844DFD2:: @ 844DFD2
    .string "$"

Text_844DFD3:: @ 844DFD3
    .string "It is protected by a sturdy shell.\n"
    .string "Once in a lifetime, it makes a magnificent\n"
    .string "pearl.$"

Text_844E028:: @ 844E028
    .string "$"

Text_844E029:: @ 844E029
    .string "It lives deep in the sea where no light\n"
    .string "ever filters down. It lights up its small\n"
    .string "fishlike tail to attract prey.$"

Text_844E09A:: @ 844E09A
    .string "$"

Text_844E09B:: @ 844E09B
    .string "Its swimming form is exquisitely elegant.\n"
    .string "With its thin mouth, it feeds on seaweed\n"
    .string "that grows between rocks.$"

Text_844E108:: @ 844E108
    .string "$"

Text_844E109:: @ 844E109
    .string "It has remained unchanged for 100\n"
    .string "million years. It was discovered\n"
    .string "during a deep-sea exploration.$"

Text_844E16B:: @ 844E16B
    .string "$"

Text_844E16C:: @ 844E16C
    .string "During the spawning season, countless\n"
    .string "LUVDISC congregate at coral reefs,\n"
    .string "turning the waters pink.$"

Text_844E1CE:: @ 844E1CE
    .string "$"

Text_844E1CF:: @ 844E1CF
    .string "Its steel-hard head can shatter boulders.\n"
    .string "It longingly hopes for wings to grow so it\n"
    .string "can fly.$"

Text_844E22D:: @ 844E22D
    .string "$"

Text_844E22E:: @ 844E22E
    .string "Its armored body makes all attacks bounce\n"
    .string "off. The armor is too tough, however,\n"
    .string "making it heavy and somewhat sluggish.$"

Text_844E2A5:: @ 844E2A5
    .string "$"

Text_844E2A6:: @ 844E2A6
    .string "It becomes uncontrollable if it is\n"
    .string "enraged. It destroys everything with\n"
    .string "shredding claws and fire.$"

Text_844E308:: @ 844E308
    .string "$"

Text_844E309:: @ 844E309
    .string "It uses magnetic waves to converse with\n"
    .string "its kind. All the cells in its body are\n"
    .string "magnetic.$"

Text_844E363:: @ 844E363
    .string "$"

Text_844E364:: @ 844E364
    .string "It floats midair using magnetism. Its body\n"
    .string "is so tough, even a crash with a jet\n"
    .string "plane won’t leave a scratch.$"

Text_844E3D1:: @ 844E3D1
    .string "$"

Text_844E3D2:: @ 844E3D2
    .string "It is formed by two METANG fusing.\n"
    .string "Its four brains are said to be superior\n"
    .string "to a supercomputer.$"

Text_844E431:: @ 844E431
    .string "$"

Text_844E432:: @ 844E432
    .string "It is entirely composed of rocks with no\n"
    .string "sign of a brain or heart. It is a mystery\n"
    .string "even to modern scientists.$"

Text_844E4A0:: @ 844E4A0
    .string "$"

Text_844E4A1:: @ 844E4A1
    .string "Research revealed that its body is made\n"
    .string "of the same kind of ice that is found at\n"
    .string "the South Pole.$"

Text_844E502:: @ 844E502
    .string "$"

Text_844E503:: @ 844E503
    .string "It is sturdier than any kind of metal.\n"
    .string "It hardened due to pressure underground\n"
    .string "over tens of thousands of years.$"

Text_844E573:: @ 844E573
    .string "$"

Text_844E574:: @ 844E574
    .string "It can telepathically communicate with\n"
    .string "people. It changes its appearance using\n"
    .string "its down that refracts light.$"

Text_844E5E1:: @ 844E5E1
    .string "$"

Text_844E5E2:: @ 844E5E2
    .string "It has a docile temperament and dislikes\n"
    .string "fighting. Tucking in its forelegs, it can\n"
    .string "fly faster than a jet plane.$"

Text_844E652:: @ 844E652
    .string "$"

Text_844E653:: @ 844E653
    .string "This POKéMON is said to have\n"
    .string "expanded the sea by bringing heavy rains.\n"
    .string "It has the power to control water.$"

Text_844E6BD:: @ 844E6BD
    .string "$"

Text_844E6BE:: @ 844E6BE
    .string "This legendary POKéMON is said to\n"
    .string "represent the land. It went to sleep after\n"
    .string "dueling KYOGRE.$"

Text_844E71B:: @ 844E71B
    .string "$"

Text_844E71C:: @ 844E71C
    .string "It has lived for hundreds of millions of\n"
    .string "years in the ozone layer. Its flying form\n"
    .string "looks like a meteor.$"

Text_844E784:: @ 844E784
    .string "$"

Text_844E785:: @ 844E785
    .string "It is said to make any wish come true.\n"
    .string "It is awake for only seven days out of\n"
    .string "a thousand years.$"

Text_844E7E5:: @ 844E7E5
    .string "$"

Text_844E7E6:: @ 844E7E6
    .string "This DEOXYS has transformed into its\n"
    .string "aggressive guise. It can fool enemies by\n"
    .string "altering its appearance.$"

Text_844E84D:: @ 844E84D
    .string "$"

    .align 2
Data2:: @ 844E850
    @ 844E850
    .string "UNKNOWN$", 12
    .2byte 0 @ in decimeters
    .2byte 0 @ in hectograms
    .4byte Text_8444C35
    .4byte Text_8444CB1
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte 0
    .2byte 0 @ padding

    @ 844E874
    .string "SEED$", 12
    .2byte 7 @ in decimeters
    .2byte 69 @ in hectograms
    .4byte Text_8444CB2
    .4byte Text_8444D1B
    .2byte 0 @ unused
    .2byte 356
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E898
    .string "SEED$", 12
    .2byte 10 @ in decimeters
    .2byte 130 @ in hectograms
    .4byte Text_8444D1C
    .4byte Text_8444D8B
    .2byte 0 @ unused
    .2byte 332
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E8BC
    .string "SEED$", 12
    .2byte 20 @ in decimeters
    .2byte 1000 @ in hectograms
    .4byte Text_8444D8C
    .4byte Text_8444DE7
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding

    @ 844E8E0
    .string "LIZARD$", 12
    .2byte 6 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text_8444DE8
    .4byte Text_8444E58
    .2byte 0 @ unused
    .2byte 410
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E904
    .string "FLAME$", 12
    .2byte 11 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte Text_8444E59
    .4byte Text_8444EC5
    .2byte 0 @ unused
    .2byte 294
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E928
    .string "FLAME$", 12
    .2byte 17 @ in decimeters
    .2byte 905 @ in hectograms
    .4byte Text_8444EC6
    .4byte Text_8444F38
    .2byte 0 @ unused
    .2byte 271
    .2byte 0
    .2byte 317
    .2byte 3
    .2byte 0 @ padding

    @ 844E94C
    .string "TINY TURTLE$", 12
    .2byte 5 @ in decimeters
    .2byte 90 @ in hectograms
    .4byte Text_8444F39
    .4byte Text_8444F92
    .2byte 0 @ unused
    .2byte 412
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E970
    .string "TURTLE$", 12
    .2byte 10 @ in decimeters
    .2byte 225 @ in hectograms
    .4byte Text_8444F93
    .4byte Text_8444FED
    .2byte 0 @ unused
    .2byte 334
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E994
    .string "SHELLFISH$", 12
    .2byte 16 @ in decimeters
    .2byte 855 @ in hectograms
    .4byte Text_8444FEE
    .4byte Text_8445058
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 329
    .2byte 3
    .2byte 0 @ padding

    @ 844E9B8
    .string "WORM$", 12
    .2byte 3 @ in decimeters
    .2byte 29 @ in hectograms
    .4byte Text_8445059
    .4byte Text_84450CB
    .2byte 0 @ unused
    .2byte 549
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E9DC
    .string "COCOON$", 12
    .2byte 7 @ in decimeters
    .2byte 99 @ in hectograms
    .4byte Text_84450CC
    .4byte Text_8445137
    .2byte 0 @ unused
    .2byte 350
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA00
    .string "BUTTERFLY$", 12
    .2byte 11 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte Text_8445138
    .4byte Text_844519E
    .2byte 0 @ unused
    .2byte 312
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA24
    .string "HAIRY BUG$", 12
    .2byte 3 @ in decimeters
    .2byte 32 @ in hectograms
    .4byte Text_844519F
    .4byte Text_844520A
    .2byte 0 @ unused
    .2byte 455
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA48
    .string "COCOON$", 12
    .2byte 6 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte Text_844520B
    .4byte Text_844527A
    .2byte 0 @ unused
    .2byte 424
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA6C
    .string "POISON BEE$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte Text_844527B
    .4byte Text_84452E6
    .2byte 0 @ unused
    .2byte 366
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA90
    .string "TINY BIRD$", 12
    .2byte 3 @ in decimeters
    .2byte 18 @ in hectograms
    .4byte Text_84452E7
    .4byte Text_8445347
    .2byte 0 @ unused
    .2byte 492
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EAB4
    .string "BIRD$", 12
    .2byte 11 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text_8445348
    .4byte Text_84453B9
    .2byte 0 @ unused
    .2byte 334
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EAD8
    .string "BIRD$", 12
    .2byte 15 @ in decimeters
    .2byte 395 @ in hectograms
    .4byte Text_84453BA
    .4byte Text_8445422
    .2byte 0 @ unused
    .2byte 269
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EAFC
    .string "MOUSE$", 12
    .2byte 3 @ in decimeters
    .2byte 35 @ in hectograms
    .4byte Text_8445423
    .4byte Text_844548F
    .2byte 0 @ unused
    .2byte 481
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EB20
    .string "MOUSE$", 12
    .2byte 7 @ in decimeters
    .2byte 185 @ in hectograms
    .4byte Text_8445490
    .4byte Text_84454E8
    .2byte 0 @ unused
    .2byte 401
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EB44
    .string "TINY BIRD$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text_84454E9
    .4byte Text_8445552
    .2byte 0 @ unused
    .2byte 571
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EB68
    .string "BEAK$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte Text_8445553
    .4byte Text_84455C2
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 844EB8C
    .string "SNAKE$", 12
    .2byte 20 @ in decimeters
    .2byte 69 @ in hectograms
    .4byte Text_84455C3
    .4byte Text_844562F
    .2byte 0 @ unused
    .2byte 298
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EBB0
    .string "COBRA$", 12
    .2byte 35 @ in decimeters
    .2byte 650 @ in hectograms
    .4byte Text_8445630
    .4byte Text_84456A1
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 296
    .2byte 1
    .2byte 0 @ padding

    @ 844EBD4
    .string "MOUSE$", 12
    .2byte 4 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte Text_84456A2
    .4byte Text_844570A
    .2byte 0 @ unused
    .2byte 479
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EBF8
    .string "MOUSE$", 12
    .2byte 8 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text_844570B
    .4byte Text_844577B
    .2byte 0 @ unused
    .2byte 426
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EC1C
    .string "MOUSE$", 12
    .2byte 6 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text_844577C
    .4byte Text_84457DC
    .2byte 0 @ unused
    .2byte 370
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EC40
    .string "MOUSE$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte Text_84457DD
    .4byte Text_8445845
    .2byte 0 @ unused
    .2byte 341
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EC64
    .string "POISON PIN$", 12
    .2byte 4 @ in decimeters
    .2byte 70 @ in hectograms
    .4byte Text_8445846
    .4byte Text_84458B9
    .2byte 0 @ unused
    .2byte 488
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EC88
    .string "POISON PIN$", 12
    .2byte 8 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte Text_84458BA
    .4byte Text_844591F
    .2byte 0 @ unused
    .2byte 381
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844ECAC
    .string "DRILL$", 12
    .2byte 13 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text_8445920
    .4byte Text_8445988
    .2byte 0 @ unused
    .2byte 283
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844ECD0
    .string "POISON PIN$", 12
    .2byte 5 @ in decimeters
    .2byte 90 @ in hectograms
    .4byte Text_8445989
    .4byte Text_84459FC
    .2byte 0 @ unused
    .2byte 480
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844ECF4
    .string "POISON PIN$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte Text_84459FD
    .4byte Text_8445A63
    .2byte 0 @ unused
    .2byte 408
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844ED18
    .string "DRILL$", 12
    .2byte 14 @ in decimeters
    .2byte 620 @ in hectograms
    .4byte Text_8445A64
    .4byte Text_8445AD1
    .2byte 0 @ unused
    .2byte 304
    .2byte 3
    .2byte 323
    .2byte 2
    .2byte 0 @ padding

    @ 844ED3C
    .string "FAIRY$", 12
    .2byte 6 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte Text_8445AD2
    .4byte Text_8445B30
    .2byte 0 @ unused
    .2byte 425
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844ED60
    .string "FAIRY$", 12
    .2byte 13 @ in decimeters
    .2byte 400 @ in hectograms
    .4byte Text_8445B31
    .4byte Text_8445B93
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 272
    .2byte -1
    .2byte 0 @ padding

    @ 844ED84
    .string "FOX$", 12
    .2byte 6 @ in decimeters
    .2byte 99 @ in hectograms
    .4byte Text_8445B94
    .4byte Text_8445BEB
    .2byte 0 @ unused
    .2byte 497
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EDA8
    .string "FOX$", 12
    .2byte 11 @ in decimeters
    .2byte 199 @ in hectograms
    .4byte Text_8445BEC
    .4byte Text_8445C43
    .2byte 0 @ unused
    .2byte 339
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EDCC
    .string "BALLOON$", 12
    .2byte 5 @ in decimeters
    .2byte 55 @ in hectograms
    .4byte Text_8445C44
    .4byte Text_8445CA9
    .2byte 0 @ unused
    .2byte 419
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EDF0
    .string "BALLOON$", 12
    .2byte 10 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text_8445CAA
    .4byte Text_8445D11
    .2byte 0 @ unused
    .2byte 328
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EE14
    .string "BAT$", 12
    .2byte 8 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte Text_8445D12
    .4byte Text_8445D7A
    .2byte 0 @ unused
    .2byte 355
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EE38
    .string "BAT$", 12
    .2byte 16 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text_8445D7B
    .4byte Text_8445DDF
    .2byte 0 @ unused
    .2byte 291
    .2byte 0
    .2byte 296
    .2byte 2
    .2byte 0 @ padding

    @ 844EE5C
    .string "WEED$", 12
    .2byte 5 @ in decimeters
    .2byte 54 @ in hectograms
    .4byte Text_8445DE0
    .4byte Text_8445E4B
    .2byte 0 @ unused
    .2byte 423
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EE80
    .string "WEED$", 12
    .2byte 8 @ in decimeters
    .2byte 86 @ in hectograms
    .4byte Text_8445E4C
    .4byte Text_8445EB9
    .2byte 0 @ unused
    .2byte 329
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EEA4
    .string "FLOWER$", 12
    .2byte 12 @ in decimeters
    .2byte 186 @ in hectograms
    .4byte Text_8445EBA
    .4byte Text_8445F22
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 844EEC8
    .string "MUSHROOM$", 12
    .2byte 3 @ in decimeters
    .2byte 54 @ in hectograms
    .4byte Text_8445F23
    .4byte Text_8445F87
    .2byte 0 @ unused
    .2byte 546
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EEEC
    .string "MUSHROOM$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte Text_8445F88
    .4byte Text_8445FEA
    .2byte 0 @ unused
    .2byte 307
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EF10
    .string "INSECT$", 12
    .2byte 10 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text_8445FEB
    .4byte Text_8446050
    .2byte 0 @ unused
    .2byte 360
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EF34
    .string "POISON MOTH$", 12
    .2byte 15 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte Text_8446051
    .4byte Text_84460B9
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 293
    .2byte 1
    .2byte 0 @ padding

    @ 844EF58
    .string "MOLE$", 12
    .2byte 2 @ in decimeters
    .2byte 8 @ in hectograms
    .4byte Text_84460BA
    .4byte Text_8446128
    .2byte 0 @ unused
    .2byte 706
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EF7C
    .string "MOLE$", 12
    .2byte 7 @ in decimeters
    .2byte 333 @ in hectograms
    .4byte Text_8446129
    .4byte Text_844618E
    .2byte 0 @ unused
    .2byte 384
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EFA0
    .string "SCRATCH CAT$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte Text_844618F
    .4byte Text_84461F0
    .2byte 0 @ unused
    .2byte 480
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EFC4
    .string "CLASSY CAT$", 12
    .2byte 10 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte Text_84461F1
    .4byte Text_844626A
    .2byte 0 @ unused
    .2byte 320
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EFE8
    .string "DUCK$", 12
    .2byte 8 @ in decimeters
    .2byte 196 @ in hectograms
    .4byte Text_844626B
    .4byte Text_84462D7
    .2byte 0 @ unused
    .2byte 347
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F00C
    .string "DUCK$", 12
    .2byte 17 @ in decimeters
    .2byte 766 @ in hectograms
    .4byte Text_84462D8
    .4byte Text_8446347
    .2byte 0 @ unused
    .2byte 272
    .2byte 4
    .2byte 287
    .2byte 1
    .2byte 0 @ padding

    @ 844F030
    .string "PIG MONKEY$", 12
    .2byte 5 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text_8446348
    .4byte Text_84463B9
    .2byte 0 @ unused
    .2byte 388
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F054
    .string "PIG MONKEY$", 12
    .2byte 10 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte Text_84463BA
    .4byte Text_8446428
    .2byte 0 @ unused
    .2byte 326
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F078
    .string "PUPPY$", 12
    .2byte 7 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte Text_8446429
    .4byte Text_8446483
    .2byte 0 @ unused
    .2byte 346
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F09C
    .string "LEGENDARY$", 12
    .2byte 19 @ in decimeters
    .2byte 1550 @ in hectograms
    .4byte Text_8446484
    .4byte Text_84464E1
    .2byte 0 @ unused
    .2byte 256
    .2byte -1
    .2byte 312
    .2byte 2
    .2byte 0 @ padding

    @ 844F0C0
    .string "TADPOLE$", 12
    .2byte 6 @ in decimeters
    .2byte 124 @ in hectograms
    .4byte Text_84464E2
    .4byte Text_8446559
    .2byte 0 @ unused
    .2byte 353
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F0E4
    .string "TADPOLE$", 12
    .2byte 10 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte Text_844655A
    .4byte Text_84465BE
    .2byte 0 @ unused
    .2byte 288
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F108
    .string "TADPOLE$", 12
    .2byte 13 @ in decimeters
    .2byte 540 @ in hectograms
    .4byte Text_84465BF
    .4byte Text_844662B
    .2byte 0 @ unused
    .2byte 256
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F12C
    .string "PSI$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte Text_844662C
    .4byte Text_8446686
    .2byte 0 @ unused
    .2byte 374
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F150
    .string "PSI$", 12
    .2byte 13 @ in decimeters
    .2byte 565 @ in hectograms
    .4byte Text_8446687
    .4byte Text_84466E7
    .2byte 0 @ unused
    .2byte 272
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F174
    .string "PSI$", 12
    .2byte 15 @ in decimeters
    .2byte 480 @ in hectograms
    .4byte Text_84466E8
    .4byte Text_8446754
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 271
    .2byte -1
    .2byte 0 @ padding

    @ 844F198
    .string "SUPERPOWER$", 12
    .2byte 8 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte Text_8446755
    .4byte Text_84467C3
    .2byte 0 @ unused
    .2byte 320
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F1BC
    .string "SUPERPOWER$", 12
    .2byte 15 @ in decimeters
    .2byte 705 @ in hectograms
    .4byte Text_84467C4
    .4byte Text_844682B
    .2byte 0 @ unused
    .2byte 304
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F1E0
    .string "SUPERPOWER$", 12
    .2byte 16 @ in decimeters
    .2byte 1300 @ in hectograms
    .4byte Text_844682C
    .4byte Text_8446887
    .2byte 0 @ unused
    .2byte 278
    .2byte 2
    .2byte 283
    .2byte 0
    .2byte 0 @ padding

    @ 844F204
    .string "FLOWER$", 12
    .2byte 7 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text_8446888
    .4byte Text_84468F5
    .2byte 0 @ unused
    .2byte 354
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F228
    .string "FLYCATCHER$", 12
    .2byte 10 @ in decimeters
    .2byte 64 @ in hectograms
    .4byte Text_84468F6
    .4byte Text_8446954
    .2byte 0 @ unused
    .2byte 256
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F24C
    .string "FLYCATCHER$", 12
    .2byte 17 @ in decimeters
    .2byte 155 @ in hectograms
    .4byte Text_8446955
    .4byte Text_84469BC
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 302
    .2byte 2
    .2byte 0 @ padding

    @ 844F270
    .string "JELLYFISH$", 12
    .2byte 9 @ in decimeters
    .2byte 455 @ in hectograms
    .4byte Text_84469BD
    .4byte Text_8446A16
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F294
    .string "JELLYFISH$", 12
    .2byte 16 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text_8446A17
    .4byte Text_8446A7F
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 312
    .2byte 0
    .2byte 0 @ padding

    @ 844F2B8
    .string "ROCK$", 12
    .2byte 4 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte Text_8446A80
    .4byte Text_8446AEF
    .2byte 0 @ unused
    .2byte 330
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F2DC
    .string "ROCK$", 12
    .2byte 10 @ in decimeters
    .2byte 1050 @ in hectograms
    .4byte Text_8446AF0
    .4byte Text_8446B55
    .2byte 0 @ unused
    .2byte 272
    .2byte 8
    .2byte 305
    .2byte 1
    .2byte 0 @ padding

    @ 844F300
    .string "MEGATON$", 12
    .2byte 14 @ in decimeters
    .2byte 3000 @ in hectograms
    .4byte Text_8446B56
    .4byte Text_8446BC3
    .2byte 0 @ unused
    .2byte 266
    .2byte 3
    .2byte 298
    .2byte 1
    .2byte 0 @ padding

    @ 844F324
    .string "FIRE HORSE$", 12
    .2byte 10 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text_8446BC4
    .4byte Text_8446C22
    .2byte 0 @ unused
    .2byte 288
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F348
    .string "FIRE HORSE$", 12
    .2byte 17 @ in decimeters
    .2byte 950 @ in hectograms
    .4byte Text_8446C23
    .4byte Text_8446C8B
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 312
    .2byte 1
    .2byte 0 @ padding

    @ 844F36C
    .string "DOPEY$", 12
    .2byte 12 @ in decimeters
    .2byte 360 @ in hectograms
    .4byte Text_8446C8C
    .4byte Text_8446D04
    .2byte 0 @ unused
    .2byte 271
    .2byte 10
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 844F390
    .string "HERMIT CRAB$", 12
    .2byte 16 @ in decimeters
    .2byte 785 @ in hectograms
    .4byte Text_8446D05
    .4byte Text_8446D73
    .2byte 0 @ unused
    .2byte 257
    .2byte -2
    .2byte 312
    .2byte 0
    .2byte 0 @ padding

    @ 844F3B4
    .string "MAGNET$", 12
    .2byte 3 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte Text_8446D74
    .4byte Text_8446DDA
    .2byte 0 @ unused
    .2byte 294
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F3D8
    .string "MAGNET$", 12
    .2byte 10 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text_8446DDB
    .4byte Text_8446E40
    .2byte 0 @ unused
    .2byte 293
    .2byte -4
    .2byte 273
    .2byte -2
    .2byte 0 @ padding

    @ 844F3FC
    .string "WILD DUCK$", 12
    .2byte 8 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text_8446E41
    .4byte Text_8446EA8
    .2byte 0 @ unused
    .2byte 317
    .2byte -2
    .2byte 256
    .2byte -3
    .2byte 0 @ padding

    @ 844F420
    .string "TWIN BIRD$", 12
    .2byte 14 @ in decimeters
    .2byte 392 @ in hectograms
    .4byte Text_8446EA9
    .4byte Text_8446F15
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 287
    .2byte 0
    .2byte 0 @ padding

    @ 844F444
    .string "TRIPLE BIRD$", 12
    .2byte 18 @ in decimeters
    .2byte 852 @ in hectograms
    .4byte Text_8446F16
    .4byte Text_8446F7B
    .2byte 0 @ unused
    .2byte 272
    .2byte -2
    .2byte 296
    .2byte 1
    .2byte 0 @ padding

    @ 844F468
    .string "SEA LION$", 12
    .2byte 11 @ in decimeters
    .2byte 900 @ in hectograms
    .4byte Text_8446F7C
    .4byte Text_8446FF2
    .2byte 0 @ unused
    .2byte 298
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F48C
    .string "SEA LION$", 12
    .2byte 17 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text_8446FF3
    .4byte Text_8447052
    .2byte 0 @ unused
    .2byte 288
    .2byte 1
    .2byte 306
    .2byte -1
    .2byte 0 @ padding

    @ 844F4B0
    .string "SLUDGE$", 12
    .2byte 9 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text_8447053
    .4byte Text_84470B6
    .2byte 0 @ unused
    .2byte 258
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F4D4
    .string "SLUDGE$", 12
    .2byte 12 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text_84470B7
    .4byte Text_8447122
    .2byte 0 @ unused
    .2byte 288
    .2byte 7
    .2byte 288
    .2byte -1
    .2byte 0 @ padding

    @ 844F4F8
    .string "BIVALVE$", 12
    .2byte 3 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text_8447123
    .4byte Text_8447185
    .2byte 0 @ unused
    .2byte 643
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F51C
    .string "BIVALVE$", 12
    .2byte 15 @ in decimeters
    .2byte 1325 @ in hectograms
    .4byte Text_8447186
    .4byte Text_84471F8
    .2byte 0 @ unused
    .2byte 264
    .2byte 0
    .2byte 288
    .2byte -1
    .2byte 0 @ padding

    @ 844F540
    .string "GAS$", 12
    .2byte 13 @ in decimeters
    .2byte 1 @ in hectograms
    .4byte Text_84471F9
    .4byte Text_8447264
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F564
    .string "GAS$", 12
    .2byte 16 @ in decimeters
    .2byte 1 @ in hectograms
    .4byte Text_8447265
    .4byte Text_84472C2
    .2byte 0 @ unused
    .2byte 269
    .2byte 2
    .2byte 308
    .2byte 1
    .2byte 0 @ padding

    @ 844F588
    .string "SHADOW$", 12
    .2byte 15 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte Text_84472C3
    .4byte Text_8447320
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 317
    .2byte 1
    .2byte 0 @ padding

    @ 844F5AC
    .string "ROCK SNAKE$", 12
    .2byte 88 @ in decimeters
    .2byte 2100 @ in hectograms
    .4byte Text_8447321
    .4byte Text_8447392
    .2byte 0 @ unused
    .2byte 257
    .2byte 0
    .2byte 515
    .2byte 12
    .2byte 0 @ padding

    @ 844F5D0
    .string "HYPNOSIS$", 12
    .2byte 10 @ in decimeters
    .2byte 324 @ in hectograms
    .4byte Text_8447393
    .4byte Text_84473F7
    .2byte 0 @ unused
    .2byte 274
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F5F4
    .string "HYPNOSIS$", 12
    .2byte 16 @ in decimeters
    .2byte 756 @ in hectograms
    .4byte Text_84473F8
    .4byte Text_8447464
    .2byte 0 @ unused
    .2byte 298
    .2byte 3
    .2byte 310
    .2byte 2
    .2byte 0 @ padding

    @ 844F618
    .string "RIVER CRAB$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte Text_8447465
    .4byte Text_84474C6
    .2byte 0 @ unused
    .2byte 469
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F63C
    .string "PINCER$", 12
    .2byte 13 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text_84474C7
    .4byte Text_8447531
    .2byte 0 @ unused
    .2byte 287
    .2byte 3
    .2byte 308
    .2byte 1
    .2byte 0 @ padding

    @ 844F660
    .string "BALL$", 12
    .2byte 5 @ in decimeters
    .2byte 104 @ in hectograms
    .4byte Text_8447532
    .4byte Text_8447589
    .2byte 0 @ unused
    .2byte 364
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F684
    .string "BALL$", 12
    .2byte 12 @ in decimeters
    .2byte 666 @ in hectograms
    .4byte Text_844758A
    .4byte Text_84475ED
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F6A8
    .string "EGG$", 12
    .2byte 4 @ in decimeters
    .2byte 25 @ in hectograms
    .4byte Text_84475EE
    .4byte Text_844765A
    .2byte 0 @ unused
    .2byte 495
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F6CC
    .string "COCONUT$", 12
    .2byte 20 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text_844765B
    .4byte Text_84476BE
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 376
    .2byte 7
    .2byte 0 @ padding

    @ 844F6F0
    .string "LONELY$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte Text_84476BF
    .4byte Text_8447726
    .2byte 0 @ unused
    .2byte 545
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F714
    .string "BONE KEEPER$", 12
    .2byte 10 @ in decimeters
    .2byte 450 @ in hectograms
    .4byte Text_8447727
    .4byte Text_844778D
    .2byte 0 @ unused
    .2byte 293
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F738
    .string "KICKING$", 12
    .2byte 15 @ in decimeters
    .2byte 498 @ in hectograms
    .4byte Text_844778E
    .4byte Text_84477F8
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 273
    .2byte -2
    .2byte 0 @ padding

    @ 844F75C
    .string "PUNCHING$", 12
    .2byte 14 @ in decimeters
    .2byte 502 @ in hectograms
    .4byte Text_84477F9
    .4byte Text_8447864
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 264
    .2byte -2
    .2byte 0 @ padding

    @ 844F780
    .string "LICKING$", 12
    .2byte 12 @ in decimeters
    .2byte 655 @ in hectograms
    .4byte Text_8447865
    .4byte Text_84478CE
    .2byte 0 @ unused
    .2byte 272
    .2byte 3
    .2byte 272
    .2byte -3
    .2byte 0 @ padding

    @ 844F7A4
    .string "POISON GAS$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text_84478CF
    .4byte Text_844792C
    .2byte 0 @ unused
    .2byte 369
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F7C8
    .string "POISON GAS$", 12
    .2byte 12 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte Text_844792D
    .4byte Text_8447993
    .2byte 0 @ unused
    .2byte 321
    .2byte -1
    .2byte 276
    .2byte -1
    .2byte 0 @ padding

    @ 844F7EC
    .string "SPIKES$", 12
    .2byte 10 @ in decimeters
    .2byte 1150 @ in hectograms
    .4byte Text_8447994
    .4byte Text_84479F6
    .2byte 0 @ unused
    .2byte 291
    .2byte 7
    .2byte 276
    .2byte -2
    .2byte 0 @ padding

    @ 844F810
    .string "DRILL$", 12
    .2byte 19 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text_84479F7
    .4byte Text_8447A5E
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 344
    .2byte 3
    .2byte 0 @ padding

    @ 844F834
    .string "EGG$", 12
    .2byte 11 @ in decimeters
    .2byte 346 @ in hectograms
    .4byte Text_8447A5F
    .4byte Text_8447ABE
    .2byte 0 @ unused
    .2byte 257
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F858
    .string "VINE$", 12
    .2byte 10 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte Text_8447ABF
    .4byte Text_8447B27
    .2byte 0 @ unused
    .2byte 320
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F87C
    .string "PARENT$", 12
    .2byte 22 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte Text_8447B28
    .4byte Text_8447B8F
    .2byte 0 @ unused
    .2byte 257
    .2byte -3
    .2byte 349
    .2byte 5
    .2byte 0 @ padding

    @ 844F8A0
    .string "DRAGON$", 12
    .2byte 4 @ in decimeters
    .2byte 80 @ in hectograms
    .4byte Text_8447B90
    .4byte Text_8447BF5
    .2byte 0 @ unused
    .2byte 399
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F8C4
    .string "DRAGON$", 12
    .2byte 12 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte Text_8447BF6
    .4byte Text_8447C5F
    .2byte 0 @ unused
    .2byte 296
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F8E8
    .string "GOLDFISH$", 12
    .2byte 6 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text_8447C60
    .4byte Text_8447CC8
    .2byte 0 @ unused
    .2byte 379
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F90C
    .string "GOLDFISH$", 12
    .2byte 13 @ in decimeters
    .2byte 390 @ in hectograms
    .4byte Text_8447CC9
    .4byte Text_8447D24
    .2byte 0 @ unused
    .2byte 304
    .2byte 1
    .2byte 288
    .2byte -2
    .2byte 0 @ padding

    @ 844F930
    .string "STAR SHAPE$", 12
    .2byte 8 @ in decimeters
    .2byte 345 @ in hectograms
    .4byte Text_8447D25
    .4byte Text_8447D84
    .2byte 0 @ unused
    .2byte 326
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F954
    .string "MYSTERIOUS$", 12
    .2byte 11 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte Text_8447D85
    .4byte Text_8447DEE
    .2byte 0 @ unused
    .2byte 301
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F978
    .string "BARRIER$", 12
    .2byte 13 @ in decimeters
    .2byte 545 @ in hectograms
    .4byte Text_8447DEF
    .4byte Text_8447E4F
    .2byte 0 @ unused
    .2byte 258
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F99C
    .string "MANTIS$", 12
    .2byte 15 @ in decimeters
    .2byte 560 @ in hectograms
    .4byte Text_8447E50
    .4byte Text_8447EB3
    .2byte 0 @ unused
    .2byte 272
    .2byte 0
    .2byte 293
    .2byte 1
    .2byte 0 @ padding

    @ 844F9C0
    .string "HUMAN SHAPE$", 12
    .2byte 14 @ in decimeters
    .2byte 406 @ in hectograms
    .4byte Text_8447EB4
    .4byte Text_8447F19
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 300
    .2byte 1
    .2byte 0 @ padding

    @ 844F9E4
    .string "ELECTRIC$", 12
    .2byte 11 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text_8447F1A
    .4byte Text_8447F7F
    .2byte 0 @ unused
    .2byte 330
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FA08
    .string "SPITFIRE$", 12
    .2byte 13 @ in decimeters
    .2byte 445 @ in hectograms
    .4byte Text_8447F80
    .4byte Text_8447FED
    .2byte 0 @ unused
    .2byte 293
    .2byte 4
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 844FA2C
    .string "STAG BEETLE$", 12
    .2byte 15 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text_8447FEE
    .4byte Text_8448059
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 257
    .2byte -2
    .2byte 0 @ padding

    @ 844FA50
    .string "WILD BULL$", 12
    .2byte 14 @ in decimeters
    .2byte 884 @ in hectograms
    .4byte Text_844805A
    .4byte Text_84480AE
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 312
    .2byte 3
    .2byte 0 @ padding

    @ 844FA74
    .string "FISH$", 12
    .2byte 9 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte Text_84480AF
    .4byte Text_8448122
    .2byte 0 @ unused
    .2byte 317
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FA98
    .string "ATROCIOUS$", 12
    .2byte 65 @ in decimeters
    .2byte 2350 @ in hectograms
    .4byte Text_8448123
    .4byte Text_8448193
    .2byte 0 @ unused
    .2byte 288
    .2byte -1
    .2byte 512
    .2byte 11
    .2byte 0 @ padding

    @ 844FABC
    .string "TRANSPORT$", 12
    .2byte 25 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte Text_8448194
    .4byte Text_84481F7
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 425
    .2byte 8
    .2byte 0 @ padding

    @ 844FAE0
    .string "TRANSFORM$", 12
    .2byte 3 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text_84481F8
    .4byte Text_8448250
    .2byte 0 @ unused
    .2byte 602
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB04
    .string "EVOLUTION$", 12
    .2byte 3 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte Text_8448251
    .4byte Text_84482AF
    .2byte 0 @ unused
    .2byte 476
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB28
    .string "BUBBLE JET$", 12
    .2byte 10 @ in decimeters
    .2byte 290 @ in hectograms
    .4byte Text_84482B0
    .4byte Text_8448320
    .2byte 0 @ unused
    .2byte 316
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB4C
    .string "LIGHTNING$", 12
    .2byte 8 @ in decimeters
    .2byte 245 @ in hectograms
    .4byte Text_8448321
    .4byte Text_8448387
    .2byte 0 @ unused
    .2byte 283
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB70
    .string "FLAME$", 12
    .2byte 9 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte Text_8448388
    .4byte Text_84483FB
    .2byte 0 @ unused
    .2byte 302
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB94
    .string "VIRTUAL$", 12
    .2byte 8 @ in decimeters
    .2byte 365 @ in hectograms
    .4byte Text_84483FC
    .4byte Text_8448467
    .2byte 0 @ unused
    .2byte 328
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FBB8
    .string "SPIRAL$", 12
    .2byte 4 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte Text_8448468
    .4byte Text_84484CD
    .2byte 0 @ unused
    .2byte 521
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FBDC
    .string "SPIRAL$", 12
    .2byte 10 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte Text_84484CE
    .4byte Text_8448537
    .2byte 0 @ unused
    .2byte 307
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FC00
    .string "SHELLFISH$", 12
    .2byte 5 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text_8448538
    .4byte Text_84485A3
    .2byte 0 @ unused
    .2byte 438
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FC24
    .string "SHELLFISH$", 12
    .2byte 13 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte Text_84485A4
    .4byte Text_844860D
    .2byte 0 @ unused
    .2byte 271
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FC48
    .string "FOSSIL$", 12
    .2byte 18 @ in decimeters
    .2byte 590 @ in hectograms
    .4byte Text_844860E
    .4byte Text_844867D
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 317
    .2byte 2
    .2byte 0 @ padding

    @ 844FC6C
    .string "SLEEPING$", 12
    .2byte 21 @ in decimeters
    .2byte 4600 @ in hectograms
    .4byte Text_844867E
    .4byte Text_84486F7
    .2byte 0 @ unused
    .2byte 275
    .2byte 1
    .2byte 408
    .2byte 7
    .2byte 0 @ padding

    @ 844FC90
    .string "FREEZE$", 12
    .2byte 17 @ in decimeters
    .2byte 554 @ in hectograms
    .4byte Text_84486F8
    .4byte Text_844875F
    .2byte 0 @ unused
    .2byte 278
    .2byte 0
    .2byte 308
    .2byte 1
    .2byte 0 @ padding

    @ 844FCB4
    .string "ELECTRIC$", 12
    .2byte 16 @ in decimeters
    .2byte 526 @ in hectograms
    .4byte Text_8448760
    .4byte Text_84487BF
    .2byte 0 @ unused
    .2byte 275
    .2byte 1
    .2byte 330
    .2byte 3
    .2byte 0 @ padding

    @ 844FCD8
    .string "FLAME$", 12
    .2byte 20 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text_84487C0
    .4byte Text_8448830
    .2byte 0 @ unused
    .2byte 270
    .2byte 1
    .2byte 379
    .2byte 6
    .2byte 0 @ padding

    @ 844FCFC
    .string "DRAGON$", 12
    .2byte 18 @ in decimeters
    .2byte 33 @ in hectograms
    .4byte Text_8448831
    .4byte Text_844888C
    .2byte 0 @ unused
    .2byte 256
    .2byte 8
    .2byte 386
    .2byte 6
    .2byte 0 @ padding

    @ 844FD20
    .string "DRAGON$", 12
    .2byte 40 @ in decimeters
    .2byte 165 @ in hectograms
    .4byte Text_844888D
    .4byte Text_84488F6
    .2byte 0 @ unused
    .2byte 274
    .2byte 0
    .2byte 423
    .2byte 6
    .2byte 0 @ padding

    @ 844FD44
    .string "DRAGON$", 12
    .2byte 22 @ in decimeters
    .2byte 2100 @ in hectograms
    .4byte Text_84488F7
    .4byte Text_8448951
    .2byte 0 @ unused
    .2byte 283
    .2byte -1
    .2byte 342
    .2byte 4
    .2byte 0 @ padding

    @ 844FD68
    .string "GENETIC$", 12
    .2byte 20 @ in decimeters
    .2byte 1220 @ in hectograms
    .4byte Text_8448952
    .4byte Text_84489B6
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 342
    .2byte 5
    .2byte 0 @ padding

    @ 844FD8C
    .string "NEW SPECIES$", 12
    .2byte 4 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text_84489B7
    .4byte Text_8448A25
    .2byte 0 @ unused
    .2byte 460
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FDB0
    .string "LEAF$", 12
    .2byte 9 @ in decimeters
    .2byte 64 @ in hectograms
    .4byte Text_8448A26
    .4byte Text_8448A7D
    .2byte 0 @ unused
    .2byte 512
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FDD4
    .string "LEAF$", 12
    .2byte 12 @ in decimeters
    .2byte 158 @ in hectograms
    .4byte Text_8448A7E
    .4byte Text_8448ADC
    .2byte 0 @ unused
    .2byte 296
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FDF8
    .string "HERB$", 12
    .2byte 18 @ in decimeters
    .2byte 1005 @ in hectograms
    .4byte Text_8448ADD
    .4byte Text_8448B3E
    .2byte 0 @ unused
    .2byte 286
    .2byte 0
    .2byte 317
    .2byte 2
    .2byte 0 @ padding

    @ 844FE1C
    .string "FIRE MOUSE$", 12
    .2byte 5 @ in decimeters
    .2byte 79 @ in hectograms
    .4byte Text_8448B3F
    .4byte Text_8448B9D
    .2byte 0 @ unused
    .2byte 539
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FE40
    .string "VOLCANO$", 12
    .2byte 9 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte Text_8448B9E
    .4byte Text_8448BFB
    .2byte 0 @ unused
    .2byte 329
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FE64
    .string "VOLCANO$", 12
    .2byte 17 @ in decimeters
    .2byte 795 @ in hectograms
    .4byte Text_8448BFC
    .4byte Text_8448C5A
    .2byte 0 @ unused
    .2byte 284
    .2byte -1
    .2byte 287
    .2byte 0
    .2byte 0 @ padding

    @ 844FE88
    .string "BIG JAW$", 12
    .2byte 6 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte Text_8448C5B
    .4byte Text_8448CB9
    .2byte 0 @ unused
    .2byte 487
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FEAC
    .string "BIG JAW$", 12
    .2byte 11 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte Text_8448CBA
    .4byte Text_8448D1D
    .2byte 0 @ unused
    .2byte 378
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FED0
    .string "BIG JAW$", 12
    .2byte 23 @ in decimeters
    .2byte 888 @ in hectograms
    .4byte Text_8448D1E
    .4byte Text_8448D89
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding

    @ 844FEF4
    .string "SCOUT$", 12
    .2byte 8 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte Text_8448D8A
    .4byte Text_8448DF2
    .2byte 0 @ unused
    .2byte 439
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FF18
    .string "LONG BODY$", 12
    .2byte 18 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte Text_8448DF3
    .4byte Text_8448E56
    .2byte 0 @ unused
    .2byte 346
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FF3C
    .string "OWL$", 12
    .2byte 7 @ in decimeters
    .2byte 212 @ in hectograms
    .4byte Text_8448E57
    .4byte Text_8448EC0
    .2byte 0 @ unused
    .2byte 380
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FF60
    .string "OWL$", 12
    .2byte 16 @ in decimeters
    .2byte 408 @ in hectograms
    .4byte Text_8448EC1
    .4byte Text_8448F1C
    .2byte 0 @ unused
    .2byte 278
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FF84
    .string "FIVE STAR$", 12
    .2byte 10 @ in decimeters
    .2byte 108 @ in hectograms
    .4byte Text_8448F1D
    .4byte Text_8448F86
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FFA8
    .string "FIVE STAR$", 12
    .2byte 14 @ in decimeters
    .2byte 356 @ in hectograms
    .4byte Text_8448F87
    .4byte Text_8448FEF
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FFCC
    .string "STRING SPIT$", 12
    .2byte 5 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text_8448FF0
    .4byte Text_8449051
    .2byte 0 @ unused
    .2byte 414
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FFF0
    .string "LONG LEG$", 12
    .2byte 11 @ in decimeters
    .2byte 335 @ in hectograms
    .4byte Text_8449052
    .4byte Text_84490BC
    .2byte 0 @ unused
    .2byte 316
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450014
    .string "BAT$", 12
    .2byte 18 @ in decimeters
    .2byte 750 @ in hectograms
    .4byte Text_84490BD
    .4byte Text_8449123
    .2byte 0 @ unused
    .2byte 279
    .2byte -1
    .2byte 313
    .2byte 2
    .2byte 0 @ padding

    @ 8450038
    .string "ANGLER$", 12
    .2byte 5 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text_8449124
    .4byte Text_8449180
    .2byte 0 @ unused
    .2byte 424
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845005C
    .string "LIGHT$", 12
    .2byte 12 @ in decimeters
    .2byte 225 @ in hectograms
    .4byte Text_8449181
    .4byte Text_84491E5
    .2byte 0 @ unused
    .2byte 269
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450080
    .string "TINY MOUSE$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text_84491E6
    .4byte Text_844924E
    .2byte 0 @ unused
    .2byte 508
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84500A4
    .string "STAR SHAPE$", 12
    .2byte 3 @ in decimeters
    .2byte 30 @ in hectograms
    .4byte Text_844924F
    .4byte Text_84492A7
    .2byte 0 @ unused
    .2byte 462
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84500C8
    .string "BALLOON$", 12
    .2byte 3 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text_84492A8
    .4byte Text_8449301
    .2byte 0 @ unused
    .2byte 457
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84500EC
    .string "SPIKE BALL$", 12
    .2byte 3 @ in decimeters
    .2byte 15 @ in hectograms
    .4byte Text_8449302
    .4byte Text_844935F
    .2byte 0 @ unused
    .2byte 507
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450110
    .string "HAPPINESS$", 12
    .2byte 6 @ in decimeters
    .2byte 32 @ in hectograms
    .4byte Text_8449360
    .4byte Text_84493C4
    .2byte 0 @ unused
    .2byte 424
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450134
    .string "TINY BIRD$", 12
    .2byte 2 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text_84493C5
    .4byte Text_8449430
    .2byte 0 @ unused
    .2byte 610
    .2byte 23
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450158
    .string "MYSTIC$", 12
    .2byte 15 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text_8449431
    .4byte Text_8449492
    .2byte 0 @ unused
    .2byte 258
    .2byte 4
    .2byte 317
    .2byte 3
    .2byte 0 @ padding

    @ 845017C
    .string "WOOL$", 12
    .2byte 6 @ in decimeters
    .2byte 78 @ in hectograms
    .4byte Text_8449493
    .4byte Text_84494F7
    .2byte 0 @ unused
    .2byte 379
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84501A0
    .string "WOOL$", 12
    .2byte 8 @ in decimeters
    .2byte 133 @ in hectograms
    .4byte Text_84494F8
    .4byte Text_8449558
    .2byte 0 @ unused
    .2byte 372
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84501C4
    .string "LIGHT$", 12
    .2byte 14 @ in decimeters
    .2byte 615 @ in hectograms
    .4byte Text_8449559
    .4byte Text_84495C3
    .2byte 0 @ unused
    .2byte 275
    .2byte 2
    .2byte 283
    .2byte -1
    .2byte 0 @ padding

    @ 84501E8
    .string "FLOWER$", 12
    .2byte 4 @ in decimeters
    .2byte 58 @ in hectograms
    .4byte Text_84495C4
    .4byte Text_8449629
    .2byte 0 @ unused
    .2byte 472
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845020C
    .string "AQUA MOUSE$", 12
    .2byte 4 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text_844962A
    .4byte Text_8449687
    .2byte 0 @ unused
    .2byte 476
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450230
    .string "AQUA RABBIT$", 12
    .2byte 8 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte Text_8449688
    .4byte Text_84496EA
    .2byte 0 @ unused
    .2byte 448
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450254
    .string "IMITATION$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte Text_84496EB
    .4byte Text_8449755
    .2byte 0 @ unused
    .2byte 305
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450278
    .string "FROG$", 12
    .2byte 11 @ in decimeters
    .2byte 339 @ in hectograms
    .4byte Text_8449756
    .4byte Text_84497BA
    .2byte 0 @ unused
    .2byte 289
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845029C
    .string "COTTONWEED$", 12
    .2byte 4 @ in decimeters
    .2byte 5 @ in hectograms
    .4byte Text_84497BB
    .4byte Text_844981D
    .2byte 0 @ unused
    .2byte 562
    .2byte -7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84502C0
    .string "COTTONWEED$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text_844981E
    .4byte Text_844987C
    .2byte 0 @ unused
    .2byte 387
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84502E4
    .string "COTTONWEED$", 12
    .2byte 8 @ in decimeters
    .2byte 30 @ in hectograms
    .4byte Text_844987D
    .4byte Text_84498E8
    .2byte 0 @ unused
    .2byte 418
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450308
    .string "LONG TAIL$", 12
    .2byte 8 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text_84498E9
    .4byte Text_844994C
    .2byte 0 @ unused
    .2byte 363
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845032C
    .string "SEED$", 12
    .2byte 3 @ in decimeters
    .2byte 18 @ in hectograms
    .4byte Text_844994D
    .4byte Text_84499B7
    .2byte 0 @ unused
    .2byte 541
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450350
    .string "SUN$", 12
    .2byte 8 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text_84499B8
    .4byte Text_8449A1F
    .2byte 0 @ unused
    .2byte 374
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450374
    .string "CLEAR WING$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte Text_8449A20
    .4byte Text_8449A81
    .2byte 0 @ unused
    .2byte 274
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450398
    .string "WATER FISH$", 12
    .2byte 4 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text_8449A82
    .4byte Text_8449AD6
    .2byte 0 @ unused
    .2byte 479
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84503BC
    .string "WATER FISH$", 12
    .2byte 14 @ in decimeters
    .2byte 750 @ in hectograms
    .4byte Text_8449AD7
    .4byte Text_8449B41
    .2byte 0 @ unused
    .2byte 273
    .2byte 4
    .2byte 273
    .2byte -2
    .2byte 0 @ padding

    @ 84503E0
    .string "SUN$", 12
    .2byte 9 @ in decimeters
    .2byte 265 @ in hectograms
    .4byte Text_8449B42
    .4byte Text_8449B9D
    .2byte 0 @ unused
    .2byte 363
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450404
    .string "MOONLIGHT$", 12
    .2byte 10 @ in decimeters
    .2byte 270 @ in hectograms
    .4byte Text_8449B9E
    .4byte Text_8449C06
    .2byte 0 @ unused
    .2byte 317
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450428
    .string "DARKNESS$", 12
    .2byte 5 @ in decimeters
    .2byte 21 @ in hectograms
    .4byte Text_8449C07
    .4byte Text_8449C71
    .2byte 0 @ unused
    .2byte 401
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845044C
    .string "ROYAL$", 12
    .2byte 20 @ in decimeters
    .2byte 795 @ in hectograms
    .4byte Text_8449C72
    .4byte Text_8449CD0
    .2byte 0 @ unused
    .2byte 265
    .2byte -1
    .2byte 330
    .2byte 4
    .2byte 0 @ padding

    @ 8450470
    .string "SCREECH$", 12
    .2byte 7 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text_8449CD1
    .4byte Text_8449D3B
    .2byte 0 @ unused
    .2byte 407
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450494
    .string "SYMBOL$", 12
    .2byte 5 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text_8449D3C
    .4byte Text_8449D92
    .2byte 0 @ unused
    .2byte 411
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84504B8
    .string "PATIENT$", 12
    .2byte 13 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte Text_8449D93
    .4byte Text_8449DF7
    .2byte 0 @ unused
    .2byte 274
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84504DC
    .string "LONG NECK$", 12
    .2byte 15 @ in decimeters
    .2byte 415 @ in hectograms
    .4byte Text_8449DF8
    .4byte Text_8449E5A
    .2byte 0 @ unused
    .2byte 281
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450500
    .string "BAGWORM$", 12
    .2byte 6 @ in decimeters
    .2byte 72 @ in hectograms
    .4byte Text_8449E5B
    .4byte Text_8449EBB
    .2byte 0 @ unused
    .2byte 445
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450524
    .string "BAGWORM$", 12
    .2byte 12 @ in decimeters
    .2byte 1258 @ in hectograms
    .4byte Text_8449EBC
    .4byte Text_8449F25
    .2byte 0 @ unused
    .2byte 293
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450548
    .string "LAND SNAKE$", 12
    .2byte 15 @ in decimeters
    .2byte 140 @ in hectograms
    .4byte Text_8449F26
    .4byte Text_8449F85
    .2byte 0 @ unused
    .2byte 284
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845056C
    .string "FLYSCORPION$", 12
    .2byte 11 @ in decimeters
    .2byte 648 @ in hectograms
    .4byte Text_8449F86
    .4byte Text_8449FEB
    .2byte 0 @ unused
    .2byte 350
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450590
    .string "IRON SNAKE$", 12
    .2byte 92 @ in decimeters
    .2byte 4000 @ in hectograms
    .4byte Text_8449FEC
    .4byte Text_844A051
    .2byte 0 @ unused
    .2byte 278
    .2byte -1
    .2byte 557
    .2byte 13
    .2byte 0 @ padding

    @ 84505B4
    .string "FAIRY$", 12
    .2byte 6 @ in decimeters
    .2byte 78 @ in hectograms
    .4byte Text_844A052
    .4byte Text_844A0B8
    .2byte 0 @ unused
    .2byte 465
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84505D8
    .string "FAIRY$", 12
    .2byte 14 @ in decimeters
    .2byte 487 @ in hectograms
    .4byte Text_844A0B9
    .4byte Text_844A11F
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84505FC
    .string "BALLOON$", 12
    .2byte 5 @ in decimeters
    .2byte 39 @ in hectograms
    .4byte Text_844A120
    .4byte Text_844A184
    .2byte 0 @ unused
    .2byte 430
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450620
    .string "PINCER$", 12
    .2byte 18 @ in decimeters
    .2byte 1180 @ in hectograms
    .4byte Text_844A185
    .4byte Text_844A1E7
    .2byte 0 @ unused
    .2byte 282
    .2byte 0
    .2byte 282
    .2byte 0
    .2byte 0 @ padding

    @ 8450644
    .string "MOLD$", 12
    .2byte 6 @ in decimeters
    .2byte 205 @ in hectograms
    .4byte Text_844A1E8
    .4byte Text_844A253
    .2byte 0 @ unused
    .2byte 485
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450668
    .string "SINGLE HORN$", 12
    .2byte 15 @ in decimeters
    .2byte 540 @ in hectograms
    .4byte Text_844A254
    .4byte Text_844A2B4
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 283
    .2byte -2
    .2byte 0 @ padding

    @ 845068C
    .string "SHARP CLAW$", 12
    .2byte 9 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text_844A2B5
    .4byte Text_844A317
    .2byte 0 @ unused
    .2byte 413
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84506B0
    .string "LITTLE BEAR$", 12
    .2byte 6 @ in decimeters
    .2byte 88 @ in hectograms
    .4byte Text_844A318
    .4byte Text_844A377
    .2byte 0 @ unused
    .2byte 455
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84506D4
    .string "HIBERNATOR$", 12
    .2byte 18 @ in decimeters
    .2byte 1258 @ in hectograms
    .4byte Text_844A378
    .4byte Text_844A3DA
    .2byte 0 @ unused
    .2byte 275
    .2byte 0
    .2byte 280
    .2byte 0
    .2byte 0 @ padding

    @ 84506F8
    .string "LAVA$", 12
    .2byte 7 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte Text_844A3DB
    .4byte Text_844A43D
    .2byte 0 @ unused
    .2byte 329
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845071C
    .string "LAVA$", 12
    .2byte 8 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text_844A43E
    .4byte Text_844A497
    .2byte 0 @ unused
    .2byte 332
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450740
    .string "PIG$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte Text_844A498
    .4byte Text_844A4F1
    .2byte 0 @ unused
    .2byte 324
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450764
    .string "SWINE$", 12
    .2byte 11 @ in decimeters
    .2byte 558 @ in hectograms
    .4byte Text_844A4F2
    .4byte Text_844A555
    .2byte 0 @ unused
    .2byte 306
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450788
    .string "CORAL$", 12
    .2byte 6 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text_844A556
    .4byte Text_844A5B7
    .2byte 0 @ unused
    .2byte 410
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84507AC
    .string "JET$", 12
    .2byte 6 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text_844A5B8
    .4byte Text_844A61D
    .2byte 0 @ unused
    .2byte 316
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84507D0
    .string "JET$", 12
    .2byte 9 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte Text_844A61E
    .4byte Text_844A685
    .2byte 0 @ unused
    .2byte 296
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84507F4
    .string "DELIVERY$", 12
    .2byte 9 @ in decimeters
    .2byte 160 @ in hectograms
    .4byte Text_844A686
    .4byte Text_844A6E4
    .2byte 0 @ unused
    .2byte 293
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450818
    .string "KITE$", 12
    .2byte 21 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte Text_844A6E5
    .4byte Text_844A750
    .2byte 0 @ unused
    .2byte 275
    .2byte 0
    .2byte 360
    .2byte 6
    .2byte 0 @ padding

    @ 845083C
    .string "ARMOR BIRD$", 12
    .2byte 17 @ in decimeters
    .2byte 505 @ in hectograms
    .4byte Text_844A751
    .4byte Text_844A7AE
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 276
    .2byte 0
    .2byte 0 @ padding

    @ 8450860
    .string "DARK$", 12
    .2byte 6 @ in decimeters
    .2byte 108 @ in hectograms
    .4byte Text_844A7AF
    .4byte Text_844A80B
    .2byte 0 @ unused
    .2byte 393
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450884
    .string "DARK$", 12
    .2byte 14 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte Text_844A80C
    .4byte Text_844A86F
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84508A8
    .string "DRAGON$", 12
    .2byte 18 @ in decimeters
    .2byte 1520 @ in hectograms
    .4byte Text_844A870
    .4byte Text_844A8D2
    .2byte 0 @ unused
    .2byte 257
    .2byte 1
    .2byte 293
    .2byte 1
    .2byte 0 @ padding

    @ 84508CC
    .string "LONG NOSE$", 12
    .2byte 5 @ in decimeters
    .2byte 335 @ in hectograms
    .4byte Text_844A8D3
    .4byte Text_844A936
    .2byte 0 @ unused
    .2byte 465
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84508F0
    .string "ARMOR$", 12
    .2byte 11 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text_844A937
    .4byte Text_844A99D
    .2byte 0 @ unused
    .2byte 313
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450914
    .string "VIRTUAL$", 12
    .2byte 6 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte Text_844A99E
    .4byte Text_844AA03
    .2byte 0 @ unused
    .2byte 320
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450938
    .string "BIG HORN$", 12
    .2byte 14 @ in decimeters
    .2byte 712 @ in hectograms
    .4byte Text_844AA04
    .4byte Text_844AA67
    .2byte 0 @ unused
    .2byte 277
    .2byte -1
    .2byte 277
    .2byte 0
    .2byte 0 @ padding

    @ 845095C
    .string "PAINTER$", 12
    .2byte 12 @ in decimeters
    .2byte 580 @ in hectograms
    .4byte Text_844AA68
    .4byte Text_844AAC6
    .2byte 0 @ unused
    .2byte 287
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450980
    .string "SCUFFLE$", 12
    .2byte 7 @ in decimeters
    .2byte 210 @ in hectograms
    .4byte Text_844AAC7
    .4byte Text_844AB2B
    .2byte 0 @ unused
    .2byte 292
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84509A4
    .string "HANDSTAND$", 12
    .2byte 14 @ in decimeters
    .2byte 480 @ in hectograms
    .4byte Text_844AB2C
    .4byte Text_844AB8E
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 257
    .2byte -2
    .2byte 0 @ padding

    @ 84509C8
    .string "KISS$", 12
    .2byte 4 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte Text_844AB8F
    .4byte Text_844ABEA
    .2byte 0 @ unused
    .2byte 440
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84509EC
    .string "ELECTRIC$", 12
    .2byte 6 @ in decimeters
    .2byte 235 @ in hectograms
    .4byte Text_844ABEB
    .4byte Text_844AC45
    .2byte 0 @ unused
    .2byte 363
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450A10
    .string "LIVE COAL$", 12
    .2byte 7 @ in decimeters
    .2byte 214 @ in hectograms
    .4byte Text_844AC46
    .4byte Text_844ACB2
    .2byte 0 @ unused
    .2byte 284
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450A34
    .string "MILK COW$", 12
    .2byte 12 @ in decimeters
    .2byte 755 @ in hectograms
    .4byte Text_844ACB3
    .4byte Text_844AD0C
    .2byte 0 @ unused
    .2byte 280
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450A58
    .string "HAPPINESS$", 12
    .2byte 15 @ in decimeters
    .2byte 468 @ in hectograms
    .4byte Text_844AD0D
    .4byte Text_844AD77
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 310
    .2byte 3
    .2byte 0 @ padding

    @ 8450A7C
    .string "THUNDER$", 12
    .2byte 19 @ in decimeters
    .2byte 1780 @ in hectograms
    .4byte Text_844AD78
    .4byte Text_844ADD2
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 359
    .2byte 6
    .2byte 0 @ padding

    @ 8450AA0
    .string "VOLCANO$", 12
    .2byte 21 @ in decimeters
    .2byte 1980 @ in hectograms
    .4byte Text_844ADD3
    .4byte Text_844AE37
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 370
    .2byte 7
    .2byte 0 @ padding

    @ 8450AC4
    .string "AURORA$", 12
    .2byte 20 @ in decimeters
    .2byte 1870 @ in hectograms
    .4byte Text_844AE38
    .4byte Text_844AE9F
    .2byte 0 @ unused
    .2byte 286
    .2byte 0
    .2byte 371
    .2byte 7
    .2byte 0 @ padding

    @ 8450AE8
    .string "ROCK SKIN$", 12
    .2byte 6 @ in decimeters
    .2byte 720 @ in hectograms
    .4byte Text_844AEA0
    .4byte Text_844AF00
    .2byte 0 @ unused
    .2byte 472
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450B0C
    .string "HARD SHELL$", 12
    .2byte 12 @ in decimeters
    .2byte 1520 @ in hectograms
    .4byte Text_844AF01
    .4byte Text_844AF64
    .2byte 0 @ unused
    .2byte 292
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450B30
    .string "ARMOR$", 12
    .2byte 20 @ in decimeters
    .2byte 2020 @ in hectograms
    .4byte Text_844AF65
    .4byte Text_844AFCD
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 383
    .2byte 7
    .2byte 0 @ padding

    @ 8450B54
    .string "DIVING$", 12
    .2byte 52 @ in decimeters
    .2byte 2160 @ in hectograms
    .4byte Text_844AFCE
    .4byte Text_844B032
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 742
    .2byte 18
    .2byte 0 @ padding

    @ 8450B78
    .string "RAINBOW$", 12
    .2byte 38 @ in decimeters
    .2byte 1990 @ in hectograms
    .4byte Text_844B033
    .4byte Text_844B099
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 620
    .2byte 16
    .2byte 0 @ padding

    @ 8450B9C
    .string "TIME TRAVEL$", 12
    .2byte 6 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text_844B09A
    .4byte Text_844B101
    .2byte 0 @ unused
    .2byte 393
    .2byte -10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450BC0
    .string "WOOD GECKO$", 12
    .2byte 5 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text_844B102
    .4byte Text_844B16D
    .2byte 0 @ unused
    .2byte 541
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450BE4
    .string "WOOD GECKO$", 12
    .2byte 9 @ in decimeters
    .2byte 216 @ in hectograms
    .4byte Text_844B16E
    .4byte Text_844B1C7
    .2byte 0 @ unused
    .2byte 360
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450C08
    .string "FOREST$", 12
    .2byte 17 @ in decimeters
    .2byte 522 @ in hectograms
    .4byte Text_844B1C8
    .4byte Text_844B233
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 313
    .2byte 3
    .2byte 0 @ padding

    @ 8450C2C
    .string "CHICK$", 12
    .2byte 4 @ in decimeters
    .2byte 25 @ in hectograms
    .4byte Text_844B234
    .4byte Text_844B28F
    .2byte 0 @ unused
    .2byte 566
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450C50
    .string "YOUNG FOWL$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte Text_844B290
    .4byte Text_844B2F3
    .2byte 0 @ unused
    .2byte 343
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450C74
    .string "BLAZE$", 12
    .2byte 19 @ in decimeters
    .2byte 520 @ in hectograms
    .4byte Text_844B2F4
    .4byte Text_844B363
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 314
    .2byte 3
    .2byte 0 @ padding

    @ 8450C98
    .string "MUD FISH$", 12
    .2byte 4 @ in decimeters
    .2byte 76 @ in hectograms
    .4byte Text_844B364
    .4byte Text_844B3CF
    .2byte 0 @ unused
    .2byte 535
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450CBC
    .string "MUD FISH$", 12
    .2byte 7 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text_844B3D0
    .4byte Text_844B438
    .2byte 0 @ unused
    .2byte 340
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450CE0
    .string "MUD FISH$", 12
    .2byte 15 @ in decimeters
    .2byte 819 @ in hectograms
    .4byte Text_844B439
    .4byte Text_844B4A7
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 282
    .2byte -2
    .2byte 0 @ padding

    @ 8450D04
    .string "BITE$", 12
    .2byte 5 @ in decimeters
    .2byte 136 @ in hectograms
    .4byte Text_844B4A8
    .4byte Text_844B518
    .2byte 0 @ unused
    .2byte 481
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450D28
    .string "BITE$", 12
    .2byte 10 @ in decimeters
    .2byte 370 @ in hectograms
    .4byte Text_844B519
    .4byte Text_844B58F
    .2byte 0 @ unused
    .2byte 359
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450D4C
    .string "TINYRACCOON$", 12
    .2byte 4 @ in decimeters
    .2byte 175 @ in hectograms
    .4byte Text_844B590
    .4byte Text_844B5F3
    .2byte 0 @ unused
    .2byte 560
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450D70
    .string "RUSHING$", 12
    .2byte 5 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte Text_844B5F4
    .4byte Text_844B663
    .2byte 0 @ unused
    .2byte 321
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450D94
    .string "WORM$", 12
    .2byte 3 @ in decimeters
    .2byte 36 @ in hectograms
    .4byte Text_844B664
    .4byte Text_844B6D5
    .2byte 0 @ unused
    .2byte 711
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450DB8
    .string "COCOON$", 12
    .2byte 6 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte Text_844B6D6
    .4byte Text_844B74B
    .2byte 0 @ unused
    .2byte 431
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450DDC
    .string "BUTTERFLY$", 12
    .2byte 10 @ in decimeters
    .2byte 284 @ in hectograms
    .4byte Text_844B74C
    .4byte Text_844B7B2
    .2byte 0 @ unused
    .2byte 298
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E00
    .string "COCOON$", 12
    .2byte 7 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text_844B7B3
    .4byte Text_844B813
    .2byte 0 @ unused
    .2byte 391
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E24
    .string "POISON MOTH$", 12
    .2byte 12 @ in decimeters
    .2byte 316 @ in hectograms
    .4byte Text_844B814
    .4byte Text_844B884
    .2byte 0 @ unused
    .2byte 269
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E48
    .string "WATER WEED$", 12
    .2byte 5 @ in decimeters
    .2byte 26 @ in hectograms
    .4byte Text_844B885
    .4byte Text_844B8ED
    .2byte 0 @ unused
    .2byte 406
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E6C
    .string "JOLLY$", 12
    .2byte 12 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte Text_844B8EE
    .4byte Text_844B964
    .2byte 0 @ unused
    .2byte 277
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E90
    .string "CAREFREE$", 12
    .2byte 15 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text_844B965
    .4byte Text_844B9BE
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 282
    .2byte 0
    .2byte 0 @ padding

    @ 8450EB4
    .string "ACORN$", 12
    .2byte 5 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text_844B9BF
    .4byte Text_844BA34
    .2byte 0 @ unused
    .2byte 472
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450ED8
    .string "WILY$", 12
    .2byte 10 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text_844BA35
    .4byte Text_844BA9D
    .2byte 0 @ unused
    .2byte 299
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450EFC
    .string "WICKED$", 12
    .2byte 13 @ in decimeters
    .2byte 596 @ in hectograms
    .4byte Text_844BA9E
    .4byte Text_844BB05
    .2byte 0 @ unused
    .2byte 290
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450F20
    .string "TINYSWALLOW$", 12
    .2byte 3 @ in decimeters
    .2byte 23 @ in hectograms
    .4byte Text_844BB06
    .4byte Text_844BB6E
    .2byte 0 @ unused
    .2byte 465
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450F44
    .string "SWALLOW$", 12
    .2byte 7 @ in decimeters
    .2byte 198 @ in hectograms
    .4byte Text_844BB6F
    .4byte Text_844BBDE
    .2byte 0 @ unused
    .2byte 428
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450F68
    .string "SEAGULL$", 12
    .2byte 6 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte Text_844BBDF
    .4byte Text_844BC3F
    .2byte 0 @ unused
    .2byte 295
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450F8C
    .string "WATER BIRD$", 12
    .2byte 12 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text_844BC40
    .4byte Text_844BCAB
    .2byte 0 @ unused
    .2byte 288
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450FB0
    .string "FEELING$", 12
    .2byte 4 @ in decimeters
    .2byte 66 @ in hectograms
    .4byte Text_844BCAC
    .4byte Text_844BD09
    .2byte 0 @ unused
    .2byte 457
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450FD4
    .string "EMOTION$", 12
    .2byte 8 @ in decimeters
    .2byte 202 @ in hectograms
    .4byte Text_844BD0A
    .4byte Text_844BD7A
    .2byte 0 @ unused
    .2byte 354
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450FF8
    .string "EMBRACE$", 12
    .2byte 16 @ in decimeters
    .2byte 484 @ in hectograms
    .4byte Text_844BD7B
    .4byte Text_844BDD6
    .2byte 0 @ unused
    .2byte 277
    .2byte 0
    .2byte 276
    .2byte -1
    .2byte 0 @ padding

    @ 845101C
    .string "POND SKATER$", 12
    .2byte 5 @ in decimeters
    .2byte 17 @ in hectograms
    .4byte Text_844BDD7
    .4byte Text_844BE35
    .2byte 0 @ unused
    .2byte 375
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451040
    .string "EYEBALL$", 12
    .2byte 8 @ in decimeters
    .2byte 36 @ in hectograms
    .4byte Text_844BE36
    .4byte Text_844BEAC
    .2byte 0 @ unused
    .2byte 378
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451064
    .string "MUSHROOM$", 12
    .2byte 4 @ in decimeters
    .2byte 45 @ in hectograms
    .4byte Text_844BEAD
    .4byte Text_844BF1A
    .2byte 0 @ unused
    .2byte 513
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451088
    .string "MUSHROOM$", 12
    .2byte 12 @ in decimeters
    .2byte 392 @ in hectograms
    .4byte Text_844BF1B
    .4byte Text_844BF87
    .2byte 0 @ unused
    .2byte 324
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84510AC
    .string "SLACKER$", 12
    .2byte 8 @ in decimeters
    .2byte 240 @ in hectograms
    .4byte Text_844BF88
    .4byte Text_844BFE3
    .2byte 0 @ unused
    .2byte 291
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84510D0
    .string "WILD MONKEY$", 12
    .2byte 14 @ in decimeters
    .2byte 465 @ in hectograms
    .4byte Text_844BFE4
    .4byte Text_844C047
    .2byte 0 @ unused
    .2byte 301
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84510F4
    .string "LAZY$", 12
    .2byte 20 @ in decimeters
    .2byte 1305 @ in hectograms
    .4byte Text_844C048
    .4byte Text_844C0C1
    .2byte 0 @ unused
    .2byte 277
    .2byte 5
    .2byte 326
    .2byte 3
    .2byte 0 @ padding

    @ 8451118
    .string "TRAINEE$", 12
    .2byte 5 @ in decimeters
    .2byte 55 @ in hectograms
    .4byte Text_844C0C2
    .4byte Text_844C122
    .2byte 0 @ unused
    .2byte 405
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845113C
    .string "NINJA$", 12
    .2byte 8 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text_844C123
    .4byte Text_844C186
    .2byte 0 @ unused
    .2byte 383
    .2byte -9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451160
    .string "SHED$", 12
    .2byte 8 @ in decimeters
    .2byte 12 @ in hectograms
    .4byte Text_844C187
    .4byte Text_844C1DB
    .2byte 0 @ unused
    .2byte 372
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451184
    .string "WHISPER$", 12
    .2byte 6 @ in decimeters
    .2byte 163 @ in hectograms
    .4byte Text_844C1DC
    .4byte Text_844C245
    .2byte 0 @ unused
    .2byte 373
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84511A8
    .string "BIG VOICE$", 12
    .2byte 10 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte Text_844C246
    .4byte Text_844C2A6
    .2byte 0 @ unused
    .2byte 356
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84511CC
    .string "LOUD NOISE$", 12
    .2byte 15 @ in decimeters
    .2byte 840 @ in hectograms
    .4byte Text_844C2A7
    .4byte Text_844C31D
    .2byte 0 @ unused
    .2byte 284
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84511F0
    .string "GUTS$", 12
    .2byte 10 @ in decimeters
    .2byte 864 @ in hectograms
    .4byte Text_844C31E
    .4byte Text_844C381
    .2byte 0 @ unused
    .2byte 256
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451214
    .string "ARM THRUST$", 12
    .2byte 23 @ in decimeters
    .2byte 2538 @ in hectograms
    .4byte Text_844C382
    .4byte Text_844C3E7
    .2byte 0 @ unused
    .2byte 268
    .2byte -1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding

    @ 8451238
    .string "POLKA DOT$", 12
    .2byte 2 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text_844C3E8
    .4byte Text_844C458
    .2byte 0 @ unused
    .2byte 603
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845125C
    .string "COMPASS$", 12
    .2byte 10 @ in decimeters
    .2byte 970 @ in hectograms
    .4byte Text_844C459
    .4byte Text_844C4B5
    .2byte 0 @ unused
    .2byte 256
    .2byte 9
    .2byte 289
    .2byte 1
    .2byte 0 @ padding

    @ 8451280
    .string "KITTEN$", 12
    .2byte 6 @ in decimeters
    .2byte 110 @ in hectograms
    .4byte Text_844C4B6
    .4byte Text_844C526
    .2byte 0 @ unused
    .2byte 492
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84512A4
    .string "PRIM$", 12
    .2byte 11 @ in decimeters
    .2byte 326 @ in hectograms
    .4byte Text_844C527
    .4byte Text_844C58E
    .2byte 0 @ unused
    .2byte 322
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84512C8
    .string "DARKNESS$", 12
    .2byte 5 @ in decimeters
    .2byte 110 @ in hectograms
    .4byte Text_844C58F
    .4byte Text_844C5E8
    .2byte 0 @ unused
    .2byte 451
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84512EC
    .string "DECEIVER$", 12
    .2byte 6 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text_844C5E9
    .4byte Text_844C653
    .2byte 0 @ unused
    .2byte 466
    .2byte 15
    .2byte 256
    .2byte -3
    .2byte 0 @ padding

    @ 8451310
    .string "IRON ARMOR$", 12
    .2byte 4 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text_844C654
    .4byte Text_844C6C5
    .2byte 0 @ unused
    .2byte 419
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451334
    .string "IRON ARMOR$", 12
    .2byte 9 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text_844C6C6
    .4byte Text_844C737
    .2byte 0 @ unused
    .2byte 275
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451358
    .string "IRON ARMOR$", 12
    .2byte 21 @ in decimeters
    .2byte 3600 @ in hectograms
    .4byte Text_844C738
    .4byte Text_844C7A0
    .2byte 0 @ unused
    .2byte 274
    .2byte -1
    .2byte 374
    .2byte 7
    .2byte 0 @ padding

    @ 845137C
    .string "MEDITATE$", 12
    .2byte 6 @ in decimeters
    .2byte 112 @ in hectograms
    .4byte Text_844C7A1
    .4byte Text_844C7FD
    .2byte 0 @ unused
    .2byte 465
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84513A0
    .string "MEDITATE$", 12
    .2byte 13 @ in decimeters
    .2byte 315 @ in hectograms
    .4byte Text_844C7FE
    .4byte Text_844C867
    .2byte 0 @ unused
    .2byte 298
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84513C4
    .string "LIGHTNING$", 12
    .2byte 6 @ in decimeters
    .2byte 152 @ in hectograms
    .4byte Text_844C868
    .4byte Text_844C8CC
    .2byte 0 @ unused
    .2byte 290
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84513E8
    .string "DISCHARGE$", 12
    .2byte 15 @ in decimeters
    .2byte 402 @ in hectograms
    .4byte Text_844C8CD
    .4byte Text_844C91D
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 257
    .2byte -2
    .2byte 0 @ padding

    @ 845140C
    .string "CHEERING$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte Text_844C91E
    .4byte Text_844C98C
    .2byte 0 @ unused
    .2byte 515
    .2byte -9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451430
    .string "CHEERING$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte Text_844C98D
    .4byte Text_844CA09
    .2byte 0 @ unused
    .2byte 512
    .2byte -7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451454
    .string "FIREFLY$", 12
    .2byte 7 @ in decimeters
    .2byte 177 @ in hectograms
    .4byte Text_844CA0A
    .4byte Text_844CA75
    .2byte 0 @ unused
    .2byte 442
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451478
    .string "FIREFLY$", 12
    .2byte 6 @ in decimeters
    .2byte 177 @ in hectograms
    .4byte Text_844CA76
    .4byte Text_844CADF
    .2byte 0 @ unused
    .2byte 572
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845149C
    .string "THORN$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text_844CAE0
    .4byte Text_844CB41
    .2byte 0 @ unused
    .2byte 677
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84514C0
    .string "STOMACH$", 12
    .2byte 4 @ in decimeters
    .2byte 103 @ in hectograms
    .4byte Text_844CB42
    .4byte Text_844CBAB
    .2byte 0 @ unused
    .2byte 593
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84514E4
    .string "POISON BAG$", 12
    .2byte 17 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte Text_844CBAC
    .4byte Text_844CC14
    .2byte 0 @ unused
    .2byte 256
    .2byte 5
    .2byte 345
    .2byte 4
    .2byte 0 @ padding

    @ 8451508
    .string "SAVAGE$", 12
    .2byte 8 @ in decimeters
    .2byte 208 @ in hectograms
    .4byte Text_844CC15
    .4byte Text_844CC76
    .2byte 0 @ unused
    .2byte 362
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845152C
    .string "BRUTAL$", 12
    .2byte 18 @ in decimeters
    .2byte 888 @ in hectograms
    .4byte Text_844CC77
    .4byte Text_844CCE0
    .2byte 0 @ unused
    .2byte 265
    .2byte 0
    .2byte 342
    .2byte 4
    .2byte 0 @ padding

    @ 8451550
    .string "BALL WHALE$", 12
    .2byte 20 @ in decimeters
    .2byte 1300 @ in hectograms
    .4byte Text_844CCE1
    .4byte Text_844CD4F
    .2byte 0 @ unused
    .2byte 256
    .2byte 10
    .2byte 493
    .2byte 10
    .2byte 0 @ padding

    @ 8451574
    .string "FLOAT WHALE$", 12
    .2byte 145 @ in decimeters
    .2byte 3980 @ in hectograms
    .4byte Text_844CD50
    .4byte Text_844CDBB
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 1428
    .2byte 20
    .2byte 0 @ padding

    @ 8451598
    .string "NUMB$", 12
    .2byte 7 @ in decimeters
    .2byte 240 @ in hectograms
    .4byte Text_844CDBC
    .4byte Text_844CE33
    .2byte 0 @ unused
    .2byte 310
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84515BC
    .string "ERUPTION$", 12
    .2byte 19 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte Text_844CE34
    .4byte Text_844CE9E
    .2byte 0 @ unused
    .2byte 256
    .2byte 6
    .2byte 345
    .2byte 4
    .2byte 0 @ padding

    @ 84515E0
    .string "COAL$", 12
    .2byte 5 @ in decimeters
    .2byte 804 @ in hectograms
    .4byte Text_844CE9F
    .4byte Text_844CEFB
    .2byte 0 @ unused
    .2byte 392
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451604
    .string "BOUNCE$", 12
    .2byte 7 @ in decimeters
    .2byte 306 @ in hectograms
    .4byte Text_844CEFC
    .4byte Text_844CF59
    .2byte 0 @ unused
    .2byte 423
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451628
    .string "MANIPULATE$", 12
    .2byte 9 @ in decimeters
    .2byte 715 @ in hectograms
    .4byte Text_844CF5A
    .4byte Text_844CFC6
    .2byte 0 @ unused
    .2byte 358
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845164C
    .string "SPOT PANDA$", 12
    .2byte 11 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text_844CFC7
    .4byte Text_844D027
    .2byte 0 @ unused
    .2byte 321
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451670
    .string "ANT PIT$", 12
    .2byte 7 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text_844D028
    .4byte Text_844D086
    .2byte 0 @ unused
    .2byte 298
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451694
    .string "VIBRATION$", 12
    .2byte 11 @ in decimeters
    .2byte 153 @ in hectograms
    .4byte Text_844D087
    .4byte Text_844D100
    .2byte 0 @ unused
    .2byte 370
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84516B8
    .string "MYSTIC$", 12
    .2byte 20 @ in decimeters
    .2byte 820 @ in hectograms
    .4byte Text_844D101
    .4byte Text_844D161
    .2byte 0 @ unused
    .2byte 280
    .2byte 0
    .2byte 299
    .2byte 2
    .2byte 0 @ padding

    @ 84516DC
    .string "CACTUS$", 12
    .2byte 4 @ in decimeters
    .2byte 513 @ in hectograms
    .4byte Text_844D162
    .4byte Text_844D1C9
    .2byte 0 @ unused
    .2byte 455
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451700
    .string "SCARECROW$", 12
    .2byte 13 @ in decimeters
    .2byte 774 @ in hectograms
    .4byte Text_844D1CA
    .4byte Text_844D233
    .2byte 0 @ unused
    .2byte 327
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451724
    .string "COTTON BIRD$", 12
    .2byte 4 @ in decimeters
    .2byte 12 @ in hectograms
    .4byte Text_844D234
    .4byte Text_844D297
    .2byte 0 @ unused
    .2byte 422
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451748
    .string "HUMMING$", 12
    .2byte 11 @ in decimeters
    .2byte 206 @ in hectograms
    .4byte Text_844D298
    .4byte Text_844D2FF
    .2byte 0 @ unused
    .2byte 327
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845176C
    .string "CAT FERRET$", 12
    .2byte 13 @ in decimeters
    .2byte 403 @ in hectograms
    .4byte Text_844D300
    .4byte Text_844D374
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451790
    .string "FANG SNAKE$", 12
    .2byte 27 @ in decimeters
    .2byte 525 @ in hectograms
    .4byte Text_844D375
    .4byte Text_844D3E7
    .2byte 0 @ unused
    .2byte 275
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84517B4
    .string "METEORITE$", 12
    .2byte 10 @ in decimeters
    .2byte 1680 @ in hectograms
    .4byte Text_844D3E8
    .4byte Text_844D458
    .2byte 0 @ unused
    .2byte 300
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84517D8
    .string "METEORITE$", 12
    .2byte 12 @ in decimeters
    .2byte 1540 @ in hectograms
    .4byte Text_844D459
    .4byte Text_844D4BF
    .2byte 0 @ unused
    .2byte 328
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84517FC
    .string "WHISKERS$", 12
    .2byte 4 @ in decimeters
    .2byte 19 @ in hectograms
    .4byte Text_844D4C0
    .4byte Text_844D516
    .2byte 0 @ unused
    .2byte 581
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451820
    .string "WHISKERS$", 12
    .2byte 9 @ in decimeters
    .2byte 236 @ in hectograms
    .4byte Text_844D517
    .4byte Text_844D580
    .2byte 0 @ unused
    .2byte 317
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451844
    .string "RUFFIAN$", 12
    .2byte 6 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text_844D581
    .4byte Text_844D5ED
    .2byte 0 @ unused
    .2byte 484
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451868
    .string "ROGUE$", 12
    .2byte 11 @ in decimeters
    .2byte 328 @ in hectograms
    .4byte Text_844D5EE
    .4byte Text_844D64D
    .2byte 0 @ unused
    .2byte 365
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845188C
    .string "CLAY DOLL$", 12
    .2byte 5 @ in decimeters
    .2byte 215 @ in hectograms
    .4byte Text_844D64E
    .4byte Text_844D6BD
    .2byte 0 @ unused
    .2byte 384
    .2byte 18
    .2byte 256
    .2byte -3
    .2byte 0 @ padding

    @ 84518B0
    .string "CLAY DOLL$", 12
    .2byte 15 @ in decimeters
    .2byte 1080 @ in hectograms
    .4byte Text_844D6BE
    .4byte Text_844D72A
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 280
    .2byte 0
    .2byte 0 @ padding

    @ 84518D4
    .string "SEA LILY$", 12
    .2byte 10 @ in decimeters
    .2byte 238 @ in hectograms
    .4byte Text_844D72B
    .4byte Text_844D798
    .2byte 0 @ unused
    .2byte 305
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84518F8
    .string "BARNACLE$", 12
    .2byte 15 @ in decimeters
    .2byte 604 @ in hectograms
    .4byte Text_844D799
    .4byte Text_844D7FE
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 269
    .2byte -1
    .2byte 0 @ padding

    @ 845191C
    .string "OLD SHRIMP$", 12
    .2byte 7 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte Text_844D7FF
    .4byte Text_844D871
    .2byte 0 @ unused
    .2byte 296
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451940
    .string "PLATE$", 12
    .2byte 15 @ in decimeters
    .2byte 682 @ in hectograms
    .4byte Text_844D872
    .4byte Text_844D8CE
    .2byte 0 @ unused
    .2byte 312
    .2byte 2
    .2byte 271
    .2byte -1
    .2byte 0 @ padding

    @ 8451964
    .string "FISH$", 12
    .2byte 6 @ in decimeters
    .2byte 74 @ in hectograms
    .4byte Text_844D8CF
    .4byte Text_844D937
    .2byte 0 @ unused
    .2byte 423
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451988
    .string "TENDER$", 12
    .2byte 62 @ in decimeters
    .2byte 1620 @ in hectograms
    .4byte Text_844D938
    .4byte Text_844D99B
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 382
    .2byte 7
    .2byte 0 @ padding

    @ 84519AC
    .string "WEATHER$", 12
    .2byte 3 @ in decimeters
    .2byte 8 @ in hectograms
    .4byte Text_844D99C
    .4byte Text_844DA06
    .2byte 0 @ unused
    .2byte 435
    .2byte -5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84519D0
    .string "COLOR SWAP$", 12
    .2byte 10 @ in decimeters
    .2byte 220 @ in hectograms
    .4byte Text_844DA07
    .4byte Text_844DA6D
    .2byte 0 @ unused
    .2byte 316
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84519F4
    .string "PUPPET$", 12
    .2byte 6 @ in decimeters
    .2byte 23 @ in hectograms
    .4byte Text_844DA6E
    .4byte Text_844DAD2
    .2byte 0 @ unused
    .2byte 440
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451A18
    .string "MARIONETTE$", 12
    .2byte 11 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte Text_844DAD3
    .4byte Text_844DB3F
    .2byte 0 @ unused
    .2byte 262
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451A3C
    .string "REQUIEM$", 12
    .2byte 8 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text_844DB40
    .4byte Text_844DBA8
    .2byte 0 @ unused
    .2byte 376
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451A60
    .string "BECKON$", 12
    .2byte 16 @ in decimeters
    .2byte 306 @ in hectograms
    .4byte Text_844DBA9
    .4byte Text_844DC12
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 299
    .2byte 2
    .2byte 0 @ padding

    @ 8451A84
    .string "FRUIT$", 12
    .2byte 20 @ in decimeters
    .2byte 1000 @ in hectograms
    .4byte Text_844DC13
    .4byte Text_844DC80
    .2byte 0 @ unused
    .2byte 283
    .2byte -1
    .2byte 371
    .2byte 6
    .2byte 0 @ padding

    @ 8451AA8
    .string "WIND CHIME$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text_844DC81
    .4byte Text_844DCF1
    .2byte 0 @ unused
    .2byte 505
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451ACC
    .string "DISASTER$", 12
    .2byte 12 @ in decimeters
    .2byte 470 @ in hectograms
    .4byte Text_844DCF2
    .4byte Text_844DD5B
    .2byte 0 @ unused
    .2byte 301
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451AF0
    .string "BRIGHT$", 12
    .2byte 6 @ in decimeters
    .2byte 140 @ in hectograms
    .4byte Text_844DD5C
    .4byte Text_844DDB6
    .2byte 0 @ unused
    .2byte 453
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451B14
    .string "SNOW HAT$", 12
    .2byte 7 @ in decimeters
    .2byte 168 @ in hectograms
    .4byte Text_844DDB7
    .4byte Text_844DE28
    .2byte 0 @ unused
    .2byte 380
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451B38
    .string "FACE$", 12
    .2byte 15 @ in decimeters
    .2byte 2565 @ in hectograms
    .4byte Text_844DE29
    .4byte Text_844DE93
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 344
    .2byte 2
    .2byte 0 @ padding

    @ 8451B5C
    .string "CLAP$", 12
    .2byte 8 @ in decimeters
    .2byte 395 @ in hectograms
    .4byte Text_844DE94
    .4byte Text_844DEF6
    .2byte 0 @ unused
    .2byte 315
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451B80
    .string "BALL ROLL$", 12
    .2byte 11 @ in decimeters
    .2byte 876 @ in hectograms
    .4byte Text_844DEF7
    .4byte Text_844DF60
    .2byte 0 @ unused
    .2byte 338
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451BA4
    .string "ICE BREAK$", 12
    .2byte 14 @ in decimeters
    .2byte 1506 @ in hectograms
    .4byte Text_844DF61
    .4byte Text_844DFD2
    .2byte 0 @ unused
    .2byte 305
    .2byte 2
    .2byte 277
    .2byte 0
    .2byte 0 @ padding

    @ 8451BC8
    .string "BIVALVE$", 12
    .2byte 4 @ in decimeters
    .2byte 525 @ in hectograms
    .4byte Text_844DFD3
    .4byte Text_844E028
    .2byte 0 @ unused
    .2byte 691
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451BEC
    .string "DEEP SEA$", 12
    .2byte 17 @ in decimeters
    .2byte 270 @ in hectograms
    .4byte Text_844E029
    .4byte Text_844E09A
    .2byte 0 @ unused
    .2byte 307
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451C10
    .string "SOUTH SEA$", 12
    .2byte 18 @ in decimeters
    .2byte 226 @ in hectograms
    .4byte Text_844E09B
    .4byte Text_844E108
    .2byte 0 @ unused
    .2byte 278
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451C34
    .string "LONGEVITY$", 12
    .2byte 10 @ in decimeters
    .2byte 234 @ in hectograms
    .4byte Text_844E109
    .4byte Text_844E16B
    .2byte 0 @ unused
    .2byte 316
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451C58
    .string "RENDEZVOUS$", 12
    .2byte 6 @ in decimeters
    .2byte 87 @ in hectograms
    .4byte Text_844E16C
    .4byte Text_844E1CE
    .2byte 0 @ unused
    .2byte 371
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451C7C
    .string "ROCK HEAD$", 12
    .2byte 6 @ in decimeters
    .2byte 421 @ in hectograms
    .4byte Text_844E1CF
    .4byte Text_844E22D
    .2byte 0 @ unused
    .2byte 448
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451CA0
    .string "ENDURANCE$", 12
    .2byte 11 @ in decimeters
    .2byte 1105 @ in hectograms
    .4byte Text_844E22E
    .4byte Text_844E2A5
    .2byte 0 @ unused
    .2byte 311
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451CC4
    .string "DRAGON$", 12
    .2byte 15 @ in decimeters
    .2byte 1026 @ in hectograms
    .4byte Text_844E2A6
    .4byte Text_844E308
    .2byte 0 @ unused
    .2byte 272
    .2byte 2
    .2byte 307
    .2byte 0
    .2byte 0 @ padding

    @ 8451CE8
    .string "IRON BALL$", 12
    .2byte 6 @ in decimeters
    .2byte 952 @ in hectograms
    .4byte Text_844E309
    .4byte Text_844E363
    .2byte 0 @ unused
    .2byte 414
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451D0C
    .string "IRON CLAW$", 12
    .2byte 12 @ in decimeters
    .2byte 2025 @ in hectograms
    .4byte Text_844E364
    .4byte Text_844E3D1
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 8451D30
    .string "IRON LEG$", 12
    .2byte 16 @ in decimeters
    .2byte 5500 @ in hectograms
    .4byte Text_844E3D2
    .4byte Text_844E431
    .2byte 0 @ unused
    .2byte 272
    .2byte 3
    .2byte 461
    .2byte 4
    .2byte 0 @ padding

    @ 8451D54
    .string "ROCK PEAK$", 12
    .2byte 17 @ in decimeters
    .2byte 2300 @ in hectograms
    .4byte Text_844E432
    .4byte Text_844E4A0
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 309
    .2byte 1
    .2byte 0 @ padding

    @ 8451D78
    .string "ICEBERG$", 12
    .2byte 18 @ in decimeters
    .2byte 1750 @ in hectograms
    .4byte Text_844E4A1
    .4byte Text_844E502
    .2byte 0 @ unused
    .2byte 265
    .2byte 0
    .2byte 317
    .2byte 3
    .2byte 0 @ padding

    @ 8451D9C
    .string "IRON$", 12
    .2byte 19 @ in decimeters
    .2byte 2050 @ in hectograms
    .4byte Text_844E503
    .4byte Text_844E573
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 359
    .2byte 6
    .2byte 0 @ padding

    @ 8451DC0
    .string "EON$", 12
    .2byte 14 @ in decimeters
    .2byte 400 @ in hectograms
    .4byte Text_844E574
    .4byte Text_844E5E1
    .2byte 0 @ unused
    .2byte 291
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451DE4
    .string "EON$", 12
    .2byte 20 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text_844E5E2
    .4byte Text_844E652
    .2byte 0 @ unused
    .2byte 273
    .2byte 0
    .2byte 313
    .2byte 3
    .2byte 0 @ padding

    @ 8451E08
    .string "SEA BASIN$", 12
    .2byte 45 @ in decimeters
    .2byte 3520 @ in hectograms
    .4byte Text_844E653
    .4byte Text_844E6BD
    .2byte 0 @ unused
    .2byte 272
    .2byte 1
    .2byte 639
    .2byte 13
    .2byte 0 @ padding

    @ 8451E2C
    .string "CONTINENT$", 12
    .2byte 35 @ in decimeters
    .2byte 9500 @ in hectograms
    .4byte Text_844E6BE
    .4byte Text_844E71B
    .2byte 0 @ unused
    .2byte 276
    .2byte 0
    .2byte 530
    .2byte 12
    .2byte 0 @ padding

    @ 8451E50
    .string "SKY HIGH$", 12
    .2byte 70 @ in decimeters
    .2byte 2065 @ in hectograms
    .4byte Text_844E71C
    .4byte Text_844E784
    .2byte 0 @ unused
    .2byte 286
    .2byte -1
    .2byte 483
    .2byte 9
    .2byte 0 @ padding

    @ 8451E74
    .string "WISH$", 12
    .2byte 3 @ in decimeters
    .2byte 11 @ in hectograms
    .4byte Text_844E785
    .4byte Text_844E7E5
    .2byte 0 @ unused
    .2byte 608
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451E98
    .string "DNA$", 12
    .2byte 17 @ in decimeters
    .2byte 608 @ in hectograms
    .4byte Text_844E7E6
    .4byte Text_844E84D
    .2byte 0 @ unused
    .2byte 293
    .2byte 0
    .2byte 337
    .2byte 2
    .2byte 0 @ padding
