kPokedexDescription1_NONE:: @ 8444C35
    .string "This is a newly discovered POKéMON. It is\n"
    .string "currently under investigation. No detailed\n"
    .string "information is available at this time.$"

kPokedexDescription2_NONE:: @ 8444CB1
    .string "$"

kPokedexDescription1_BULBASAUR:: @ 8444CB2
    .string "There is a plant seed on its back right\n"
    .string "from the day this POKéMON is born.\n"
    .string "The seed slowly grows larger.$"

kPokedexDescription2_BULBASAUR:: @ 8444D1B
    .string "$"

kPokedexDescription1_IVYSAUR:: @ 8444D1C
    .string "There is a plant bulb on its back.\n"
    .string "When it absorbs nutrients, the bulb is said\n"
    .string "to blossom into a large flower.$"

kPokedexDescription2_IVYSAUR:: @ 8444D8B
    .string "$"

kPokedexDescription1_VENUSAUR:: @ 8444D8C
    .string "A bewitching aroma wafts from its flower.\n"
    .string "The fragrance becalms those engaged in\n"
    .string "a battle.$"

kPokedexDescription2_VENUSAUR:: @ 8444DE7
    .string "$"

kPokedexDescription1_CHARMANDER:: @ 8444DE8
    .string "From the time it is born, a flame burns\n"
    .string "at the tip of its tail. Its life would end\n"
    .string "if the flame were to go out.$"

kPokedexDescription2_CHARMANDER:: @ 8444E58
    .string "$"

kPokedexDescription1_CHARMELEON:: @ 8444E59
    .string "It lashes about with its tail to knock\n"
    .string "down its foe. It then tears up the fallen\n"
    .string "opponent with sharp claws.$"

kPokedexDescription2_CHARMELEON:: @ 8444EC5
    .string "$"

kPokedexDescription1_CHARIZARD:: @ 8444EC6
    .string "Its wings can carry this POKéMON close to\n"
    .string "an altitude of 4,600 feet. It blows out\n"
    .string "fire at very high temperatures.$"

kPokedexDescription2_CHARIZARD:: @ 8444F38
    .string "$"

kPokedexDescription1_SQUIRTLE:: @ 8444F39
    .string "When it retracts its long neck into its\n"
    .string "shell, it squirts out water with vigorous\n"
    .string "force.$"

kPokedexDescription2_SQUIRTLE:: @ 8444F92
    .string "$"

kPokedexDescription1_WARTORTLE:: @ 8444F93
    .string "This POKéMON is very popular as a pet.\n"
    .string "Its fur-covered tail is a symbol of its\n"
    .string "longevity.$"

kPokedexDescription2_WARTORTLE:: @ 8444FED
    .string "$"

kPokedexDescription1_BLASTOISE:: @ 8444FEE
    .string "It crushes its foe under its heavy body\n"
    .string "to cause fainting. In a pinch, it will\n"
    .string "withdraw inside its shell.$"

kPokedexDescription2_BLASTOISE:: @ 8445058
    .string "$"

kPokedexDescription1_CATERPIE:: @ 8445059
    .string "It is covered with a green skin. When it\n"
    .string "grows, it sheds the skin, covers itself\n"
    .string "with silk, and becomes a cocoon.$"

kPokedexDescription2_CATERPIE:: @ 84450CB
    .string "$"

kPokedexDescription1_METAPOD:: @ 84450CC
    .string "Even though it is encased in a sturdy\n"
    .string "shell, the body inside is tender.\n"
    .string "It can’t withstand a harsh attack.$"

kPokedexDescription2_METAPOD:: @ 8445137
    .string "$"

kPokedexDescription1_BUTTERFREE:: @ 8445138
    .string "The wings are protected by rain-repellent\n"
    .string "dust. As a result, this POKéMON can fly\n"
    .string "about even in rain.$"

kPokedexDescription2_BUTTERFREE:: @ 844519E
    .string "$"

kPokedexDescription1_WEEDLE:: @ 844519F
    .string "Often found in forests and grasslands.\n"
    .string "It has a sharp, toxic barb of around two\n"
    .string "inches on top of its head.$"

kPokedexDescription2_WEEDLE:: @ 844520A
    .string "$"

kPokedexDescription1_KAKUNA:: @ 844520B
    .string "This POKéMON is in a temporary stage\n"
    .string "while making its body. It is almost\n"
    .string "completely unable to move on its own.$"

kPokedexDescription2_KAKUNA:: @ 844527A
    .string "$"

kPokedexDescription1_BEEDRILL:: @ 844527B
    .string "May appear in a swarm. Flies at violent\n"
    .string "speeds, all the while stabbing with the\n"
    .string "toxic stinger on its rear.$"

kPokedexDescription2_BEEDRILL:: @ 84452E6
    .string "$"

kPokedexDescription1_PIDGEY:: @ 84452E7
    .string "Does not like to fight. It hides in\n"
    .string "tall grass and so on, foraging for food\n"
    .string "such as small bugs.$"

kPokedexDescription2_PIDGEY:: @ 8445347
    .string "$"

kPokedexDescription1_PIDGEOTTO:: @ 8445348
    .string "The claws on its feet are well developed.\n"
    .string "It can carry prey such as an EXEGGCUTE\n"
    .string "to its nest over 60 miles away.$"

kPokedexDescription2_PIDGEOTTO:: @ 84453B9
    .string "$"

kPokedexDescription1_PIDGEOT:: @ 84453BA
    .string "It spreads its gorgeous wings widely to\n"
    .string "intimidate enemies. It races through the\n"
    .string "skies at Mach-2 speed.$"

kPokedexDescription2_PIDGEOT:: @ 8445422
    .string "$"

kPokedexDescription1_RATTATA:: @ 8445423
    .string "Its fangs are long and very sharp.\n"
    .string "They grow continuously, so it gnaws on\n"
    .string "hard things to whittle them down.$"

kPokedexDescription2_RATTATA:: @ 844548F
    .string "$"

kPokedexDescription1_RATICATE:: @ 8445490
    .string "Its rear feet have three toes each.\n"
    .string "They are webbed, enabling it to swim\n"
    .string "across rivers.$"

kPokedexDescription2_RATICATE:: @ 84454E8
    .string "$"

kPokedexDescription1_SPEAROW:: @ 84454E9
    .string "It busily flits around here and there.\n"
    .string "Even if it is frail, it can be a tough\n"
    .string "foe that uses MIRROR MOVE.$"

kPokedexDescription2_SPEAROW:: @ 8445552
    .string "$"

kPokedexDescription1_FEAROW:: @ 8445553
    .string "Its huge and magnificent wings can keep it\n"
    .string "aloft in the sky. It can remain flying a\n"
    .string "whole day without landing.$"

kPokedexDescription2_FEAROW:: @ 84455C2
    .string "$"

kPokedexDescription1_EKANS:: @ 84455C3
    .string "A very common sight in grassland, etc.\n"
    .string "It flicks its tongue in and out to sense\n"
    .string "danger in its surroundings.$"

kPokedexDescription2_EKANS:: @ 844562F
    .string "$"

kPokedexDescription1_ARBOK:: @ 8445630
    .string "The pattern on its belly appears to be a\n"
    .string "frightening face. Weak foes will flee just\n"
    .string "at the sight of the pattern.$"

kPokedexDescription2_ARBOK:: @ 84456A1
    .string "$"

kPokedexDescription1_PIKACHU:: @ 84456A2
    .string "It has small electric sacs on both its\n"
    .string "cheeks. If threatened, it looses electric\n"
    .string "charges from the sacs.$"

kPokedexDescription2_PIKACHU:: @ 844570A
    .string "$"

kPokedexDescription1_RAICHU:: @ 844570B
    .string "Its electric charges can reach even\n"
    .string "100,000 volts. Careless contact can cause\n"
    .string "even an Indian elephant to faint.$"

kPokedexDescription2_RAICHU:: @ 844577B
    .string "$"

kPokedexDescription1_SANDSHREW:: @ 844577C
    .string "It burrows and lives underground.\n"
    .string "If threatened, it curls itself up into a\n"
    .string "ball for protection.$"

kPokedexDescription2_SANDSHREW:: @ 84457DC
    .string "$"

kPokedexDescription1_SANDSLASH:: @ 84457DD
    .string "It is adept at attacking with the spines\n"
    .string "on its back and its sharp claws while\n"
    .string "quickly scurrying about.$"

kPokedexDescription2_SANDSLASH:: @ 8445845
    .string "$"

kPokedexDescription1_NIDORAN_F:: @ 8445846
    .string "Though small, it must be treated with\n"
    .string "caution because of its powerfully toxic\n"
    .string "barbs. The female has smaller horns.$"

kPokedexDescription2_NIDORAN_F:: @ 84458B9
    .string "$"

kPokedexDescription1_NIDORINA:: @ 84458BA
    .string "The female has a gentle temperament.\n"
    .string "It emits ultrasonic cries that have the\n"
    .string "power to befuddle foes.$"

kPokedexDescription2_NIDORINA:: @ 844591F
    .string "$"

kPokedexDescription1_NIDOQUEEN:: @ 8445920
    .string "The body is covered by stiff, needle-\n"
    .string "like scales. If it becomes excited,\n"
    .string "the needles bristle outwards.$"

kPokedexDescription2_NIDOQUEEN:: @ 8445988
    .string "$"

kPokedexDescription1_NIDORAN_M:: @ 8445989
    .string "Its large ears are flapped like wings\n"
    .string "when it is listening to distant sounds.\n"
    .string "It extends toxic barbs when angered.$"

kPokedexDescription2_NIDORAN_M:: @ 84459FC
    .string "$"

kPokedexDescription1_NIDORINO:: @ 84459FD
    .string "It is easily angered. By swinging its well-\n"
    .string "developed horn wildly, it can even punch\n"
    .string "through diamond.$"

kPokedexDescription2_NIDORINO:: @ 8445A63
    .string "$"

kPokedexDescription1_NIDOKING:: @ 8445A64
    .string "It is recognized by its rock-hard hide\n"
    .string "and its extended horn. Be careful with\n"
    .string "the horn as it contains venom.$"

kPokedexDescription2_NIDOKING:: @ 8445AD1
    .string "$"

kPokedexDescription1_CLEFAIRY:: @ 8445AD2
    .string "Its adorable appearance makes it popular\n"
    .string "as a pet. However, it is rare and\n"
    .string "difficult to find.$"

kPokedexDescription2_CLEFAIRY:: @ 8445B30
    .string "$"

kPokedexDescription1_CLEFABLE:: @ 8445B31
    .string "It has an acute sense of hearing. It can\n"
    .string "easily hear a pin being dropped nearly\n"
    .string "1,100 yards away.$"

kPokedexDescription2_CLEFABLE:: @ 8445B93
    .string "$"

kPokedexDescription1_VULPIX:: @ 8445B94
    .string "While young, it has six gorgeous tails.\n"
    .string "When it grows, several new tails are\n"
    .string "sprouted.$"

kPokedexDescription2_VULPIX:: @ 8445BEB
    .string "$"

kPokedexDescription1_NINETALES:: @ 8445BEC
    .string "It has nine long tails and fur that \n"
    .string "gleams gold. It is said to live for \n"
    .string "1,000 years.$"

kPokedexDescription2_NINETALES:: @ 8445C43
    .string "$"

kPokedexDescription1_JIGGLYPUFF:: @ 8445C44
    .string "It captivates foes with its huge, round\n"
    .string "eyes, then lulls them to sleep by singing\n"
    .string "a soothing melody.$"

kPokedexDescription2_JIGGLYPUFF:: @ 8445CA9
    .string "$"

kPokedexDescription1_WIGGLYTUFF:: @ 8445CAA
    .string "Its fur is extremely fine, dense, and\n"
    .string "supple. The exquisitely pleasant fur\n"
    .string "conveys an image of luxury.$"

kPokedexDescription2_WIGGLYTUFF:: @ 8445D11
    .string "$"

kPokedexDescription1_ZUBAT:: @ 8445D12
    .string "It has no eyes. Instead, it relies on\n"
    .string "its ultrasonic cries for echo location to\n"
    .string "flit about in darkness.$"

kPokedexDescription2_ZUBAT:: @ 8445D7A
    .string "$"

kPokedexDescription1_GOLBAT:: @ 8445D7B
    .string "It clamps down on its prey with needle-\n"
    .string "sharp fangs and drains over 10 ounces of\n"
    .string "blood in one gulp.$"

kPokedexDescription2_GOLBAT:: @ 8445DDF
    .string "$"

kPokedexDescription1_ODDISH:: @ 8445DE0
    .string "Its scientific name is “Oddium Wanderus.”\n"
    .string "At night, it is said to walk nearly 1,000\n"
    .string "feet on its two roots.$"

kPokedexDescription2_ODDISH:: @ 8445E4B
    .string "$"

kPokedexDescription1_GLOOM:: @ 8445E4C
    .string "Its pistils exude an incredibly foul odor.\n"
    .string "The horrid stench can cause fainting at a\n"
    .string "distance of 1.25 miles.$"

kPokedexDescription2_GLOOM:: @ 8445EB9
    .string "$"

kPokedexDescription1_VILEPLUME:: @ 8445EBA
    .string "Its petals are the largest in the world.\n"
    .string "It fiendishly scatters allergy-causing\n"
    .string "pollen from its petals.$"

kPokedexDescription2_VILEPLUME:: @ 8445F22
    .string "$"

kPokedexDescription1_PARAS:: @ 8445F23
    .string "Growing out of the bug’s back are\n"
    .string "mushrooms called tochukaso. The mushrooms\n"
    .string "grow with the bug host.$"

kPokedexDescription2_PARAS:: @ 8445F87
    .string "$"

kPokedexDescription1_PARASECT:: @ 8445F88
    .string "It scatters toxic spores from the\n"
    .string "mushroom cap. In China, the spores are\n"
    .string "used as herbal medicine.$"

kPokedexDescription2_PARASECT:: @ 8445FEA
    .string "$"

kPokedexDescription1_VENONAT:: @ 8445FEB
    .string "Its eyes act as radar, enabling it to be\n"
    .string "active in darkness. The eyes can also\n"
    .string "shoot powerful beams.$"

kPokedexDescription2_VENONAT:: @ 8446050
    .string "$"

kPokedexDescription1_VENOMOTH:: @ 8446051
    .string "The wings are covered with dustlike\n"
    .string "scales. Every time it flaps its wings, it\n"
    .string "looses highly toxic dust.$"

kPokedexDescription2_VENOMOTH:: @ 84460B9
    .string "$"

kPokedexDescription1_DIGLETT:: @ 84460BA
    .string "It burrows through the ground at a\n"
    .string "shallow depth. It leaves raised earth in\n"
    .string "its wake, making it easy to spot.$"

kPokedexDescription2_DIGLETT:: @ 8446128
    .string "$"

kPokedexDescription1_DUGTRIO:: @ 8446129
    .string "In battle, it digs through the ground and\n"
    .string "strikes the unsuspecting foe from an\n"
    .string "unexpected direction.$"

kPokedexDescription2_DUGTRIO:: @ 844618E
    .string "$"

kPokedexDescription1_MEOWTH:: @ 844618F
    .string "All it does is sleep during the daytime.\n"
    .string "At night, it patrols its territory with its\n"
    .string "eyes aglow.$"

kPokedexDescription2_MEOWTH:: @ 84461F0
    .string "$"

kPokedexDescription1_PERSIAN:: @ 84461F1
    .string "Has a vicious temperament. Beware if it\n"
    .string "raises its tail straight up. It is a signal\n"
    .string "that it is about to pounce and bite.$"

kPokedexDescription2_PERSIAN:: @ 844626A
    .string "$"

kPokedexDescription1_PSYDUCK:: @ 844626B
    .string "It is constantly wracked by a headache.\n"
    .string "When the headache turns intense, it begins\n"
    .string "using mysterious powers.$"

kPokedexDescription2_PSYDUCK:: @ 84462D7
    .string "$"

kPokedexDescription1_GOLDUCK:: @ 84462D8
    .string "The forelegs are webbed, helping to make\n"
    .string "it an adept swimmer. It can be seen\n"
    .string "swimming elegantly in lakes, etc.$"

kPokedexDescription2_GOLDUCK:: @ 8446347
    .string "$"

kPokedexDescription1_MANKEY:: @ 8446348
    .string "Light and agile on its feet, and ferocious\n"
    .string "in temperament. When angered, it flies into\n"
    .string "an uncontrollable frenzy.$"

kPokedexDescription2_MANKEY:: @ 84463B9
    .string "$"

kPokedexDescription1_PRIMEAPE:: @ 84463BA
    .string "It is always outrageously furious. If it\n"
    .string "gives chase, it will tenaciously track the\n"
    .string "target no matter how far.$"

kPokedexDescription2_PRIMEAPE:: @ 8446428
    .string "$"

kPokedexDescription1_GROWLITHE:: @ 8446429
    .string "Very friendly and faithful to people.\n"
    .string "It will try to repel enemies by barking\n"
    .string "and biting.$"

kPokedexDescription2_GROWLITHE:: @ 8446483
    .string "$"

kPokedexDescription1_ARCANINE:: @ 8446484
    .string "A POKéMON that is described in Chinese\n"
    .string "legends. It is said to race at an\n"
    .string "unbelievable speed.$"

kPokedexDescription2_ARCANINE:: @ 84464E1
    .string "$"

kPokedexDescription1_POLIWAG:: @ 84464E2
    .string "Its slick black skin is thin and damp.\n"
    .string "A part of its internal organs can be seen\n"
    .string "through the skin as a spiral pattern.$"

kPokedexDescription2_POLIWAG:: @ 8446559
    .string "$"

kPokedexDescription1_POLIWHIRL:: @ 844655A
    .string "Its two legs are well developed.\n"
    .string "Even though it can live on the ground,\n"
    .string "it prefers living in water.$"

kPokedexDescription2_POLIWHIRL:: @ 84465BE
    .string "$"

kPokedexDescription1_POLIWRATH:: @ 84465BF
    .string "An adept swimmer, it knows the front\n"
    .string "crawl, butterfly, and more. It is faster\n"
    .string "than the best human swimmers.$"

kPokedexDescription2_POLIWRATH:: @ 844662B
    .string "$"

kPokedexDescription1_ABRA:: @ 844662C
    .string "It sleeps for 18 hours a day. It uses a\n"
    .string "variety of extrasensory powers even\n"
    .string "while asleep.$"

kPokedexDescription2_ABRA:: @ 8446686
    .string "$"

kPokedexDescription1_KADABRA:: @ 8446687
    .string "It happened one morning - a boy with\n"
    .string "extrasensory powers awoke in bed\n"
    .string "transformed into KADABRA.$"

kPokedexDescription2_KADABRA:: @ 84466E7
    .string "$"

kPokedexDescription1_ALAKAZAM:: @ 84466E8
    .string "It does not like physical attacks very \n"
    .string "much. Instead, it freely uses extra-\n"
    .string "sensory powers to defeat foes.$"

kPokedexDescription2_ALAKAZAM:: @ 8446754
    .string "$"

kPokedexDescription1_MACHOP:: @ 8446755
    .string "Its whole body is composed of muscles.\n"
    .string "Even though it’s the size of a human\n"
    .string "child, it can hurl 100 grown-ups.$"

kPokedexDescription2_MACHOP:: @ 84467C3
    .string "$"

kPokedexDescription1_MACHOKE:: @ 84467C4
    .string "Its formidable body never gets tired.\n"
    .string "It helps people by doing work such as\n"
    .string "the moving of heavy goods.$"

kPokedexDescription2_MACHOKE:: @ 844682B
    .string "$"

kPokedexDescription1_MACHAMP:: @ 844682C
    .string "Its four ruggedly developed arms can\n"
    .string "launch a flurry of 1,000 punches in just\n"
    .string "two seconds.$"

kPokedexDescription2_MACHAMP:: @ 8446887
    .string "$"

kPokedexDescription1_BELLSPROUT:: @ 8446888
    .string "Its bud looks like a human face. Because\n"
    .string "of the bud, it is rumored to be a type of\n"
    .string "legendary mandrake plant.$"

kPokedexDescription2_BELLSPROUT:: @ 84468F5
    .string "$"

kPokedexDescription1_WEEPINBELL:: @ 84468F6
    .string "The leafy parts act as cutters for\n"
    .string "slashing foes. It spits a fluid that\n"
    .string "dissolves everything.$"

kPokedexDescription2_WEEPINBELL:: @ 8446954
    .string "$"

kPokedexDescription1_VICTREEBEL:: @ 8446955
    .string "Lures prey into its mouth with a honeylike\n"
    .string "aroma. The helpless prey is melted with\n"
    .string "a dissolving fluid.$"

kPokedexDescription2_VICTREEBEL:: @ 84469BC
    .string "$"

kPokedexDescription1_TENTACOOL:: @ 84469BD
    .string "Its eyes are as transparent as crystals.\n"
    .string "From them, it shoots mysterious\n"
    .string "beams of light.$"

kPokedexDescription2_TENTACOOL:: @ 8446A16
    .string "$"

kPokedexDescription1_TENTACRUEL:: @ 8446A17
    .string "It has 80 tentacles that move about\n"
    .string "freely. They can sting, causing poisoning\n"
    .string "and sharp, stabbing pain.$"

kPokedexDescription2_TENTACRUEL:: @ 8446A7F
    .string "$"

kPokedexDescription1_GEODUDE:: @ 8446A80
    .string "Its round form makes it easy to pick up.\n"
    .string "Some people have used them to hurl\n"
    .string "at each other in a snowball fight.$"

kPokedexDescription2_GEODUDE:: @ 8446AEF
    .string "$"

kPokedexDescription1_GRAVELER:: @ 8446AF0
    .string "Be careful while hiking on mountain trails.\n"
    .string "GRAVELER may come rolling down the path\n"
    .string "without slowing.$"

kPokedexDescription2_GRAVELER:: @ 8446B55
    .string "$"

kPokedexDescription1_GOLEM:: @ 8446B56
    .string "It is enclosed in a hard shell that is as\n"
    .string "rugged as slabs of rock. It sheds skin\n"
    .string "once a year to grow larger.$"

kPokedexDescription2_GOLEM:: @ 8446BC3
    .string "$"

kPokedexDescription1_PONYTA:: @ 8446BC4
    .string "Its body is light, and its legs are\n"
    .string "incredibly powerful. It can clear\n"
    .string "Ayers Rock in one leap.$"

kPokedexDescription2_PONYTA:: @ 8446C22
    .string "$"

kPokedexDescription1_RAPIDASH:: @ 8446C23
    .string "It can gallop at a top speed of 150\n"
    .string "miles per hour. It can race as fast as a\n"
    .string "bullet train while ablaze.$"

kPokedexDescription2_RAPIDASH:: @ 8446C8B
    .string "$"

kPokedexDescription1_SLOWPOKE:: @ 8446C8C
    .string "It is always vacantly lost in thought, but\n"
    .string "no one knows what it is thinking about.\n"
    .string "It is good at fishing with its tail.$"

kPokedexDescription2_SLOWPOKE:: @ 8446D04
    .string "$"

kPokedexDescription1_SLOWBRO:: @ 8446D05
    .string "When a SLOWPOKE went hunting in the sea,\n"
    .string "its tail was bitten by a SHELLDER. That\n"
    .string "made it evolve into SLOWBRO.$"

kPokedexDescription2_SLOWBRO:: @ 8446D73
    .string "$"

kPokedexDescription1_MAGNEMITE:: @ 8446D74
    .string "It moves while constantly hovering.\n"
    .string "It discharges THUNDER WAVE and so on\n"
    .string "from the units at its sides.$"

kPokedexDescription2_MAGNEMITE:: @ 8446DDA
    .string "$"

kPokedexDescription1_MAGNETON:: @ 8446DDB
    .string "A linked cluster formed of several\n"
    .string "MAGNEMITE. It discharges powerful\n"
    .string "magnetic waves at high voltage.$"

kPokedexDescription2_MAGNETON:: @ 8446E40
    .string "$"

kPokedexDescription1_FARFETCHD:: @ 8446E41
    .string "It always walks about with a plant stalk\n"
    .string "clamped in its beak. The stalk is used for\n"
    .string "building its nest.$"

kPokedexDescription2_FARFETCHD:: @ 8446EA8
    .string "$"

kPokedexDescription1_DODUO:: @ 8446EA9
    .string "A two-headed POKéMON that was discovered\n"
    .string "as a sudden mutation. It runs at a pace\n"
    .string "of over 60 miles per hour.$"

kPokedexDescription2_DODUO:: @ 8446F15
    .string "$"

kPokedexDescription1_DODRIO:: @ 8446F16
    .string "An odd species that is rarely found.\n"
    .string "The three heads respectively represent\n"
    .string "joy, sadness, and anger.$"

kPokedexDescription2_DODRIO:: @ 8446F7B
    .string "$"

kPokedexDescription1_SEEL:: @ 8446F7C
    .string "Covered with light blue fur, its hide is\n"
    .string "thick and tough. It is active in bitter\n"
    .string "cold of minus 40 degrees Fahrenheit.$"

kPokedexDescription2_SEEL:: @ 8446FF2
    .string "$"

kPokedexDescription1_DEWGONG:: @ 8446FF3
    .string "Its body is covered with a pure white\n"
    .string "fur. The colder the weather, the more\n"
    .string "active it becomes.$"

kPokedexDescription2_DEWGONG:: @ 8447052
    .string "$"

kPokedexDescription1_GRIMER:: @ 8447053
    .string "Sludge exposed to X rays from the moon\n"
    .string "transformed into GRIMER. It loves feeding\n"
    .string "on filthy things.$"

kPokedexDescription2_GRIMER:: @ 84470B6
    .string "$"

kPokedexDescription1_MUK:: @ 84470B7
    .string "It is usually undetectable because it\n"
    .string "blends in with the ground. Touching it can\n"
    .string "cause terrible poisoning.$"

kPokedexDescription2_MUK:: @ 8447122
    .string "$"

kPokedexDescription1_SHELLDER:: @ 8447123
    .string "It is encased in a shell that is harder\n"
    .string "than diamond. Inside, however, it is\n"
    .string "surprisingly tender.$"

kPokedexDescription2_SHELLDER:: @ 8447185
    .string "$"

kPokedexDescription1_CLOYSTER:: @ 8447186
    .string "Its shell is extremely hard. It cannot be\n"
    .string "shattered, even with a bomb. The shell\n"
    .string "opens only when it is attacking.$"

kPokedexDescription2_CLOYSTER:: @ 84471F8
    .string "$"

kPokedexDescription1_GASTLY:: @ 84471F9
    .string "A being that exists as a thin gas. It can\n"
    .string "topple an Indian elephant by enveloping\n"
    .string "the prey in two seconds.$"

kPokedexDescription2_GASTLY:: @ 8447264
    .string "$"

kPokedexDescription1_HAUNTER:: @ 8447265
    .string "If you get the feeling of being watched\n"
    .string "in darkness when nobody is around,\n"
    .string "HAUNTER is there.$"

kPokedexDescription2_HAUNTER:: @ 84472C2
    .string "$"

kPokedexDescription1_GENGAR:: @ 84472C3
    .string "It is said to emerge from darkness to\n"
    .string "steal the lives of those who become lost\n"
    .string "in mountains.$"

kPokedexDescription2_GENGAR:: @ 8447320
    .string "$"

kPokedexDescription1_ONIX:: @ 8447321
    .string "It usually lives underground. It searches\n"
    .string "for food while boring its way through the\n"
    .string "ground at 50 miles per hour.$"

kPokedexDescription2_ONIX:: @ 8447392
    .string "$"

kPokedexDescription1_DROWZEE:: @ 8447393
    .string "A descendent of the legendary animal\n"
    .string "baku, which is said to eat dreams. It is\n"
    .string "skilled at hypnotism.$"

kPokedexDescription2_DROWZEE:: @ 84473F7
    .string "$"

kPokedexDescription1_HYPNO:: @ 84473F8
    .string "It carries a pendulum-like device. There\n"
    .string "once was an incident in which it took \n"
    .string "away a child it hypnotized.$"

kPokedexDescription2_HYPNO:: @ 8447464
    .string "$"

kPokedexDescription1_KRABBY:: @ 8447465
    .string "It can be found near the sea. The large\n"
    .string "pincers grow back if they are torn out of\n"
    .string "their sockets.$"

kPokedexDescription2_KRABBY:: @ 84474C6
    .string "$"

kPokedexDescription1_KINGLER:: @ 84474C7
    .string "Its large and hard pincer has 10,000-\n"
    .string "horsepower strength. However, being so\n"
    .string "big, it is unwieldy to move.$"

kPokedexDescription2_KINGLER:: @ 8447531
    .string "$"

kPokedexDescription1_VOLTORB:: @ 8447532
    .string "A life-form whose identity is unknown.\n"
    .string "It is said to SCREECH or suddenly\n"
    .string "SELFDESTRUCT.$"

kPokedexDescription2_VOLTORB:: @ 8447589
    .string "$"

kPokedexDescription1_ELECTRODE:: @ 844758A
    .string "It explodes in response to even minor\n"
    .string "stimuli. It is feared, with the nickname\n"
    .string "of “The Bomb Ball.”$"

kPokedexDescription2_ELECTRODE:: @ 84475ED
    .string "$"

kPokedexDescription1_EXEGGCUTE:: @ 84475EE
    .string "Even though it appears to be eggs of\n"
    .string "some sort, it was discovered to be a life-\n"
    .string "form more like plant seeds.$"

kPokedexDescription2_EXEGGCUTE:: @ 844765A
    .string "$"

kPokedexDescription1_EXEGGUTOR:: @ 844765B
    .string "It is called “The Walking Tropical\n"
    .string "Rainforest.” Each of the nuts has\n"
    .string "a face and a will of its own.$"

kPokedexDescription2_EXEGGUTOR:: @ 84476BE
    .string "$"

kPokedexDescription1_CUBONE:: @ 84476BF
    .string "It wears the skull of its dead mother on\n"
    .string "its head. When it becomes lonesome, it is\n"
    .string "said to cry loudly.$"

kPokedexDescription2_CUBONE:: @ 8447726
    .string "$"

kPokedexDescription1_MAROWAK:: @ 8447727
    .string "It is small and was originally very weak.\n"
    .string "Its temperament turned ferocious when it\n"
    .string "began using bones.$"

kPokedexDescription2_MAROWAK:: @ 844778D
    .string "$"

kPokedexDescription1_HITMONLEE:: @ 844778E
    .string "The legs freely contract and stretch.\n"
    .string "The stretchy legs allow it to hit a\n"
    .string "distant foe with a rising kick.$"

kPokedexDescription2_HITMONLEE:: @ 84477F8
    .string "$"

kPokedexDescription1_HITMONCHAN:: @ 84477F9
    .string "The spirit of a pro boxer has infused this\n"
    .string "POKéMON. It throws punches that are\n"
    .string "faster than a bullet train.$"

kPokedexDescription2_HITMONCHAN:: @ 8447864
    .string "$"

kPokedexDescription1_LICKITUNG:: @ 8447865
    .string "Its tongue is twice the length of its\n"
    .string "body. It can be moved like an arm for\n"
    .string "grabbing food and attacking.$"

kPokedexDescription2_LICKITUNG:: @ 84478CE
    .string "$"

kPokedexDescription1_KOFFING:: @ 84478CF
    .string "Its thin, balloon-like body is inflated by\n"
    .string "horribly toxic gases. It reeks when it is\n"
    .string "nearby.$"

kPokedexDescription2_KOFFING:: @ 844792C
    .string "$"

kPokedexDescription1_WEEZING:: @ 844792D
    .string "Very rarely, a sudden mutation can result\n"
    .string "in two small KOFFING twins becoming\n"
    .string "conjoined as a WEEZING.$"

kPokedexDescription2_WEEZING:: @ 8447993
    .string "$"

kPokedexDescription1_RHYHORN:: @ 8447994
    .string "Strong, but not too bright, this POKéMON\n"
    .string "can shatter even a skyscraper with its\n"
    .string "charging TACKLES.$"

kPokedexDescription2_RHYHORN:: @ 84479F6
    .string "$"

kPokedexDescription1_RHYDON:: @ 84479F7
    .string "It begins walking on its hind legs after\n"
    .string "evolution. It can punch holes through\n"
    .string "boulders with its horn.$"

kPokedexDescription2_RHYDON:: @ 8447A5E
    .string "$"

kPokedexDescription1_CHANSEY:: @ 8447A5F
    .string "It lays several eggs a day. The eggs are\n"
    .string "apparently rich in nutrients and extremely\n"
    .string "delicious.$"

kPokedexDescription2_CHANSEY:: @ 8447ABE
    .string "$"

kPokedexDescription1_TANGELA:: @ 8447ABF
    .string "Blue plant vines cloak the POKéMON’s\n"
    .string "identity in a tangled mass. It entangles\n"
    .string "anything that gets close.$"

kPokedexDescription2_TANGELA:: @ 8447B27
    .string "$"

kPokedexDescription1_KANGASKHAN:: @ 8447B28
    .string "The female raises its offspring in a pouch\n"
    .string "on its belly. It is skilled at attacking\n"
    .string "using COMET PUNCH.$"

kPokedexDescription2_KANGASKHAN:: @ 8447B8F
    .string "$"

kPokedexDescription1_HORSEA:: @ 8447B90
    .string "It maintains balance using its tail, which\n"
    .string "is wound up like a coil. It may spray ink\n"
    .string "from its mouth.$"

kPokedexDescription2_HORSEA:: @ 8447BF5
    .string "$"

kPokedexDescription1_SEADRA:: @ 8447BF6
    .string "Its body bristles with sharp spikes.\n"
    .string "Carelessly trying to touch it could cause\n"
    .string "fainting from the spikes.$"

kPokedexDescription2_SEADRA:: @ 8447C5F
    .string "$"

kPokedexDescription1_GOLDEEN:: @ 8447C60
    .string "Its dorsal and pectoral fins are strongly\n"
    .string "developed like muscles. It can swim at a\n"
    .string "speed of five knots.$"

kPokedexDescription2_GOLDEEN:: @ 8447CC8
    .string "$"

kPokedexDescription1_SEAKING:: @ 8447CC9
    .string "The horn on its head is sharp like a\n"
    .string "drill. It bores a hole in a boulder to\n"
    .string "make its nest.$"

kPokedexDescription2_SEAKING:: @ 8447D24
    .string "$"

kPokedexDescription1_STARYU:: @ 8447D25
    .string "It appears in large numbers by seashores.\n"
    .string "At night, its central core flashes with a\n"
    .string "red light.$"

kPokedexDescription2_STARYU:: @ 8447D84
    .string "$"

kPokedexDescription1_STARMIE:: @ 8447D85
    .string "This POKéMON has a geometric body.\n"
    .string "Because of its body, the locals suspect\n"
    .string "that it is an alien creature.$"

kPokedexDescription2_STARMIE:: @ 8447DEE
    .string "$"

kPokedexDescription1_MR_MIME:: @ 8447DEF
    .string "It is adept at conning people. It is said\n"
    .string "to be able to create walls out of thin\n"
    .string "air by miming.$"

kPokedexDescription2_MR_MIME:: @ 8447E4F
    .string "$"

kPokedexDescription1_SCYTHER:: @ 8447E50
    .string "It tears and shreds prey with its wickedly\n"
    .string "sharp scythes. It very rarely spreads its\n"
    .string "wings to fly.$"

kPokedexDescription2_SCYTHER:: @ 8447EB3
    .string "$"

kPokedexDescription1_JYNX:: @ 8447EB4
    .string "It speaks using a language that sounds\n"
    .string "human. Research is under way to determine\n"
    .string "what is being said.$"

kPokedexDescription2_JYNX:: @ 8447F19
    .string "$"

kPokedexDescription1_ELECTABUZZ:: @ 8447F1A
    .string "It loves to feed on strong electricity.\n"
    .string "It occasionally appears around large\n"
    .string "power plants and so on.$"

kPokedexDescription2_ELECTABUZZ:: @ 8447F7F
    .string "$"

kPokedexDescription1_MAGMAR:: @ 8447F80
    .string "Found near the mouth of a volcano.\n"
    .string "This fire-breather’s body temperature is\n"
    .string "nearly 2,200 degrees Fahrenheit.$"

kPokedexDescription2_MAGMAR:: @ 8447FED
    .string "$"

kPokedexDescription1_PINSIR:: @ 8447FEE
    .string "Its two long pincer horns are powerful.\n"
    .string "Once they grip an enemy, they won’t\n"
    .string "release until the foe is torn.$"

kPokedexDescription2_PINSIR:: @ 8448059
    .string "$"

kPokedexDescription1_TAUROS:: @ 844805A
    .string "When it is about to TACKLE, it whips\n"
    .string "its body repeatedly with its three\n"
    .string "long tails.$"

kPokedexDescription2_TAUROS:: @ 84480AE
    .string "$"

kPokedexDescription1_MAGIKARP:: @ 84480AF
    .string "It is virtually worthless in terms of both\n"
    .string "power and speed. It is the most weak and\n"
    .string "pathetic POKéMON in the world.$"

kPokedexDescription2_MAGIKARP:: @ 8448122
    .string "$"

kPokedexDescription1_GYARADOS:: @ 8448123
    .string "It has an extremely aggressive nature.\n"
    .string "The HYPER BEAM it shoots from its mouth\n"
    .string "totally incinerates all targets.$"

kPokedexDescription2_GYARADOS:: @ 8448193
    .string "$"

kPokedexDescription1_LAPRAS:: @ 8448194
    .string "Its high intelligence enables it to\n"
    .string "understand human speech. It likes to ferry\n"
    .string "people on its back.$"

kPokedexDescription2_LAPRAS:: @ 84481F7
    .string "$"

kPokedexDescription1_DITTO:: @ 84481F8
    .string "It can freely recombine its own cellular\n"
    .string "structure to transform into other life-\n"
    .string "forms.$"

kPokedexDescription2_DITTO:: @ 8448250
    .string "$"

kPokedexDescription1_EEVEE:: @ 8448251
    .string "An extremely rare POKéMON that may\n"
    .string "evolve in a number of different ways\n"
    .string "depending on stimuli.$"

kPokedexDescription2_EEVEE:: @ 84482AF
    .string "$"

kPokedexDescription1_VAPOREON:: @ 84482B0
    .string "Its body’s cellular structure is similar to\n"
    .string "the molecular composition of water.\n"
    .string "It can melt invisibly in water.$"

kPokedexDescription2_VAPOREON:: @ 8448320
    .string "$"

kPokedexDescription1_JOLTEON:: @ 8448321
    .string "If it is angered or startled, the fur all\n"
    .string "over its body bristles like sharp needles\n"
    .string "that pierce foes.$"

kPokedexDescription2_JOLTEON:: @ 8448387
    .string "$"

kPokedexDescription1_FLAREON:: @ 8448388
    .string "It has a flame bag inside its body. After\n"
    .string "inhaling deeply, it blows out flames of\n"
    .string "nearly 3,100 degrees Fahrenheit.$"

kPokedexDescription2_FLAREON:: @ 84483FB
    .string "$"

kPokedexDescription1_PORYGON:: @ 84483FC
    .string "Using the most advanced technologies,\n"
    .string "scientists finally succeeded in making the\n"
    .string "first artificial POKéMON.$"

kPokedexDescription2_PORYGON:: @ 8448467
    .string "$"

kPokedexDescription1_OMANYTE:: @ 8448468
    .string "A prehistoric POKéMON that lived in the\n"
    .string "primordial sea, it swims by twisting its\n"
    .string "10 tentacles about.$"

kPokedexDescription2_OMANYTE:: @ 84484CD
    .string "$"

kPokedexDescription1_OMASTAR:: @ 84484CE
    .string "Its tentacles are highly developed as if\n"
    .string "they are hands and feet. As soon as it\n"
    .string "ensnares prey, it bites.$"

kPokedexDescription2_OMASTAR:: @ 8448537
    .string "$"

kPokedexDescription1_KABUTO:: @ 8448538
    .string "This POKéMON was regenerated from the\n"
    .string "fossil of an ancient creature. It protects\n"
    .string "itself with a hard shell.$"

kPokedexDescription2_KABUTO:: @ 84485A3
    .string "$"

kPokedexDescription1_KABUTOPS:: @ 84485A4
    .string "It swims freely through water. It catches\n"
    .string "prey with its scythe-like arms and drains\n"
    .string "the victim’s fluids.$"

kPokedexDescription2_KABUTOPS:: @ 844860D
    .string "$"

kPokedexDescription1_AERODACTYL:: @ 844860E
    .string "It was regenerated from a dinosaur’s\n"
    .string "genetic matter that was found in amber.\n"
    .string "It flies with high-pitched cries.$"

kPokedexDescription2_AERODACTYL:: @ 844867D
    .string "$"

kPokedexDescription1_SNORLAX:: @ 844867E
    .string "It is not satisfied unless it eats over 880\n"
    .string "pounds of food every day. When it is done\n"
    .string "eating, it goes promptly to sleep.$"

kPokedexDescription2_SNORLAX:: @ 84486F7
    .string "$"

kPokedexDescription1_ARTICUNO:: @ 84486F8
    .string "One of the legendary bird POKéMON.\n"
    .string "With its long tail trailing behind, its\n"
    .string "flying form is magnificent.$"

kPokedexDescription2_ARTICUNO:: @ 844875F
    .string "$"

kPokedexDescription1_ZAPDOS:: @ 8448760
    .string "One of the legendary bird POKéMON.\n"
    .string "While it is flying, it makes crackling and\n"
    .string "snapping sounds.$"

kPokedexDescription2_ZAPDOS:: @ 84487BF
    .string "$"

kPokedexDescription1_MOLTRES:: @ 84487C0
    .string "One of the legendary bird POKéMON.\n"
    .string "Those seeing it are overwhelmed by its\n"
    .string "orange wings that seem to be on fire.$"

kPokedexDescription2_MOLTRES:: @ 8448830
    .string "$"

kPokedexDescription1_DRATINI:: @ 8448831
    .string "Even the young can exceed 6.5 feet in\n"
    .string "length. It grows larger by repeatedly\n"
    .string "shedding skin.$"

kPokedexDescription2_DRATINI:: @ 844888C
    .string "$"

kPokedexDescription1_DRAGONAIR:: @ 844888D
    .string "It is said to live in seas and lakes.\n"
    .string "Even though it has no wings, it has been\n"
    .string "seen flying occasionally.$"

kPokedexDescription2_DRAGONAIR:: @ 84488F6
    .string "$"

kPokedexDescription1_DRAGONITE:: @ 84488F7
    .string "It can fly in spite of its big and bulky\n"
    .string "physique. It circles the globe in just\n"
    .string "16 hours.$"

kPokedexDescription2_DRAGONITE:: @ 8448951
    .string "$"

kPokedexDescription1_MEWTWO:: @ 8448952
    .string "A POKéMON whose genetic code was\n"
    .string "repeatedly recombined for research.\n"
    .string "It turned vicious as a result.$"

kPokedexDescription2_MEWTWO:: @ 84489B6
    .string "$"

kPokedexDescription1_MEW:: @ 84489B7
    .string "A POKéMON of South America that was\n"
    .string "thought to have been extinct. It is very\n"
    .string "intelligent and learns any move.$"

kPokedexDescription2_MEW:: @ 8448A25
    .string "$"

kPokedexDescription1_CHIKORITA:: @ 8448A26
.ifeq (REVISION - 0)
    .string "Its pleasantly aromatic leaves have the\n"
.else
    .string "Its pleasantly aromatic leaf has the\n"
.endif
    .string "ability to check the humidity and\n"
    .string "temperature.$"

kPokedexDescription2_CHIKORITA:: @ 8448A7D
    .string "$"

kPokedexDescription1_BAYLEEF:: @ 8448A7E
    .string "A spicy aroma emanates from around its\n"
    .string "neck. The aroma acts as a stimulant to\n"
    .string "restore health.$"

kPokedexDescription2_BAYLEEF:: @ 8448ADC
    .string "$"

kPokedexDescription1_MEGANIUM:: @ 8448ADD
    .string "MEGANIUM’s breath has the power to revive\n"
    .string "dead grass and plants. It can make them\n"
    .string "healthy again.$"

kPokedexDescription2_MEGANIUM:: @ 8448B3E
    .string "$"

kPokedexDescription1_CYNDAQUIL:: @ 8448B3F
    .string "It usually stays hunched over. If it is\n"
    .string "angry or surprised, it shoots flames out\n"
    .string "of its back.$"

kPokedexDescription2_CYNDAQUIL:: @ 8448B9D
    .string "$"

kPokedexDescription1_QUILAVA:: @ 8448B9E
    .string "This POKéMON is fully covered by\n"
    .string "nonflammable fur. It can withstand any\n"
    .string "kind of fire attack.$"

kPokedexDescription2_QUILAVA:: @ 8448BFB
    .string "$"

kPokedexDescription1_TYPHLOSION:: @ 8448BFC
    .string "It has a secret, devastating move. It\n"
    .string "rubs its blazing fur together to cause\n"
    .string "huge explosions.$"

kPokedexDescription2_TYPHLOSION:: @ 8448C5A
    .string "$"

kPokedexDescription1_TOTODILE:: @ 8448C5B
    .string "It is small but rough and tough. It won’t\n"
    .string "hesitate to take a bite out of anything\n"
    .string "that moves.$"

kPokedexDescription2_TOTODILE:: @ 8448CB9
    .string "$"

kPokedexDescription1_CROCONAW:: @ 8448CBA
    .string "It opens its huge jaws wide when\n"
    .string "attacking. If it loses any fangs while\n"
    .string "biting, they grow back in.$"

kPokedexDescription2_CROCONAW:: @ 8448D1D
    .string "$"

kPokedexDescription1_FERALIGATR:: @ 8448D1E
    .string "It is hard for it to support its own\n"
    .string "weight out of water, so it gets down on\n"
    .string "all fours. But it moves fast.$"

kPokedexDescription2_FERALIGATR:: @ 8448D89
    .string "$"

kPokedexDescription1_SENTRET:: @ 8448D8A
    .string "It stands on its tail so it can see a long\n"
    .string "way. If it spots an enemy, it cries loudly\n"
    .string "to warn its kind.$"

kPokedexDescription2_SENTRET:: @ 8448DF2
    .string "$"

kPokedexDescription1_FURRET:: @ 8448DF3
    .string "There is no telling where its tail begins.\n"
    .string "Despite its short legs, it is quick at\n"
    .string "hunting RATTATA.$"

kPokedexDescription2_FURRET:: @ 8448E56
    .string "$"

kPokedexDescription1_HOOTHOOT:: @ 8448E57
    .string "It has a perfect sense of time. Whatever\n"
    .string "happens, it keeps rhythm by precisely\n"
    .string "tilting its head in time.$"

kPokedexDescription2_HOOTHOOT:: @ 8448EC0
    .string "$"

kPokedexDescription1_NOCTOWL:: @ 8448EC1
    .string "When it needs to think, it rotates its head\n"
    .string "180 degrees to sharpen its intellectual\n"
    .string "power.$"

kPokedexDescription2_NOCTOWL:: @ 8448F1C
    .string "$"

kPokedexDescription1_LEDYBA:: @ 8448F1D
    .string "When the weather turns cold, numerous\n"
    .string "LEDYBA gather from everywhere to cluster\n"
    .string "and keep each other warm.$"

kPokedexDescription2_LEDYBA:: @ 8448F86
    .string "$"

kPokedexDescription1_LEDIAN:: @ 8448F87
    .string "The star patterns on its back grow larger\n"
    .string "or smaller depending on the number of\n"
    .string "stars in the night sky.$"

kPokedexDescription2_LEDIAN:: @ 8448FEF
    .string "$"

kPokedexDescription1_SPINARAK:: @ 8448FF0
    .string "It spins a web using fine--but durable--\n"
    .string "thread. It then waits patiently for prey\n"
    .string "to be trapped.$"

kPokedexDescription2_SPINARAK:: @ 8449051
    .string "$"

kPokedexDescription1_ARIADOS:: @ 8449052
    .string "A single strand of a special string is\n"
    .string "endlessly spun out of its rear. The string\n"
    .string "leads back to its nest.$"

kPokedexDescription2_ARIADOS:: @ 84490BC
    .string "$"

kPokedexDescription1_CROBAT:: @ 84490BD
    .string "The development of wings on its legs\n"
    .string "enables it to fly fast but also makes it\n"
    .string "tough to stop and rest.$"

kPokedexDescription2_CROBAT:: @ 8449123
    .string "$"

kPokedexDescription1_CHINCHOU:: @ 8449124
    .string "On the dark ocean floor, its only means\n"
    .string "of communication is its constantly\n"
    .string "flashing lights.$"

kPokedexDescription2_CHINCHOU:: @ 8449180
    .string "$"

kPokedexDescription1_LANTURN:: @ 8449181
    .string "It blinds prey with an intense burst of\n"
    .string "light, then swallows the immobilized prey\n"
    .string "in a single gulp.$"

kPokedexDescription2_LANTURN:: @ 84491E5
    .string "$"

kPokedexDescription1_PICHU:: @ 84491E6
    .string "Despite its small size, it can zap even\n"
    .string "adult humans. However, if it does so, it\n"
    .string "also surprises itself.$"

kPokedexDescription2_PICHU:: @ 844924E
    .string "$"

kPokedexDescription1_CLEFFA:: @ 844924F
    .string "When numerous meteors illuminate the\n"
    .string "night sky, sightings of CLEFFA strangely\n"
    .string "increase.$"

kPokedexDescription2_CLEFFA:: @ 84492A7
    .string "$"

kPokedexDescription1_IGGLYBUFF:: @ 84492A8
    .string "Its extremely flexible and elastic body\n"
    .string "makes it bounce continuously--anytime,\n"
    .string "anywhere.$"

kPokedexDescription2_IGGLYBUFF:: @ 8449301
    .string "$"

kPokedexDescription1_TOGEPI:: @ 8449302
    .string "A proverb claims that happiness will come\n"
    .string "to anyone who can make a sleeping TOGEPI\n"
    .string "stand up.$"

kPokedexDescription2_TOGEPI:: @ 844935F
    .string "$"

kPokedexDescription1_TOGETIC:: @ 8449360
    .string "It grows dispirited if it is not with kind\n"
    .string "people. It can float in midair without\n"
    .string "moving its wings.$"

kPokedexDescription2_TOGETIC:: @ 84493C4
    .string "$"

kPokedexDescription1_NATU:: @ 84493C5
    .string "It usually forages for food on the ground\n"
    .string "but may, on rare occasions, hop onto\n"
    .string "branches to peck at shoots.$"

kPokedexDescription2_NATU:: @ 8449430
    .string "$"

kPokedexDescription1_XATU:: @ 8449431
    .string "In South America, it is said that its right\n"
    .string "eye sees the future and its left eye\n"
    .string "views the past.$"

kPokedexDescription2_XATU:: @ 8449492
    .string "$"

kPokedexDescription1_MAREEP:: @ 8449493
    .string "Its fleece grows continually. In the\n"
    .string "summer, the fleece is fully shed, but it\n"
    .string "grows back in a week.$"

kPokedexDescription2_MAREEP:: @ 84494F7
    .string "$"

kPokedexDescription1_FLAAFFY:: @ 84494F8
    .string "Its fluffy fleece easily stores\n"
    .string "electricity. Its rubbery hide keeps it\n"
    .string "from being electrocuted.$"

kPokedexDescription2_FLAAFFY:: @ 8449558
    .string "$"

kPokedexDescription1_AMPHAROS:: @ 8449559
    .string "The bright light on its tail can be seen\n"
    .string "far away. It has been treasured since\n"
    .string "ancient times as a beacon.$"

kPokedexDescription2_AMPHAROS:: @ 84495C3
    .string "$"

kPokedexDescription1_BELLOSSOM:: @ 84495C4
    .string "Plentiful in the tropics. When it dances,\n"
    .string "its petals rub together and make a\n"
    .string "pleasant ringing sound.$"

kPokedexDescription2_BELLOSSOM:: @ 8449629
    .string "$"

kPokedexDescription1_MARILL:: @ 844962A
    .string "The end of its tail serves as a buoy that\n"
    .string "keeps it from drowning, even in a vicious\n"
    .string "current.$"

kPokedexDescription2_MARILL:: @ 8449687
    .string "$"

kPokedexDescription1_AZUMARILL:: @ 8449688
    .string "When it plays in water, it rolls up its\n"
    .string "elongated ears to prevent their insides\n"
    .string "from getting wet.$"

kPokedexDescription2_AZUMARILL:: @ 84496EA
    .string "$"

kPokedexDescription1_SUDOWOODO:: @ 84496EB
    .string "It disguises itself as a tree to avoid\n"
    .string "attack. It hates water, so it will\n"
    .string "disappear if it starts raining.$"

kPokedexDescription2_SUDOWOODO:: @ 8449755
    .string "$"

kPokedexDescription1_POLITOED:: @ 8449756
    .string "Whenever three or more of these get\n"
    .string "together, they sing in a loud voice that\n"
    .string "sounds like bellowing.$"

kPokedexDescription2_POLITOED:: @ 84497BA
    .string "$"

kPokedexDescription1_HOPPIP:: @ 84497BB
    .string "Its body is so light, it must grip the\n"
    .string "ground firmly with its feet to keep from\n"
    .string "being blown away.$"

kPokedexDescription2_HOPPIP:: @ 844981D
    .string "$"

kPokedexDescription1_SKIPLOOM:: @ 844981E
    .string "It spreads its petals to absorb sunlight.\n"
    .string "It also floats in the air to get closer to\n"
    .string "the sun.$"

kPokedexDescription2_SKIPLOOM:: @ 844987C
    .string "$"

kPokedexDescription1_JUMPLUFF:: @ 844987D
    .string "It drifts on seasonal winds and spreads\n"
    .string "its cotton-like spores all over the world \n"
    .string "to make more offspring.$"

kPokedexDescription2_JUMPLUFF:: @ 84498E8
    .string "$"

kPokedexDescription1_AIPOM:: @ 84498E9
    .string "It lives atop tall trees. When leaping\n"
    .string "from branch to branch, it deftly uses its\n"
    .string "tail for balance.$"

kPokedexDescription2_AIPOM:: @ 844994C
    .string "$"

kPokedexDescription1_SUNKERN:: @ 844994D
    .string "It lives by drinking only dewdrops from\n"
    .string "under the leaves of plants. It is said\n"
    .string "that it eats nothing else.$"

kPokedexDescription2_SUNKERN:: @ 84499B7
    .string "$"

kPokedexDescription1_SUNFLORA:: @ 84499B8
    .string "In the daytime, it rushes about in a\n"
    .string "hectic manner, but it comes to a complete\n"
    .string "stop when the sun sets.$"

kPokedexDescription2_SUNFLORA:: @ 8449A1F
    .string "$"

kPokedexDescription1_YANMA:: @ 8449A20
    .string "Its large eyes can scan 360 degrees.\n"
    .string "It looks in all directions to seek out\n"
    .string "insects as its prey.$"

kPokedexDescription2_YANMA:: @ 8449A81
    .string "$"

kPokedexDescription1_WOOPER:: @ 8449A82
    .string "When it walks around on the ground,\n"
    .string "it coats its body with a slimy, poisonous\n"
    .string "film.$"

kPokedexDescription2_WOOPER:: @ 8449AD6
    .string "$"

kPokedexDescription1_QUAGSIRE:: @ 8449AD7
    .string "Due to its relaxed and carefree attitude,\n"
    .string "it often bumps its head on boulders and\n"
    .string "boat hulls as it swims.$"

kPokedexDescription2_QUAGSIRE:: @ 8449B41
    .string "$"

kPokedexDescription1_ESPEON:: @ 8449B42
    .string "By reading air currents, it can predict\n"
    .string "things such as the weather or its foe’s\n"
    .string "next move.$"

kPokedexDescription2_ESPEON:: @ 8449B9D
    .string "$"

kPokedexDescription1_UMBREON:: @ 8449B9E
    .string "When darkness falls, the rings on its body\n"
    .string "begin to glow, striking fear in the hearts\n"
    .string "of anyone nearby.$"

kPokedexDescription2_UMBREON:: @ 8449C06
    .string "$"

kPokedexDescription1_MURKROW:: @ 8449C07
    .string "It is said that when chased, it lures its\n"
    .string "attacker onto dark mountain trails where\n"
    .string "the foe will get lost.$"

kPokedexDescription2_MURKROW:: @ 8449C71
    .string "$"

kPokedexDescription1_SLOWKING:: @ 8449C72
    .string "When its head was bitten, toxins entered\n"
    .string "SLOWPOKE’s head and unlocked an\n"
    .string "extraordinary power.$"

kPokedexDescription2_SLOWKING:: @ 8449CD0
    .string "$"

kPokedexDescription1_MISDREAVUS:: @ 8449CD1
    .string "It loves to bite and yank people’s hair\n"
    .string "from behind without warning, just to see\n"
    .string "their shocked reactions.$"

kPokedexDescription2_MISDREAVUS:: @ 8449D3B
    .string "$"

kPokedexDescription1_UNOWN:: @ 8449D3C
    .string "Its flat, thin body is always stuck on\n"
    .string "walls. Its shape appears to have some\n"
    .string "meaning.$"

kPokedexDescription2_UNOWN:: @ 8449D92
    .string "$"

kPokedexDescription1_WOBBUFFET:: @ 8449D93
    .string "To keep its pitch-black tail hidden, it\n"
    .string "lives quietly in the darkness. It is never\n"
    .string "first to attack.$"

kPokedexDescription2_WOBBUFFET:: @ 8449DF7
    .string "$"

kPokedexDescription1_GIRAFARIG:: @ 8449DF8
    .string "Its tail, which also contains a small\n"
    .string "brain, may bite on its own if it notices an\n"
    .string "alluring smell.$"

kPokedexDescription2_GIRAFARIG:: @ 8449E5A
    .string "$"

kPokedexDescription1_PINECO:: @ 8449E5B
    .string "It hangs and waits for flying-insect prey\n"
    .string "to come near. It does not move about\n"
    .string "much on its own.$"

kPokedexDescription2_PINECO:: @ 8449EBB
    .string "$"

kPokedexDescription1_FORRETRESS:: @ 8449EBC
    .string "It remains immovably rooted to its tree.\n"
    .string "It scatters pieces of its hard shell to\n"
    .string "drive its enemies away.$"

kPokedexDescription2_FORRETRESS:: @ 8449F25
    .string "$"

kPokedexDescription1_DUNSPARCE:: @ 8449F26
    .string "If spotted, it escapes by burrowing with\n"
    .string "its tail. It can hover just slightly using\n"
    .string "its wings.$"

kPokedexDescription2_DUNSPARCE:: @ 8449F85
    .string "$"

kPokedexDescription1_GLIGAR:: @ 8449F86
    .string "It usually clings to cliffs. When it spots\n"
    .string "its prey, it spreads its wings and glides\n"
    .string "down to attack.$"

kPokedexDescription2_GLIGAR:: @ 8449FEB
    .string "$"

kPokedexDescription1_STEELIX:: @ 8449FEC
    .string "It is said that if an ONIX lives for over\n"
    .string "100 years, its composition changes to\n"
    .string "become diamond-like.$"

kPokedexDescription2_STEELIX:: @ 844A051
    .string "$"

kPokedexDescription1_SNUBBULL:: @ 844A052
    .string "It has an active, playful nature. Many\n"
    .string "women like to frolic with it because of\n"
    .string "its affectionate ways.$"

kPokedexDescription2_SNUBBULL:: @ 844A0B8
    .string "$"

kPokedexDescription1_GRANBULL:: @ 844A0B9
    .string "Because its fangs are too heavy, it\n"
    .string "always keeps its head tilted down.\n"
    .string "However, its BITE is powerful.$"

kPokedexDescription2_GRANBULL:: @ 844A11F
    .string "$"

kPokedexDescription1_QWILFISH:: @ 844A120
    .string "The small spikes covering its body\n"
    .string "developed from scales. They inject a\n"
    .string "toxin that causes fainting.$"

kPokedexDescription2_QWILFISH:: @ 844A184
    .string "$"

kPokedexDescription1_SCIZOR:: @ 844A185
    .string "Its wings are not used for flying.\n"
    .string "They are flapped at high speed to adjust\n"
    .string "its body temperature.$"

kPokedexDescription2_SCIZOR:: @ 844A1E7
    .string "$"

kPokedexDescription1_SHUCKLE:: @ 844A1E8
    .string "It stores BERRIES inside its shell.\n"
    .string "To avoid attacks, it hides beneath rocks\n"
    .string "and remains completely still.$"

kPokedexDescription2_SHUCKLE:: @ 844A253
    .string "$"

kPokedexDescription1_HERACROSS:: @ 844A254
    .string "Usually docile, but if disturbed while\n"
    .string "sipping honey, it chases off the intruder\n"
    .string "with its horn.$"

kPokedexDescription2_HERACROSS:: @ 844A2B4
    .string "$"

kPokedexDescription1_SNEASEL:: @ 844A2B5
    .string "Vicious in nature, it drives PIDGEY from\n"
    .string "their nests and feasts on the eggs that\n"
    .string "are left behind.$"

kPokedexDescription2_SNEASEL:: @ 844A317
    .string "$"

kPokedexDescription1_TEDDIURSA:: @ 844A318
    .string "Before food becomes scarce in wintertime,\n"
    .string "its habit is to hoard food in many hidden\n"
    .string "locations.$"

kPokedexDescription2_TEDDIURSA:: @ 844A377
    .string "$"

kPokedexDescription1_URSARING:: @ 844A378
    .string "With its ability to distinguish any smell,\n"
    .string "it unfailingly finds all food buried deep\n"
    .string "underground.$"

kPokedexDescription2_URSARING:: @ 844A3DA
    .string "$"

kPokedexDescription1_SLUGMA:: @ 844A3DB
    .string "A common sight in volcanic areas, it\n"
    .string "slowly slithers around in a constant\n"
    .string "search for warm places.$"

kPokedexDescription2_SLUGMA:: @ 844A43D
    .string "$"

kPokedexDescription1_MAGCARGO:: @ 844A43E
    .string "Its brittle shell occasionally spouts\n"
    .string "intense flames that circulate throughout\n"
    .string "its body.$"

kPokedexDescription2_MAGCARGO:: @ 844A497
    .string "$"

kPokedexDescription1_SWINUB:: @ 844A498
    .string "If it smells something enticing, it dashes\n"
    .string "off headlong to find the source of the\n"
    .string "aroma.$"

kPokedexDescription2_SWINUB:: @ 844A4F1
    .string "$"

kPokedexDescription1_PILOSWINE:: @ 844A4F2
    .string "If it charges at an enemy, the hairs on\n"
    .string "its back stand up straight. It is very\n"
    .string "sensitive to sound.$"

kPokedexDescription2_PILOSWINE:: @ 844A555
    .string "$"

kPokedexDescription1_CORSOLA:: @ 844A556
    .string "In a south sea nation, the people live in\n"
    .string "communities that are built on groups of\n"
    .string "these POKéMON.$"

kPokedexDescription2_CORSOLA:: @ 844A5B7
    .string "$"

kPokedexDescription1_REMORAID:: @ 844A5B8
    .string "Using its dorsal fin as a suction pad, it\n"
    .string "clings to a MANTINE’s underside to\n"
    .string "scavenge for leftovers.$"

kPokedexDescription2_REMORAID:: @ 844A61D
    .string "$"

kPokedexDescription1_OCTILLERY:: @ 844A61E
    .string "It instinctively sneaks into rocky holes.\n"
    .string "If it gets sleepy, it steals the nest of a\n"
    .string "fellow OCTILLERY.$"

kPokedexDescription2_OCTILLERY:: @ 844A685
    .string "$"

kPokedexDescription1_DELIBIRD:: @ 844A686
    .string "It nests at the edge of sharp cliffs.\n"
    .string "It spends all day carrying food to its\n"
    .string "awaiting chicks.$"

kPokedexDescription2_DELIBIRD:: @ 844A6E4
    .string "$"

kPokedexDescription1_MANTINE:: @ 844A6E5
    .string "Swimming freely in open seas, it may fly\n"
    .string "out of the water and over the waves if it\n"
    .string "builds up enough speed.$"

kPokedexDescription2_MANTINE:: @ 844A750
    .string "$"

kPokedexDescription1_SKARMORY:: @ 844A751
    .string "After nesting in bramble bushes, the wings\n"
    .string "of its chicks grow hard from scratches by\n"
    .string "thorns.$"

kPokedexDescription2_SKARMORY:: @ 844A7AE
    .string "$"

kPokedexDescription1_HOUNDOUR:: @ 844A7AF
    .string "To corner prey, they check each other’s\n"
    .string "location using barks that only they can\n"
    .string "understand.$"

kPokedexDescription2_HOUNDOUR:: @ 844A80B
    .string "$"

kPokedexDescription1_HOUNDOOM:: @ 844A80C
    .string "Upon hearing its eerie howls, other\n"
    .string "POKéMON get the shivers and head straight\n"
    .string "back to their nests.$"

kPokedexDescription2_HOUNDOOM:: @ 844A86F
    .string "$"

kPokedexDescription1_KINGDRA:: @ 844A870
    .string "It sleeps deep on the ocean floor to\n"
    .string "build its energy. It is said to cause\n"
    .string "tornadoes as it wakes.$"

kPokedexDescription2_KINGDRA:: @ 844A8D2
    .string "$"

kPokedexDescription1_PHANPY:: @ 844A8D3
    .string "As a sign of affection, it bumps with its\n"
    .string "snout. However, it is so strong, it may\n"
    .string "send you flying.$"

kPokedexDescription2_PHANPY:: @ 844A936
    .string "$"

kPokedexDescription1_DONPHAN:: @ 844A937
    .string "The longer and bigger its tusks, the\n"
    .string "higher its rank in its herd. The tusks take\n"
    .string "a long time to grow.$"

kPokedexDescription2_DONPHAN:: @ 844A99D
    .string "$"

kPokedexDescription1_PORYGON2:: @ 844A99E
    .string "Further research enhanced its abilities.\n"
    .string "Sometimes, it may exhibit motions that\n"
    .string "were not programmed.$"

kPokedexDescription2_PORYGON2:: @ 844AA03
    .string "$"

kPokedexDescription1_STANTLER:: @ 844AA04
    .string "Those who stare at its antlers will\n"
    .string "gradually lose control of their senses\n"
    .string "and be unable to stand.$"

kPokedexDescription2_STANTLER:: @ 844AA67
    .string "$"

kPokedexDescription1_SMEARGLE:: @ 844AA68
    .string "Once it becomes an adult, it has a\n"
    .string "tendency to let its comrades plant\n"
    .string "footprints on its back.$"

kPokedexDescription2_SMEARGLE:: @ 844AAC6
    .string "$"

kPokedexDescription1_TYROGUE:: @ 844AAC7
    .string "Even though it is small, it can’t be\n"
    .string "ignored because it will slug any handy\n"
    .string "target without warning.$"

kPokedexDescription2_TYROGUE:: @ 844AB2B
    .string "$"

kPokedexDescription1_HITMONTOP:: @ 844AB2C
    .string "It launches kicks while spinning. If it\n"
    .string "spins at high speed, it may bore its way\n"
    .string "into the ground.$"

kPokedexDescription2_HITMONTOP:: @ 844AB8E
    .string "$"

kPokedexDescription1_SMOOCHUM:: @ 844AB8F
    .string "It always rocks its head slowly backwards\n"
    .string "and forwards as if it is trying to kiss\n"
    .string "someone.$"

kPokedexDescription2_SMOOCHUM:: @ 844ABEA
    .string "$"

kPokedexDescription1_ELEKID:: @ 844ABEB
    .string "Even in the most vicious storm, this\n"
    .string "POKéMON plays happily if thunder rumbles\n"
    .string "in the sky.$"

kPokedexDescription2_ELEKID:: @ 844AC45
    .string "$"

kPokedexDescription1_MAGBY:: @ 844AC46
    .string "It is found in volcanic craters. Its body\n"
    .string "heat exceeds 1,100 degrees Fahrenheit,\n"
    .string "so don’t underestimate it.$"

kPokedexDescription2_MAGBY:: @ 844ACB2
    .string "$"

kPokedexDescription1_MILTANK:: @ 844ACB3
    .string "If it has just had a baby, the milk it\n"
    .string "produces contains much more nutrition than\n"
    .string "usual.$"

kPokedexDescription2_MILTANK:: @ 844AD0C
    .string "$"

kPokedexDescription1_BLISSEY:: @ 844AD0D
    .string "It has a very compassionate nature. If it\n"
    .string "sees a sick POKéMON, it will nurse the\n"
    .string "sufferer back to health.$"

kPokedexDescription2_BLISSEY:: @ 844AD77
    .string "$"

kPokedexDescription1_RAIKOU:: @ 844AD78
    .string "This POKéMON races across the\n"
    .string "land while barking a cry that sounds\n"
    .string "like crashing thunder.$"

kPokedexDescription2_RAIKOU:: @ 844ADD2
    .string "$"

kPokedexDescription1_ENTEI:: @ 844ADD3
    .string "A POKéMON that races across the land.\n"
    .string "It is said that one is born every time a\n"
    .string "new volcano appears.$"

kPokedexDescription2_ENTEI:: @ 844AE37
    .string "$"

kPokedexDescription1_SUICUNE:: @ 844AE38
    .string "This POKéMON races across the land.\n"
    .string "It is said that north winds will somehow\n"
    .string "blow whenever it appears.$"

kPokedexDescription2_SUICUNE:: @ 844AE9F
    .string "$"

kPokedexDescription1_LARVITAR:: @ 844AEA0
    .string "It is born deep underground. It can’t\n"
    .string "emerge until it has entirely consumed the\n"
    .string "soil around it.$"

kPokedexDescription2_LARVITAR:: @ 844AF00
    .string "$"

kPokedexDescription1_PUPITAR:: @ 844AF01
    .string "Even sealed in its shell, it can move\n"
    .string "freely. Hard and fast, it has outstanding\n"
    .string "destructive power.$"

kPokedexDescription2_PUPITAR:: @ 844AF64
    .string "$"

kPokedexDescription1_TYRANITAR:: @ 844AF65
.ifeq (REVISION - 0)
    .string "Its body can’t be harmed by any sort of\n"
    .string "attack, so it is very eager to make\n"
    .string "challenges against enemies.$"
.else
    .string "It has an impudent nature. Having great\n"
    .string "strength, it can even change surrounding\n"
    .string "landforms.$"
.endif

kPokedexDescription2_TYRANITAR:: @ 844AFCD
    .string "$"

kPokedexDescription1_LUGIA:: @ 844AFCE
    .string "It is said to be the guardian of the seas.\n"
    .string "It is rumored to have been seen on the\n"
    .string "night of a storm.$"

kPokedexDescription2_LUGIA:: @ 844B032
    .string "$"

kPokedexDescription1_HO_OH:: @ 844B033
    .string "A legend says that its body glows in\n"
    .string "seven colors. A rainbow is said to form\n"
    .string "behind it when it flies.$"

kPokedexDescription2_HO_OH:: @ 844B099
    .string "$"

kPokedexDescription1_CELEBI:: @ 844B09A
    .string "When CELEBI disappears deep in a forest,\n"
    .string "it is said to leave behind an egg it\n"
    .string "brought from the future.$"

kPokedexDescription2_CELEBI:: @ 844B101
    .string "$"

kPokedexDescription1_TREECKO:: @ 844B102
    .string "It quickly scales even vertical walls.\n"
    .string "It senses humidity with its tail to predict\n"
    .string "the next day’s weather.$"

kPokedexDescription2_TREECKO:: @ 844B16D
    .string "$"

kPokedexDescription1_GROVYLE:: @ 844B16E
    .string "Its strongly developed thigh muscles\n"
    .string "give it astounding agility and jumping\n"
    .string "performance.$"

kPokedexDescription2_GROVYLE:: @ 844B1C7
    .string "$"

kPokedexDescription1_SCEPTILE:: @ 844B1C8
    .string "The leaves on its forelegs are as sharp\n"
    .string "as swords. It agilely leaps about the\n"
    .string "branches of trees to strike.$"

kPokedexDescription2_SCEPTILE:: @ 844B233
    .string "$"

kPokedexDescription1_TORCHIC:: @ 844B234
    .string "It has a flame sac inside its belly that\n"
    .string "perpetually burns. It feels warm if it is\n"
    .string "hugged.$"

kPokedexDescription2_TORCHIC:: @ 844B28F
    .string "$"

kPokedexDescription1_COMBUSKEN:: @ 844B290
    .string "It boosts its concentration by emitting\n"
    .string "harsh cries. Its kicks have outstanding\n"
    .string "destructive power.$"

kPokedexDescription2_COMBUSKEN:: @ 844B2F3
    .string "$"

kPokedexDescription1_BLAZIKEN:: @ 844B2F4
    .string "When facing a tough foe, it looses flames\n"
    .string "from its wrists. Its powerful legs let it\n"
    .string "jump clear over buildings.$"

kPokedexDescription2_BLAZIKEN:: @ 844B363
    .string "$"

kPokedexDescription1_MUDKIP:: @ 844B364
    .string "Its large tail fin propels it through\n"
    .string "water with powerful acceleration. It is\n"
    .string "strong in spite of its size.$"

kPokedexDescription2_MUDKIP:: @ 844B3CF
    .string "$"

kPokedexDescription1_MARSHTOMP:: @ 844B3D0
    .string "It is at its best when on muddy ground\n"
    .string "with poor footing. It quickly overwhelms\n"
    .string "foes struggling in mud.$"

kPokedexDescription2_MARSHTOMP:: @ 844B438
    .string "$"

kPokedexDescription1_SWAMPERT:: @ 844B439
    .string "Its arms are rock-hard. With one swing,\n"
    .string "they can batter down its foe. It makes its\n"
    .string "nest on beautiful beaches.$"

kPokedexDescription2_SWAMPERT:: @ 844B4A7
    .string "$"

kPokedexDescription1_POOCHYENA:: @ 844B4A8
    .string "It has a very tenacious nature. Its acute\n"
    .string "sense of smell lets it chase a chosen\n"
    .string "prey without ever losing track.$"

kPokedexDescription2_POOCHYENA:: @ 844B518
    .string "$"

kPokedexDescription1_MIGHTYENA:: @ 844B519
    .string "It will always obey the commands of a\n"
    .string "skilled TRAINER. Its behavior arises from\n"
    .string "its living in packs in ancient times.$"

kPokedexDescription2_MIGHTYENA:: @ 844B58F
    .string "$"

kPokedexDescription1_ZIGZAGOON:: @ 844B590
    .string "A POKéMON with abundant curiosity.\n"
    .string "It shows an interest in everything, so it\n"
    .string "always zigs and zags.$"

kPokedexDescription2_ZIGZAGOON:: @ 844B5F3
    .string "$"

kPokedexDescription1_LINOONE:: @ 844B5F4
    .string "When running in a straight line, it can top\n"
    .string "60 miles per hour. However, it has a\n"
    .string "tough time with curved roads.$"

kPokedexDescription2_LINOONE:: @ 844B663
    .string "$"

kPokedexDescription1_WURMPLE:: @ 844B664
    .string "It lives amidst tall grass and in forests.\n"
    .string "When attacked, it resists by pointing its\n"
    .string "venomous spikes at the foe.$"

kPokedexDescription2_WURMPLE:: @ 844B6D5
    .string "$"

kPokedexDescription1_SILCOON:: @ 844B6D6
    .string "It conserves its energy by moving as\n"
    .string "little as possible. It awaits evolution\n"
    .string "while drinking only a little rainwater.$"

kPokedexDescription2_SILCOON:: @ 844B74B
    .string "$"

kPokedexDescription1_BEAUTIFLY:: @ 844B74C
    .string "Despite its appearance, it has an\n"
    .string "aggressive nature. It attacks by jabbing\n"
    .string "with its long, thin mouth.$"

kPokedexDescription2_BEAUTIFLY:: @ 844B7B2
    .string "$"

kPokedexDescription1_CASCOON:: @ 844B7B3
    .string "Its body, which is made of soft silk,\n"
    .string "hardens over time. When cracks appear,\n"
    .string "evolution is near.$"

kPokedexDescription2_CASCOON:: @ 844B813
    .string "$"

kPokedexDescription1_DUSTOX:: @ 844B814
    .string "It scatters horribly toxic dust when it\n"
    .string "senses danger. They tend to gather in the\n"
    .string "glow of streetlamps at night.$"

kPokedexDescription2_DUSTOX:: @ 844B884
    .string "$"

kPokedexDescription1_LOTAD:: @ 844B885
    .string "It searches about for clean water. If it\n"
    .string "does not drink water for too long, the\n"
    .string "leaf on its head wilts.$"

kPokedexDescription2_LOTAD:: @ 844B8ED
    .string "$"

kPokedexDescription1_LOMBRE:: @ 844B8EE
    .string "It lives at the water’s edge where it is\n"
    .string "sunny. It sleeps on a bed of water grass\n"
    .string "by day and becomes active at night.$"

kPokedexDescription2_LOMBRE:: @ 844B964
    .string "$"

kPokedexDescription1_LUDICOLO:: @ 844B965
    .string "The rhythm of bright, festive music\n"
    .string "activates LUDICOLO’s cells, making it more\n"
    .string "powerful.$"

kPokedexDescription2_LUDICOLO:: @ 844B9BE
    .string "$"

kPokedexDescription1_SEEDOT:: @ 844B9BF
    .string "If it remains still, it becomes impossible\n"
    .string "to distinguish from real nuts. It delights\n"
    .string "in surprising foraging PIDGEY.$"

kPokedexDescription2_SEEDOT:: @ 844BA34
    .string "$"

kPokedexDescription1_NUZLEAF:: @ 844BA35
    .string "They live in holes bored in large trees.\n"
    .string "The sound of NUZLEAF’s grass flute fills\n"
    .string "listeners with dread.$"

kPokedexDescription2_NUZLEAF:: @ 844BA9D
    .string "$"

kPokedexDescription1_SHIFTRY:: @ 844BA9E
    .string "A POKéMON that was feared as a forest\n"
    .string "guardian. It can read the foe’s mind and\n"
    .string "take preemptive action.$"

kPokedexDescription2_SHIFTRY:: @ 844BB05
    .string "$"

kPokedexDescription1_TAILLOW:: @ 844BB06
    .string "It dislikes cold seasons. They migrate to\n"
    .string "other lands in search of warmth, flying\n"
    .string "over 180 miles a day.$"

kPokedexDescription2_TAILLOW:: @ 844BB6E
    .string "$"

kPokedexDescription1_SWELLOW:: @ 844BB6F
    .string "If its two tail feathers are standing at\n"
    .string "attention, it is proof of good health.\n"
    .string "It soars elegantly in the sky.$"

kPokedexDescription2_SWELLOW:: @ 844BBDE
    .string "$"

kPokedexDescription1_WINGULL:: @ 844BBDF
    .string "It rides upon ocean winds as if it were\n"
    .string "a glider. In the winter, it hides food\n"
    .string "around its nest.$"

kPokedexDescription2_WINGULL:: @ 844BC3F
    .string "$"

kPokedexDescription1_PELIPPER:: @ 844BC40
    .string "It is a flying transporter that carries\n"
    .string "small POKéMON in its beak. It bobs on the\n"
    .string "waves to rest its wings.$"

kPokedexDescription2_PELIPPER:: @ 844BCAB
    .string "$"

kPokedexDescription1_RALTS:: @ 844BCAC
    .string "It is highly attuned to the emotions of\n"
    .string "people and POKéMON. It hides if it senses\n"
    .string "hostility.$"

kPokedexDescription2_RALTS:: @ 844BD09
    .string "$"

kPokedexDescription1_KIRLIA:: @ 844BD0A
    .string "The cheerful spirit of its TRAINER gives\n"
    .string "it energy for its psychokinetic power.\n"
    .string "It spins and dances when happy.$"

kPokedexDescription2_KIRLIA:: @ 844BD7A
    .string "$"

kPokedexDescription1_GARDEVOIR:: @ 844BD7B
    .string "It has the power to predict the future.\n"
    .string "Its power peaks when it is protecting its\n"
    .string "TRAINER.$"

kPokedexDescription2_GARDEVOIR:: @ 844BDD6
    .string "$"

kPokedexDescription1_SURSKIT:: @ 844BDD7
    .string "They usually live on ponds, but after an\n"
    .string "evening shower, they may appear on\n"
    .string "puddles in towns.$"

kPokedexDescription2_SURSKIT:: @ 844BE35
    .string "$"

kPokedexDescription1_MASQUERAIN:: @ 844BE36
    .string "The antennae have distinctive patterns\n"
    .string "that look like eyes. When it rains, they\n"
    .string "grow heavy, making flight impossible.$"

kPokedexDescription2_MASQUERAIN:: @ 844BEAC
    .string "$"

kPokedexDescription1_SHROOMISH:: @ 844BEAD
    .string "It prefers damp places. By day it remains\n"
    .string "still in the forest shade. It releases\n"
    .string "toxic powder from its head.$"

kPokedexDescription2_SHROOMISH:: @ 844BF1A
    .string "$"

kPokedexDescription1_BRELOOM:: @ 844BF1B
    .string "The seeds on its tail are made of toxic\n"
    .string "spores. It knocks out foes with quick,\n"
    .string "virtually invisible punches.$"

kPokedexDescription2_BRELOOM:: @ 844BF87
    .string "$"

kPokedexDescription1_SLAKOTH:: @ 844BF88
    .string "It sleeps for 20 hours every day. Making\n"
    .string "drowsy those that see it is one of\n"
    .string "its abilities.$"

kPokedexDescription2_SLAKOTH:: @ 844BFE3
    .string "$"

kPokedexDescription1_VIGOROTH:: @ 844BFE4
    .string "It is always hungry because it won’t stop\n"
    .string "rampaging. Even while it is eating, it\n"
    .string "can’t keep still.$"

kPokedexDescription2_VIGOROTH:: @ 844C047
    .string "$"

kPokedexDescription1_SLAKING:: @ 844C048
    .string "It is the world’s most slothful POKéMON.\n"
    .string "However, it can exert horrifying power by\n"
    .string "releasing pent-up energy all at once.$"

kPokedexDescription2_SLAKING:: @ 844C0C1
    .string "$"

kPokedexDescription1_NINCADA:: @ 844C0C2
    .string "Because it lived almost entirely\n"
    .string "underground, it is nearly blind.\n"
    .string "It uses its antennae instead.$"

kPokedexDescription2_NINCADA:: @ 844C122
    .string "$"

kPokedexDescription1_NINJASK:: @ 844C123
    .string "This POKéMON is so quick, it is said to\n"
    .string "be able to avoid any attack. It loves to\n"
    .string "feed on tree sap.$"

kPokedexDescription2_NINJASK:: @ 844C186
    .string "$"

kPokedexDescription1_SHEDINJA:: @ 844C187
    .string "A most peculiar POKéMON that somehow\n"
    .string "appears in a POKé BALL when a NINCADA\n"
    .string "evolves.$"

kPokedexDescription2_SHEDINJA:: @ 844C1DB
    .string "$"

kPokedexDescription1_WHISMUR:: @ 844C1DC
    .string "It usually murmurs, but starts crying\n"
    .string "loudly if it senses danger. It stops when\n"
    .string "its ear covers are shut.$"

kPokedexDescription2_WHISMUR:: @ 844C245
    .string "$"

kPokedexDescription1_LOUDRED:: @ 844C246
    .string "When it stamps its feet and bellows, it\n"
    .string "generates ultrasonic waves that can blow\n"
    .string "apart a house.$"

kPokedexDescription2_LOUDRED:: @ 844C2A6
    .string "$"

kPokedexDescription1_EXPLOUD:: @ 844C2A7
    .string "It emits a variety of sounds from the \n"
    .string "holes all over its body. Its loud cries\n"
    .string "can be heard from over six miles away.$"

kPokedexDescription2_EXPLOUD:: @ 844C31D
    .string "$"

kPokedexDescription1_MAKUHITA:: @ 844C31E
    .string "It grows stronger by enduring harsh\n"
    .string "training. It is a gutsy POKéMON that can\n"
    .string "withstand any attack.$"

kPokedexDescription2_MAKUHITA:: @ 844C381
    .string "$"

kPokedexDescription1_HARIYAMA:: @ 844C382
    .string "It stomps on the ground to build power.\n"
    .string "It can send a 10-ton truck flying with a\n"
    .string "straight-arm punch.$"

kPokedexDescription2_HARIYAMA:: @ 844C3E7
    .string "$"

kPokedexDescription1_AZURILL:: @ 844C3E8
    .string "It battles by flinging around its tail,\n"
    .string "which is bigger than its body. The\n"
    .string "tail is a flotation device in water.$"

kPokedexDescription2_AZURILL:: @ 844C458
    .string "$"

kPokedexDescription1_NOSEPASS:: @ 844C459
    .string "Its magnetic nose consistently faces\n"
    .string "north. Travelers check NOSEPASS to get\n"
    .string "their bearings.$"

kPokedexDescription2_NOSEPASS:: @ 844C4B5
    .string "$"

kPokedexDescription1_SKITTY:: @ 844C4B6
    .string "It is said to be difficult to earn its\n"
    .string "trust. However, it is extremely popular\n"
    .string "for its cute looks and behavior.$"

kPokedexDescription2_SKITTY:: @ 844C526
    .string "$"

kPokedexDescription1_DELCATTY:: @ 844C527
    .string "The favorite of trend-conscious\n"
    .string "female TRAINERS, they are used in\n"
    .string "competition for their style and fur.$"

kPokedexDescription2_DELCATTY:: @ 844C58E
    .string "$"

kPokedexDescription1_SABLEYE:: @ 844C58F
    .string "It feeds on gemstone crystals.\n"
    .string "In darkness, its eyes sparkle with the\n"
    .string "glitter of jewels.$"

kPokedexDescription2_SABLEYE:: @ 844C5E8
    .string "$"

kPokedexDescription1_MAWILE:: @ 844C5E9
    .string "It uses its docile-looking face to lull\n"
    .string "foes into complacency, then bites with its\n"
    .string "huge, relentless jaws.$"

kPokedexDescription2_MAWILE:: @ 844C653
    .string "$"

kPokedexDescription1_ARON:: @ 844C654
    .string "It eats iron to build its steel body.\n"
    .string "It is a pest that descends from mountains\n"
    .string "to eat bridges and train tracks.$"

kPokedexDescription2_ARON:: @ 844C6C5
    .string "$"

kPokedexDescription1_LAIRON:: @ 844C6C6
    .string "It habitually shows off its strength with\n"
    .string "the size of sparks it creates by ramming\n"
    .string "its steel body into boulders.$"

kPokedexDescription2_LAIRON:: @ 844C737
    .string "$"

kPokedexDescription1_AGGRON:: @ 844C738
    .string "It claims a large mountain as its sole\n"
    .string "territory. It mercilessly thrashes those\n"
    .string "that violate its space.$"

kPokedexDescription2_AGGRON:: @ 844C7A0
    .string "$"

kPokedexDescription1_MEDITITE:: @ 844C7A1
    .string "It never skips its daily yoga training.\n"
    .string "It heightens its inner strength through\n"
    .string "meditation.$"

kPokedexDescription2_MEDITITE:: @ 844C7FD
    .string "$"

kPokedexDescription1_MEDICHAM:: @ 844C7FE
    .string "It elegantly avoids attacks with dance-\n"
    .string "like steps, then launches a devastating\n"
    .string "blow in the same motion.$"

kPokedexDescription2_MEDICHAM:: @ 844C867
    .string "$"

kPokedexDescription1_ELECTRIKE:: @ 844C868
    .string "It stores static electricity in its fur\n"
    .string "for discharging. It gives off sparks if a\n"
    .string "storm approaches.$"

kPokedexDescription2_ELECTRIKE:: @ 844C8CC
    .string "$"

kPokedexDescription1_MANECTRIC:: @ 844C8CD
    .string "It rarely appears before people.\n"
    .string "It is said to nest where lightning has\n"
    .string "fallen.$"

kPokedexDescription2_MANECTRIC:: @ 844C91D
    .string "$"

kPokedexDescription1_PLUSLE:: @ 844C91E
    .string "It cheers on partners while scattering\n"
    .string "sparks from its body. It climbs telephone\n"
    .string "poles to absorb electricity.$"

kPokedexDescription2_PLUSLE:: @ 844C98C
    .string "$"

kPokedexDescription1_MINUN:: @ 844C98D
    .string "Its dislike of water makes it take shelter\n"
    .string "under the eaves of houses in rain. It uses\n"
    .string "pom-poms made of sparks for cheering.$"

kPokedexDescription2_MINUN:: @ 844CA09
    .string "$"

kPokedexDescription1_VOLBEAT:: @ 844CA0A
    .string "It lives around clean ponds. At night,\n"
    .string "its rear lights up. It converses with\n"
    .string "others by flashing its light.$"

kPokedexDescription2_VOLBEAT:: @ 844CA75
    .string "$"

kPokedexDescription1_ILLUMISE:: @ 844CA76
    .string "It guides VOLBEAT to draw signs in night\n"
    .string "skies. There are scientists that study the\n"
    .string "patterns it creates.$"

kPokedexDescription2_ILLUMISE:: @ 844CADF
    .string "$"

kPokedexDescription1_ROSELIA:: @ 844CAE0
    .string "Its flowers give off a relaxing fragrance.\n"
    .string "The stronger its aroma, the healthier\n"
    .string "the ROSELIA is.$"

kPokedexDescription2_ROSELIA:: @ 844CB41
    .string "$"

kPokedexDescription1_GULPIN:: @ 844CB42
    .string "There is nothing its stomach can’t digest.\n"
    .string "While it is digesting, vile, overpowering\n"
    .string "gases are expelled.$"

kPokedexDescription2_GULPIN:: @ 844CBAB
    .string "$"

kPokedexDescription1_SWALOT:: @ 844CBAC
    .string "It can swallow a tire whole in one gulp.\n"
    .string "It secretes a horribly toxic fluid from\n"
    .string "the pores on its body.$"

kPokedexDescription2_SWALOT:: @ 844CC14
    .string "$"

kPokedexDescription1_CARVANHA:: @ 844CC15
    .string "It lives in massive rivers that course\n"
    .string "through jungles. It swarms prey that\n"
    .string "enter its territory.$"

kPokedexDescription2_CARVANHA:: @ 844CC76
    .string "$"

kPokedexDescription1_SHARPEDO:: @ 844CC77
    .string "The ruffian of the seas, it has fangs that\n"
    .string "crunch through iron. It swims by jetting\n"
    .string "water from its rear.$"

kPokedexDescription2_SHARPEDO:: @ 844CCE0
    .string "$"

kPokedexDescription1_WAILMER:: @ 844CCE1
    .string "When it sucks in a large volume of\n"
    .string "seawater, it becomes like a big, bouncy\n"
    .string "ball. It eats a ton of food daily.$"

kPokedexDescription2_WAILMER:: @ 844CD4F
    .string "$"

kPokedexDescription1_WAILORD:: @ 844CD50
    .string "It is among the largest of all POKéMON.\n"
    .string "It herds prey in a pack then swallows the\n"
    .string "massed prey in one gulp.$"

kPokedexDescription2_WAILORD:: @ 844CDBB
    .string "$"

kPokedexDescription1_NUMEL:: @ 844CDBC
    .string "Magma of almost 2,200 degrees Fahrenheit\n"
    .string "courses through its body. When it grows\n"
    .string "cold, the magma hardens and slows it.$"

kPokedexDescription2_NUMEL:: @ 844CE33
    .string "$"

kPokedexDescription1_CAMERUPT:: @ 844CE34
    .string "If angered, the humps on its back erupt\n"
    .string "in a shower of molten lava. It lives in\n"
    .string "the craters of volcanoes.$"

kPokedexDescription2_CAMERUPT:: @ 844CE9E
    .string "$"

kPokedexDescription1_TORKOAL:: @ 844CE9F
    .string "It burns coal inside its shell. If it is\n"
    .string "attacked, it belches thick, black smoke\n"
    .string "and flees.$"

kPokedexDescription2_TORKOAL:: @ 844CEFB
    .string "$"

kPokedexDescription1_SPOINK:: @ 844CEFC
    .string "It apparently dies if it stops bouncing\n"
    .string "about. It carries a pearl from CLAMPERL\n"
    .string "on its head.$"

kPokedexDescription2_SPOINK:: @ 844CF59
    .string "$"

kPokedexDescription1_GRUMPIG:: @ 844CF5A
    .string "It can gain control over foes by doing\n"
    .string "odd dance steps. The black pearls on its\n"
    .string "forehead are precious gems.$"

kPokedexDescription2_GRUMPIG:: @ 844CFC6
    .string "$"

kPokedexDescription1_SPINDA:: @ 844CFC7
    .string "No two SPINDA are said to have identical\n"
    .string "patterns. It confuses foes with its\n"
    .string "stumbling motions.$"

kPokedexDescription2_SPINDA:: @ 844D027
    .string "$"

kPokedexDescription1_TRAPINCH:: @ 844D028
    .string "It lives in arid deserts. It makes a\n"
    .string "sloping pit trap in sand where it\n"
    .string "patiently awaits prey.$"

kPokedexDescription2_TRAPINCH:: @ 844D086
    .string "$"

kPokedexDescription1_VIBRAVA:: @ 844D087
    .string "It generates ultrasonic waves by violently\n"
    .string "flapping its wings. After making its prey\n"
    .string "faint, it melts the prey with acid.$"

kPokedexDescription2_VIBRAVA:: @ 844D100
    .string "$"

kPokedexDescription1_FLYGON:: @ 844D101
    .string "It hides itself by kicking up desert sand\n"
    .string "with its wings. Red covers shield its eyes\n"
    .string "from sand.$"

kPokedexDescription2_FLYGON:: @ 844D161
    .string "$"

kPokedexDescription1_CACNEA:: @ 844D162
    .string "It prefers harsh environments such as\n"
    .string "deserts. It can survive for 30 days on\n"
    .string "water stored in its body.$"

kPokedexDescription2_CACNEA:: @ 844D1C9
    .string "$"

kPokedexDescription1_CACTURNE:: @ 844D1CA
    .string "It lives in deserts. It becomes active at\n"
    .string "night when it hunts for prey exhausted\n"
    .string "from the desert’s heat.$"

kPokedexDescription2_CACTURNE:: @ 844D233
    .string "$"

kPokedexDescription1_SWABLU:: @ 844D234
    .string "It constantly grooms its cotton-like\n"
    .string "wings. It takes a shower to clean\n"
    .string "itself if it becomes dirty.$"

kPokedexDescription2_SWABLU:: @ 844D297
    .string "$"

kPokedexDescription1_ALTARIA:: @ 844D298
    .string "If you hear a beautiful melody trilling\n"
    .string "deep among mountains far from people,\n"
    .string "it is ALTARIA’s humming.$"

kPokedexDescription2_ALTARIA:: @ 844D2FF
    .string "$"

kPokedexDescription1_ZANGOOSE:: @ 844D300
    .string "If it comes across a SEVIPER, its fur\n"
    .string "bristles and it assumes its battle pose.\n"
    .string "Its sharp claws are its best weapon.$"

kPokedexDescription2_ZANGOOSE:: @ 844D374
    .string "$"

kPokedexDescription1_SEVIPER:: @ 844D375
    .string "It sharpens its swordlike tail on hard\n"
    .string "rocks. It hides in tall grass and strikes\n"
    .string "unwary prey with venomous fangs.$"

kPokedexDescription2_SEVIPER:: @ 844D3E7
    .string "$"

kPokedexDescription1_LUNATONE:: @ 844D3E8
    .string "Its health ebbs and flows with the lunar\n"
    .string "cycle. It brims with power when exposed\n"
    .string "to the light of the full moon.$"

kPokedexDescription2_LUNATONE:: @ 844D458
    .string "$"

kPokedexDescription1_SOLROCK:: @ 844D459
    .string "It absorbs solar energy during the day.\n"
    .string "Always expressionless, it can sense what\n"
    .string "its foe is thinking.$"

kPokedexDescription2_SOLROCK:: @ 844D4BF
    .string "$"

kPokedexDescription1_BARBOACH:: @ 844D4C0
    .string "It probes muddy riverbeds with its two\n"
    .string "long whiskers. A slimy film protects its\n"
    .string "body.$"

kPokedexDescription2_BARBOACH:: @ 844D516
    .string "$"

kPokedexDescription1_WHISCASH:: @ 844D517
    .string "It makes its nest at the bottom of \n"
    .string "swamps. It will eat anything - if it is\n"
    .string "alive, WHISCASH will eat it.$"

kPokedexDescription2_WHISCASH:: @ 844D580
    .string "$"

kPokedexDescription1_CORPHISH:: @ 844D581
    .string "It came from overseas. It is a very hardy\n"
    .string "creature that will quickly proliferate,\n"
    .string "even in polluted streams.$"

kPokedexDescription2_CORPHISH:: @ 844D5ED
    .string "$"

kPokedexDescription1_CRAWDAUNT:: @ 844D5EE
    .string "A rough customer that wildly flails its\n"
    .string "giant claws. It is said to be extremely\n"
    .string "hard to raise.$"

kPokedexDescription2_CRAWDAUNT:: @ 844D64D
    .string "$"

kPokedexDescription1_BALTOY:: @ 844D64E
    .string "It was discovered in ancient ruins.\n"
    .string "While moving, it constantly spins. It\n"
    .string "stands on one foot even when asleep.$"

kPokedexDescription2_BALTOY:: @ 844D6BD
    .string "$"

kPokedexDescription1_CLAYDOL:: @ 844D6BE
    .string "It appears to have been born from clay\n"
    .string "dolls made by ancient people. It uses\n"
    .string "telekinesis to float and move.$"

kPokedexDescription2_CLAYDOL:: @ 844D72A
    .string "$"

kPokedexDescription1_LILEEP:: @ 844D72B
    .string "It became extinct roughly 100 million\n"
    .string "years ago. It was regenerated from a\n"
    .string "fossil using advanced techniques.$"

kPokedexDescription2_LILEEP:: @ 844D798
    .string "$"

kPokedexDescription1_CRADILY:: @ 844D799
    .string "It ensnares prey with its eight tentacles.\n"
    .string "It then melts the prey with a strong acid\n"
    .string "before feeding.$"

kPokedexDescription2_CRADILY:: @ 844D7FE
    .string "$"

kPokedexDescription1_ANORITH:: @ 844D7FF
    .string "It is a kind of POKéMON progenitor.\n"
    .string "It uses its extending claws to catch prey\n"
    .string "hiding among rocks on the seafloor.$"

kPokedexDescription2_ANORITH:: @ 844D871
    .string "$"

kPokedexDescription1_ARMALDO:: @ 844D872
    .string "Protected by a hard shell, its body is\n"
    .string "very sturdy. It skewers prey with its\n"
    .string "claws to feed.$"

kPokedexDescription2_ARMALDO:: @ 844D8CE
    .string "$"

kPokedexDescription1_FEEBAS:: @ 844D8CF
    .string "Ridiculed for its shabby appearance,\n"
    .string "it is ignored by researchers. It lives in\n"
    .string "ponds choked with weeds.$"

kPokedexDescription2_FEEBAS:: @ 844D937
    .string "$"

kPokedexDescription1_MILOTIC:: @ 844D938
    .string "MILOTIC is breathtakingly beautiful.\n"
    .string "Those that see it are said to forget their\n"
    .string "combative spirits.$"

kPokedexDescription2_MILOTIC:: @ 844D99B
    .string "$"

kPokedexDescription1_CASTFORM:: @ 844D99C
    .string "It has the ability to change its form into\n"
    .string "the sun, the rain, or a snow cloud, \n"
    .string "depending on the weather.$"

kPokedexDescription2_CASTFORM:: @ 844DA06
    .string "$"

kPokedexDescription1_KECLEON:: @ 844DA07
    .string "It changes body color to blend in with\n"
    .string "its surroundings. It also changes color if\n"
    .string "it is happy or sad.$"

kPokedexDescription2_KECLEON:: @ 844DA6D
    .string "$"

kPokedexDescription1_SHUPPET:: @ 844DA6E
    .string "It loves to feed on feelings like envy and\n"
    .string "malice. Its upright horn catches the\n"
    .string "emotions of people.$"

kPokedexDescription2_SHUPPET:: @ 844DAD2
    .string "$"

kPokedexDescription1_BANETTE:: @ 844DAD3
    .string "Strong feelings of hatred turned a puppet\n"
    .string "into a POKéMON. If it opens its mouth,\n"
    .string "its cursed energy escapes.$"

kPokedexDescription2_BANETTE:: @ 844DB3F
    .string "$"

kPokedexDescription1_DUSKULL:: @ 844DB40
    .string "Making itself invisible, it silently sneaks\n"
    .string "up to prey. It has the ability to slip\n"
    .string "through thick walls.$"

kPokedexDescription2_DUSKULL:: @ 844DBA8
    .string "$"

kPokedexDescription1_DUSCLOPS:: @ 844DBA9
    .string "Its body is entirely hollow. When it opens\n"
    .string "its mouth, it sucks everything in as if it\n"
    .string "were a black hole.$"

kPokedexDescription2_DUSCLOPS:: @ 844DC12
    .string "$"

kPokedexDescription1_TROPIUS:: @ 844DC13
    .string "It lives in tropical jungles. The bunch of\n"
    .string "fruit around its neck is delicious.\n"
    .string "The fruit grows twice a year.$"

kPokedexDescription2_TROPIUS:: @ 844DC80
    .string "$"

kPokedexDescription1_CHIMECHO:: @ 844DC81
    .string "It travels by riding on winds. It cleverly\n"
    .string "uses its long tail to pluck nuts and\n"
    .string "berries, which it loves to eat.$"

kPokedexDescription2_CHIMECHO:: @ 844DCF1
    .string "$"

kPokedexDescription1_ABSOL:: @ 844DCF2
    .string "It appears when it senses an impending\n"
    .string "natural disaster. As a result, it was\n"
    .string "mistaken as a doom-bringer.$"

kPokedexDescription2_ABSOL:: @ 844DD5B
    .string "$"

kPokedexDescription1_WYNAUT:: @ 844DD5C
    .string "It tends to move in a pack with others.\n"
    .string "They cluster in a tight group to sleep in\n"
    .string "a cave.$"

kPokedexDescription2_WYNAUT:: @ 844DDB6
    .string "$"

kPokedexDescription1_SNORUNT:: @ 844DDB7
    .string "It is said that a home visited by a\n"
    .string "SNORUNT will prosper. It can withstand\n"
    .string "cold of minus 150 degrees Fahrenheit.$"

kPokedexDescription2_SNORUNT:: @ 844DE28
    .string "$"

kPokedexDescription1_GLALIE:: @ 844DE29
    .string "It has a body of ice that won’t melt,\n"
    .string "even with fire. It can instantly freeze\n"
    .string "moisture in the atmosphere.$"

kPokedexDescription2_GLALIE:: @ 844DE93
    .string "$"

kPokedexDescription1_SPHEAL:: @ 844DE94
    .string "Its body is covered in fluffy fur. The\n"
    .string "fur keeps it from feeling cold while\n"
    .string "it is rolling on ice.$"

kPokedexDescription2_SPHEAL:: @ 844DEF6
    .string "$"

kPokedexDescription1_SEALEO:: @ 844DEF7
    .string "It touches new things with its nose to\n"
    .string "test for smell and feel. It plays by\n"
    .string "spinning SPHEAL on its nose.$"

kPokedexDescription2_SEALEO:: @ 844DF60
    .string "$"

kPokedexDescription1_WALREIN:: @ 844DF61
    .string "It swims through icy seas while shattering\n"
    .string "ice floes with its large tusks. It is\n"
    .string "protected by its thick blubber.$"

kPokedexDescription2_WALREIN:: @ 844DFD2
    .string "$"

kPokedexDescription1_CLAMPERL:: @ 844DFD3
    .string "It is protected by a sturdy shell.\n"
    .string "Once in a lifetime, it makes a magnificent\n"
    .string "pearl.$"

kPokedexDescription2_CLAMPERL:: @ 844E028
    .string "$"

kPokedexDescription1_HUNTAIL:: @ 844E029
    .string "It lives deep in the sea where no light\n"
    .string "ever filters down. It lights up its small\n"
    .string "fishlike tail to attract prey.$"

kPokedexDescription2_HUNTAIL:: @ 844E09A
    .string "$"

kPokedexDescription1_GOREBYSS:: @ 844E09B
    .string "Its swimming form is exquisitely elegant.\n"
    .string "With its thin mouth, it feeds on seaweed\n"
    .string "that grows between rocks.$"

kPokedexDescription2_GOREBYSS:: @ 844E108
    .string "$"

kPokedexDescription1_RELICANTH:: @ 844E109
    .string "It has remained unchanged for 100\n"
    .string "million years. It was discovered\n"
    .string "during a deep-sea exploration.$"

kPokedexDescription2_RELICANTH:: @ 844E16B
    .string "$"

kPokedexDescription1_LUVDISC:: @ 844E16C
    .string "During the spawning season, countless\n"
    .string "LUVDISC congregate at coral reefs,\n"
    .string "turning the waters pink.$"

kPokedexDescription2_LUVDISC:: @ 844E1CE
    .string "$"

kPokedexDescription1_BAGON:: @ 844E1CF
    .string "Its steel-hard head can shatter boulders.\n"
    .string "It longingly hopes for wings to grow so it\n"
    .string "can fly.$"

kPokedexDescription2_BAGON:: @ 844E22D
    .string "$"

kPokedexDescription1_SHELGON:: @ 844E22E
    .string "Its armored body makes all attacks bounce\n"
    .string "off. The armor is too tough, however,\n"
    .string "making it heavy and somewhat sluggish.$"

kPokedexDescription2_SHELGON:: @ 844E2A5
    .string "$"

kPokedexDescription1_SALAMENCE:: @ 844E2A6
    .string "It becomes uncontrollable if it is\n"
    .string "enraged. It destroys everything with\n"
    .string "shredding claws and fire.$"

kPokedexDescription2_SALAMENCE:: @ 844E308
    .string "$"

kPokedexDescription1_BELDUM:: @ 844E309
    .string "It uses magnetic waves to converse with\n"
    .string "its kind. All the cells in its body are\n"
    .string "magnetic.$"

kPokedexDescription2_BELDUM:: @ 844E363
    .string "$"

kPokedexDescription1_METANG:: @ 844E364
    .string "It floats midair using magnetism. Its body\n"
    .string "is so tough, even a crash with a jet\n"
    .string "plane won’t leave a scratch.$"

kPokedexDescription2_METANG:: @ 844E3D1
    .string "$"

kPokedexDescription1_METAGROSS:: @ 844E3D2
    .string "It is formed by two METANG fusing.\n"
    .string "Its four brains are said to be superior\n"
    .string "to a supercomputer.$"

kPokedexDescription2_METAGROSS:: @ 844E431
    .string "$"

kPokedexDescription1_REGIROCK:: @ 844E432
    .string "It is entirely composed of rocks with no\n"
    .string "sign of a brain or heart. It is a mystery\n"
    .string "even to modern scientists.$"

kPokedexDescription2_REGIROCK:: @ 844E4A0
    .string "$"

kPokedexDescription1_REGICE:: @ 844E4A1
    .string "Research revealed that its body is made\n"
    .string "of the same kind of ice that is found at\n"
    .string "the South Pole.$"

kPokedexDescription2_REGICE:: @ 844E502
    .string "$"

kPokedexDescription1_REGISTEEL:: @ 844E503
    .string "It is sturdier than any kind of metal.\n"
    .string "It hardened due to pressure underground\n"
    .string "over tens of thousands of years.$"

kPokedexDescription2_REGISTEEL:: @ 844E573
    .string "$"

kPokedexDescription1_LATIAS:: @ 844E574
    .string "It can telepathically communicate with\n"
    .string "people. It changes its appearance using\n"
    .string "its down that refracts light.$"

kPokedexDescription2_LATIAS:: @ 844E5E1
    .string "$"

kPokedexDescription1_LATIOS:: @ 844E5E2
    .string "It has a docile temperament and dislikes\n"
    .string "fighting. Tucking in its forelegs, it can\n"
    .string "fly faster than a jet plane.$"

kPokedexDescription2_LATIOS:: @ 844E652
    .string "$"

kPokedexDescription1_KYOGRE:: @ 844E653
    .string "This POKéMON is said to have\n"
    .string "expanded the sea by bringing heavy rains.\n"
    .string "It has the power to control water.$"

kPokedexDescription2_KYOGRE:: @ 844E6BD
    .string "$"

kPokedexDescription1_GROUDON:: @ 844E6BE
    .string "This legendary POKéMON is said to\n"
    .string "represent the land. It went to sleep after\n"
    .string "dueling KYOGRE.$"

kPokedexDescription2_GROUDON:: @ 844E71B
    .string "$"

kPokedexDescription1_RAYQUAZA:: @ 844E71C
    .string "It has lived for hundreds of millions of\n"
    .string "years in the ozone layer. Its flying form\n"
    .string "looks like a meteor.$"

kPokedexDescription2_RAYQUAZA:: @ 844E784
    .string "$"

kPokedexDescription1_JIRACHI:: @ 844E785
    .string "It is said to make any wish come true.\n"
    .string "It is awake for only seven days out of\n"
    .string "a thousand years.$"

kPokedexDescription2_JIRACHI:: @ 844E7E5
    .string "$"

kPokedexDescription1_DEOXYS:: @ 844E7E6
    .string "This DEOXYS has transformed into its\n"
    .string "aggressive guise. It can fool enemies by\n"
    .string "altering its appearance.$"

kPokedexDescription2_DEOXYS:: @ 844E84D
    .string "$"

