
Text2_8444A71:: @ 8444A71
    .string "This is a newly discovered POKéMON. It is\n"
    .string "currently under investigation. No detailed\n"
    .string "information is available at this time.$"

Text2_8444AED:: @ 8444AED
    .string "$"

Text2_8444AEE:: @ 8444AEE
    .string "A strange seed was planted on its back at\n"
    .string "birth. The plant sprouts and grows with\n"
    .string "this POKéMON.$"

Text2_8444B4E:: @ 8444B4E
    .string "$"

Text2_8444B4F:: @ 8444B4F
    .string "When the bulb on its back grows large, it\n"
    .string "appears to lose the ability to stand on\n"
    .string "its hind legs.$"

Text2_8444BB0:: @ 8444BB0
    .string "$"

Text2_8444BB1:: @ 8444BB1
    .string "Its plant blooms when it is absorbing\n"
    .string "solar energy. It stays on the move to\n"
    .string "seek sunlight.$"

Text2_8444C0C:: @ 8444C0C
    .string " $"

Text2_8444C0E:: @ 8444C0E
    .string "It has a preference for hot things.\n"
    .string "When it rains, steam is said to spout from\n"
    .string "the tip of its tail.$"

Text2_8444C72:: @ 8444C72
    .string "$"

Text2_8444C73:: @ 8444C73
    .string "When it swings its burning tail, it\n"
    .string "elevates the air temperature to \n"
    .string "unbearably high levels.$"

Text2_8444CD0:: @ 8444CD0
    .string "$"

Text2_8444CD1:: @ 8444CD1
    .string "It spits fire that is hot enough to melt\n"
    .string "boulders. It may cause forest fires by\n"
    .string "blowing flames.$"

Text2_8444D31:: @ 8444D31
    .string "$"

Text2_8444D32:: @ 8444D32
    .string "After birth, its back swells and hardens\n"
    .string "into a shell. It powerfully sprays foam \n"
    .string "from its mouth.$"

Text2_8444D94:: @ 8444D94
    .string "$"

Text2_8444D95:: @ 8444D95
    .string "It often hides in water to stalk unwary\n"
    .string "prey. For fast swimming, it moves its\n"
    .string "ears to maintain balance.$"

Text2_8444DFD:: @ 8444DFD
    .string "$"

Text2_8444DFE:: @ 8444DFE
    .string "The pressurized water jets on this brutal\n"
    .string "POKéMON’s shell are used for high-\n"
    .string "speed tackles.$"

Text2_8444E5A:: @ 8444E5A
    .string "$"

Text2_8444E5B:: @ 8444E5B
    .string "Its short feet are tipped with suction\n"
    .string "pads that enable it to tirelessly climb\n"
    .string "slopes and walls.$"

Text2_8444EBC:: @ 8444EBC
    .string "$"

Text2_8444EBD:: @ 8444EBD
    .string "This POKéMON is vulnerable to attack\n"
    .string "while its shell is soft, exposing its weak\n"
    .string "and tender body.$"

Text2_8444F1E:: @ 8444F1E
    .string " $"

Text2_8444F20:: @ 8444F20
    .string "In battle, it flaps its wings at great\n"
    .string "speed to release highly toxic dust into\n"
    .string "the air.$"

Text2_8444F78:: @ 8444F78
    .string " $"

Text2_8444F7A:: @ 8444F7A
    .string "Often found in forests, eating leaves.\n"
    .string "It has a sharp stinger on its head that\n"
    .string "injects poison.$"

Text2_8444FD9:: @ 8444FD9
    .string "$"

Text2_8444FDA:: @ 8444FDA
    .string "Almost incapable of moving, this POKéMON\n"
    .string "can only harden its shell to protect\n"
    .string "itself when it is in danger.$"

Text2_8445045:: @ 8445045
    .string "$"

Text2_8445046:: @ 8445046
    .string "It flies at high speed and attacks using \n"
    .string "the large venomous stingers on its\n"
    .string "forelegs and tail.$"

Text2_84450A6:: @ 84450A6
    .string "$"

Text2_84450A7:: @ 84450A7
    .string "A common sight in forests and woods.\n"
    .string "It flaps its wings at ground level to kick\n"
    .string "up blinding sand.$"

Text2_8445109:: @ 8445109
    .string "$"

Text2_844510A:: @ 844510A
    .string "Very protective of its sprawling\n"
    .string "territorial area, this POKéMON will\n"
    .string "fiercely peck at any intruder.$"

Text2_844516E:: @ 844516E
    .string "$"

Text2_844516F:: @ 844516F
    .string "When hunting, it skims the surface of\n"
    .string "water at high speed to pick off unwary\n"
    .string "prey such as MAGIKARP.$"

Text2_84451D3:: @ 84451D3
    .string "$"

Text2_84451D4:: @ 84451D4
    .string "Bites anything when it attacks. Small and\n"
    .string "very quick, it is a common sight in many\n"
    .string "places.$"

Text2_844522F:: @ 844522F
    .string "$"

Text2_8445230:: @ 8445230
    .string "It uses its whiskers to maintain its\n"
    .string "balance. It apparently slows down if\n"
    .string "they are cut off.$"

Text2_844528C:: @ 844528C
    .string "$"

Text2_844528D:: @ 844528D
    .string "Eats bugs in grassy areas. It has to flap\n"
    .string "its short wings at high speed to stay\n"
    .string "airborne.$"

Text2_84452E7:: @ 84452E7
    .string "$"

Text2_84452E8:: @ 84452E8
    .string "With its huge and magnificent wings, it can\n"
    .string "keep aloft without ever having to land\n"
    .string "for rest.$"

Text2_8445345:: @ 8445345
    .string "$"

Text2_8445346:: @ 8445346
    .string "Moving silently and stealthily, it eats\n"
    .string "the eggs of birds, such as PIDGEY\n"
    .string "and SPEAROW, whole.$"

Text2_84453A4:: @ 84453A4
    .string "$"

Text2_84453A5:: @ 84453A5
    .string "It is rumored that the ferocious warning\n"
    .string "markings on its belly differ from area to\n"
    .string "area.$"

Text2_84453FE:: @ 84453FE
    .string "$"

Text2_84453FF:: @ 84453FF
    .string "When several of these POKéMON gather,\n"
    .string "their electricity can build and cause\n"
    .string "lightning storms.$"

Text2_844545D:: @ 844545D
    .string "$"

Text2_844545E:: @ 844545E
    .string "Its long tail serves as a ground to\n"
    .string "protect itself from its own high-voltage\n"
    .string "power.$"

Text2_84454B2:: @ 84454B2
    .string "$"

Text2_84454B3:: @ 84454B3
    .string "Burrows deep underground in arid locations\n"
    .string "far from water. It only emerges to hunt\n"
    .string "for prey.$"

Text2_8445510:: @ 8445510
    .string "$"

Text2_8445511:: @ 8445511
    .string "Curls up into a spiny ball when\n"
    .string "threatened. It can roll while curled up\n"
    .string "to attack or escape.$"

Text2_844556E:: @ 844556E
    .string "$"

Text2_844556F:: @ 844556F
    .string "Although small, its venomous barbs render\n"
    .string "this POKéMON dangerous. The female has\n"
    .string "smaller horns.$"

Text2_84455CF:: @ 84455CF
    .string "$"

Text2_84455D0:: @ 84455D0
    .string "The female’s horns develop slowly.\n"
    .string "Prefers physical attacks such as clawing\n"
    .string "and biting.$"

Text2_8445628:: @ 8445628
    .string "$"

Text2_8445629:: @ 8445629
    .string "Its hard scales provide strong protection.\n"
    .string "It uses its hefty bulk to execute\n"
    .string "powerful moves.$"

Text2_8445686:: @ 8445686
    .string "$"

Text2_8445687:: @ 8445687
    .string "It stiffens its ears to sense danger.\n"
    .string "The larger its horns, the more \n"
    .string "powerful its secreted venom.$"

Text2_84456EA:: @ 84456EA
    .string "$"

Text2_84456EB:: @ 84456EB
    .string "An aggressive POKéMON that is quick to\n"
    .string "attack. The horn on its head secretes a\n"
    .string "powerful venom.$"

Text2_844574A:: @ 844574A
    .string "$"

Text2_844574B:: @ 844574B
    .string "It uses its powerful tail in battle to\n"
    .string "smash, constrict, then break the prey’s\n"
    .string "bones.$"

Text2_84457A1:: @ 84457A1
    .string "$"

Text2_84457A2:: @ 84457A2
    .string "With its magical and cute appeal, it has \n"
    .string "many admirers. It is rare and found only\n"
    .string "in certain areas.$"

Text2_8445807:: @ 8445807
    .string "$"

Text2_8445808:: @ 8445808
    .string "A timid fairy POKéMON that is rarely seen,\n"
    .string "it will run and hide the moment it senses\n"
    .string "people.$"

Text2_8445865:: @ 8445865
    .string "$"

Text2_8445866:: @ 8445866
    .string "When it is born, it has just one snow-\n"
    .string "white tail. The tail splits from its tip as\n"
    .string "it grows older.$"

Text2_84458C9:: @ 84458C9
    .string "$"

Text2_84458CA:: @ 84458CA
    .string "Very smart and very vengeful. Grabbing\n"
    .string "one of its many tails could result in a\n"
    .string "1,000-year curse.$"

Text2_844592B:: @ 844592B
    .string "$"

Text2_844592C:: @ 844592C
    .string "When its huge eyes waver, it sings a\n"
    .string "mysteriously soothing melody that lulls\n"
    .string "its enemies to sleep.$"

Text2_844598F:: @ 844598F
    .string "$"

Text2_8445990:: @ 8445990
    .string "The body is soft and rubbery. When\n"
    .string "angered, it will suck in air and inflate\n"
    .string "itself to an enormous size.$"

Text2_84459F8:: @ 84459F8
    .string "$"

Text2_84459F9:: @ 84459F9
    .string "It forms colonies in perpetually dark \n"
    .string "places and uses ultrasonic waves to  \n"
    .string "identify and approach targets.$"

Text2_8445A65:: @ 8445A65
    .string "$"

Text2_8445A66:: @ 8445A66
    .string "Once it bites, it will not stop draining\n"
    .string "energy from the victim even if it gets too\n"
    .string "heavy to fly.$"

Text2_8445AC8:: @ 8445AC8
    .string "$"

Text2_8445AC9:: @ 8445AC9
    .string "During the day, it keeps its face buried\n"
    .string "in the ground. At night, it wanders around\n"
    .string "sowing its seeds.$"

Text2_8445B2F:: @ 8445B2F
    .string "$"

Text2_8445B30:: @ 8445B30
    .string "The fluid that oozes from its mouth isn’t\n"
    .string "drool. It is a nectar that is used to\n"
    .string "attract prey.$"

Text2_8445B8E:: @ 8445B8E
    .string "$"

Text2_8445B8F:: @ 8445B8F
    .string "The larger its petals, the more toxic\n"
    .string "pollen it contains. Its big head is heavy\n"
    .string "and hard to hold up.$"

Text2_8445BF4:: @ 8445BF4
    .string "$"

Text2_8445BF5:: @ 8445BF5
    .string "Burrows to suck tree roots. The mushrooms\n"
    .string "on its back grow by drawing nutrients from\n"
    .string "the bug host.$"

Text2_8445C58:: @ 8445C58
    .string "$"

Text2_8445C59:: @ 8445C59
    .string "A host-parasite pair in which the parasite\n"
    .string "mushroom has taken over the host bug.\n"
    .string "Prefers damp places. $"

Text2_8445CC0:: @ 8445CC0
    .string "$"

Text2_8445CC1:: @ 8445CC1
    .string "Lives in the shadows of tall trees where\n"
    .string "it eats bugs. It is attracted by light\n"
    .string "at night.$"

Text2_8445D1B:: @ 8445D1B
    .string "$"

Text2_8445D1C:: @ 8445D1C
    .string "The dustlike scales covering its wings\n"
    .string "are color-coded to indicate the kinds of\n"
    .string "poison it has.$"

Text2_8445D7B:: @ 8445D7B
    .string "$"

Text2_8445D7C:: @ 8445D7C
    .string "Lives about one yard underground where it\n"
    .string "feeds on plant roots. It sometimes appears\n"
    .string "aboveground.$"

Text2_8445DDE:: @ 8445DDE
    .string "$"

Text2_8445DDF:: @ 8445DDF
    .string "A team of DIGLETT triplets. It triggers\n"
    .string "huge earthquakes by burrowing 60 miles\n"
    .string "underground.$"

Text2_8445E3B:: @ 8445E3B
    .string "$"

Text2_8445E3C:: @ 8445E3C
    .string "Adores round objects. It wanders the\n"
    .string "streets on a nightly basis to look for\n"
    .string "dropped loose change.$"

Text2_8445E9E:: @ 8445E9E
    .string "$"

Text2_8445E9F:: @ 8445E9F
    .string "Although its fur has many admirers, it is\n"
    .string "tough to raise as a pet because of its\n"
    .string "fickle meanness.$"

Text2_8445F01:: @ 8445F01
    .string "$"

Text2_8445F02:: @ 8445F02
    .string "While lulling its enemies with its vacant\n"
    .string "look, this wily POKéMON will use\n"
    .string "psychokinetic powers.$"

Text2_8445F63:: @ 8445F63
    .string "$"

Text2_8445F64:: @ 8445F64
    .string "Often seen swimming elegantly by\n"
    .string "lakeshores. It is often mistaken for the\n"
    .string "Japanese monster Kappa.$"

Text2_8445FC6:: @ 8445FC6
    .string "$"

Text2_8445FC7:: @ 8445FC7
    .string "Extremely quick to anger. It could be\n"
    .string "docile one moment, then thrashing away \n"
    .string "the next instant.$"

Text2_8446027:: @ 8446027
    .string "$"

Text2_8446028:: @ 8446028
    .string "Always furious and tenacious to boot.\n"
    .string "It will not abandon chasing its quarry\n"
    .string "until it catches up.$"

Text2_844608A:: @ 844608A
    .string "$"

Text2_844608B:: @ 844608B
    .string "It is very protective of its territory.\n"
    .string "It will bark and bite to repel intruders\n"
    .string "from its space.$"

Text2_84460EC:: @ 84460EC
    .string "$"

Text2_84460ED:: @ 84460ED
    .string "A POKéMON that has long been admired\n"
    .string "for its beauty. It runs agilely as if\n"
    .string "on wings.$"

Text2_8446142:: @ 8446142
    .string "$"

Text2_8446143:: @ 8446143
    .string "Its newly grown legs prevent it from\n"
    .string "walking well. It appears to prefer\n"
    .string "swimming over walking.$"

Text2_84461A2:: @ 84461A2
    .string "$"

Text2_84461A3:: @ 84461A3
    .string "It can live in or out of water. When out\n"
    .string "of water, it constantly sweats to keep its\n"
    .string "body slimy.$"

Text2_8446203:: @ 8446203
    .string "$"

Text2_8446204:: @ 8446204
    .string "A swimmer adept at both the front crawl\n"
    .string "and breaststroke. Easily overtakes the\n"
    .string "best human swimmers.$"

Text2_8446268:: @ 8446268
    .string "$"

Text2_8446269:: @ 8446269
    .string "Using its ability to read minds, it will\n"
    .string "sense impending danger and TELEPORT to\n"
    .string "safety.$"

Text2_84462C1:: @ 84462C1
    .string "$"

Text2_84462C2:: @ 84462C2
    .string "It emits special alpha waves from its\n"
    .string "body that induce headaches just by being\n"
    .string "close.$"

Text2_8446318:: @ 8446318
    .string "$"

Text2_8446319:: @ 8446319
    .string "Its brain can outperform a supercomputer.\n"
    .string "Its IQ (intelligence quotient) is said to\n"
    .string "be around 5,000.$"

Text2_844637E:: @ 844637E
    .string "$"

Text2_844637F:: @ 844637F
    .string "Loves to build its muscles. It trains in\n"
    .string "all styles of martial arts to become even\n"
    .string "stronger.$"

Text2_84463DC:: @ 84463DC
    .string "$"

Text2_84463DD:: @ 84463DD
    .string "Its muscular body is so powerful, it must\n"
    .string "wear a power-save belt to be able to\n"
    .string "regulate its motions.$"

Text2_8446442:: @ 8446442
    .string "$"

Text2_8446443:: @ 8446443
    .string "Its superpowerful punches are said to\n"
    .string "knock the victim flying clear over the\n"
    .string "horizon.$"

Text2_8446499:: @ 8446499
    .string "$"

Text2_844649A:: @ 844649A
    .string "A carnivorous POKéMON that traps and eats\n"
    .string "bugs. It appears to use its root feet to\n"
    .string "replenish moisture.$"

Text2_8446501:: @ 8446501
    .string "$"

Text2_8446502:: @ 8446502
    .string "It spits out POISONPOWDER to immobilize\n"
    .string "the enemy and then finishes it with a\n"
    .string "spray of ACID.$"

Text2_844655F:: @ 844655F
    .string "$"

Text2_8446560:: @ 8446560
    .string "Said to live in huge colonies deep in\n"
    .string "jungles, although no one has ever\n"
    .string "returned from there.$"

Text2_84465BD:: @ 84465BD
    .string "$"

Text2_84465BE:: @ 84465BE
    .string "Drifts in shallow seas. Anglers who hook\n"
    .string "them by accident are often punished by\n"
    .string "their stingers.$"

Text2_844661E:: @ 844661E
    .string "$"

Text2_844661F:: @ 844661F
    .string "The tentacles are normally kept short.\n"
    .string "On hunts, they are extended to ensnare\n"
    .string "and immobilize prey.$"

Text2_8446682:: @ 8446682
    .string "$"

Text2_8446683:: @ 8446683
    .string "Found in fields and mountains. Mistaking\n"
    .string "them for boulders, people often step or\n"
    .string "trip on them.$"

Text2_84466E2:: @ 84466E2
    .string "$"

Text2_84466E3:: @ 84466E3
    .string "Rolls down slopes to move. It rolls over\n"
    .string "any obstacle without slowing or changing\n"
    .string "its direction.$"

Text2_8446744:: @ 8446744
    .string "$"

Text2_8446745:: @ 8446745
    .string "Its boulder-like body is extremely hard.\n"
    .string "It can easily withstand dynamite blasts\n"
    .string "without taking damage.$"

Text2_84467AD:: @ 84467AD
    .string "$"

Text2_84467AE:: @ 84467AE
    .string "Its hooves are ten times harder than\n"
    .string "diamond. It can trample anything\n"
    .string "completely flat in little time.$"

Text2_8446814:: @ 8446814
    .string "$"

Text2_8446815:: @ 8446815
    .string "Very competitive, this POKéMON will chase\n"
    .string "anything that moves fast in the hopes of\n"
    .string "racing it.$"

Text2_8446873:: @ 8446873
    .string "$"

Text2_8446874:: @ 8446874
    .string "Incredibly slow and dopey. It takes five\n"
    .string "seconds for it to feel pain when under\n"
    .string "attack.$"

Text2_84468CC:: @ 84468CC
    .string "$"

Text2_84468CD:: @ 84468CD
    .string "The SHELLDER that latches onto\n"
    .string "SLOWPOKE’s tail is said to feed on the\n"
    .string "host’s leftover scraps.$"

Text2_844692B:: @ 844692B
    .string "$"

Text2_844692C:: @ 844692C
    .string "Uses antigravity to stay suspended.\n"
    .string "Appears without warning and uses THUNDER\n"
    .string "WAVE and similar moves.$"

Text2_8446991:: @ 8446991
    .string "$"

Text2_8446992:: @ 8446992
    .string "Formed by several MAGNEMITE linked\n"
    .string "together. They frequently appear when\n"
    .string "sunspots flare up.$"

Text2_84469EE:: @ 84469EE
    .string "$"

Text2_84469EF:: @ 84469EF
    .string "The plant stalk it holds is its weapon.\n"
    .string "The stalk is used like a sword to cut all\n"
    .string "sorts of things.$"

Text2_8446A52:: @ 8446A52
    .string "$"

Text2_8446A53:: @ 8446A53
    .string "A bird that makes up for its poor flying\n"
    .string "with its fast foot speed. Leaves giant\n"
    .string "footprints.$"

Text2_8446AAF:: @ 8446AAF
    .string "$"

Text2_8446AB0:: @ 8446AB0
    .string "Uses its three brains to execute complex\n"
    .string "plans. While two heads sleep, one head is\n"
    .string "said to stay awake.$"

Text2_8446B17:: @ 8446B17
    .string "$"

Text2_8446B18:: @ 8446B18
    .string "The protruding horn on its head is very\n"
    .string "hard. It is used for bashing through thick\n"
    .string "icebergs.$"

Text2_8446B75:: @ 8446B75
    .string "$"

Text2_8446B76:: @ 8446B76
    .string "It stores thermal energy in the body.\n"
    .string "It swims at a steady eight knots even in\n"
    .string "intensely cold waters.$"

Text2_8446BDC:: @ 8446BDC
    .string "$"

Text2_8446BDD:: @ 8446BDD
    .string "Appears in filthy areas. It thrives by\n"
    .string "sucking up polluted sludge that is pumped\n"
    .string "out of factories.$"

Text2_8446C40:: @ 8446C40
    .string "$"

Text2_8446C41:: @ 8446C41
    .string "Thickly covered with a filthy, vile\n"
    .string "sludge. It is so toxic, even its footprints\n"
    .string "contain poison.$"

Text2_8446CA1:: @ 8446CA1
    .string "$"

Text2_8446CA2:: @ 8446CA2
    .string "Its hard shell repels any kind of attack.\n"
    .string "It is vulnerable only when its shell is\n"
    .string "open.$"

Text2_8446CFA:: @ 8446CFA
    .string "$"

Text2_8446CFB:: @ 8446CFB
    .string "When attacked, it launches its horns in\n"
    .string "quick volleys. Its innards have never been\n"
    .string "seen.$"

Text2_8446D54:: @ 8446D54
    .string "$"

Text2_8446D55:: @ 8446D55
    .string "Almost invisible, this gaseous POKéMON\n"
    .string "cloaks the target and puts it to sleep\n"
    .string "without notice.$"

Text2_8446DB3:: @ 8446DB3
    .string "$"

Text2_8446DB4:: @ 8446DB4
    .string "Because of its ability to slip through\n"
    .string "block walls, it is said to be from another\n"
    .string "dimension.$"

Text2_8446E11:: @ 8446E11
    .string "$"

Text2_8446E12:: @ 8446E12
    .string "On the night of a full moon, if shadows\n"
    .string "move on their own and laugh, it must be\n"
    .string "GENGAR’s doing.$"

Text2_8446E72:: @ 8446E72
    .string "$"

Text2_8446E73:: @ 8446E73
    .string "As it grows, the stone portions of its\n"
    .string "body harden to become similar to\n"
    .string "black-colored diamonds.$"

Text2_8446ED3:: @ 8446ED3
    .string "$"

Text2_8446ED4:: @ 8446ED4
    .string "Puts enemies to sleep, then eats their\n"
    .string "dreams. Occasionally gets sick from eating\n"
    .string "only bad dreams.$"

Text2_8446F37:: @ 8446F37
    .string "$"

Text2_8446F38:: @ 8446F38
    .string "When it locks eyes with an enemy, it will\n"
    .string "use a mix of PSI moves such as HYPNOSIS\n"
    .string "and CONFUSION.$"

Text2_8446F99:: @ 8446F99
    .string "$"

Text2_8446F9A:: @ 8446F9A
    .string "Its pincers are not only powerful weapons,\n"
    .string "they are used for balance when walking\n"
    .string "sideways.$"

Text2_8446FF6:: @ 8446FF6
    .string "$"

Text2_8446FF7:: @ 8446FF7
    .string "The large pincer has 10,000-horsepower\n"
    .string "crushing force. However, its huge size\n"
    .string "makes it unwieldy to use.$"

Text2_844705F:: @ 844705F
    .string "$"

Text2_8447060:: @ 8447060
    .string "Usually found in power plants. Easily\n"
    .string "mistaken for a POKé BALL, it has\n"
    .string "zapped many people.$"

Text2_84470BB:: @ 84470BB
    .string "$"

Text2_84470BC:: @ 84470BC
    .string "It stores electric energy under very high\n"
    .string "pressure. It often explodes with little or\n"
    .string "no provocation.$"

Text2_8447121:: @ 8447121
    .string "$"

Text2_8447122:: @ 8447122
    .string "It is often mistaken for eggs. When\n"
    .string "disturbed, they quickly gather and attack\n"
    .string "in swarms.$"

Text2_844717B:: @ 844717B
    .string "$"

Text2_844717C:: @ 844717C
    .string "It is said that on rare occasions, one\n"
    .string "of its heads will drop off and continue on\n"
    .string "as an EXEGGCUTE.$"

Text2_84471DF:: @ 84471DF
    .string "$"

Text2_84471E0:: @ 84471E0
    .string "Because it never removes its skull helmet,\n"
    .string "no one has ever seen this POKéMON’s real\n"
    .string "face.$"

Text2_844723A:: @ 844723A
    .string "$"

Text2_844723B:: @ 844723B
    .string "The bone it holds is its key weapon.\n"
    .string "It throws the bone skillfully like a\n"
    .string "boomerang to KO targets.$"

Text2_844729E:: @ 844729E
    .string "$"

Text2_844729F:: @ 844729F
    .string "When in a hurry, its legs lengthen\n"
    .string "progressively. It runs smoothly with\n"
    .string "extra-long, loping strides.$"

Text2_8447303:: @ 8447303
    .string "$"

Text2_8447304:: @ 8447304
    .string "While apparently doing nothing, it fires\n"
    .string "punches in lightning-fast volleys that are\n"
    .string "impossible to see.$"

Text2_844736B:: @ 844736B
    .string "$"

Text2_844736C:: @ 844736C
    .string "Its tongue can be extended like a\n"
    .string "chameleon’s. It leaves a tingling\n"
    .string "sensation when it licks enemies.$"

Text2_84473D1:: @ 84473D1
    .string "$"

Text2_84473D2:: @ 84473D2
    .string "Because it stores several kinds of toxic\n"
    .string "gases in its body, it is prone to\n"
    .string "exploding without warning.$"

Text2_8447438:: @ 8447438
    .string "$"

Text2_8447439:: @ 8447439
    .string "Where two kinds of poison gases meet, two\n"
    .string "KOFFING can fuse into a WEEZING over\n"
    .string "many years.$"

Text2_8447494:: @ 8447494
    .string "$"

Text2_8447495:: @ 8447495
    .string "Its massive bones are 1,000 times harder\n"
    .string "than human bones. Its TACKLE can knock a\n"
    .string "semitrailer flying.$"

Text2_84474FB:: @ 84474FB
    .string "$"

Text2_84474FC:: @ 84474FC
    .string "Protected by an armor-like hide, it is\n"
    .string "capable of living in molten lava of 3,600\n"
    .string "degrees Fahrenheit.$"

Text2_8447561:: @ 8447561
    .string "$"

Text2_8447562:: @ 8447562
    .string "A rare and elusive POKéMON that is said\n"
    .string "to bring happiness to those who manage to\n"
    .string "catch one.$"

Text2_84475BF:: @ 84475BF
    .string "$"

Text2_84475C0:: @ 84475C0
    .string "The whole body is swathed with wide vines\n"
    .string "that are similar to seaweed. The vines\n"
    .string "sway as it walks.$"

Text2_8447623:: @ 8447623
    .string "$"

Text2_8447624:: @ 8447624
    .string "The infant rarely ventures out of its\n"
    .string "mother’s protective pouch until it is\n"
    .string "three years old.$"

Text2_8447681:: @ 8447681
    .string "$"

Text2_8447682:: @ 8447682
    .string "Known to shoot down flying bugs with\n"
    .string "precision blasts of ink from the surface\n"
    .string "of the water.$"

Text2_84476DE:: @ 84476DE
    .string "$"

Text2_84476DF:: @ 84476DF
    .string "It is capable of swimming backwards by\n"
    .string "rapidly flapping its winglike pectoral fins\n"
    .string "and stout tail.$"

Text2_8447742:: @ 8447742
    .string "$"

Text2_8447743:: @ 8447743
    .string "Its tail fin billows like an elegant\n"
    .string "ballroom dress, giving it the nickname of\n"
    .string "“The Water Queen.”$"

Text2_84477A5:: @ 84477A5
    .string "$"

Text2_84477A6:: @ 84477A6
    .string "In the autumn spawning season, they can\n"
    .string "be seen swimming powerfully up rivers and\n"
    .string "creeks.$"

Text2_8447800:: @ 8447800
    .string "$"

Text2_8447801:: @ 8447801
    .string "An enigmatic POKéMON that can effortlessly\n"
    .string "regenerate any appendage it loses in\n"
    .string "battle.$"

Text2_8447859:: @ 8447859
    .string "$"

Text2_844785A:: @ 844785A
    .string "Its central core glows with the seven\n"
    .string "colors of the rainbow. Some people value\n"
    .string "the core as a gem.$"

Text2_84478BC:: @ 84478BC
    .string "$"

Text2_84478BD:: @ 84478BD
    .string "If interrupted while it is miming, it will\n"
    .string "suddenly DOUBLESLAP the offender with its\n"
    .string "broad hands.$"

Text2_844791F:: @ 844791F
    .string "$"

Text2_8447920:: @ 8447920
    .string "With ninja-like agility and speed, it can\n"
    .string "create the illusion that there is more\n"
    .string "than one of itself.$"

Text2_8447985:: @ 8447985
    .string "$"

Text2_8447986:: @ 8447986
    .string "It seductively wiggles its hips as it\n"
    .string "walks. It can cause people to dance in\n"
    .string "unison with it.$"

Text2_84479E3:: @ 84479E3
    .string "$"

Text2_84479E4:: @ 84479E4
    .string "Normally found near power plants, they\n"
    .string "can wander away and cause major\n"
    .string "blackouts in cities.$"

Text2_8447A40:: @ 8447A40
    .string "$"

Text2_8447A41:: @ 8447A41
    .string "Its body always burns with an orange glow\n"
    .string "that enables it to hide perfectly amidst\n"
    .string "flames.$"

Text2_8447A9C:: @ 8447A9C
    .string "$"

Text2_8447A9D:: @ 8447A9D
    .string "If it fails to crush the foe in its\n"
    .string "pincers, it will swing around and toss\n"
    .string "the opponent.$"

Text2_8447AF6:: @ 8447AF6
    .string "$"

Text2_8447AF7:: @ 8447AF7
    .string "When it targets an enemy, it charges\n"
    .string "furiously while whipping its body with its\n"
    .string "long tails.$"

Text2_8447B53:: @ 8447B53
    .string "$"

Text2_8447B54:: @ 8447B54
    .string "In the distant past, it was somewhat\n"
    .string "stronger than the horribly weak\n"
    .string "descendants that exist today.$"

Text2_8447BB7:: @ 8447BB7
    .string "$"

Text2_8447BB8:: @ 8447BB8
    .string "Rarely seen in the wild. Huge and vicious,\n"
    .string "it is capable of destroying entire cities\n"
    .string "in a rage.$"

Text2_8447C18:: @ 8447C18
    .string "$"

Text2_8447C19:: @ 8447C19
    .string "A POKéMON that has been overhunted\n"
    .string "almost to extinction. It can ferry people\n"
    .string "on its back.$"

Text2_8447C73:: @ 8447C73
    .string "$"

Text2_8447C74:: @ 8447C74
    .string "Capable of copying an opponent’s genetic\n"
    .string "code to instantly transform itself into a\n"
    .string "duplicate of the enemy.$"

Text2_8447CDF:: @ 8447CDF
    .string "$"

Text2_8447CE0:: @ 8447CE0
    .string "Its genetic code is irregular. It may\n"
    .string "mutate if it is exposed to radiation from\n"
    .string "element STONES.$"

Text2_8447D40:: @ 8447D40
    .string "$"

Text2_8447D41:: @ 8447D41
    .string "Lives close to water. Its long tail is\n"
    .string "ridged with a fin which is often mistaken\n"
    .string "for a mermaid’s.$"

Text2_8447DA3:: @ 8447DA3
    .string "$"

Text2_8447DA4:: @ 8447DA4
    .string "It accumulates negative ions in the\n"
    .string "atmosphere to blast out 10,000-volt\n"
    .string "lightning bolts.$"

Text2_8447DFD:: @ 8447DFD
    .string "$"

Text2_8447DFE:: @ 8447DFE
    .string "When storing thermal energy in its body,\n"
    .string "its temperature can soar to over 1,600\n"
    .string "degrees Fahrenheit.$"

Text2_8447E62:: @ 8447E62
    .string "$"

Text2_8447E63:: @ 8447E63
    .string "A POKéMON that consists entirely of\n"
    .string "programming code. It is capable of moving\n"
    .string "freely in cyberspace.$"

Text2_8447EC7:: @ 8447EC7
    .string "$"

Text2_8447EC8:: @ 8447EC8
    .string "Although long extinct, in rare cases, it\n"
    .string "can be genetically regenerated from\n"
    .string "fossils.$"

Text2_8447F1E:: @ 8447F1E
    .string "$"

Text2_8447F1F:: @ 8447F1F
    .string "Despite having strong fangs and tentacles,\n"
    .string "it went extinct when its heavy shell made\n"
    .string "it unable to catch prey.$"

Text2_8447F8D:: @ 8447F8D
    .string "$"

Text2_8447F8E:: @ 8447F8E
    .string "A POKéMON that was regenerated from a\n"
    .string "fossil found in what was once the ocean\n"
    .string "floor long ago.$"

Text2_8447FEC:: @ 8447FEC
    .string "$"

Text2_8447FED:: @ 8447FED
    .string "Its sleek shape is perfect for swimming.\n"
    .string "It slashes prey with its claws and drains\n"
    .string "their fluids.$"

Text2_844804E:: @ 844804E
    .string "$"

Text2_844804F:: @ 844804F
    .string "A ferocious, prehistoric POKéMON that\n"
    .string "goes for the enemy’s throat with its\n"
    .string "serrated, sawlike fangs.$"

Text2_84480B3:: @ 84480B3
    .string "$"

Text2_84480B4:: @ 84480B4
    .string "Very lazy. Just eats and sleeps. As its\n"
    .string "rotund bulk builds, it becomes steadily\n"
    .string "more slothful.$"

Text2_8448113:: @ 8448113
    .string "$"

Text2_8448114:: @ 8448114
    .string "A legendary bird POKéMON that is said to\n"
    .string "appear to doomed people who are lost in\n"
    .string "icy mountains.$"

Text2_8448174:: @ 8448174
    .string "$"

Text2_8448175:: @ 8448175
    .string "A legendary bird POKéMON that is said to\n"
    .string "appear from clouds while dropping\n"
    .string "enormous lightning bolts.$"

Text2_84481DA:: @ 84481DA
    .string "$"

Text2_84481DB:: @ 84481DB
    .string "It is said to be the legendary bird\n"
    .string "POKéMON of fire. Every flap of its wings\n"
    .string "creates a dazzling flare of flames.$"

Text2_844824C:: @ 844824C
    .string "$"

Text2_844824D:: @ 844824D
    .string "Long considered a mythical POKéMON until\n"
    .string "recently, when a small colony was found\n"
    .string "living underwater.$"

Text2_84482B1:: @ 84482B1
    .string "$"

Text2_84482B2:: @ 84482B2
    .string "A mystical POKéMON that exudes a gentle\n"
    .string "aura. It is said to have the ability to\n"
    .string "change the weather.$"

Text2_8448316:: @ 8448316
    .string "$"

Text2_8448317:: @ 8448317
    .string "Only a very few people ever see this\n"
    .string "POKéMON. Its intelligence is said to\n"
    .string "match that of humans.$"

Text2_8448377:: @ 8448377
    .string "$"

Text2_8448378:: @ 8448378
    .string "It was created by a scientist after years\n"
    .string "of horrific gene-splicing and DNA-\n"
    .string "engineering experiments.$"

Text2_84483DE:: @ 84483DE
    .string "$"

Text2_84483DF:: @ 84483DF
    .string "So rare that it is still said to be a\n"
    .string "mirage by many experts. Only a few people\n"
    .string "have seen it worldwide.$"

Text2_8448447:: @ 8448447
    .string "$"

Text2_8448448:: @ 8448448
    .string "A sweet aroma gently wafts from the leaf\n"
    .string "on its head. It is docile and loves to\n"
    .string "soak up the sun’s rays.$"

Text2_84484B0:: @ 84484B0
    .string "$"

Text2_84484B1:: @ 84484B1
    .string "The scent of spices comes from around\n"
    .string "its neck. Somehow, sniffing it makes you\n"
    .string "want to fight.$"

Text2_844850F:: @ 844850F
    .string "$"

Text2_8448510:: @ 8448510
    .string "The aroma that rises from its petals\n"
    .string "contains a substance that calms aggressive\n"
    .string "feelings.$"

Text2_844856A:: @ 844856A
    .string "$"

Text2_844856B:: @ 844856B
    .string "It is timid and always curls itself up in\n"
    .string "a ball. If attacked, it flares up its back\n"
    .string "for protection.$"

Text2_84485D0:: @ 84485D0
    .string "$"

Text2_84485D1:: @ 84485D1
    .string "Be careful if it turns its back during\n"
    .string "battle. It means that it will attack with\n"
    .string "the fire on its back.$"

Text2_8448638:: @ 8448638
    .string "$"

Text2_8448639:: @ 8448639
    .string "If its rage peaks, it becomes so hot that\n"
    .string "anything that touches it will instantly go\n"
    .string "up in flames.$"

Text2_844869C:: @ 844869C
    .string "$"

Text2_844869D:: @ 844869D
    .string "Its well-developed jaws are powerful and\n"
    .string "capable of crushing anything. Even its\n"
    .string "TRAINER must be careful.$"

Text2_8448706:: @ 8448706
    .string "$"

Text2_8448707:: @ 8448707
    .string "If it loses a fang, a new one grows back\n"
    .string "in its place. There are always 48 fangs\n"
    .string "lining its mouth.$"

Text2_844876A:: @ 844876A
    .string "$"

Text2_844876B:: @ 844876B
    .string "When it bites with its massive and\n"
    .string "powerful jaws, it shakes its head and\n"
    .string "savagely tears up its victim.$"

Text2_84487D2:: @ 84487D2
    .string "$"

Text2_84487D3:: @ 84487D3
    .string "A very cautious POKéMON, it raises itself\n"
    .string "up using its tail to get a better view of\n"
    .string "its surroundings.$"

Text2_8448839:: @ 8448839
    .string "$"

Text2_844883A:: @ 844883A
    .string "It makes a nest to suit its long and skinny\n"
    .string "body. The nest is impossible for other\n"
    .string "POKéMON to enter.$"

Text2_844889F:: @ 844889F
    .string "$"

Text2_84488A0:: @ 84488A0
    .string "It always stands on one foot. It changes\n"
    .string "feet so fast, the movement can rarely be\n"
    .string "seen.$"

Text2_84488F8:: @ 84488F8
    .string "$"

Text2_84488F9:: @ 84488F9
    .string "Its eyes are specially adapted. They\n"
    .string "concentrate even faint light and enable it\n"
    .string "to see in the dark.$"

Text2_844895D:: @ 844895D
    .string "$"

Text2_844895E:: @ 844895E
    .string "It is very timid. It will be afraid to\n"
    .string "move if it is alone. But it will be active\n"
    .string "if it is in a group.$"

Text2_84489C5:: @ 84489C5
    .string "$"

Text2_84489C6:: @ 84489C6
    .string "When the stars flicker in the night sky, it\n"
    .string "flutters about, scattering a glowing\n"
    .string "powder.$"

Text2_8448A1F:: @ 8448A1F
    .string "$"

Text2_8448A20:: @ 8448A20
    .string "It lies still in the same pose for days\n"
    .string "in its web, waiting for its unsuspecting\n"
    .string "prey to wander close.$"

Text2_8448A87:: @ 8448A87
    .string "$"

Text2_8448A88:: @ 8448A88
    .string "It spins string not only from its rear but\n"
    .string "also from its mouth. It is hard to tell\n"
    .string "which end is which.$"

Text2_8448AEF:: @ 8448AEF
    .string "$"

Text2_8448AF0:: @ 8448AF0
    .string "It flies so silently through the dark on\n"
    .string "its four wings that it may not be noticed\n"
    .string "even when nearby.$"

Text2_8448B55:: @ 8448B55
    .string "$"

Text2_8448B56:: @ 8448B56
    .string "It shoots positive and negative\n"
    .string "electricity between the tips of its two\n"
    .string "antennae and zaps its enemies.$"

Text2_8448BBD:: @ 8448BBD
    .string "$"

Text2_8448BBE:: @ 8448BBE
    .string "The light it emits is so bright that it can\n"
    .string "illuminate the sea’s surface from a depth\n"
    .string "of over three miles.$"

Text2_8448C29:: @ 8448C29
    .string "$"

Text2_8448C2A:: @ 8448C2A
    .string "It is not yet skilled at storing\n"
    .string "electricity. It may send out a jolt if\n"
    .string "amused or startled.$"

Text2_8448C86:: @ 8448C86
    .string "$"

Text2_8448C87:: @ 8448C87
    .string "Because of its unusual, starlike\n"
    .string "silhouette, people believe that it came\n"
    .string "here on a meteor.$"

Text2_8448CE2:: @ 8448CE2
    .string "$"

Text2_8448CE3:: @ 8448CE3
    .string "It has a very soft body. If it starts to\n"
    .string "roll, it will bounce all over and be\n"
    .string "impossible to stop.$"

Text2_8448D45:: @ 8448D45
    .string "$"

Text2_8448D46:: @ 8448D46
    .string "The shell seems to be filled with joy.\n"
    .string "It is said that it will share good luck\n"
    .string "when treated kindly.$"

Text2_8448DAA:: @ 8448DAA
    .string "$"

Text2_8448DAB:: @ 8448DAB
    .string "They say that it will appear before\n"
    .string "kindhearted, caring people and shower\n"
    .string "them with happiness.$"

Text2_8448E0A:: @ 8448E0A
    .string "$"

Text2_8448E0B:: @ 8448E0B
    .string "Because its wings aren’t yet fully grown,\n"
    .string "it has to hop to get around. It is always\n"
    .string "staring at something.$"

Text2_8448E75:: @ 8448E75
    .string "$"

Text2_8448E76:: @ 8448E76
    .string "They say that it stays still and quiet\n"
    .string "because it is seeing both the past and\n"
    .string "future at the same time.$"

Text2_8448EDD:: @ 8448EDD
    .string "$"

Text2_8448EDE:: @ 8448EDE
    .string "If static electricity builds in its body,\n"
    .string "its fleece doubles in volume. Touching\n"
    .string "it will shock you.$"

Text2_8448F42:: @ 8448F42
    .string "$"

Text2_8448F43:: @ 8448F43
    .string "As a result of storing too much\n"
    .string "electricity, it developed patches where\n"
    .string "even downy wool won’t grow.$"

Text2_8448FA7:: @ 8448FA7
    .string "$"

Text2_8448FA8:: @ 8448FA8
    .string "The tail’s tip shines brightly and can be\n"
    .string "seen from far away. It acts as a beacon\n"
    .string "for lost people.$"

Text2_844900B:: @ 844900B
    .string "$"

Text2_844900C:: @ 844900C
    .string "BELLOSSOM gather at times and appear to\n"
    .string "dance. They say that the dance is a\n"
    .string "ritual to summon the sun.$"

Text2_8449072:: @ 8449072
    .string "$"

Text2_8449073:: @ 8449073
    .string "The tip of its tail, which contains oil\n"
    .string "that is lighter than water, lets it swim\n"
    .string "without drowning.$"

Text2_84490D6:: @ 84490D6
    .string "$"

Text2_84490D7:: @ 84490D7
    .string "By keeping still and listening intently, it\n"
    .string "can even tell what is in wild, fast-moving\n"
    .string "rivers.$"

Text2_8449136:: @ 8449136
    .string "$"

Text2_8449137:: @ 8449137
    .string "Although it always pretends to be a tree,\n"
    .string "its composition appears to be closer to a\n"
    .string "rock than a plant.$"

Text2_844919E:: @ 844919E
    .string "$"

Text2_844919F:: @ 844919F
    .string "If POLIWAG and POLIWHIRL hear its\n"
    .string "echoing cry, they respond by gathering\n"
    .string "from far and wide.$"

Text2_84491FB:: @ 84491FB
    .string "$"

Text2_84491FC:: @ 84491FC
    .string "To keep from being blown away by the\n"
    .string "wind, they gather in clusters. They do\n"
    .string "enjoy gentle breezes, though.$"

Text2_8449266:: @ 8449266
    .string "$"

Text2_8449267:: @ 8449267
    .string "The bloom on top of its head opens and\n"
    .string "closes as the temperature fluctuates up\n"
    .string "and down.$"

Text2_84492C0:: @ 84492C0
    .string "$"

Text2_84492C1:: @ 84492C1
    .string "Once it catches the wind, it deftly\n"
    .string "controls its cotton-puff spores to float,\n"
    .string "even around the world.$"

Text2_8449326:: @ 8449326
    .string "$"

Text2_8449327:: @ 8449327
    .string "Its tail is so powerful that it can use it\n"
    .string "to grab a tree branch and hold itself up\n"
    .string "in the air.$"

Text2_8449387:: @ 8449387
    .string "$"

Text2_8449388:: @ 8449388
    .string "It may drop out of the sky suddenly.\n"
    .string "If attacked by a SPEAROW, it will\n"
    .string "violently shake its leaves.$"

Text2_84493EB:: @ 84493EB
    .string "$"

Text2_84493EC:: @ 84493EC
    .string "It converts sunlight into energy. In the\n"
    .string "darkness after sunset, it closes its petals\n"
    .string "and becomes still.$"

Text2_8449454:: @ 8449454
    .string "$"

Text2_8449455:: @ 8449455
    .string "If it flaps its wings really fast, it can\n"
    .string "generate shock waves that will shatter\n"
    .string "windows in the area.$"

Text2_84494BB:: @ 84494BB
    .string "$"

Text2_84494BC:: @ 84494BC
    .string "This POKéMON lives in cold water. It will\n"
    .string "leave the water to search for food when\n"
    .string "it gets cold outside.$"

Text2_8449524:: @ 8449524
    .string "$"

Text2_8449525:: @ 8449525
    .string "This carefree POKéMON has an easygoing\n"
    .string "nature. While swimming, it always bumps\n"
    .string "into boat hulls.$"

Text2_8449585:: @ 8449585
    .string "$"

Text2_8449586:: @ 8449586
    .string "It uses the fine hair that covers its body\n"
    .string "to sense air currents and predict its\n"
    .string "enemy’s actions.$"

Text2_84495E8:: @ 84495E8
    .string "$"

Text2_84495E9:: @ 84495E9
    .string "When agitated, this POKéMON protects\n"
    .string "itself by spraying poisonous sweat from its\n"
    .string "pores.$"

Text2_8449641:: @ 8449641
    .string "$"

Text2_8449642:: @ 8449642
    .string "Feared and loathed by many, it is\n"
    .string "believed to bring misfortune to all those\n"
    .string "who see it at night.$"

Text2_84496A3:: @ 84496A3
    .string "$"

Text2_84496A4:: @ 84496A4
    .string "It has incredible intellect and intuition.\n"
    .string "Whatever the situation, it remains calm\n"
    .string "and collected.$"

Text2_8449706:: @ 8449706
    .string "$"

Text2_8449707:: @ 8449707
    .string "It likes playing mischievous tricks such as\n"
    .string "screaming and wailing to startle people at\n"
    .string "night. $"

Text2_8449766:: @ 8449766
    .string "$"

Text2_8449767:: @ 8449767
    .string "Their shapes look like hieroglyphs on\n"
    .string "ancient tablets. It is said that the two\n"
    .string "are somehow related.$"

Text2_84497CB:: @ 84497CB
    .string "$"

Text2_84497CC:: @ 84497CC
    .string "It hates light and shock. If attacked,\n"
    .string "it inflates its body to pump up its\n"
    .string "counterstrike.$"

Text2_8449826:: @ 8449826
    .string "$"

Text2_8449827:: @ 8449827
    .string "Its tail has a small brain of its own.\n"
    .string "Beware! If you get close, it may react\n"
    .string "to your scent and bite.$"

Text2_844988D:: @ 844988D
    .string "$"

Text2_844988E:: @ 844988E
    .string "It likes to make its shell thicker by\n"
    .string "adding layers of tree bark. The extra\n"
    .string "weight doesn’t bother it.$"

Text2_84498F4:: @ 84498F4
    .string "$"

Text2_84498F5:: @ 84498F5
    .string "Its entire body is shielded by a steel-\n"
    .string "hard shell. What lurks inside the armor is\n"
    .string "a total mystery.$"

Text2_8449959:: @ 8449959
    .string "$"

Text2_844995A:: @ 844995A
    .string "When spotted, this POKéMON escapes\n"
    .string "backward by furiously boring into the\n"
    .string "ground with its tail.$"

Text2_84499B9:: @ 84499B9
    .string "$"

Text2_84499BA:: @ 84499BA
    .string "It flies straight at its target’s face,\n"
    .string "then clamps down on the startled\n"
    .string "victim to inject poison.$"

Text2_8449A1C:: @ 8449A1C
    .string "$"

Text2_8449A1D:: @ 8449A1D
    .string "Its body has been compressed deep under\n"
    .string "the ground. As a result, it is even harder\n"
    .string "than diamond.$"

Text2_8449A7E:: @ 8449A7E
    .string "$"

Text2_8449A7F:: @ 8449A7F
    .string "Although it looks frightening, it is\n"
    .string "actually kind and affectionate. It is very\n"
    .string "popular among women.$"

Text2_8449AE4:: @ 8449AE4
    .string "$"

Text2_8449AE5:: @ 8449AE5
    .string "It is actually timid and easily spooked.\n"
    .string "If attacked, it flails about to fend off\n"
    .string "its attacker.$"

Text2_8449B45:: @ 8449B45
    .string "$"

Text2_8449B46:: @ 8449B46
    .string "To fire its poison spikes, it must inflate\n"
    .string "its body by drinking over 2.6 gallons of \n"
    .string "water all at once.$"

Text2_8449BAE:: @ 8449BAE
    .string "$"

Text2_8449BAF:: @ 8449BAF
    .string "It swings its eye-patterned pincers up to\n"
    .string "scare its foes. This makes it look like it\n"
    .string "has three heads.$"

Text2_8449C15:: @ 8449C15
    .string "$"

Text2_8449C16:: @ 8449C16
    .string "The BERRIES it stores in its vaselike\n"
    .string "shell decompose and become a gooey\n"
    .string "liquid.$"

Text2_8449C67:: @ 8449C67
    .string "$"

Text2_8449C68:: @ 8449C68
    .string "This powerful POKéMON thrusts its prized\n"
    .string "horn under its enemies’ bellies, then lifts\n"
    .string "and throws them.$"

Text2_8449CCE:: @ 8449CCE
    .string "$"

Text2_8449CCF:: @ 8449CCF
    .string "Its paws conceal sharp claws.\n"
    .string "If attacked, it suddenly extends the\n"
    .string "claws and startles its enemy.$"

Text2_8449D30:: @ 8449D30
    .string "$"

Text2_8449D31:: @ 8449D31
    .string "If it finds honey, its crescent mark glows.\n"
    .string "It always licks its paws because they are\n"
    .string "soaked with honey.$"

Text2_8449D9A:: @ 8449D9A
    .string "$"

Text2_8449D9B:: @ 8449D9B
    .string "Although it is a good climber, it prefers\n"
    .string "to snap stout trees with its forelegs and\n"
    .string "eat fallen BERRIES.$"

Text2_8449E03:: @ 8449E03
    .string "$"

Text2_8449E04:: @ 8449E04
    .string "It never sleeps. It has to keep moving\n"
    .string "because if it stopped, its magma body\n"
    .string "would cool and harden.$"

Text2_8449E68:: @ 8449E68
    .string "$"

Text2_8449E69:: @ 8449E69
    .string "The shell on its back is just skin that\n"
    .string "has cooled and hardened. It breaks easily\n"
    .string "with a slight touch.$"

Text2_8449ED0:: @ 8449ED0
    .string "$"

Text2_8449ED1:: @ 8449ED1
    .string "It rubs its snout on the ground to find\n"
    .string "and dig up food. It sometimes discovers\n"
    .string "hot springs.$"

Text2_8449F2E:: @ 8449F2E
    .string "$"

Text2_8449F2F:: @ 8449F2F
    .string "Because the long hair all over its body\n"
    .string "obscures its sight, it just keeps charging\n"
    .string "repeatedly.$"

Text2_8449F8E:: @ 8449F8E
    .string "$"

Text2_8449F8F:: @ 8449F8F
    .string "It continuously sheds and grows. The tip\n"
    .string "of its head is prized as a treasure for\n"
    .string "its beauty.$"

Text2_8449FEC:: @ 8449FEC
    .string "$"

Text2_8449FED:: @ 8449FED
    .string "It has superb accuracy. The water it\n"
    .string "shoots out can strike even moving prey\n"
    .string "from more than 100 yards.$"

Text2_844A053:: @ 844A053
    .string "$"

Text2_844A054:: @ 844A054
    .string "It traps enemies with its suction-cupped\n"
    .string "tentacles, then smashes them with its\n"
    .string "rock-hard head.$"

Text2_844A0B3:: @ 844A0B3
    .string "$"

Text2_844A0B4:: @ 844A0B4
    .string "It carries food all day long. There are\n"
    .string "tales about lost people who were saved\n"
    .string "by the food it had.$"

Text2_844A117:: @ 844A117
    .string "$"

Text2_844A118:: @ 844A118
    .string "As it majestically swims, it doesn’t care\n"
    .string "if REMORAID attach to it to scavenge\n"
    .string "for its leftovers.$"

Text2_844A17A:: @ 844A17A
    .string "$"

Text2_844A17B:: @ 844A17B
    .string "Its sturdy wings look heavy, but its bones\n"
    .string "are hollow and light, allowing it to fly\n"
    .string "freely in the sky.$"

Text2_844A1E2:: @ 844A1E2
    .string "$"

Text2_844A1E3:: @ 844A1E3
    .string "It uses different kinds of cries for\n"
    .string "communicating with others of its kind and\n"
    .string "for pursuing prey.$"

Text2_844A245:: @ 844A245
    .string "$"

Text2_844A246:: @ 844A246
    .string "If you are burned by the flames it shoots\n"
    .string "from its mouth, the pain will never go\n"
    .string "away.$"

Text2_844A29D:: @ 844A29D
    .string "$"

Text2_844A29E:: @ 844A29E
    .string "It is said that it usually hides in\n"
    .string "underwater caves. It can create\n"
    .string "whirlpools by yawning.$"

Text2_844A2F9:: @ 844A2F9
    .string "$"

Text2_844A2FA:: @ 844A2FA
    .string "It swings its long snout around playfully,\n"
    .string "but because it is so strong, this can be\n"
    .string "dangerous.$"

Text2_844A359:: @ 844A359
    .string "$"

Text2_844A35A:: @ 844A35A
    .string "It has sharp, hard tusks and a rugged\n"
    .string "hide. Its TACKLE is strong enough to\n"
    .string "knock down a house.$"

Text2_844A3B9:: @ 844A3B9
    .string "$"

Text2_844A3BA:: @ 844A3BA
    .string "This upgraded version of PORYGON is\n"
    .string "designed for space exploration. However,\n"
    .string "it can’t even fly.$"

Text2_844A41A:: @ 844A41A
    .string "$"

Text2_844A41B:: @ 844A41B
    .string "Its curved antlers subtly change the flow\n"
    .string "of air to create a strange space where\n"
    .string "reality is distorted.$"

Text2_844A482:: @ 844A482
    .string "$"

Text2_844A483:: @ 844A483
    .string "A special fluid oozes from the tip of its\n"
    .string "tail. It paints the fluid everywhere to\n"
    .string "mark its territory.$"

Text2_844A4E9:: @ 844A4E9
    .string "$"

Text2_844A4EA:: @ 844A4EA
    .string "It is always bursting with energy. To make\n"
    .string "itself stronger, it keeps on fighting even\n"
    .string "if it loses.$"

Text2_844A54D:: @ 844A54D
    .string "$"

Text2_844A54E:: @ 844A54E
    .string "If you become enchanted by its smooth,\n"
    .string "elegant, dance-like kicks, you may get\n"
    .string "drilled hard.$"

Text2_844A5AA:: @ 844A5AA
    .string "$"

Text2_844A5AB:: @ 844A5AB
    .string "Its lips are the most sensitive parts on\n"
    .string "its body. It always uses its lips first to\n"
    .string "examine things.$"

Text2_844A60F:: @ 844A60F
    .string "$"

Text2_844A610:: @ 844A610
    .string "It rotates its arms to generate\n"
    .string "electricity, but it tires easily, so it\n"
    .string "charges up only a little bit.$"

Text2_844A676:: @ 844A676
    .string "$"

Text2_844A677:: @ 844A677
    .string "Each and every time it inhales and\n"
    .string "exhales, hot embers dribble out of its\n"
    .string "mouth and nostrils.$"

Text2_844A6D5:: @ 844A6D5
    .string "$"

Text2_844A6D6:: @ 844A6D6
    .string "Its milk is packed with nutrition, making\n"
    .string "it the ultimate beverage for the sick or\n"
    .string "weary.$"

Text2_844A730:: @ 844A730
    .string "$"

Text2_844A731:: @ 844A731
    .string "Anyone who takes even one bite of\n"
    .string "BLISSEY’s egg becomes unfailingly caring\n"
    .string "and pleasant to everyone.$"

Text2_844A796:: @ 844A796
    .string "$"

Text2_844A797:: @ 844A797
    .string "The rain clouds it carries let it fire\n"
    .string "thunderbolts at will. They say that it\n"
    .string "descended with lightning.$"

Text2_844A7FF:: @ 844A7FF
    .string "$"

Text2_844A800:: @ 844A800
    .string "Volcanoes erupt when it barks. Unable to\n"
    .string "restrain its extreme power, it races\n"
    .string "headlong around the land.$"

Text2_844A868:: @ 844A868
    .string "$"

Text2_844A869:: @ 844A869
    .string "Said to be the reincarnation of north\n"
    .string "winds, it can instantly purify filthy,\n"
    .string "murky water.$"

Text2_844A8C3:: @ 844A8C3
    .string "$"

Text2_844A8C4:: @ 844A8C4
    .string "It feeds on soil. After it has eaten a\n"
    .string "large mountain, it will fall asleep so it\n"
    .string "can grow.$"

Text2_844A91F:: @ 844A91F
    .string "$"

Text2_844A920:: @ 844A920
    .string "Its shell is as hard as sheet rock, and it\n"
    .string "is also very strong. Its THRASHING can\n"
    .string "topple a mountain.$"

Text2_844A985:: @ 844A985
    .string "$"

Text2_844A986:: @ 844A986
    .string "Its body can’t be harmed by any sort of\n"
    .string "attack, so it is very eager to make\n"
    .string "challenges against enemies.$"

Text2_844A9EE:: @ 844A9EE
    .string "$"

Text2_844A9EF:: @ 844A9EF
    .string "It is said that it quietly spends its time\n"
    .string "deep at the bottom of the sea because\n"
    .string "its powers are too strong.$"

Text2_844AA5B:: @ 844AA5B
    .string "$"

Text2_844AA5C:: @ 844AA5C
    .string "Legends claim this POKéMON flies the\n"
    .string "world’s skies continuously on its\n"
    .string "magnificent seven-colored wings.$"

Text2_844AAC4:: @ 844AAC4
    .string "$"

Text2_844AAC5:: @ 844AAC5
    .string "This POKéMON wanders across time.\n"
    .string "Grass and trees flourish in the forests in\n"
    .string "which it has appeared.$"

Text2_844AB29:: @ 844AB29
    .string "$"

Text2_844AB2A:: @ 844AB2A
    .string "It quickly scales even vertical walls.\n"
    .string "It senses humidity with its tail to predict\n"
    .string "the next day’s weather.$"

Text2_844AB95:: @ 844AB95
    .string "$"

Text2_844AB96:: @ 844AB96
    .string "Its strongly developed thigh muscles\n"
    .string "give it astounding agility and jumping\n"
    .string "performance.$"

Text2_844ABEF:: @ 844ABEF
    .string "$"

Text2_844ABF0:: @ 844ABF0
    .string "The leaves on its forelegs are as sharp\n"
    .string "as swords. It agilely leaps about the\n"
    .string "branches of trees to strike.$"

Text2_844AC5B:: @ 844AC5B
    .string "$"

Text2_844AC5C:: @ 844AC5C
    .string "It has a flame sac inside its belly that\n"
    .string "perpetually burns. It feels warm if it is\n"
    .string "hugged.$"

Text2_844ACB7:: @ 844ACB7
    .string "$"

Text2_844ACB8:: @ 844ACB8
    .string "It boosts its concentration by emitting\n"
    .string "harsh cries. Its kicks have outstanding\n"
    .string "destructive power.$"

Text2_844AD1B:: @ 844AD1B
    .string "$"

Text2_844AD1C:: @ 844AD1C
    .string "When facing a tough foe, it looses flames\n"
    .string "from its wrists. Its powerful legs let it\n"
    .string "jump clear over buildings.$"

Text2_844AD8B:: @ 844AD8B
    .string "$"

Text2_844AD8C:: @ 844AD8C
    .string "Its large tail fin propels it through\n"
    .string "water with powerful acceleration. It is\n"
    .string "strong in spite of its size.$"

Text2_844ADF7:: @ 844ADF7
    .string "$"

Text2_844ADF8:: @ 844ADF8
    .string "It is at its best when on muddy ground\n"
    .string "with poor footing. It quickly overwhelms\n"
    .string "foes struggling in mud.$"

Text2_844AE60:: @ 844AE60
    .string "$"

Text2_844AE61:: @ 844AE61
    .string "Its arms are rock-hard. With one swing,\n"
    .string "they can batter down its foe. It makes its\n"
    .string "nest on beautiful beaches.$"

Text2_844AECF:: @ 844AECF
    .string "$"

Text2_844AED0:: @ 844AED0
    .string "It has a very tenacious nature. Its acute\n"
    .string "sense of smell lets it chase a chosen\n"
    .string "prey without ever losing track.$"

Text2_844AF40:: @ 844AF40
    .string "$"

Text2_844AF41:: @ 844AF41
    .string "It will always obey the commands of a\n"
    .string "skilled TRAINER. Its behavior arises from\n"
    .string "its living in packs in ancient times.$"

Text2_844AFB7:: @ 844AFB7
    .string "$"

Text2_844AFB8:: @ 844AFB8
    .string "A POKéMON with abundant curiosity.\n"
    .string "It shows an interest in everything, so it\n"
    .string "always zigs and zags.$"

Text2_844B01B:: @ 844B01B
    .string "$"

Text2_844B01C:: @ 844B01C
    .string "When running in a straight line, it can top\n"
    .string "60 miles per hour. However, it has a\n"
    .string "tough time with curved roads.$"

Text2_844B08B:: @ 844B08B
    .string "$"

Text2_844B08C:: @ 844B08C
    .string "It lives amidst tall grass and in forests.\n"
    .string "When attacked, it resists by pointing its\n"
    .string "venomous spikes at the foe.$"

Text2_844B0FD:: @ 844B0FD
    .string "$"

Text2_844B0FE:: @ 844B0FE
    .string "It conserves its energy by moving as\n"
    .string "little as possible. It awaits evolution\n"
    .string "while drinking only a little rainwater.$"

Text2_844B173:: @ 844B173
    .string "$"

Text2_844B174:: @ 844B174
    .string "Despite its appearance, it has an\n"
    .string "aggressive nature. It attacks by jabbing\n"
    .string "with its long, thin mouth.$"

Text2_844B1DA:: @ 844B1DA
    .string "$"

Text2_844B1DB:: @ 844B1DB
    .string "Its body, which is made of soft silk,\n"
    .string "hardens over time. When cracks appear,\n"
    .string "evolution is near.$"

Text2_844B23B:: @ 844B23B
    .string "$"

Text2_844B23C:: @ 844B23C
    .string "It scatters horribly toxic dust when it\n"
    .string "senses danger. They tend to gather in the\n"
    .string "glow of streetlamps at night.$"

Text2_844B2AC:: @ 844B2AC
    .string "$"

Text2_844B2AD:: @ 844B2AD
    .string "It searches about for clean water. If it\n"
    .string "does not drink water for too long, the\n"
    .string "leaf on its head wilts.$"

Text2_844B315:: @ 844B315
    .string "$"

Text2_844B316:: @ 844B316
    .string "It lives at the water’s edge where it is\n"
    .string "sunny. It sleeps on a bed of water grass\n"
    .string "by day and becomes active at night.$"

Text2_844B38C:: @ 844B38C
    .string "$"

Text2_844B38D:: @ 844B38D
    .string "The rhythm of bright, festive music\n"
    .string "activates LUDICOLO’s cells, making it more\n"
    .string "powerful.$"

Text2_844B3E6:: @ 844B3E6
    .string "$"

Text2_844B3E7:: @ 844B3E7
    .string "If it remains still, it becomes impossible\n"
    .string "to distinguish from real nuts. It delights\n"
    .string "in surprising foraging PIDGEY.$"

Text2_844B45C:: @ 844B45C
    .string "$"

Text2_844B45D:: @ 844B45D
    .string "They live in holes bored in large trees.\n"
    .string "The sound of NUZLEAF’s grass flute fills\n"
    .string "listeners with dread.$"

Text2_844B4C5:: @ 844B4C5
    .string "$"

Text2_844B4C6:: @ 844B4C6
    .string "A POKéMON that was feared as a forest\n"
    .string "guardian. It can read the foe’s mind and\n"
    .string "take preemptive action.$"

Text2_844B52D:: @ 844B52D
    .string "$"

Text2_844B52E:: @ 844B52E
    .string "It dislikes cold seasons. They migrate to\n"
    .string "other lands in search of warmth, flying\n"
    .string "over 180 miles a day.$"

Text2_844B596:: @ 844B596
    .string "$"

Text2_844B597:: @ 844B597
    .string "If its two tail feathers are standing at\n"
    .string "attention, it is proof of good health.\n"
    .string "It soars elegantly in the sky.$"

Text2_844B606:: @ 844B606
    .string "$"

Text2_844B607:: @ 844B607
    .string "It rides upon ocean winds as if it were\n"
    .string "a glider. In the winter, it hides food\n"
    .string "around its nest.$"

Text2_844B667:: @ 844B667
    .string "$"

Text2_844B668:: @ 844B668
    .string "It is a flying transporter that carries\n"
    .string "small POKéMON in its beak. It bobs on the\n"
    .string "waves to rest its wings.$"

Text2_844B6D3:: @ 844B6D3
    .string "$"

Text2_844B6D4:: @ 844B6D4
    .string "It is highly attuned to the emotions of\n"
    .string "people and POKéMON. It hides if it senses\n"
    .string "hostility.$"

Text2_844B731:: @ 844B731
    .string "$"

Text2_844B732:: @ 844B732
    .string "The cheerful spirit of its TRAINER gives\n"
    .string "it energy for its psychokinetic power.\n"
    .string "It spins and dances when happy.$"

Text2_844B7A2:: @ 844B7A2
    .string "$"

Text2_844B7A3:: @ 844B7A3
    .string "It has the power to predict the future.\n"
    .string "Its power peaks when it is protecting its\n"
    .string "TRAINER.$"

Text2_844B7FE:: @ 844B7FE
    .string "$"

Text2_844B7FF:: @ 844B7FF
    .string "They usually live on ponds, but after an\n"
    .string "evening shower, they may appear on\n"
    .string "puddles in towns.$"

Text2_844B85D:: @ 844B85D
    .string "$"

Text2_844B85E:: @ 844B85E
    .string "The antennae have distinctive patterns\n"
    .string "that look like eyes. When it rains, they\n"
    .string "grow heavy, making flight impossible.$"

Text2_844B8D4:: @ 844B8D4
    .string "$"

Text2_844B8D5:: @ 844B8D5
    .string "It prefers damp places. By day it remains\n"
    .string "still in the forest shade. It releases\n"
    .string "toxic powder from its head.$"

Text2_844B942:: @ 844B942
    .string "$"

Text2_844B943:: @ 844B943
    .string "The seeds on its tail are made of toxic\n"
    .string "spores. It knocks out foes with quick,\n"
    .string "virtually invisible punches.$"

Text2_844B9AF:: @ 844B9AF
    .string "$"

Text2_844B9B0:: @ 844B9B0
    .string "It sleeps for 20 hours every day. Making\n"
    .string "drowsy those that see it is one of\n"
    .string "its abilities.$"

Text2_844BA0B:: @ 844BA0B
    .string "$"

Text2_844BA0C:: @ 844BA0C
    .string "It is always hungry because it won’t stop\n"
    .string "rampaging. Even while it is eating, it\n"
    .string "can’t keep still.$"

Text2_844BA6F:: @ 844BA6F
    .string "$"

Text2_844BA70:: @ 844BA70
    .string "It is the world’s most slothful POKéMON.\n"
    .string "However, it can exert horrifying power by\n"
    .string "releasing pent-up energy all at once.$"

Text2_844BAE9:: @ 844BAE9
    .string "$"

Text2_844BAEA:: @ 844BAEA
    .string "Because it lived almost entirely\n"
    .string "underground, it is nearly blind.\n"
    .string "It uses its antennae instead.$"

Text2_844BB4A:: @ 844BB4A
    .string "$"

Text2_844BB4B:: @ 844BB4B
    .string "This POKéMON is so quick, it is said to\n"
    .string "be able to avoid any attack. It loves to\n"
    .string "feed on tree sap.$"

Text2_844BBAE:: @ 844BBAE
    .string "$"

Text2_844BBAF:: @ 844BBAF
    .string "A most peculiar POKéMON that somehow\n"
    .string "appears in a POKé BALL when a NINCADA\n"
    .string "evolves.$"

Text2_844BC03:: @ 844BC03
    .string "$"

Text2_844BC04:: @ 844BC04
    .string "It usually murmurs, but starts crying\n"
    .string "loudly if it senses danger. It stops when\n"
    .string "its ear covers are shut.$"

Text2_844BC6D:: @ 844BC6D
    .string "$"

Text2_844BC6E:: @ 844BC6E
    .string "When it stamps its feet and bellows, it\n"
    .string "generates ultrasonic waves that can blow\n"
    .string "apart a house.$"

Text2_844BCCE:: @ 844BCCE
    .string "$"

Text2_844BCCF:: @ 844BCCF
    .string "It emits a variety of sounds from the \n"
    .string "holes all over its body. Its loud cries\n"
    .string "can be heard from over six miles away.$"

Text2_844BD45:: @ 844BD45
    .string "$"

Text2_844BD46:: @ 844BD46
    .string "It grows stronger by enduring harsh\n"
    .string "training. It is a gutsy POKéMON that can\n"
    .string "withstand any attack.$"

Text2_844BDA9:: @ 844BDA9
    .string "$"

Text2_844BDAA:: @ 844BDAA
    .string "It stomps on the ground to build power.\n"
    .string "It can send a 10-ton truck flying with a\n"
    .string "straight-arm punch.$"

Text2_844BE0F:: @ 844BE0F
    .string "$"

Text2_844BE10:: @ 844BE10
    .string "It battles by flinging around its tail,\n"
    .string "which is bigger than its body. The\n"
    .string "tail is a flotation device in water.$"

Text2_844BE80:: @ 844BE80
    .string "$"

Text2_844BE81:: @ 844BE81
    .string "Its magnetic nose consistently faces\n"
    .string "north. Travelers check NOSEPASS to get\n"
    .string "their bearings.$"

Text2_844BEDD:: @ 844BEDD
    .string "$"

Text2_844BEDE:: @ 844BEDE
    .string "It is said to be difficult to earn its\n"
    .string "trust. However, it is extremely popular\n"
    .string "for its cute looks and behavior.$"

Text2_844BF4E:: @ 844BF4E
    .string "$"

Text2_844BF4F:: @ 844BF4F
    .string "The favorite of trend-conscious\n"
    .string "female TRAINERS, they are used in\n"
    .string "competition for their style and fur.$"

Text2_844BFB6:: @ 844BFB6
    .string "$"

Text2_844BFB7:: @ 844BFB7
    .string "It feeds on gemstone crystals.\n"
    .string "In darkness, its eyes sparkle with the\n"
    .string "glitter of jewels.$"

Text2_844C010:: @ 844C010
    .string "$"

Text2_844C011:: @ 844C011
    .string "It uses its docile-looking face to lull\n"
    .string "foes into complacency, then bites with its\n"
    .string "huge, relentless jaws.$"

Text2_844C07B:: @ 844C07B
    .string "$"

Text2_844C07C:: @ 844C07C
    .string "It eats iron to build its steel body.\n"
    .string "It is a pest that descends from mountains\n"
    .string "to eat bridges and train tracks.$"

Text2_844C0ED:: @ 844C0ED
    .string "$"

Text2_844C0EE:: @ 844C0EE
    .string "It habitually shows off its strength with\n"
    .string "the size of sparks it creates by ramming\n"
    .string "its steel body into boulders.$"

Text2_844C15F:: @ 844C15F
    .string "$"

Text2_844C160:: @ 844C160
    .string "It claims a large mountain as its sole\n"
    .string "territory. It mercilessly thrashes those\n"
    .string "that violate its space.$"

Text2_844C1C8:: @ 844C1C8
    .string "$"

Text2_844C1C9:: @ 844C1C9
    .string "It never skips its daily yoga training.\n"
    .string "It heightens its inner strength through\n"
    .string "meditation.$"

Text2_844C225:: @ 844C225
    .string "$"

Text2_844C226:: @ 844C226
    .string "It elegantly avoids attacks with dance-\n"
    .string "like steps, then launches a devastating\n"
    .string "blow in the same motion.$"

Text2_844C28F:: @ 844C28F
    .string "$"

Text2_844C290:: @ 844C290
    .string "It stores static electricity in its fur\n"
    .string "for discharging. It gives off sparks if a\n"
    .string "storm approaches.$"

Text2_844C2F4:: @ 844C2F4
    .string "$"

Text2_844C2F5:: @ 844C2F5
    .string "It rarely appears before people.\n"
    .string "It is said to nest where lightning has\n"
    .string "fallen.$"

Text2_844C345:: @ 844C345
    .string "$"

Text2_844C346:: @ 844C346
    .string "It cheers on partners while scattering\n"
    .string "sparks from its body. It climbs telephone\n"
    .string "poles to absorb electricity.$"

Text2_844C3B4:: @ 844C3B4
    .string "$"

Text2_844C3B5:: @ 844C3B5
    .string "Its dislike of water makes it take shelter\n"
    .string "under the eaves of houses in rain. It uses\n"
    .string "pom-poms made of sparks for cheering.$"

Text2_844C431:: @ 844C431
    .string "$"

Text2_844C432:: @ 844C432
    .string "It lives around clean ponds. At night,\n"
    .string "its rear lights up. It converses with\n"
    .string "others by flashing its light.$"

Text2_844C49D:: @ 844C49D
    .string "$"

Text2_844C49E:: @ 844C49E
    .string "It guides VOLBEAT to draw signs in night\n"
    .string "skies. There are scientists that study the\n"
    .string "patterns it creates.$"

Text2_844C507:: @ 844C507
    .string "$"

Text2_844C508:: @ 844C508
    .string "Its flowers give off a relaxing fragrance.\n"
    .string "The stronger its aroma, the healthier\n"
    .string "the ROSELIA is.$"

Text2_844C569:: @ 844C569
    .string "$"

Text2_844C56A:: @ 844C56A
    .string "There is nothing its stomach can’t digest.\n"
    .string "While it is digesting, vile, overpowering\n"
    .string "gases are expelled.$"

Text2_844C5D3:: @ 844C5D3
    .string "$"

Text2_844C5D4:: @ 844C5D4
    .string "It can swallow a tire whole in one gulp.\n"
    .string "It secretes a horribly toxic fluid from\n"
    .string "the pores on its body.$"

Text2_844C63C:: @ 844C63C
    .string "$"

Text2_844C63D:: @ 844C63D
    .string "It lives in massive rivers that course\n"
    .string "through jungles. It swarms prey that\n"
    .string "enter its territory.$"

Text2_844C69E:: @ 844C69E
    .string "$"

Text2_844C69F:: @ 844C69F
    .string "The ruffian of the seas, it has fangs that\n"
    .string "crunch through iron. It swims by jetting\n"
    .string "water from its rear.$"

Text2_844C708:: @ 844C708
    .string "$"

Text2_844C709:: @ 844C709
    .string "When it sucks in a large volume of\n"
    .string "seawater, it becomes like a big, bouncy\n"
    .string "ball. It eats a ton of food daily.$"

Text2_844C777:: @ 844C777
    .string "$"

Text2_844C778:: @ 844C778
    .string "It is among the largest of all POKéMON.\n"
    .string "It herds prey in a pack then swallows the\n"
    .string "massed prey in one gulp.$"

Text2_844C7E3:: @ 844C7E3
    .string "$"

Text2_844C7E4:: @ 844C7E4
    .string "Magma of almost 2,200 degrees Fahrenheit\n"
    .string "courses through its body. When it grows\n"
    .string "cold, the magma hardens and slows it.$"

Text2_844C85B:: @ 844C85B
    .string "$"

Text2_844C85C:: @ 844C85C
    .string "If angered, the humps on its back erupt\n"
    .string "in a shower of molten lava. It lives in\n"
    .string "the craters of volcanoes.$"

Text2_844C8C6:: @ 844C8C6
    .string "$"

Text2_844C8C7:: @ 844C8C7
    .string "It burns coal inside its shell. If it is\n"
    .string "attacked, it belches thick, black smoke\n"
    .string "and flees.$"

Text2_844C923:: @ 844C923
    .string "$"

Text2_844C924:: @ 844C924
    .string "It apparently dies if it stops bouncing\n"
    .string "about. It carries a pearl from CLAMPERL\n"
    .string "on its head.$"

Text2_844C981:: @ 844C981
    .string "$"

Text2_844C982:: @ 844C982
    .string "It can gain control over foes by doing\n"
    .string "odd dance steps. The black pearls on its\n"
    .string "forehead are precious gems.$"

Text2_844C9EE:: @ 844C9EE
    .string "$"

Text2_844C9EF:: @ 844C9EF
    .string "No two SPINDA are said to have identical\n"
    .string "patterns. It confuses foes with its\n"
    .string "stumbling motions.$"

Text2_844CA4F:: @ 844CA4F
    .string "$"

Text2_844CA50:: @ 844CA50
    .string "It lives in arid deserts. It makes a\n"
    .string "sloping pit trap in sand where it\n"
    .string "patiently awaits prey.$"

Text2_844CAAE:: @ 844CAAE
    .string "$"

Text2_844CAAF:: @ 844CAAF
    .string "It generates ultrasonic waves by violently\n"
    .string "flapping its wings. After making its prey\n"
    .string "faint, it melts the prey with acid.$"

Text2_844CB28:: @ 844CB28
    .string "$"

Text2_844CB29:: @ 844CB29
    .string "It hides itself by kicking up desert sand\n"
    .string "with its wings. Red covers shield its eyes\n"
    .string "from sand.$"

Text2_844CB89:: @ 844CB89
    .string "$"

Text2_844CB8A:: @ 844CB8A
    .string "It prefers harsh environments such as\n"
    .string "deserts. It can survive for 30 days on\n"
    .string "water stored in its body.$"

Text2_844CBF1:: @ 844CBF1
    .string "$"

Text2_844CBF2:: @ 844CBF2
    .string "It lives in deserts. It becomes active at\n"
    .string "night when it hunts for prey exhausted\n"
    .string "from the desert’s heat.$"

Text2_844CC5B:: @ 844CC5B
    .string "$"

Text2_844CC5C:: @ 844CC5C
    .string "It constantly grooms its cotton-like\n"
    .string "wings. It takes a shower to clean\n"
    .string "itself if it becomes dirty.$"

Text2_844CCBF:: @ 844CCBF
    .string "$"

Text2_844CCC0:: @ 844CCC0
    .string "If you hear a beautiful melody trilling\n"
    .string "deep among mountains far from people,\n"
    .string "it is ALTARIA’s humming.$"

Text2_844CD27:: @ 844CD27
    .string "$"

Text2_844CD28:: @ 844CD28
    .string "If it comes across a SEVIPER, its fur\n"
    .string "bristles and it assumes its battle pose.\n"
    .string "Its sharp claws are its best weapon.$"

Text2_844CD9C:: @ 844CD9C
    .string "$"

Text2_844CD9D:: @ 844CD9D
    .string "It sharpens its swordlike tail on hard\n"
    .string "rocks. It hides in tall grass and strikes\n"
    .string "unwary prey with venomous fangs.$"

Text2_844CE0F:: @ 844CE0F
    .string "$"

Text2_844CE10:: @ 844CE10
    .string "Its health ebbs and flows with the lunar\n"
    .string "cycle. It brims with power when exposed\n"
    .string "to the light of the full moon.$"

Text2_844CE80:: @ 844CE80
    .string "$"

Text2_844CE81:: @ 844CE81
    .string "It absorbs solar energy during the day.\n"
    .string "Always expressionless, it can sense what\n"
    .string "its foe is thinking.$"

Text2_844CEE7:: @ 844CEE7
    .string "$"

Text2_844CEE8:: @ 844CEE8
    .string "It probes muddy riverbeds with its two\n"
    .string "long whiskers. A slimy film protects its\n"
    .string "body.$"

Text2_844CF3E:: @ 844CF3E
    .string "$"

Text2_844CF3F:: @ 844CF3F
    .string "It makes its nest at the bottom of \n"
    .string "swamps. It will eat anything - if it is\n"
    .string "alive, WHISCASH will eat it.$"

Text2_844CFA8:: @ 844CFA8
    .string "$"

Text2_844CFA9:: @ 844CFA9
    .string "It came from overseas. It is a very hardy\n"
    .string "creature that will quickly proliferate,\n"
    .string "even in polluted streams.$"

Text2_844D015:: @ 844D015
    .string "$"

Text2_844D016:: @ 844D016
    .string "A rough customer that wildly flails its\n"
    .string "giant claws. It is said to be extremely\n"
    .string "hard to raise.$"

Text2_844D075:: @ 844D075
    .string "$"

Text2_844D076:: @ 844D076
    .string "It was discovered in ancient ruins.\n"
    .string "While moving, it constantly spins. It\n"
    .string "stands on one foot even when asleep.$"

Text2_844D0E5:: @ 844D0E5
    .string "$"

Text2_844D0E6:: @ 844D0E6
    .string "It appears to have been born from clay\n"
    .string "dolls made by ancient people. It uses\n"
    .string "telekinesis to float and move.$"

Text2_844D152:: @ 844D152
    .string "$"

Text2_844D153:: @ 844D153
    .string "It became extinct roughly 100 million\n"
    .string "years ago. It was regenerated from a\n"
    .string "fossil using advanced techniques.$"

Text2_844D1C0:: @ 844D1C0
    .string "$"

Text2_844D1C1:: @ 844D1C1
    .string "It ensnares prey with its eight tentacles.\n"
    .string "It then melts the prey with a strong acid\n"
    .string "before feeding.$"

Text2_844D226:: @ 844D226
    .string "$"

Text2_844D227:: @ 844D227
    .string "It is a kind of POKéMON progenitor.\n"
    .string "It uses its extending claws to catch prey\n"
    .string "hiding among rocks on the seafloor.$"

Text2_844D299:: @ 844D299
    .string "$"

Text2_844D29A:: @ 844D29A
    .string "Protected by a hard shell, its body is\n"
    .string "very sturdy. It skewers prey with its\n"
    .string "claws to feed.$"

Text2_844D2F6:: @ 844D2F6
    .string "$"

Text2_844D2F7:: @ 844D2F7
    .string "Ridiculed for its shabby appearance,\n"
    .string "it is ignored by researchers. It lives in\n"
    .string "ponds choked with weeds.$"

Text2_844D35F:: @ 844D35F
    .string "$"

Text2_844D360:: @ 844D360
    .string "MILOTIC is breathtakingly beautiful.\n"
    .string "Those that see it are said to forget their\n"
    .string "combative spirits.$"

Text2_844D3C3:: @ 844D3C3
    .string "$"

Text2_844D3C4:: @ 844D3C4
    .string "It has the ability to change its form into\n"
    .string "the sun, the rain, or a snow cloud, \n"
    .string "depending on the weather.$"

Text2_844D42E:: @ 844D42E
    .string "$"

Text2_844D42F:: @ 844D42F
    .string "It changes body color to blend in with\n"
    .string "its surroundings. It also changes color if\n"
    .string "it is happy or sad.$"

Text2_844D495:: @ 844D495
    .string "$"

Text2_844D496:: @ 844D496
    .string "It loves to feed on feelings like envy and\n"
    .string "malice. Its upright horn catches the\n"
    .string "emotions of people.$"

Text2_844D4FA:: @ 844D4FA
    .string "$"

Text2_844D4FB:: @ 844D4FB
    .string "Strong feelings of hatred turned a puppet\n"
    .string "into a POKéMON. If it opens its mouth,\n"
    .string "its cursed energy escapes.$"

Text2_844D567:: @ 844D567
    .string "$"

Text2_844D568:: @ 844D568
    .string "Making itself invisible, it silently sneaks\n"
    .string "up to prey. It has the ability to slip\n"
    .string "through thick walls.$"

Text2_844D5D0:: @ 844D5D0
    .string "$"

Text2_844D5D1:: @ 844D5D1
    .string "Its body is entirely hollow. When it opens\n"
    .string "its mouth, it sucks everything in as if it\n"
    .string "were a black hole.$"

Text2_844D63A:: @ 844D63A
    .string "$"

Text2_844D63B:: @ 844D63B
    .string "It lives in tropical jungles. The bunch of\n"
    .string "fruit around its neck is delicious.\n"
    .string "The fruit grows twice a year.$"

Text2_844D6A8:: @ 844D6A8
    .string "$"

Text2_844D6A9:: @ 844D6A9
    .string "It travels by riding on winds. It cleverly\n"
    .string "uses its long tail to pluck nuts and\n"
    .string "berries, which it loves to eat.$"

Text2_844D719:: @ 844D719
    .string "$"

Text2_844D71A:: @ 844D71A
    .string "It appears when it senses an impending\n"
    .string "natural disaster. As a result, it was\n"
    .string "mistaken as a doom-bringer.$"

Text2_844D783:: @ 844D783
    .string "$"

Text2_844D784:: @ 844D784
    .string "It tends to move in a pack with others.\n"
    .string "They cluster in a tight group to sleep in\n"
    .string "a cave.$"

Text2_844D7DE:: @ 844D7DE
    .string "$"

Text2_844D7DF:: @ 844D7DF
    .string "It is said that a home visited by a\n"
    .string "SNORUNT will prosper. It can withstand\n"
    .string "cold of minus 150 degrees Fahrenheit.$"

Text2_844D850:: @ 844D850
    .string "$"

Text2_844D851:: @ 844D851
    .string "It has a body of ice that won’t melt,\n"
    .string "even with fire. It can instantly freeze\n"
    .string "moisture in the atmosphere.$"

Text2_844D8BB:: @ 844D8BB
    .string "$"

Text2_844D8BC:: @ 844D8BC
    .string "Its body is covered in fluffy fur.\n"
    .string "The fur keeps it from feeling cold while\n"
    .string "it is rolling on ice.$"

Text2_844D91E:: @ 844D91E
    .string "$"

Text2_844D91F:: @ 844D91F
    .string "It touches new things with its nose to\n"
    .string "test for smell and feel. It plays by\n"
    .string "spinning SPHEAL on its nose.$"

Text2_844D988:: @ 844D988
    .string "$"

Text2_844D989:: @ 844D989
    .string "It swims through icy seas while shattering\n"
    .string "ice floes with its large tusks. It is\n"
    .string "protected by its thick blubber.$"

Text2_844D9FA:: @ 844D9FA
    .string "$"

Text2_844D9FB:: @ 844D9FB
    .string "It is protected by a sturdy shell.\n"
    .string "Once in a lifetime, it makes a magnificent\n"
    .string "pearl.$"

Text2_844DA50:: @ 844DA50
    .string "$"

Text2_844DA51:: @ 844DA51
    .string "It lives deep in the sea where no light\n"
    .string "ever filters down. It lights up its small\n"
    .string "fishlike tail to attract prey.$"

Text2_844DAC2:: @ 844DAC2
    .string "$"

Text2_844DAC3:: @ 844DAC3
    .string "Its swimming form is exquisitely elegant.\n"
    .string "With its thin mouth, it feeds on seaweed\n"
    .string "that grows between rocks.$"

Text2_844DB30:: @ 844DB30
    .string "$"

Text2_844DB31:: @ 844DB31
    .string "It has remained unchanged for 100\n"
    .string "million years. It was discovered\n"
    .string "during a deep-sea exploration.$"

Text2_844DB93:: @ 844DB93
    .string "$"

Text2_844DB94:: @ 844DB94
    .string "During the spawning season, countless\n"
    .string "LUVDISC congregate at coral reefs,\n"
    .string "turning the waters pink.$"

Text2_844DBF6:: @ 844DBF6
    .string "$"

Text2_844DBF7:: @ 844DBF7
    .string "Its steel-hard head can shatter boulders.\n"
    .string "It longingly hopes for wings to grow so it\n"
    .string "can fly.$"

Text2_844DC55:: @ 844DC55
    .string "$"

Text2_844DC56:: @ 844DC56
    .string "Its armored body makes all attacks bounce\n"
    .string "off. The armor is too tough, however,\n"
    .string "making it heavy and somewhat sluggish.$"

Text2_844DCCD:: @ 844DCCD
    .string "$"

Text2_844DCCE:: @ 844DCCE
    .string "It becomes uncontrollable if it is\n"
    .string "enraged. It destroys everything with\n"
    .string "shredding claws and fire.$"

Text2_844DD30:: @ 844DD30
    .string "$"

Text2_844DD31:: @ 844DD31
    .string "It uses magnetic waves to converse with\n"
    .string "its kind. All the cells in its body are\n"
    .string "magnetic.$"

Text2_844DD8B:: @ 844DD8B
    .string "$"

Text2_844DD8C:: @ 844DD8C
    .string "It floats midair using magnetism. Its body\n"
    .string "is so tough, even a crash with a jet\n"
    .string "plane won’t leave a scratch.$"

Text2_844DDF9:: @ 844DDF9
    .string "$"

Text2_844DDFA:: @ 844DDFA
    .string "It is formed by two METANG fusing.\n"
    .string "Its four brains are said to be superior\n"
    .string "to a supercomputer.$"

Text2_844DE59:: @ 844DE59
    .string "$"

Text2_844DE5A:: @ 844DE5A
    .string "It is entirely composed of rocks with no\n"
    .string "sign of a brain or heart. It is a mystery\n"
    .string "even to modern scientists.$"

Text2_844DEC8:: @ 844DEC8
    .string "$"

Text2_844DEC9:: @ 844DEC9
    .string "Research revealed that its body is made\n"
    .string "of the same kind of ice that is found at\n"
    .string "the South Pole.$"

Text2_844DF2A:: @ 844DF2A
    .string "$"

Text2_844DF2B:: @ 844DF2B
    .string "It is sturdier than any kind of metal.\n"
    .string "It hardened due to pressure underground\n"
    .string "over tens of thousands of years.$"

Text2_844DF9B:: @ 844DF9B
    .string "$"

Text2_844DF9C:: @ 844DF9C
    .string "It can telepathically communicate with\n"
    .string "people. It changes its appearance using\n"
    .string "its down that refracts light.$"

Text2_844E009:: @ 844E009
    .string "$"

Text2_844E00A:: @ 844E00A
    .string "It has a docile temperament and dislikes\n"
    .string "fighting. Tucking in its forelegs, it can\n"
    .string "fly faster than a jet plane.$"

Text2_844E07A:: @ 844E07A
    .string "$"

Text2_844E07B:: @ 844E07B
    .string "This POKéMON is said to have expanded\n"
    .string "the sea by bringing heavy rains.\n"
    .string "It has the power to control water.$"

Text2_844E0E5:: @ 844E0E5
    .string "$"

Text2_844E0E6:: @ 844E0E6
    .string "This legendary POKéMON is said to\n"
    .string "represent the land. It went to sleep after\n"
    .string "dueling KYOGRE.$"

Text2_844E143:: @ 844E143
    .string "$"

Text2_844E144:: @ 844E144
    .string "It has lived for hundreds of millions of\n"
    .string "years in the ozone layer. Its flying form\n"
    .string "looks like a meteor.$"

Text2_844E1AC:: @ 844E1AC
    .string "$"

Text2_844E1AD:: @ 844E1AD
    .string "It is said to make any wish come true.\n"
    .string "It is awake for only seven days out of\n"
    .string "a thousand years.$"

Text2_844E20D:: @ 844E20D
    .string "$"

Text2_844E20E:: @ 844E20E
    .string "When it changes form, an aurora appears.\n"
    .string "It absorbs attacks by altering its\n"
    .string "cellular structure.$"

Text2_844E26E:: @ 844E26E
    .string "$"

    .incbin "baserom-lg.gba", 0x44E26F, 0x1

Data2:: @ 844E270
    @ 844E270
    .string "UNKNOWN$", 12
    .2byte 0 @ in decimeters
    .2byte 0 @ in hectograms
    .4byte Text2_8444A71
    .4byte Text2_8444AED
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte 0
    .2byte 0 @ padding

    @ 844E294
    .string "SEED$", 12
    .2byte 7 @ in decimeters
    .2byte 69 @ in hectograms
    .4byte Text2_8444AEE
    .4byte Text2_8444B4E
    .2byte 0 @ unused
    .2byte 356
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E2B8
    .string "SEED$", 12
    .2byte 10 @ in decimeters
    .2byte 130 @ in hectograms
    .4byte Text2_8444B4F
    .4byte Text2_8444BB0
    .2byte 0 @ unused
    .2byte 332
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E2DC
    .string "SEED$", 12
    .2byte 20 @ in decimeters
    .2byte 1000 @ in hectograms
    .4byte Text2_8444BB1
    .4byte Text2_8444C0C
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding

    @ 844E300
    .string "LIZARD$", 12
    .2byte 6 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text2_8444C0E
    .4byte Text2_8444C72
    .2byte 0 @ unused
    .2byte 410
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E324
    .string "FLAME$", 12
    .2byte 11 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte Text2_8444C73
    .4byte Text2_8444CD0
    .2byte 0 @ unused
    .2byte 294
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E348
    .string "FLAME$", 12
    .2byte 17 @ in decimeters
    .2byte 905 @ in hectograms
    .4byte Text2_8444CD1
    .4byte Text2_8444D31
    .2byte 0 @ unused
    .2byte 271
    .2byte 0
    .2byte 317
    .2byte 3
    .2byte 0 @ padding

    @ 844E36C
    .string "TINY TURTLE$", 12
    .2byte 5 @ in decimeters
    .2byte 90 @ in hectograms
    .4byte Text2_8444D32
    .4byte Text2_8444D94
    .2byte 0 @ unused
    .2byte 412
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E390
    .string "TURTLE$", 12
    .2byte 10 @ in decimeters
    .2byte 225 @ in hectograms
    .4byte Text2_8444D95
    .4byte Text2_8444DFD
    .2byte 0 @ unused
    .2byte 334
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E3B4
    .string "SHELLFISH$", 12
    .2byte 16 @ in decimeters
    .2byte 855 @ in hectograms
    .4byte Text2_8444DFE
    .4byte Text2_8444E5A
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 329
    .2byte 3
    .2byte 0 @ padding

    @ 844E3D8
    .string "WORM$", 12
    .2byte 3 @ in decimeters
    .2byte 29 @ in hectograms
    .4byte Text2_8444E5B
    .4byte Text2_8444EBC
    .2byte 0 @ unused
    .2byte 549
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E3FC
    .string "COCOON$", 12
    .2byte 7 @ in decimeters
    .2byte 99 @ in hectograms
    .4byte Text2_8444EBD
    .4byte Text2_8444F1E
    .2byte 0 @ unused
    .2byte 350
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E420
    .string "BUTTERFLY$", 12
    .2byte 11 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte Text2_8444F20
    .4byte Text2_8444F78
    .2byte 0 @ unused
    .2byte 312
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E444
    .string "HAIRY BUG$", 12
    .2byte 3 @ in decimeters
    .2byte 32 @ in hectograms
    .4byte Text2_8444F7A
    .4byte Text2_8444FD9
    .2byte 0 @ unused
    .2byte 455
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E468
    .string "COCOON$", 12
    .2byte 6 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte Text2_8444FDA
    .4byte Text2_8445045
    .2byte 0 @ unused
    .2byte 424
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E48C
    .string "POISON BEE$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte Text2_8445046
    .4byte Text2_84450A6
    .2byte 0 @ unused
    .2byte 366
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E4B0
    .string "TINY BIRD$", 12
    .2byte 3 @ in decimeters
    .2byte 18 @ in hectograms
    .4byte Text2_84450A7
    .4byte Text2_8445109
    .2byte 0 @ unused
    .2byte 492
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E4D4
    .string "BIRD$", 12
    .2byte 11 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text2_844510A
    .4byte Text2_844516E
    .2byte 0 @ unused
    .2byte 334
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E4F8
    .string "BIRD$", 12
    .2byte 15 @ in decimeters
    .2byte 395 @ in hectograms
    .4byte Text2_844516F
    .4byte Text2_84451D3
    .2byte 0 @ unused
    .2byte 269
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E51C
    .string "MOUSE$", 12
    .2byte 3 @ in decimeters
    .2byte 35 @ in hectograms
    .4byte Text2_84451D4
    .4byte Text2_844522F
    .2byte 0 @ unused
    .2byte 481
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E540
    .string "MOUSE$", 12
    .2byte 7 @ in decimeters
    .2byte 185 @ in hectograms
    .4byte Text2_8445230
    .4byte Text2_844528C
    .2byte 0 @ unused
    .2byte 401
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E564
    .string "TINY BIRD$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text2_844528D
    .4byte Text2_84452E7
    .2byte 0 @ unused
    .2byte 571
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E588
    .string "BEAK$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte Text2_84452E8
    .4byte Text2_8445345
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 844E5AC
    .string "SNAKE$", 12
    .2byte 20 @ in decimeters
    .2byte 69 @ in hectograms
    .4byte Text2_8445346
    .4byte Text2_84453A4
    .2byte 0 @ unused
    .2byte 298
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E5D0
    .string "COBRA$", 12
    .2byte 35 @ in decimeters
    .2byte 650 @ in hectograms
    .4byte Text2_84453A5
    .4byte Text2_84453FE
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 296
    .2byte 1
    .2byte 0 @ padding

    @ 844E5F4
    .string "MOUSE$", 12
    .2byte 4 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte Text2_84453FF
    .4byte Text2_844545D
    .2byte 0 @ unused
    .2byte 479
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E618
    .string "MOUSE$", 12
    .2byte 8 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text2_844545E
    .4byte Text2_84454B2
    .2byte 0 @ unused
    .2byte 426
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E63C
    .string "MOUSE$", 12
    .2byte 6 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text2_84454B3
    .4byte Text2_8445510
    .2byte 0 @ unused
    .2byte 370
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E660
    .string "MOUSE$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte Text2_8445511
    .4byte Text2_844556E
    .2byte 0 @ unused
    .2byte 341
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E684
    .string "POISON PIN$", 12
    .2byte 4 @ in decimeters
    .2byte 70 @ in hectograms
    .4byte Text2_844556F
    .4byte Text2_84455CF
    .2byte 0 @ unused
    .2byte 488
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E6A8
    .string "POISON PIN$", 12
    .2byte 8 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte Text2_84455D0
    .4byte Text2_8445628
    .2byte 0 @ unused
    .2byte 381
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E6CC
    .string "DRILL$", 12
    .2byte 13 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text2_8445629
    .4byte Text2_8445686
    .2byte 0 @ unused
    .2byte 283
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E6F0
    .string "POISON PIN$", 12
    .2byte 5 @ in decimeters
    .2byte 90 @ in hectograms
    .4byte Text2_8445687
    .4byte Text2_84456EA
    .2byte 0 @ unused
    .2byte 480
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E714
    .string "POISON PIN$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte Text2_84456EB
    .4byte Text2_844574A
    .2byte 0 @ unused
    .2byte 408
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E738
    .string "DRILL$", 12
    .2byte 14 @ in decimeters
    .2byte 620 @ in hectograms
    .4byte Text2_844574B
    .4byte Text2_84457A1
    .2byte 0 @ unused
    .2byte 304
    .2byte 3
    .2byte 323
    .2byte 2
    .2byte 0 @ padding

    @ 844E75C
    .string "FAIRY$", 12
    .2byte 6 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte Text2_84457A2
    .4byte Text2_8445807
    .2byte 0 @ unused
    .2byte 425
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E780
    .string "FAIRY$", 12
    .2byte 13 @ in decimeters
    .2byte 400 @ in hectograms
    .4byte Text2_8445808
    .4byte Text2_8445865
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 272
    .2byte -1
    .2byte 0 @ padding

    @ 844E7A4
    .string "FOX$", 12
    .2byte 6 @ in decimeters
    .2byte 99 @ in hectograms
    .4byte Text2_8445866
    .4byte Text2_84458C9
    .2byte 0 @ unused
    .2byte 497
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E7C8
    .string "FOX$", 12
    .2byte 11 @ in decimeters
    .2byte 199 @ in hectograms
    .4byte Text2_84458CA
    .4byte Text2_844592B
    .2byte 0 @ unused
    .2byte 339
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E7EC
    .string "BALLOON$", 12
    .2byte 5 @ in decimeters
    .2byte 55 @ in hectograms
    .4byte Text2_844592C
    .4byte Text2_844598F
    .2byte 0 @ unused
    .2byte 419
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E810
    .string "BALLOON$", 12
    .2byte 10 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text2_8445990
    .4byte Text2_84459F8
    .2byte 0 @ unused
    .2byte 328
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E834
    .string "BAT$", 12
    .2byte 8 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte Text2_84459F9
    .4byte Text2_8445A65
    .2byte 0 @ unused
    .2byte 355
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E858
    .string "BAT$", 12
    .2byte 16 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text2_8445A66
    .4byte Text2_8445AC8
    .2byte 0 @ unused
    .2byte 291
    .2byte 0
    .2byte 296
    .2byte 2
    .2byte 0 @ padding

    @ 844E87C
    .string "WEED$", 12
    .2byte 5 @ in decimeters
    .2byte 54 @ in hectograms
    .4byte Text2_8445AC9
    .4byte Text2_8445B2F
    .2byte 0 @ unused
    .2byte 423
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E8A0
    .string "WEED$", 12
    .2byte 8 @ in decimeters
    .2byte 86 @ in hectograms
    .4byte Text2_8445B30
    .4byte Text2_8445B8E
    .2byte 0 @ unused
    .2byte 329
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E8C4
    .string "FLOWER$", 12
    .2byte 12 @ in decimeters
    .2byte 186 @ in hectograms
    .4byte Text2_8445B8F
    .4byte Text2_8445BF4
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 844E8E8
    .string "MUSHROOM$", 12
    .2byte 3 @ in decimeters
    .2byte 54 @ in hectograms
    .4byte Text2_8445BF5
    .4byte Text2_8445C58
    .2byte 0 @ unused
    .2byte 546
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E90C
    .string "MUSHROOM$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte Text2_8445C59
    .4byte Text2_8445CC0
    .2byte 0 @ unused
    .2byte 307
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E930
    .string "INSECT$", 12
    .2byte 10 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text2_8445CC1
    .4byte Text2_8445D1B
    .2byte 0 @ unused
    .2byte 360
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E954
    .string "POISON MOTH$", 12
    .2byte 15 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte Text2_8445D1C
    .4byte Text2_8445D7B
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 293
    .2byte 1
    .2byte 0 @ padding

    @ 844E978
    .string "MOLE$", 12
    .2byte 2 @ in decimeters
    .2byte 8 @ in hectograms
    .4byte Text2_8445D7C
    .4byte Text2_8445DDE
    .2byte 0 @ unused
    .2byte 706
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E99C
    .string "MOLE$", 12
    .2byte 7 @ in decimeters
    .2byte 333 @ in hectograms
    .4byte Text2_8445DDF
    .4byte Text2_8445E3B
    .2byte 0 @ unused
    .2byte 384
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E9C0
    .string "SCRATCH CAT$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte Text2_8445E3C
    .4byte Text2_8445E9E
    .2byte 0 @ unused
    .2byte 480
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844E9E4
    .string "CLASSY CAT$", 12
    .2byte 10 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte Text2_8445E9F
    .4byte Text2_8445F01
    .2byte 0 @ unused
    .2byte 320
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA08
    .string "DUCK$", 12
    .2byte 8 @ in decimeters
    .2byte 196 @ in hectograms
    .4byte Text2_8445F02
    .4byte Text2_8445F63
    .2byte 0 @ unused
    .2byte 347
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA2C
    .string "DUCK$", 12
    .2byte 17 @ in decimeters
    .2byte 766 @ in hectograms
    .4byte Text2_8445F64
    .4byte Text2_8445FC6
    .2byte 0 @ unused
    .2byte 272
    .2byte 4
    .2byte 287
    .2byte 1
    .2byte 0 @ padding

    @ 844EA50
    .string "PIG MONKEY$", 12
    .2byte 5 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text2_8445FC7
    .4byte Text2_8446027
    .2byte 0 @ unused
    .2byte 388
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA74
    .string "PIG MONKEY$", 12
    .2byte 10 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte Text2_8446028
    .4byte Text2_844608A
    .2byte 0 @ unused
    .2byte 326
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EA98
    .string "PUPPY$", 12
    .2byte 7 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte Text2_844608B
    .4byte Text2_84460EC
    .2byte 0 @ unused
    .2byte 346
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EABC
    .string "LEGENDARY$", 12
    .2byte 19 @ in decimeters
    .2byte 1550 @ in hectograms
    .4byte Text2_84460ED
    .4byte Text2_8446142
    .2byte 0 @ unused
    .2byte 256
    .2byte -1
    .2byte 312
    .2byte 2
    .2byte 0 @ padding

    @ 844EAE0
    .string "TADPOLE$", 12
    .2byte 6 @ in decimeters
    .2byte 124 @ in hectograms
    .4byte Text2_8446143
    .4byte Text2_84461A2
    .2byte 0 @ unused
    .2byte 353
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EB04
    .string "TADPOLE$", 12
    .2byte 10 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte Text2_84461A3
    .4byte Text2_8446203
    .2byte 0 @ unused
    .2byte 288
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EB28
    .string "TADPOLE$", 12
    .2byte 13 @ in decimeters
    .2byte 540 @ in hectograms
    .4byte Text2_8446204
    .4byte Text2_8446268
    .2byte 0 @ unused
    .2byte 256
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EB4C
    .string "PSI$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte Text2_8446269
    .4byte Text2_84462C1
    .2byte 0 @ unused
    .2byte 374
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EB70
    .string "PSI$", 12
    .2byte 13 @ in decimeters
    .2byte 565 @ in hectograms
    .4byte Text2_84462C2
    .4byte Text2_8446318
    .2byte 0 @ unused
    .2byte 272
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EB94
    .string "PSI$", 12
    .2byte 15 @ in decimeters
    .2byte 480 @ in hectograms
    .4byte Text2_8446319
    .4byte Text2_844637E
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 271
    .2byte -1
    .2byte 0 @ padding

    @ 844EBB8
    .string "SUPERPOWER$", 12
    .2byte 8 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte Text2_844637F
    .4byte Text2_84463DC
    .2byte 0 @ unused
    .2byte 320
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EBDC
    .string "SUPERPOWER$", 12
    .2byte 15 @ in decimeters
    .2byte 705 @ in hectograms
    .4byte Text2_84463DD
    .4byte Text2_8446442
    .2byte 0 @ unused
    .2byte 304
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EC00
    .string "SUPERPOWER$", 12
    .2byte 16 @ in decimeters
    .2byte 1300 @ in hectograms
    .4byte Text2_8446443
    .4byte Text2_8446499
    .2byte 0 @ unused
    .2byte 278
    .2byte 2
    .2byte 283
    .2byte 0
    .2byte 0 @ padding

    @ 844EC24
    .string "FLOWER$", 12
    .2byte 7 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text2_844649A
    .4byte Text2_8446501
    .2byte 0 @ unused
    .2byte 354
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EC48
    .string "FLYCATCHER$", 12
    .2byte 10 @ in decimeters
    .2byte 64 @ in hectograms
    .4byte Text2_8446502
    .4byte Text2_844655F
    .2byte 0 @ unused
    .2byte 256
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EC6C
    .string "FLYCATCHER$", 12
    .2byte 17 @ in decimeters
    .2byte 155 @ in hectograms
    .4byte Text2_8446560
    .4byte Text2_84465BD
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 302
    .2byte 2
    .2byte 0 @ padding

    @ 844EC90
    .string "JELLYFISH$", 12
    .2byte 9 @ in decimeters
    .2byte 455 @ in hectograms
    .4byte Text2_84465BE
    .4byte Text2_844661E
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844ECB4
    .string "JELLYFISH$", 12
    .2byte 16 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text2_844661F
    .4byte Text2_8446682
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 312
    .2byte 0
    .2byte 0 @ padding

    @ 844ECD8
    .string "ROCK$", 12
    .2byte 4 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte Text2_8446683
    .4byte Text2_84466E2
    .2byte 0 @ unused
    .2byte 330
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844ECFC
    .string "ROCK$", 12
    .2byte 10 @ in decimeters
    .2byte 1050 @ in hectograms
    .4byte Text2_84466E3
    .4byte Text2_8446744
    .2byte 0 @ unused
    .2byte 272
    .2byte 8
    .2byte 305
    .2byte 1
    .2byte 0 @ padding

    @ 844ED20
    .string "MEGATON$", 12
    .2byte 14 @ in decimeters
    .2byte 3000 @ in hectograms
    .4byte Text2_8446745
    .4byte Text2_84467AD
    .2byte 0 @ unused
    .2byte 266
    .2byte 3
    .2byte 298
    .2byte 1
    .2byte 0 @ padding

    @ 844ED44
    .string "FIRE HORSE$", 12
    .2byte 10 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text2_84467AE
    .4byte Text2_8446814
    .2byte 0 @ unused
    .2byte 288
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844ED68
    .string "FIRE HORSE$", 12
    .2byte 17 @ in decimeters
    .2byte 950 @ in hectograms
    .4byte Text2_8446815
    .4byte Text2_8446873
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 312
    .2byte 1
    .2byte 0 @ padding

    @ 844ED8C
    .string "DOPEY$", 12
    .2byte 12 @ in decimeters
    .2byte 360 @ in hectograms
    .4byte Text2_8446874
    .4byte Text2_84468CC
    .2byte 0 @ unused
    .2byte 271
    .2byte 10
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 844EDB0
    .string "HERMIT CRAB$", 12
    .2byte 16 @ in decimeters
    .2byte 785 @ in hectograms
    .4byte Text2_84468CD
    .4byte Text2_844692B
    .2byte 0 @ unused
    .2byte 257
    .2byte -2
    .2byte 312
    .2byte 0
    .2byte 0 @ padding

    @ 844EDD4
    .string "MAGNET$", 12
    .2byte 3 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte Text2_844692C
    .4byte Text2_8446991
    .2byte 0 @ unused
    .2byte 294
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EDF8
    .string "MAGNET$", 12
    .2byte 10 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text2_8446992
    .4byte Text2_84469EE
    .2byte 0 @ unused
    .2byte 293
    .2byte -4
    .2byte 273
    .2byte -2
    .2byte 0 @ padding

    @ 844EE1C
    .string "WILD DUCK$", 12
    .2byte 8 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text2_84469EF
    .4byte Text2_8446A52
    .2byte 0 @ unused
    .2byte 317
    .2byte -2
    .2byte 256
    .2byte -3
    .2byte 0 @ padding

    @ 844EE40
    .string "TWIN BIRD$", 12
    .2byte 14 @ in decimeters
    .2byte 392 @ in hectograms
    .4byte Text2_8446A53
    .4byte Text2_8446AAF
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 287
    .2byte 0
    .2byte 0 @ padding

    @ 844EE64
    .string "TRIPLE BIRD$", 12
    .2byte 18 @ in decimeters
    .2byte 852 @ in hectograms
    .4byte Text2_8446AB0
    .4byte Text2_8446B17
    .2byte 0 @ unused
    .2byte 272
    .2byte -2
    .2byte 296
    .2byte 1
    .2byte 0 @ padding

    @ 844EE88
    .string "SEA LION$", 12
    .2byte 11 @ in decimeters
    .2byte 900 @ in hectograms
    .4byte Text2_8446B18
    .4byte Text2_8446B75
    .2byte 0 @ unused
    .2byte 298
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EEAC
    .string "SEA LION$", 12
    .2byte 17 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text2_8446B76
    .4byte Text2_8446BDC
    .2byte 0 @ unused
    .2byte 288
    .2byte 1
    .2byte 306
    .2byte -1
    .2byte 0 @ padding

    @ 844EED0
    .string "SLUDGE$", 12
    .2byte 9 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text2_8446BDD
    .4byte Text2_8446C40
    .2byte 0 @ unused
    .2byte 258
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EEF4
    .string "SLUDGE$", 12
    .2byte 12 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text2_8446C41
    .4byte Text2_8446CA1
    .2byte 0 @ unused
    .2byte 288
    .2byte 7
    .2byte 288
    .2byte -1
    .2byte 0 @ padding

    @ 844EF18
    .string "BIVALVE$", 12
    .2byte 3 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text2_8446CA2
    .4byte Text2_8446CFA
    .2byte 0 @ unused
    .2byte 643
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EF3C
    .string "BIVALVE$", 12
    .2byte 15 @ in decimeters
    .2byte 1325 @ in hectograms
    .4byte Text2_8446CFB
    .4byte Text2_8446D54
    .2byte 0 @ unused
    .2byte 264
    .2byte 0
    .2byte 288
    .2byte -1
    .2byte 0 @ padding

    @ 844EF60
    .string "GAS$", 12
    .2byte 13 @ in decimeters
    .2byte 1 @ in hectograms
    .4byte Text2_8446D55
    .4byte Text2_8446DB3
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844EF84
    .string "GAS$", 12
    .2byte 16 @ in decimeters
    .2byte 1 @ in hectograms
    .4byte Text2_8446DB4
    .4byte Text2_8446E11
    .2byte 0 @ unused
    .2byte 269
    .2byte 2
    .2byte 308
    .2byte 1
    .2byte 0 @ padding

    @ 844EFA8
    .string "SHADOW$", 12
    .2byte 15 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte Text2_8446E12
    .4byte Text2_8446E72
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 317
    .2byte 1
    .2byte 0 @ padding

    @ 844EFCC
    .string "ROCK SNAKE$", 12
    .2byte 88 @ in decimeters
    .2byte 2100 @ in hectograms
    .4byte Text2_8446E73
    .4byte Text2_8446ED3
    .2byte 0 @ unused
    .2byte 257
    .2byte 0
    .2byte 515
    .2byte 12
    .2byte 0 @ padding

    @ 844EFF0
    .string "HYPNOSIS$", 12
    .2byte 10 @ in decimeters
    .2byte 324 @ in hectograms
    .4byte Text2_8446ED4
    .4byte Text2_8446F37
    .2byte 0 @ unused
    .2byte 274
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F014
    .string "HYPNOSIS$", 12
    .2byte 16 @ in decimeters
    .2byte 756 @ in hectograms
    .4byte Text2_8446F38
    .4byte Text2_8446F99
    .2byte 0 @ unused
    .2byte 298
    .2byte 3
    .2byte 310
    .2byte 2
    .2byte 0 @ padding

    @ 844F038
    .string "RIVER CRAB$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte Text2_8446F9A
    .4byte Text2_8446FF6
    .2byte 0 @ unused
    .2byte 469
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F05C
    .string "PINCER$", 12
    .2byte 13 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text2_8446FF7
    .4byte Text2_844705F
    .2byte 0 @ unused
    .2byte 287
    .2byte 3
    .2byte 308
    .2byte 1
    .2byte 0 @ padding

    @ 844F080
    .string "BALL$", 12
    .2byte 5 @ in decimeters
    .2byte 104 @ in hectograms
    .4byte Text2_8447060
    .4byte Text2_84470BB
    .2byte 0 @ unused
    .2byte 364
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F0A4
    .string "BALL$", 12
    .2byte 12 @ in decimeters
    .2byte 666 @ in hectograms
    .4byte Text2_84470BC
    .4byte Text2_8447121
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F0C8
    .string "EGG$", 12
    .2byte 4 @ in decimeters
    .2byte 25 @ in hectograms
    .4byte Text2_8447122
    .4byte Text2_844717B
    .2byte 0 @ unused
    .2byte 495
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F0EC
    .string "COCONUT$", 12
    .2byte 20 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text2_844717C
    .4byte Text2_84471DF
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 376
    .2byte 7
    .2byte 0 @ padding

    @ 844F110
    .string "LONELY$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte Text2_84471E0
    .4byte Text2_844723A
    .2byte 0 @ unused
    .2byte 545
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F134
    .string "BONE KEEPER$", 12
    .2byte 10 @ in decimeters
    .2byte 450 @ in hectograms
    .4byte Text2_844723B
    .4byte Text2_844729E
    .2byte 0 @ unused
    .2byte 293
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F158
    .string "KICKING$", 12
    .2byte 15 @ in decimeters
    .2byte 498 @ in hectograms
    .4byte Text2_844729F
    .4byte Text2_8447303
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 273
    .2byte -2
    .2byte 0 @ padding

    @ 844F17C
    .string "PUNCHING$", 12
    .2byte 14 @ in decimeters
    .2byte 502 @ in hectograms
    .4byte Text2_8447304
    .4byte Text2_844736B
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 264
    .2byte -2
    .2byte 0 @ padding

    @ 844F1A0
    .string "LICKING$", 12
    .2byte 12 @ in decimeters
    .2byte 655 @ in hectograms
    .4byte Text2_844736C
    .4byte Text2_84473D1
    .2byte 0 @ unused
    .2byte 272
    .2byte 3
    .2byte 272
    .2byte -3
    .2byte 0 @ padding

    @ 844F1C4
    .string "POISON GAS$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text2_84473D2
    .4byte Text2_8447438
    .2byte 0 @ unused
    .2byte 369
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F1E8
    .string "POISON GAS$", 12
    .2byte 12 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte Text2_8447439
    .4byte Text2_8447494
    .2byte 0 @ unused
    .2byte 321
    .2byte -1
    .2byte 276
    .2byte -1
    .2byte 0 @ padding

    @ 844F20C
    .string "SPIKES$", 12
    .2byte 10 @ in decimeters
    .2byte 1150 @ in hectograms
    .4byte Text2_8447495
    .4byte Text2_84474FB
    .2byte 0 @ unused
    .2byte 291
    .2byte 7
    .2byte 276
    .2byte -2
    .2byte 0 @ padding

    @ 844F230
    .string "DRILL$", 12
    .2byte 19 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text2_84474FC
    .4byte Text2_8447561
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 344
    .2byte 3
    .2byte 0 @ padding

    @ 844F254
    .string "EGG$", 12
    .2byte 11 @ in decimeters
    .2byte 346 @ in hectograms
    .4byte Text2_8447562
    .4byte Text2_84475BF
    .2byte 0 @ unused
    .2byte 257
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F278
    .string "VINE$", 12
    .2byte 10 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte Text2_84475C0
    .4byte Text2_8447623
    .2byte 0 @ unused
    .2byte 320
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F29C
    .string "PARENT$", 12
    .2byte 22 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte Text2_8447624
    .4byte Text2_8447681
    .2byte 0 @ unused
    .2byte 257
    .2byte -3
    .2byte 349
    .2byte 5
    .2byte 0 @ padding

    @ 844F2C0
    .string "DRAGON$", 12
    .2byte 4 @ in decimeters
    .2byte 80 @ in hectograms
    .4byte Text2_8447682
    .4byte Text2_84476DE
    .2byte 0 @ unused
    .2byte 399
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F2E4
    .string "DRAGON$", 12
    .2byte 12 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte Text2_84476DF
    .4byte Text2_8447742
    .2byte 0 @ unused
    .2byte 296
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F308
    .string "GOLDFISH$", 12
    .2byte 6 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text2_8447743
    .4byte Text2_84477A5
    .2byte 0 @ unused
    .2byte 379
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F32C
    .string "GOLDFISH$", 12
    .2byte 13 @ in decimeters
    .2byte 390 @ in hectograms
    .4byte Text2_84477A6
    .4byte Text2_8447800
    .2byte 0 @ unused
    .2byte 304
    .2byte 1
    .2byte 288
    .2byte -2
    .2byte 0 @ padding

    @ 844F350
    .string "STAR SHAPE$", 12
    .2byte 8 @ in decimeters
    .2byte 345 @ in hectograms
    .4byte Text2_8447801
    .4byte Text2_8447859
    .2byte 0 @ unused
    .2byte 326
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F374
    .string "MYSTERIOUS$", 12
    .2byte 11 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte Text2_844785A
    .4byte Text2_84478BC
    .2byte 0 @ unused
    .2byte 301
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F398
    .string "BARRIER$", 12
    .2byte 13 @ in decimeters
    .2byte 545 @ in hectograms
    .4byte Text2_84478BD
    .4byte Text2_844791F
    .2byte 0 @ unused
    .2byte 258
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F3BC
    .string "MANTIS$", 12
    .2byte 15 @ in decimeters
    .2byte 560 @ in hectograms
    .4byte Text2_8447920
    .4byte Text2_8447985
    .2byte 0 @ unused
    .2byte 272
    .2byte 0
    .2byte 293
    .2byte 1
    .2byte 0 @ padding

    @ 844F3E0
    .string "HUMAN SHAPE$", 12
    .2byte 14 @ in decimeters
    .2byte 406 @ in hectograms
    .4byte Text2_8447986
    .4byte Text2_84479E3
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 300
    .2byte 1
    .2byte 0 @ padding

    @ 844F404
    .string "ELECTRIC$", 12
    .2byte 11 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte Text2_84479E4
    .4byte Text2_8447A40
    .2byte 0 @ unused
    .2byte 330
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F428
    .string "SPITFIRE$", 12
    .2byte 13 @ in decimeters
    .2byte 445 @ in hectograms
    .4byte Text2_8447A41
    .4byte Text2_8447A9C
    .2byte 0 @ unused
    .2byte 293
    .2byte 4
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 844F44C
    .string "STAG BEETLE$", 12
    .2byte 15 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text2_8447A9D
    .4byte Text2_8447AF6
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 257
    .2byte -2
    .2byte 0 @ padding

    @ 844F470
    .string "WILD BULL$", 12
    .2byte 14 @ in decimeters
    .2byte 884 @ in hectograms
    .4byte Text2_8447AF7
    .4byte Text2_8447B53
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 312
    .2byte 3
    .2byte 0 @ padding

    @ 844F494
    .string "FISH$", 12
    .2byte 9 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte Text2_8447B54
    .4byte Text2_8447BB7
    .2byte 0 @ unused
    .2byte 317
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F4B8
    .string "ATROCIOUS$", 12
    .2byte 65 @ in decimeters
    .2byte 2350 @ in hectograms
    .4byte Text2_8447BB8
    .4byte Text2_8447C18
    .2byte 0 @ unused
    .2byte 288
    .2byte -1
    .2byte 512
    .2byte 11
    .2byte 0 @ padding

    @ 844F4DC
    .string "TRANSPORT$", 12
    .2byte 25 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte Text2_8447C19
    .4byte Text2_8447C73
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 425
    .2byte 8
    .2byte 0 @ padding

    @ 844F500
    .string "TRANSFORM$", 12
    .2byte 3 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text2_8447C74
    .4byte Text2_8447CDF
    .2byte 0 @ unused
    .2byte 602
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F524
    .string "EVOLUTION$", 12
    .2byte 3 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte Text2_8447CE0
    .4byte Text2_8447D40
    .2byte 0 @ unused
    .2byte 476
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F548
    .string "BUBBLE JET$", 12
    .2byte 10 @ in decimeters
    .2byte 290 @ in hectograms
    .4byte Text2_8447D41
    .4byte Text2_8447DA3
    .2byte 0 @ unused
    .2byte 316
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F56C
    .string "LIGHTNING$", 12
    .2byte 8 @ in decimeters
    .2byte 245 @ in hectograms
    .4byte Text2_8447DA4
    .4byte Text2_8447DFD
    .2byte 0 @ unused
    .2byte 283
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F590
    .string "FLAME$", 12
    .2byte 9 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte Text2_8447DFE
    .4byte Text2_8447E62
    .2byte 0 @ unused
    .2byte 302
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F5B4
    .string "VIRTUAL$", 12
    .2byte 8 @ in decimeters
    .2byte 365 @ in hectograms
    .4byte Text2_8447E63
    .4byte Text2_8447EC7
    .2byte 0 @ unused
    .2byte 328
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F5D8
    .string "SPIRAL$", 12
    .2byte 4 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte Text2_8447EC8
    .4byte Text2_8447F1E
    .2byte 0 @ unused
    .2byte 521
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F5FC
    .string "SPIRAL$", 12
    .2byte 10 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte Text2_8447F1F
    .4byte Text2_8447F8D
    .2byte 0 @ unused
    .2byte 307
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F620
    .string "SHELLFISH$", 12
    .2byte 5 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text2_8447F8E
    .4byte Text2_8447FEC
    .2byte 0 @ unused
    .2byte 438
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F644
    .string "SHELLFISH$", 12
    .2byte 13 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte Text2_8447FED
    .4byte Text2_844804E
    .2byte 0 @ unused
    .2byte 271
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F668
    .string "FOSSIL$", 12
    .2byte 18 @ in decimeters
    .2byte 590 @ in hectograms
    .4byte Text2_844804F
    .4byte Text2_84480B3
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 317
    .2byte 2
    .2byte 0 @ padding

    @ 844F68C
    .string "SLEEPING$", 12
    .2byte 21 @ in decimeters
    .2byte 4600 @ in hectograms
    .4byte Text2_84480B4
    .4byte Text2_8448113
    .2byte 0 @ unused
    .2byte 275
    .2byte 1
    .2byte 408
    .2byte 7
    .2byte 0 @ padding

    @ 844F6B0
    .string "FREEZE$", 12
    .2byte 17 @ in decimeters
    .2byte 554 @ in hectograms
    .4byte Text2_8448114
    .4byte Text2_8448174
    .2byte 0 @ unused
    .2byte 278
    .2byte 0
    .2byte 308
    .2byte 1
    .2byte 0 @ padding

    @ 844F6D4
    .string "ELECTRIC$", 12
    .2byte 16 @ in decimeters
    .2byte 526 @ in hectograms
    .4byte Text2_8448175
    .4byte Text2_84481DA
    .2byte 0 @ unused
    .2byte 275
    .2byte 1
    .2byte 330
    .2byte 3
    .2byte 0 @ padding

    @ 844F6F8
    .string "FLAME$", 12
    .2byte 20 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text2_84481DB
    .4byte Text2_844824C
    .2byte 0 @ unused
    .2byte 270
    .2byte 1
    .2byte 379
    .2byte 6
    .2byte 0 @ padding

    @ 844F71C
    .string "DRAGON$", 12
    .2byte 18 @ in decimeters
    .2byte 33 @ in hectograms
    .4byte Text2_844824D
    .4byte Text2_84482B1
    .2byte 0 @ unused
    .2byte 256
    .2byte 8
    .2byte 386
    .2byte 6
    .2byte 0 @ padding

    @ 844F740
    .string "DRAGON$", 12
    .2byte 40 @ in decimeters
    .2byte 165 @ in hectograms
    .4byte Text2_84482B2
    .4byte Text2_8448316
    .2byte 0 @ unused
    .2byte 274
    .2byte 0
    .2byte 423
    .2byte 6
    .2byte 0 @ padding

    @ 844F764
    .string "DRAGON$", 12
    .2byte 22 @ in decimeters
    .2byte 2100 @ in hectograms
    .4byte Text2_8448317
    .4byte Text2_8448377
    .2byte 0 @ unused
    .2byte 283
    .2byte -1
    .2byte 342
    .2byte 4
    .2byte 0 @ padding

    @ 844F788
    .string "GENETIC$", 12
    .2byte 20 @ in decimeters
    .2byte 1220 @ in hectograms
    .4byte Text2_8448378
    .4byte Text2_84483DE
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 342
    .2byte 5
    .2byte 0 @ padding

    @ 844F7AC
    .string "NEW SPECIES$", 12
    .2byte 4 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text2_84483DF
    .4byte Text2_8448447
    .2byte 0 @ unused
    .2byte 460
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F7D0
    .string "LEAF$", 12
    .2byte 9 @ in decimeters
    .2byte 64 @ in hectograms
    .4byte Text2_8448448
    .4byte Text2_84484B0
    .2byte 0 @ unused
    .2byte 512
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F7F4
    .string "LEAF$", 12
    .2byte 12 @ in decimeters
    .2byte 158 @ in hectograms
    .4byte Text2_84484B1
    .4byte Text2_844850F
    .2byte 0 @ unused
    .2byte 296
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F818
    .string "HERB$", 12
    .2byte 18 @ in decimeters
    .2byte 1005 @ in hectograms
    .4byte Text2_8448510
    .4byte Text2_844856A
    .2byte 0 @ unused
    .2byte 286
    .2byte 0
    .2byte 317
    .2byte 2
    .2byte 0 @ padding

    @ 844F83C
    .string "FIRE MOUSE$", 12
    .2byte 5 @ in decimeters
    .2byte 79 @ in hectograms
    .4byte Text2_844856B
    .4byte Text2_84485D0
    .2byte 0 @ unused
    .2byte 539
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F860
    .string "VOLCANO$", 12
    .2byte 9 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte Text2_84485D1
    .4byte Text2_8448638
    .2byte 0 @ unused
    .2byte 329
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F884
    .string "VOLCANO$", 12
    .2byte 17 @ in decimeters
    .2byte 795 @ in hectograms
    .4byte Text2_8448639
    .4byte Text2_844869C
    .2byte 0 @ unused
    .2byte 284
    .2byte -1
    .2byte 287
    .2byte 0
    .2byte 0 @ padding

    @ 844F8A8
    .string "BIG JAW$", 12
    .2byte 6 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte Text2_844869D
    .4byte Text2_8448706
    .2byte 0 @ unused
    .2byte 487
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F8CC
    .string "BIG JAW$", 12
    .2byte 11 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte Text2_8448707
    .4byte Text2_844876A
    .2byte 0 @ unused
    .2byte 378
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F8F0
    .string "BIG JAW$", 12
    .2byte 23 @ in decimeters
    .2byte 888 @ in hectograms
    .4byte Text2_844876B
    .4byte Text2_84487D2
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding

    @ 844F914
    .string "SCOUT$", 12
    .2byte 8 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte Text2_84487D3
    .4byte Text2_8448839
    .2byte 0 @ unused
    .2byte 439
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F938
    .string "LONG BODY$", 12
    .2byte 18 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte Text2_844883A
    .4byte Text2_844889F
    .2byte 0 @ unused
    .2byte 346
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F95C
    .string "OWL$", 12
    .2byte 7 @ in decimeters
    .2byte 212 @ in hectograms
    .4byte Text2_84488A0
    .4byte Text2_84488F8
    .2byte 0 @ unused
    .2byte 380
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F980
    .string "OWL$", 12
    .2byte 16 @ in decimeters
    .2byte 408 @ in hectograms
    .4byte Text2_84488F9
    .4byte Text2_844895D
    .2byte 0 @ unused
    .2byte 278
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F9A4
    .string "FIVE STAR$", 12
    .2byte 10 @ in decimeters
    .2byte 108 @ in hectograms
    .4byte Text2_844895E
    .4byte Text2_84489C5
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F9C8
    .string "FIVE STAR$", 12
    .2byte 14 @ in decimeters
    .2byte 356 @ in hectograms
    .4byte Text2_84489C6
    .4byte Text2_8448A1F
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844F9EC
    .string "STRING SPIT$", 12
    .2byte 5 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text2_8448A20
    .4byte Text2_8448A87
    .2byte 0 @ unused
    .2byte 414
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FA10
    .string "LONG LEG$", 12
    .2byte 11 @ in decimeters
    .2byte 335 @ in hectograms
    .4byte Text2_8448A88
    .4byte Text2_8448AEF
    .2byte 0 @ unused
    .2byte 316
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FA34
    .string "BAT$", 12
    .2byte 18 @ in decimeters
    .2byte 750 @ in hectograms
    .4byte Text2_8448AF0
    .4byte Text2_8448B55
    .2byte 0 @ unused
    .2byte 279
    .2byte -1
    .2byte 313
    .2byte 2
    .2byte 0 @ padding

    @ 844FA58
    .string "ANGLER$", 12
    .2byte 5 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text2_8448B56
    .4byte Text2_8448BBD
    .2byte 0 @ unused
    .2byte 424
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FA7C
    .string "LIGHT$", 12
    .2byte 12 @ in decimeters
    .2byte 225 @ in hectograms
    .4byte Text2_8448BBE
    .4byte Text2_8448C29
    .2byte 0 @ unused
    .2byte 269
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FAA0
    .string "TINY MOUSE$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text2_8448C2A
    .4byte Text2_8448C86
    .2byte 0 @ unused
    .2byte 508
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FAC4
    .string "STAR SHAPE$", 12
    .2byte 3 @ in decimeters
    .2byte 30 @ in hectograms
    .4byte Text2_8448C87
    .4byte Text2_8448CE2
    .2byte 0 @ unused
    .2byte 462
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FAE8
    .string "BALLOON$", 12
    .2byte 3 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text2_8448CE3
    .4byte Text2_8448D45
    .2byte 0 @ unused
    .2byte 457
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB0C
    .string "SPIKE BALL$", 12
    .2byte 3 @ in decimeters
    .2byte 15 @ in hectograms
    .4byte Text2_8448D46
    .4byte Text2_8448DAA
    .2byte 0 @ unused
    .2byte 507
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB30
    .string "HAPPINESS$", 12
    .2byte 6 @ in decimeters
    .2byte 32 @ in hectograms
    .4byte Text2_8448DAB
    .4byte Text2_8448E0A
    .2byte 0 @ unused
    .2byte 424
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB54
    .string "TINY BIRD$", 12
    .2byte 2 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text2_8448E0B
    .4byte Text2_8448E75
    .2byte 0 @ unused
    .2byte 610
    .2byte 23
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FB78
    .string "MYSTIC$", 12
    .2byte 15 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text2_8448E76
    .4byte Text2_8448EDD
    .2byte 0 @ unused
    .2byte 258
    .2byte 4
    .2byte 317
    .2byte 3
    .2byte 0 @ padding

    @ 844FB9C
    .string "WOOL$", 12
    .2byte 6 @ in decimeters
    .2byte 78 @ in hectograms
    .4byte Text2_8448EDE
    .4byte Text2_8448F42
    .2byte 0 @ unused
    .2byte 379
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FBC0
    .string "WOOL$", 12
    .2byte 8 @ in decimeters
    .2byte 133 @ in hectograms
    .4byte Text2_8448F43
    .4byte Text2_8448FA7
    .2byte 0 @ unused
    .2byte 372
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FBE4
    .string "LIGHT$", 12
    .2byte 14 @ in decimeters
    .2byte 615 @ in hectograms
    .4byte Text2_8448FA8
    .4byte Text2_844900B
    .2byte 0 @ unused
    .2byte 275
    .2byte 2
    .2byte 283
    .2byte -1
    .2byte 0 @ padding

    @ 844FC08
    .string "FLOWER$", 12
    .2byte 4 @ in decimeters
    .2byte 58 @ in hectograms
    .4byte Text2_844900C
    .4byte Text2_8449072
    .2byte 0 @ unused
    .2byte 472
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FC2C
    .string "AQUA MOUSE$", 12
    .2byte 4 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text2_8449073
    .4byte Text2_84490D6
    .2byte 0 @ unused
    .2byte 476
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FC50
    .string "AQUA RABBIT$", 12
    .2byte 8 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte Text2_84490D7
    .4byte Text2_8449136
    .2byte 0 @ unused
    .2byte 448
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FC74
    .string "IMITATION$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte Text2_8449137
    .4byte Text2_844919E
    .2byte 0 @ unused
    .2byte 305
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FC98
    .string "FROG$", 12
    .2byte 11 @ in decimeters
    .2byte 339 @ in hectograms
    .4byte Text2_844919F
    .4byte Text2_84491FB
    .2byte 0 @ unused
    .2byte 289
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FCBC
    .string "COTTONWEED$", 12
    .2byte 4 @ in decimeters
    .2byte 5 @ in hectograms
    .4byte Text2_84491FC
    .4byte Text2_8449266
    .2byte 0 @ unused
    .2byte 562
    .2byte -7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FCE0
    .string "COTTONWEED$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text2_8449267
    .4byte Text2_84492C0
    .2byte 0 @ unused
    .2byte 387
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FD04
    .string "COTTONWEED$", 12
    .2byte 8 @ in decimeters
    .2byte 30 @ in hectograms
    .4byte Text2_84492C1
    .4byte Text2_8449326
    .2byte 0 @ unused
    .2byte 418
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FD28
    .string "LONG TAIL$", 12
    .2byte 8 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text2_8449327
    .4byte Text2_8449387
    .2byte 0 @ unused
    .2byte 363
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FD4C
    .string "SEED$", 12
    .2byte 3 @ in decimeters
    .2byte 18 @ in hectograms
    .4byte Text2_8449388
    .4byte Text2_84493EB
    .2byte 0 @ unused
    .2byte 541
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FD70
    .string "SUN$", 12
    .2byte 8 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text2_84493EC
    .4byte Text2_8449454
    .2byte 0 @ unused
    .2byte 374
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FD94
    .string "CLEAR WING$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte Text2_8449455
    .4byte Text2_84494BB
    .2byte 0 @ unused
    .2byte 274
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FDB8
    .string "WATER FISH$", 12
    .2byte 4 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte Text2_84494BC
    .4byte Text2_8449524
    .2byte 0 @ unused
    .2byte 479
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FDDC
    .string "WATER FISH$", 12
    .2byte 14 @ in decimeters
    .2byte 750 @ in hectograms
    .4byte Text2_8449525
    .4byte Text2_8449585
    .2byte 0 @ unused
    .2byte 273
    .2byte 4
    .2byte 273
    .2byte -2
    .2byte 0 @ padding

    @ 844FE00
    .string "SUN$", 12
    .2byte 9 @ in decimeters
    .2byte 265 @ in hectograms
    .4byte Text2_8449586
    .4byte Text2_84495E8
    .2byte 0 @ unused
    .2byte 363
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FE24
    .string "MOONLIGHT$", 12
    .2byte 10 @ in decimeters
    .2byte 270 @ in hectograms
    .4byte Text2_84495E9
    .4byte Text2_8449641
    .2byte 0 @ unused
    .2byte 317
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FE48
    .string "DARKNESS$", 12
    .2byte 5 @ in decimeters
    .2byte 21 @ in hectograms
    .4byte Text2_8449642
    .4byte Text2_84496A3
    .2byte 0 @ unused
    .2byte 401
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FE6C
    .string "ROYAL$", 12
    .2byte 20 @ in decimeters
    .2byte 795 @ in hectograms
    .4byte Text2_84496A4
    .4byte Text2_8449706
    .2byte 0 @ unused
    .2byte 265
    .2byte -1
    .2byte 330
    .2byte 4
    .2byte 0 @ padding

    @ 844FE90
    .string "SCREECH$", 12
    .2byte 7 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text2_8449707
    .4byte Text2_8449766
    .2byte 0 @ unused
    .2byte 407
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FEB4
    .string "SYMBOL$", 12
    .2byte 5 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text2_8449767
    .4byte Text2_84497CB
    .2byte 0 @ unused
    .2byte 411
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FED8
    .string "PATIENT$", 12
    .2byte 13 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte Text2_84497CC
    .4byte Text2_8449826
    .2byte 0 @ unused
    .2byte 274
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FEFC
    .string "LONG NECK$", 12
    .2byte 15 @ in decimeters
    .2byte 415 @ in hectograms
    .4byte Text2_8449827
    .4byte Text2_844988D
    .2byte 0 @ unused
    .2byte 281
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FF20
    .string "BAGWORM$", 12
    .2byte 6 @ in decimeters
    .2byte 72 @ in hectograms
    .4byte Text2_844988E
    .4byte Text2_84498F4
    .2byte 0 @ unused
    .2byte 445
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FF44
    .string "BAGWORM$", 12
    .2byte 12 @ in decimeters
    .2byte 1258 @ in hectograms
    .4byte Text2_84498F5
    .4byte Text2_8449959
    .2byte 0 @ unused
    .2byte 293
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FF68
    .string "LAND SNAKE$", 12
    .2byte 15 @ in decimeters
    .2byte 140 @ in hectograms
    .4byte Text2_844995A
    .4byte Text2_84499B9
    .2byte 0 @ unused
    .2byte 284
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FF8C
    .string "FLYSCORPION$", 12
    .2byte 11 @ in decimeters
    .2byte 648 @ in hectograms
    .4byte Text2_84499BA
    .4byte Text2_8449A1C
    .2byte 0 @ unused
    .2byte 350
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FFB0
    .string "IRON SNAKE$", 12
    .2byte 92 @ in decimeters
    .2byte 4000 @ in hectograms
    .4byte Text2_8449A1D
    .4byte Text2_8449A7E
    .2byte 0 @ unused
    .2byte 278
    .2byte -1
    .2byte 557
    .2byte 13
    .2byte 0 @ padding

    @ 844FFD4
    .string "FAIRY$", 12
    .2byte 6 @ in decimeters
    .2byte 78 @ in hectograms
    .4byte Text2_8449A7F
    .4byte Text2_8449AE4
    .2byte 0 @ unused
    .2byte 465
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 844FFF8
    .string "FAIRY$", 12
    .2byte 14 @ in decimeters
    .2byte 487 @ in hectograms
    .4byte Text2_8449AE5
    .4byte Text2_8449B45
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845001C
    .string "BALLOON$", 12
    .2byte 5 @ in decimeters
    .2byte 39 @ in hectograms
    .4byte Text2_8449B46
    .4byte Text2_8449BAE
    .2byte 0 @ unused
    .2byte 430
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450040
    .string "PINCER$", 12
    .2byte 18 @ in decimeters
    .2byte 1180 @ in hectograms
    .4byte Text2_8449BAF
    .4byte Text2_8449C15
    .2byte 0 @ unused
    .2byte 282
    .2byte 0
    .2byte 282
    .2byte 0
    .2byte 0 @ padding

    @ 8450064
    .string "MOLD$", 12
    .2byte 6 @ in decimeters
    .2byte 205 @ in hectograms
    .4byte Text2_8449C16
    .4byte Text2_8449C67
    .2byte 0 @ unused
    .2byte 485
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450088
    .string "SINGLE HORN$", 12
    .2byte 15 @ in decimeters
    .2byte 540 @ in hectograms
    .4byte Text2_8449C68
    .4byte Text2_8449CCE
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 283
    .2byte -2
    .2byte 0 @ padding

    @ 84500AC
    .string "SHARP CLAW$", 12
    .2byte 9 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text2_8449CCF
    .4byte Text2_8449D30
    .2byte 0 @ unused
    .2byte 413
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84500D0
    .string "LITTLE BEAR$", 12
    .2byte 6 @ in decimeters
    .2byte 88 @ in hectograms
    .4byte Text2_8449D31
    .4byte Text2_8449D9A
    .2byte 0 @ unused
    .2byte 455
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84500F4
    .string "HIBERNATOR$", 12
    .2byte 18 @ in decimeters
    .2byte 1258 @ in hectograms
    .4byte Text2_8449D9B
    .4byte Text2_8449E03
    .2byte 0 @ unused
    .2byte 275
    .2byte 0
    .2byte 280
    .2byte 0
    .2byte 0 @ padding

    @ 8450118
    .string "LAVA$", 12
    .2byte 7 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte Text2_8449E04
    .4byte Text2_8449E68
    .2byte 0 @ unused
    .2byte 329
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845013C
    .string "LAVA$", 12
    .2byte 8 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text2_8449E69
    .4byte Text2_8449ED0
    .2byte 0 @ unused
    .2byte 332
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450160
    .string "PIG$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte Text2_8449ED1
    .4byte Text2_8449F2E
    .2byte 0 @ unused
    .2byte 324
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450184
    .string "SWINE$", 12
    .2byte 11 @ in decimeters
    .2byte 558 @ in hectograms
    .4byte Text2_8449F2F
    .4byte Text2_8449F8E
    .2byte 0 @ unused
    .2byte 306
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84501A8
    .string "CORAL$", 12
    .2byte 6 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text2_8449F8F
    .4byte Text2_8449FEC
    .2byte 0 @ unused
    .2byte 410
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84501CC
    .string "JET$", 12
    .2byte 6 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text2_8449FED
    .4byte Text2_844A053
    .2byte 0 @ unused
    .2byte 316
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84501F0
    .string "JET$", 12
    .2byte 9 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte Text2_844A054
    .4byte Text2_844A0B3
    .2byte 0 @ unused
    .2byte 296
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450214
    .string "DELIVERY$", 12
    .2byte 9 @ in decimeters
    .2byte 160 @ in hectograms
    .4byte Text2_844A0B4
    .4byte Text2_844A117
    .2byte 0 @ unused
    .2byte 293
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450238
    .string "KITE$", 12
    .2byte 21 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte Text2_844A118
    .4byte Text2_844A17A
    .2byte 0 @ unused
    .2byte 275
    .2byte 0
    .2byte 360
    .2byte 6
    .2byte 0 @ padding

    @ 845025C
    .string "ARMOR BIRD$", 12
    .2byte 17 @ in decimeters
    .2byte 505 @ in hectograms
    .4byte Text2_844A17B
    .4byte Text2_844A1E2
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 276
    .2byte 0
    .2byte 0 @ padding

    @ 8450280
    .string "DARK$", 12
    .2byte 6 @ in decimeters
    .2byte 108 @ in hectograms
    .4byte Text2_844A1E3
    .4byte Text2_844A245
    .2byte 0 @ unused
    .2byte 393
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84502A4
    .string "DARK$", 12
    .2byte 14 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte Text2_844A246
    .4byte Text2_844A29D
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84502C8
    .string "DRAGON$", 12
    .2byte 18 @ in decimeters
    .2byte 1520 @ in hectograms
    .4byte Text2_844A29E
    .4byte Text2_844A2F9
    .2byte 0 @ unused
    .2byte 257
    .2byte 1
    .2byte 293
    .2byte 1
    .2byte 0 @ padding

    @ 84502EC
    .string "LONG NOSE$", 12
    .2byte 5 @ in decimeters
    .2byte 335 @ in hectograms
    .4byte Text2_844A2FA
    .4byte Text2_844A359
    .2byte 0 @ unused
    .2byte 465
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450310
    .string "ARMOR$", 12
    .2byte 11 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text2_844A35A
    .4byte Text2_844A3B9
    .2byte 0 @ unused
    .2byte 313
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450334
    .string "VIRTUAL$", 12
    .2byte 6 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte Text2_844A3BA
    .4byte Text2_844A41A
    .2byte 0 @ unused
    .2byte 320
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450358
    .string "BIG HORN$", 12
    .2byte 14 @ in decimeters
    .2byte 712 @ in hectograms
    .4byte Text2_844A41B
    .4byte Text2_844A482
    .2byte 0 @ unused
    .2byte 277
    .2byte -1
    .2byte 277
    .2byte 0
    .2byte 0 @ padding

    @ 845037C
    .string "PAINTER$", 12
    .2byte 12 @ in decimeters
    .2byte 580 @ in hectograms
    .4byte Text2_844A483
    .4byte Text2_844A4E9
    .2byte 0 @ unused
    .2byte 287
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84503A0
    .string "SCUFFLE$", 12
    .2byte 7 @ in decimeters
    .2byte 210 @ in hectograms
    .4byte Text2_844A4EA
    .4byte Text2_844A54D
    .2byte 0 @ unused
    .2byte 292
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84503C4
    .string "HANDSTAND$", 12
    .2byte 14 @ in decimeters
    .2byte 480 @ in hectograms
    .4byte Text2_844A54E
    .4byte Text2_844A5AA
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 257
    .2byte -2
    .2byte 0 @ padding

    @ 84503E8
    .string "KISS$", 12
    .2byte 4 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte Text2_844A5AB
    .4byte Text2_844A60F
    .2byte 0 @ unused
    .2byte 440
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845040C
    .string "ELECTRIC$", 12
    .2byte 6 @ in decimeters
    .2byte 235 @ in hectograms
    .4byte Text2_844A610
    .4byte Text2_844A676
    .2byte 0 @ unused
    .2byte 363
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450430
    .string "LIVE COAL$", 12
    .2byte 7 @ in decimeters
    .2byte 214 @ in hectograms
    .4byte Text2_844A677
    .4byte Text2_844A6D5
    .2byte 0 @ unused
    .2byte 284
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450454
    .string "MILK COW$", 12
    .2byte 12 @ in decimeters
    .2byte 755 @ in hectograms
    .4byte Text2_844A6D6
    .4byte Text2_844A730
    .2byte 0 @ unused
    .2byte 280
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450478
    .string "HAPPINESS$", 12
    .2byte 15 @ in decimeters
    .2byte 468 @ in hectograms
    .4byte Text2_844A731
    .4byte Text2_844A796
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 310
    .2byte 3
    .2byte 0 @ padding

    @ 845049C
    .string "THUNDER$", 12
    .2byte 19 @ in decimeters
    .2byte 1780 @ in hectograms
    .4byte Text2_844A797
    .4byte Text2_844A7FF
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 359
    .2byte 6
    .2byte 0 @ padding

    @ 84504C0
    .string "VOLCANO$", 12
    .2byte 21 @ in decimeters
    .2byte 1980 @ in hectograms
    .4byte Text2_844A800
    .4byte Text2_844A868
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 370
    .2byte 7
    .2byte 0 @ padding

    @ 84504E4
    .string "AURORA$", 12
    .2byte 20 @ in decimeters
    .2byte 1870 @ in hectograms
    .4byte Text2_844A869
    .4byte Text2_844A8C3
    .2byte 0 @ unused
    .2byte 286
    .2byte 0
    .2byte 371
    .2byte 7
    .2byte 0 @ padding

    @ 8450508
    .string "ROCK SKIN$", 12
    .2byte 6 @ in decimeters
    .2byte 720 @ in hectograms
    .4byte Text2_844A8C4
    .4byte Text2_844A91F
    .2byte 0 @ unused
    .2byte 472
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845052C
    .string "HARD SHELL$", 12
    .2byte 12 @ in decimeters
    .2byte 1520 @ in hectograms
    .4byte Text2_844A920
    .4byte Text2_844A985
    .2byte 0 @ unused
    .2byte 292
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450550
    .string "ARMOR$", 12
    .2byte 20 @ in decimeters
    .2byte 2020 @ in hectograms
    .4byte Text2_844A986
    .4byte Text2_844A9EE
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 383
    .2byte 7
    .2byte 0 @ padding

    @ 8450574
    .string "DIVING$", 12
    .2byte 52 @ in decimeters
    .2byte 2160 @ in hectograms
    .4byte Text2_844A9EF
    .4byte Text2_844AA5B
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 742
    .2byte 18
    .2byte 0 @ padding

    @ 8450598
    .string "RAINBOW$", 12
    .2byte 38 @ in decimeters
    .2byte 1990 @ in hectograms
    .4byte Text2_844AA5C
    .4byte Text2_844AAC4
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 620
    .2byte 16
    .2byte 0 @ padding

    @ 84505BC
    .string "TIME TRAVEL$", 12
    .2byte 6 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text2_844AAC5
    .4byte Text2_844AB29
    .2byte 0 @ unused
    .2byte 393
    .2byte -10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84505E0
    .string "WOOD GECKO$", 12
    .2byte 5 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text2_844AB2A
    .4byte Text2_844AB95
    .2byte 0 @ unused
    .2byte 541
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450604
    .string "WOOD GECKO$", 12
    .2byte 9 @ in decimeters
    .2byte 216 @ in hectograms
    .4byte Text2_844AB96
    .4byte Text2_844ABEF
    .2byte 0 @ unused
    .2byte 360
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450628
    .string "FOREST$", 12
    .2byte 17 @ in decimeters
    .2byte 522 @ in hectograms
    .4byte Text2_844ABF0
    .4byte Text2_844AC5B
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 313
    .2byte 3
    .2byte 0 @ padding

    @ 845064C
    .string "CHICK$", 12
    .2byte 4 @ in decimeters
    .2byte 25 @ in hectograms
    .4byte Text2_844AC5C
    .4byte Text2_844ACB7
    .2byte 0 @ unused
    .2byte 566
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450670
    .string "YOUNG FOWL$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte Text2_844ACB8
    .4byte Text2_844AD1B
    .2byte 0 @ unused
    .2byte 343
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450694
    .string "BLAZE$", 12
    .2byte 19 @ in decimeters
    .2byte 520 @ in hectograms
    .4byte Text2_844AD1C
    .4byte Text2_844AD8B
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 314
    .2byte 3
    .2byte 0 @ padding

    @ 84506B8
    .string "MUD FISH$", 12
    .2byte 4 @ in decimeters
    .2byte 76 @ in hectograms
    .4byte Text2_844AD8C
    .4byte Text2_844ADF7
    .2byte 0 @ unused
    .2byte 535
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84506DC
    .string "MUD FISH$", 12
    .2byte 7 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text2_844ADF8
    .4byte Text2_844AE60
    .2byte 0 @ unused
    .2byte 340
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450700
    .string "MUD FISH$", 12
    .2byte 15 @ in decimeters
    .2byte 819 @ in hectograms
    .4byte Text2_844AE61
    .4byte Text2_844AECF
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 282
    .2byte -2
    .2byte 0 @ padding

    @ 8450724
    .string "BITE$", 12
    .2byte 5 @ in decimeters
    .2byte 136 @ in hectograms
    .4byte Text2_844AED0
    .4byte Text2_844AF40
    .2byte 0 @ unused
    .2byte 481
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450748
    .string "BITE$", 12
    .2byte 10 @ in decimeters
    .2byte 370 @ in hectograms
    .4byte Text2_844AF41
    .4byte Text2_844AFB7
    .2byte 0 @ unused
    .2byte 359
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845076C
    .string "TINYRACCOON$", 12
    .2byte 4 @ in decimeters
    .2byte 175 @ in hectograms
    .4byte Text2_844AFB8
    .4byte Text2_844B01B
    .2byte 0 @ unused
    .2byte 560
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450790
    .string "RUSHING$", 12
    .2byte 5 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte Text2_844B01C
    .4byte Text2_844B08B
    .2byte 0 @ unused
    .2byte 321
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84507B4
    .string "WORM$", 12
    .2byte 3 @ in decimeters
    .2byte 36 @ in hectograms
    .4byte Text2_844B08C
    .4byte Text2_844B0FD
    .2byte 0 @ unused
    .2byte 711
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84507D8
    .string "COCOON$", 12
    .2byte 6 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte Text2_844B0FE
    .4byte Text2_844B173
    .2byte 0 @ unused
    .2byte 431
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84507FC
    .string "BUTTERFLY$", 12
    .2byte 10 @ in decimeters
    .2byte 284 @ in hectograms
    .4byte Text2_844B174
    .4byte Text2_844B1DA
    .2byte 0 @ unused
    .2byte 298
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450820
    .string "COCOON$", 12
    .2byte 7 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text2_844B1DB
    .4byte Text2_844B23B
    .2byte 0 @ unused
    .2byte 391
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450844
    .string "POISON MOTH$", 12
    .2byte 12 @ in decimeters
    .2byte 316 @ in hectograms
    .4byte Text2_844B23C
    .4byte Text2_844B2AC
    .2byte 0 @ unused
    .2byte 269
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450868
    .string "WATER WEED$", 12
    .2byte 5 @ in decimeters
    .2byte 26 @ in hectograms
    .4byte Text2_844B2AD
    .4byte Text2_844B315
    .2byte 0 @ unused
    .2byte 406
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845088C
    .string "JOLLY$", 12
    .2byte 12 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte Text2_844B316
    .4byte Text2_844B38C
    .2byte 0 @ unused
    .2byte 277
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84508B0
    .string "CAREFREE$", 12
    .2byte 15 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte Text2_844B38D
    .4byte Text2_844B3E6
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 282
    .2byte 0
    .2byte 0 @ padding

    @ 84508D4
    .string "ACORN$", 12
    .2byte 5 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte Text2_844B3E7
    .4byte Text2_844B45C
    .2byte 0 @ unused
    .2byte 472
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84508F8
    .string "WILY$", 12
    .2byte 10 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text2_844B45D
    .4byte Text2_844B4C5
    .2byte 0 @ unused
    .2byte 299
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845091C
    .string "WICKED$", 12
    .2byte 13 @ in decimeters
    .2byte 596 @ in hectograms
    .4byte Text2_844B4C6
    .4byte Text2_844B52D
    .2byte 0 @ unused
    .2byte 290
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450940
    .string "TINYSWALLOW$", 12
    .2byte 3 @ in decimeters
    .2byte 23 @ in hectograms
    .4byte Text2_844B52E
    .4byte Text2_844B596
    .2byte 0 @ unused
    .2byte 465
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450964
    .string "SWALLOW$", 12
    .2byte 7 @ in decimeters
    .2byte 198 @ in hectograms
    .4byte Text2_844B597
    .4byte Text2_844B606
    .2byte 0 @ unused
    .2byte 428
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450988
    .string "SEAGULL$", 12
    .2byte 6 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte Text2_844B607
    .4byte Text2_844B667
    .2byte 0 @ unused
    .2byte 295
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84509AC
    .string "WATER BIRD$", 12
    .2byte 12 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte Text2_844B668
    .4byte Text2_844B6D3
    .2byte 0 @ unused
    .2byte 288
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84509D0
    .string "FEELING$", 12
    .2byte 4 @ in decimeters
    .2byte 66 @ in hectograms
    .4byte Text2_844B6D4
    .4byte Text2_844B731
    .2byte 0 @ unused
    .2byte 457
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84509F4
    .string "EMOTION$", 12
    .2byte 8 @ in decimeters
    .2byte 202 @ in hectograms
    .4byte Text2_844B732
    .4byte Text2_844B7A2
    .2byte 0 @ unused
    .2byte 354
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450A18
    .string "EMBRACE$", 12
    .2byte 16 @ in decimeters
    .2byte 484 @ in hectograms
    .4byte Text2_844B7A3
    .4byte Text2_844B7FE
    .2byte 0 @ unused
    .2byte 277
    .2byte 0
    .2byte 276
    .2byte -1
    .2byte 0 @ padding

    @ 8450A3C
    .string "POND SKATER$", 12
    .2byte 5 @ in decimeters
    .2byte 17 @ in hectograms
    .4byte Text2_844B7FF
    .4byte Text2_844B85D
    .2byte 0 @ unused
    .2byte 375
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450A60
    .string "EYEBALL$", 12
    .2byte 8 @ in decimeters
    .2byte 36 @ in hectograms
    .4byte Text2_844B85E
    .4byte Text2_844B8D4
    .2byte 0 @ unused
    .2byte 378
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450A84
    .string "MUSHROOM$", 12
    .2byte 4 @ in decimeters
    .2byte 45 @ in hectograms
    .4byte Text2_844B8D5
    .4byte Text2_844B942
    .2byte 0 @ unused
    .2byte 513
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450AA8
    .string "MUSHROOM$", 12
    .2byte 12 @ in decimeters
    .2byte 392 @ in hectograms
    .4byte Text2_844B943
    .4byte Text2_844B9AF
    .2byte 0 @ unused
    .2byte 324
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450ACC
    .string "SLACKER$", 12
    .2byte 8 @ in decimeters
    .2byte 240 @ in hectograms
    .4byte Text2_844B9B0
    .4byte Text2_844BA0B
    .2byte 0 @ unused
    .2byte 291
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450AF0
    .string "WILD MONKEY$", 12
    .2byte 14 @ in decimeters
    .2byte 465 @ in hectograms
    .4byte Text2_844BA0C
    .4byte Text2_844BA6F
    .2byte 0 @ unused
    .2byte 301
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450B14
    .string "LAZY$", 12
    .2byte 20 @ in decimeters
    .2byte 1305 @ in hectograms
    .4byte Text2_844BA70
    .4byte Text2_844BAE9
    .2byte 0 @ unused
    .2byte 277
    .2byte 5
    .2byte 326
    .2byte 3
    .2byte 0 @ padding

    @ 8450B38
    .string "TRAINEE$", 12
    .2byte 5 @ in decimeters
    .2byte 55 @ in hectograms
    .4byte Text2_844BAEA
    .4byte Text2_844BB4A
    .2byte 0 @ unused
    .2byte 405
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450B5C
    .string "NINJA$", 12
    .2byte 8 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte Text2_844BB4B
    .4byte Text2_844BBAE
    .2byte 0 @ unused
    .2byte 383
    .2byte -9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450B80
    .string "SHED$", 12
    .2byte 8 @ in decimeters
    .2byte 12 @ in hectograms
    .4byte Text2_844BBAF
    .4byte Text2_844BC03
    .2byte 0 @ unused
    .2byte 372
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450BA4
    .string "WHISPER$", 12
    .2byte 6 @ in decimeters
    .2byte 163 @ in hectograms
    .4byte Text2_844BC04
    .4byte Text2_844BC6D
    .2byte 0 @ unused
    .2byte 373
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450BC8
    .string "BIG VOICE$", 12
    .2byte 10 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte Text2_844BC6E
    .4byte Text2_844BCCE
    .2byte 0 @ unused
    .2byte 356
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450BEC
    .string "LOUD NOISE$", 12
    .2byte 15 @ in decimeters
    .2byte 840 @ in hectograms
    .4byte Text2_844BCCF
    .4byte Text2_844BD45
    .2byte 0 @ unused
    .2byte 284
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450C10
    .string "GUTS$", 12
    .2byte 10 @ in decimeters
    .2byte 864 @ in hectograms
    .4byte Text2_844BD46
    .4byte Text2_844BDA9
    .2byte 0 @ unused
    .2byte 256
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450C34
    .string "ARM THRUST$", 12
    .2byte 23 @ in decimeters
    .2byte 2538 @ in hectograms
    .4byte Text2_844BDAA
    .4byte Text2_844BE0F
    .2byte 0 @ unused
    .2byte 268
    .2byte -1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding

    @ 8450C58
    .string "POLKA DOT$", 12
    .2byte 2 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text2_844BE10
    .4byte Text2_844BE80
    .2byte 0 @ unused
    .2byte 603
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450C7C
    .string "COMPASS$", 12
    .2byte 10 @ in decimeters
    .2byte 970 @ in hectograms
    .4byte Text2_844BE81
    .4byte Text2_844BEDD
    .2byte 0 @ unused
    .2byte 256
    .2byte 9
    .2byte 289
    .2byte 1
    .2byte 0 @ padding

    @ 8450CA0
    .string "KITTEN$", 12
    .2byte 6 @ in decimeters
    .2byte 110 @ in hectograms
    .4byte Text2_844BEDE
    .4byte Text2_844BF4E
    .2byte 0 @ unused
    .2byte 492
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450CC4
    .string "PRIM$", 12
    .2byte 11 @ in decimeters
    .2byte 326 @ in hectograms
    .4byte Text2_844BF4F
    .4byte Text2_844BFB6
    .2byte 0 @ unused
    .2byte 322
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450CE8
    .string "DARKNESS$", 12
    .2byte 5 @ in decimeters
    .2byte 110 @ in hectograms
    .4byte Text2_844BFB7
    .4byte Text2_844C010
    .2byte 0 @ unused
    .2byte 451
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450D0C
    .string "DECEIVER$", 12
    .2byte 6 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text2_844C011
    .4byte Text2_844C07B
    .2byte 0 @ unused
    .2byte 466
    .2byte 15
    .2byte 256
    .2byte -3
    .2byte 0 @ padding

    @ 8450D30
    .string "IRON ARMOR$", 12
    .2byte 4 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text2_844C07C
    .4byte Text2_844C0ED
    .2byte 0 @ unused
    .2byte 419
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450D54
    .string "IRON ARMOR$", 12
    .2byte 9 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte Text2_844C0EE
    .4byte Text2_844C15F
    .2byte 0 @ unused
    .2byte 275
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450D78
    .string "IRON ARMOR$", 12
    .2byte 21 @ in decimeters
    .2byte 3600 @ in hectograms
    .4byte Text2_844C160
    .4byte Text2_844C1C8
    .2byte 0 @ unused
    .2byte 274
    .2byte -1
    .2byte 374
    .2byte 7
    .2byte 0 @ padding

    @ 8450D9C
    .string "MEDITATE$", 12
    .2byte 6 @ in decimeters
    .2byte 112 @ in hectograms
    .4byte Text2_844C1C9
    .4byte Text2_844C225
    .2byte 0 @ unused
    .2byte 465
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450DC0
    .string "MEDITATE$", 12
    .2byte 13 @ in decimeters
    .2byte 315 @ in hectograms
    .4byte Text2_844C226
    .4byte Text2_844C28F
    .2byte 0 @ unused
    .2byte 298
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450DE4
    .string "LIGHTNING$", 12
    .2byte 6 @ in decimeters
    .2byte 152 @ in hectograms
    .4byte Text2_844C290
    .4byte Text2_844C2F4
    .2byte 0 @ unused
    .2byte 290
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E08
    .string "DISCHARGE$", 12
    .2byte 15 @ in decimeters
    .2byte 402 @ in hectograms
    .4byte Text2_844C2F5
    .4byte Text2_844C345
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 257
    .2byte -2
    .2byte 0 @ padding

    @ 8450E2C
    .string "CHEERING$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte Text2_844C346
    .4byte Text2_844C3B4
    .2byte 0 @ unused
    .2byte 515
    .2byte -9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E50
    .string "CHEERING$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte Text2_844C3B5
    .4byte Text2_844C431
    .2byte 0 @ unused
    .2byte 512
    .2byte -7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E74
    .string "FIREFLY$", 12
    .2byte 7 @ in decimeters
    .2byte 177 @ in hectograms
    .4byte Text2_844C432
    .4byte Text2_844C49D
    .2byte 0 @ unused
    .2byte 442
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450E98
    .string "FIREFLY$", 12
    .2byte 6 @ in decimeters
    .2byte 177 @ in hectograms
    .4byte Text2_844C49E
    .4byte Text2_844C507
    .2byte 0 @ unused
    .2byte 572
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450EBC
    .string "THORN$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte Text2_844C508
    .4byte Text2_844C569
    .2byte 0 @ unused
    .2byte 677
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450EE0
    .string "STOMACH$", 12
    .2byte 4 @ in decimeters
    .2byte 103 @ in hectograms
    .4byte Text2_844C56A
    .4byte Text2_844C5D3
    .2byte 0 @ unused
    .2byte 593
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450F04
    .string "POISON BAG$", 12
    .2byte 17 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte Text2_844C5D4
    .4byte Text2_844C63C
    .2byte 0 @ unused
    .2byte 256
    .2byte 5
    .2byte 345
    .2byte 4
    .2byte 0 @ padding

    @ 8450F28
    .string "SAVAGE$", 12
    .2byte 8 @ in decimeters
    .2byte 208 @ in hectograms
    .4byte Text2_844C63D
    .4byte Text2_844C69E
    .2byte 0 @ unused
    .2byte 362
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450F4C
    .string "BRUTAL$", 12
    .2byte 18 @ in decimeters
    .2byte 888 @ in hectograms
    .4byte Text2_844C69F
    .4byte Text2_844C708
    .2byte 0 @ unused
    .2byte 265
    .2byte 0
    .2byte 342
    .2byte 4
    .2byte 0 @ padding

    @ 8450F70
    .string "BALL WHALE$", 12
    .2byte 20 @ in decimeters
    .2byte 1300 @ in hectograms
    .4byte Text2_844C709
    .4byte Text2_844C777
    .2byte 0 @ unused
    .2byte 256
    .2byte 10
    .2byte 493
    .2byte 10
    .2byte 0 @ padding

    @ 8450F94
    .string "FLOAT WHALE$", 12
    .2byte 145 @ in decimeters
    .2byte 3980 @ in hectograms
    .4byte Text2_844C778
    .4byte Text2_844C7E3
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 1428
    .2byte 20
    .2byte 0 @ padding

    @ 8450FB8
    .string "NUMB$", 12
    .2byte 7 @ in decimeters
    .2byte 240 @ in hectograms
    .4byte Text2_844C7E4
    .4byte Text2_844C85B
    .2byte 0 @ unused
    .2byte 310
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8450FDC
    .string "ERUPTION$", 12
    .2byte 19 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte Text2_844C85C
    .4byte Text2_844C8C6
    .2byte 0 @ unused
    .2byte 256
    .2byte 6
    .2byte 345
    .2byte 4
    .2byte 0 @ padding

    @ 8451000
    .string "COAL$", 12
    .2byte 5 @ in decimeters
    .2byte 804 @ in hectograms
    .4byte Text2_844C8C7
    .4byte Text2_844C923
    .2byte 0 @ unused
    .2byte 392
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451024
    .string "BOUNCE$", 12
    .2byte 7 @ in decimeters
    .2byte 306 @ in hectograms
    .4byte Text2_844C924
    .4byte Text2_844C981
    .2byte 0 @ unused
    .2byte 423
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451048
    .string "MANIPULATE$", 12
    .2byte 9 @ in decimeters
    .2byte 715 @ in hectograms
    .4byte Text2_844C982
    .4byte Text2_844C9EE
    .2byte 0 @ unused
    .2byte 358
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845106C
    .string "SPOT PANDA$", 12
    .2byte 11 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte Text2_844C9EF
    .4byte Text2_844CA4F
    .2byte 0 @ unused
    .2byte 321
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451090
    .string "ANT PIT$", 12
    .2byte 7 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text2_844CA50
    .4byte Text2_844CAAE
    .2byte 0 @ unused
    .2byte 298
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84510B4
    .string "VIBRATION$", 12
    .2byte 11 @ in decimeters
    .2byte 153 @ in hectograms
    .4byte Text2_844CAAF
    .4byte Text2_844CB28
    .2byte 0 @ unused
    .2byte 370
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84510D8
    .string "MYSTIC$", 12
    .2byte 20 @ in decimeters
    .2byte 820 @ in hectograms
    .4byte Text2_844CB29
    .4byte Text2_844CB89
    .2byte 0 @ unused
    .2byte 280
    .2byte 0
    .2byte 299
    .2byte 2
    .2byte 0 @ padding

    @ 84510FC
    .string "CACTUS$", 12
    .2byte 4 @ in decimeters
    .2byte 513 @ in hectograms
    .4byte Text2_844CB8A
    .4byte Text2_844CBF1
    .2byte 0 @ unused
    .2byte 455
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451120
    .string "SCARECROW$", 12
    .2byte 13 @ in decimeters
    .2byte 774 @ in hectograms
    .4byte Text2_844CBF2
    .4byte Text2_844CC5B
    .2byte 0 @ unused
    .2byte 327
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451144
    .string "COTTON BIRD$", 12
    .2byte 4 @ in decimeters
    .2byte 12 @ in hectograms
    .4byte Text2_844CC5C
    .4byte Text2_844CCBF
    .2byte 0 @ unused
    .2byte 422
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451168
    .string "HUMMING$", 12
    .2byte 11 @ in decimeters
    .2byte 206 @ in hectograms
    .4byte Text2_844CCC0
    .4byte Text2_844CD27
    .2byte 0 @ unused
    .2byte 327
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845118C
    .string "CAT FERRET$", 12
    .2byte 13 @ in decimeters
    .2byte 403 @ in hectograms
    .4byte Text2_844CD28
    .4byte Text2_844CD9C
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84511B0
    .string "FANG SNAKE$", 12
    .2byte 27 @ in decimeters
    .2byte 525 @ in hectograms
    .4byte Text2_844CD9D
    .4byte Text2_844CE0F
    .2byte 0 @ unused
    .2byte 275
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84511D4
    .string "METEORITE$", 12
    .2byte 10 @ in decimeters
    .2byte 1680 @ in hectograms
    .4byte Text2_844CE10
    .4byte Text2_844CE80
    .2byte 0 @ unused
    .2byte 300
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84511F8
    .string "METEORITE$", 12
    .2byte 12 @ in decimeters
    .2byte 1540 @ in hectograms
    .4byte Text2_844CE81
    .4byte Text2_844CEE7
    .2byte 0 @ unused
    .2byte 328
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845121C
    .string "WHISKERS$", 12
    .2byte 4 @ in decimeters
    .2byte 19 @ in hectograms
    .4byte Text2_844CEE8
    .4byte Text2_844CF3E
    .2byte 0 @ unused
    .2byte 581
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451240
    .string "WHISKERS$", 12
    .2byte 9 @ in decimeters
    .2byte 236 @ in hectograms
    .4byte Text2_844CF3F
    .4byte Text2_844CFA8
    .2byte 0 @ unused
    .2byte 317
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451264
    .string "RUFFIAN$", 12
    .2byte 6 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte Text2_844CFA9
    .4byte Text2_844D015
    .2byte 0 @ unused
    .2byte 484
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451288
    .string "ROGUE$", 12
    .2byte 11 @ in decimeters
    .2byte 328 @ in hectograms
    .4byte Text2_844D016
    .4byte Text2_844D075
    .2byte 0 @ unused
    .2byte 365
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84512AC
    .string "CLAY DOLL$", 12
    .2byte 5 @ in decimeters
    .2byte 215 @ in hectograms
    .4byte Text2_844D076
    .4byte Text2_844D0E5
    .2byte 0 @ unused
    .2byte 384
    .2byte 18
    .2byte 256
    .2byte -3
    .2byte 0 @ padding

    @ 84512D0
    .string "CLAY DOLL$", 12
    .2byte 15 @ in decimeters
    .2byte 1080 @ in hectograms
    .4byte Text2_844D0E6
    .4byte Text2_844D152
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 280
    .2byte 0
    .2byte 0 @ padding

    @ 84512F4
    .string "SEA LILY$", 12
    .2byte 10 @ in decimeters
    .2byte 238 @ in hectograms
    .4byte Text2_844D153
    .4byte Text2_844D1C0
    .2byte 0 @ unused
    .2byte 305
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451318
    .string "BARNACLE$", 12
    .2byte 15 @ in decimeters
    .2byte 604 @ in hectograms
    .4byte Text2_844D1C1
    .4byte Text2_844D226
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 269
    .2byte -1
    .2byte 0 @ padding

    @ 845133C
    .string "OLD SHRIMP$", 12
    .2byte 7 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte Text2_844D227
    .4byte Text2_844D299
    .2byte 0 @ unused
    .2byte 296
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451360
    .string "PLATE$", 12
    .2byte 15 @ in decimeters
    .2byte 682 @ in hectograms
    .4byte Text2_844D29A
    .4byte Text2_844D2F6
    .2byte 0 @ unused
    .2byte 312
    .2byte 2
    .2byte 271
    .2byte -1
    .2byte 0 @ padding

    @ 8451384
    .string "FISH$", 12
    .2byte 6 @ in decimeters
    .2byte 74 @ in hectograms
    .4byte Text2_844D2F7
    .4byte Text2_844D35F
    .2byte 0 @ unused
    .2byte 423
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84513A8
    .string "TENDER$", 12
    .2byte 62 @ in decimeters
    .2byte 1620 @ in hectograms
    .4byte Text2_844D360
    .4byte Text2_844D3C3
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 382
    .2byte 7
    .2byte 0 @ padding

    @ 84513CC
    .string "WEATHER$", 12
    .2byte 3 @ in decimeters
    .2byte 8 @ in hectograms
    .4byte Text2_844D3C4
    .4byte Text2_844D42E
    .2byte 0 @ unused
    .2byte 435
    .2byte -5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84513F0
    .string "COLOR SWAP$", 12
    .2byte 10 @ in decimeters
    .2byte 220 @ in hectograms
    .4byte Text2_844D42F
    .4byte Text2_844D495
    .2byte 0 @ unused
    .2byte 316
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451414
    .string "PUPPET$", 12
    .2byte 6 @ in decimeters
    .2byte 23 @ in hectograms
    .4byte Text2_844D496
    .4byte Text2_844D4FA
    .2byte 0 @ unused
    .2byte 440
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451438
    .string "MARIONETTE$", 12
    .2byte 11 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte Text2_844D4FB
    .4byte Text2_844D567
    .2byte 0 @ unused
    .2byte 262
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845145C
    .string "REQUIEM$", 12
    .2byte 8 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte Text2_844D568
    .4byte Text2_844D5D0
    .2byte 0 @ unused
    .2byte 376
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451480
    .string "BECKON$", 12
    .2byte 16 @ in decimeters
    .2byte 306 @ in hectograms
    .4byte Text2_844D5D1
    .4byte Text2_844D63A
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 299
    .2byte 2
    .2byte 0 @ padding

    @ 84514A4
    .string "FRUIT$", 12
    .2byte 20 @ in decimeters
    .2byte 1000 @ in hectograms
    .4byte Text2_844D63B
    .4byte Text2_844D6A8
    .2byte 0 @ unused
    .2byte 283
    .2byte -1
    .2byte 371
    .2byte 6
    .2byte 0 @ padding

    @ 84514C8
    .string "WIND CHIME$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte Text2_844D6A9
    .4byte Text2_844D719
    .2byte 0 @ unused
    .2byte 505
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84514EC
    .string "DISASTER$", 12
    .2byte 12 @ in decimeters
    .2byte 470 @ in hectograms
    .4byte Text2_844D71A
    .4byte Text2_844D783
    .2byte 0 @ unused
    .2byte 301
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451510
    .string "BRIGHT$", 12
    .2byte 6 @ in decimeters
    .2byte 140 @ in hectograms
    .4byte Text2_844D784
    .4byte Text2_844D7DE
    .2byte 0 @ unused
    .2byte 453
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451534
    .string "SNOW HAT$", 12
    .2byte 7 @ in decimeters
    .2byte 168 @ in hectograms
    .4byte Text2_844D7DF
    .4byte Text2_844D850
    .2byte 0 @ unused
    .2byte 380
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451558
    .string "FACE$", 12
    .2byte 15 @ in decimeters
    .2byte 2565 @ in hectograms
    .4byte Text2_844D851
    .4byte Text2_844D8BB
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 344
    .2byte 2
    .2byte 0 @ padding

    @ 845157C
    .string "CLAP$", 12
    .2byte 8 @ in decimeters
    .2byte 395 @ in hectograms
    .4byte Text2_844D8BC
    .4byte Text2_844D91E
    .2byte 0 @ unused
    .2byte 315
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84515A0
    .string "BALL ROLL$", 12
    .2byte 11 @ in decimeters
    .2byte 876 @ in hectograms
    .4byte Text2_844D91F
    .4byte Text2_844D988
    .2byte 0 @ unused
    .2byte 338
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84515C4
    .string "ICE BREAK$", 12
    .2byte 14 @ in decimeters
    .2byte 1506 @ in hectograms
    .4byte Text2_844D989
    .4byte Text2_844D9FA
    .2byte 0 @ unused
    .2byte 305
    .2byte 2
    .2byte 277
    .2byte 0
    .2byte 0 @ padding

    @ 84515E8
    .string "BIVALVE$", 12
    .2byte 4 @ in decimeters
    .2byte 525 @ in hectograms
    .4byte Text2_844D9FB
    .4byte Text2_844DA50
    .2byte 0 @ unused
    .2byte 691
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845160C
    .string "DEEP SEA$", 12
    .2byte 17 @ in decimeters
    .2byte 270 @ in hectograms
    .4byte Text2_844DA51
    .4byte Text2_844DAC2
    .2byte 0 @ unused
    .2byte 307
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451630
    .string "SOUTH SEA$", 12
    .2byte 18 @ in decimeters
    .2byte 226 @ in hectograms
    .4byte Text2_844DAC3
    .4byte Text2_844DB30
    .2byte 0 @ unused
    .2byte 278
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451654
    .string "LONGEVITY$", 12
    .2byte 10 @ in decimeters
    .2byte 234 @ in hectograms
    .4byte Text2_844DB31
    .4byte Text2_844DB93
    .2byte 0 @ unused
    .2byte 316
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451678
    .string "RENDEZVOUS$", 12
    .2byte 6 @ in decimeters
    .2byte 87 @ in hectograms
    .4byte Text2_844DB94
    .4byte Text2_844DBF6
    .2byte 0 @ unused
    .2byte 371
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845169C
    .string "ROCK HEAD$", 12
    .2byte 6 @ in decimeters
    .2byte 421 @ in hectograms
    .4byte Text2_844DBF7
    .4byte Text2_844DC55
    .2byte 0 @ unused
    .2byte 448
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84516C0
    .string "ENDURANCE$", 12
    .2byte 11 @ in decimeters
    .2byte 1105 @ in hectograms
    .4byte Text2_844DC56
    .4byte Text2_844DCCD
    .2byte 0 @ unused
    .2byte 311
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84516E4
    .string "DRAGON$", 12
    .2byte 15 @ in decimeters
    .2byte 1026 @ in hectograms
    .4byte Text2_844DCCE
    .4byte Text2_844DD30
    .2byte 0 @ unused
    .2byte 272
    .2byte 2
    .2byte 307
    .2byte 0
    .2byte 0 @ padding

    @ 8451708
    .string "IRON BALL$", 12
    .2byte 6 @ in decimeters
    .2byte 952 @ in hectograms
    .4byte Text2_844DD31
    .4byte Text2_844DD8B
    .2byte 0 @ unused
    .2byte 414
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 845172C
    .string "IRON CLAW$", 12
    .2byte 12 @ in decimeters
    .2byte 2025 @ in hectograms
    .4byte Text2_844DD8C
    .4byte Text2_844DDF9
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 272
    .2byte -2
    .2byte 0 @ padding

    @ 8451750
    .string "IRON LEG$", 12
    .2byte 16 @ in decimeters
    .2byte 5500 @ in hectograms
    .4byte Text2_844DDFA
    .4byte Text2_844DE59
    .2byte 0 @ unused
    .2byte 272
    .2byte 3
    .2byte 461
    .2byte 4
    .2byte 0 @ padding

    @ 8451774
    .string "ROCK PEAK$", 12
    .2byte 17 @ in decimeters
    .2byte 2300 @ in hectograms
    .4byte Text2_844DE5A
    .4byte Text2_844DEC8
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 309
    .2byte 1
    .2byte 0 @ padding

    @ 8451798
    .string "ICEBERG$", 12
    .2byte 18 @ in decimeters
    .2byte 1750 @ in hectograms
    .4byte Text2_844DEC9
    .4byte Text2_844DF2A
    .2byte 0 @ unused
    .2byte 265
    .2byte 0
    .2byte 317
    .2byte 3
    .2byte 0 @ padding

    @ 84517BC
    .string "IRON$", 12
    .2byte 19 @ in decimeters
    .2byte 2050 @ in hectograms
    .4byte Text2_844DF2B
    .4byte Text2_844DF9B
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 359
    .2byte 6
    .2byte 0 @ padding

    @ 84517E0
    .string "EON$", 12
    .2byte 14 @ in decimeters
    .2byte 400 @ in hectograms
    .4byte Text2_844DF9C
    .4byte Text2_844E009
    .2byte 0 @ unused
    .2byte 291
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 8451804
    .string "EON$", 12
    .2byte 20 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte Text2_844E00A
    .4byte Text2_844E07A
    .2byte 0 @ unused
    .2byte 273
    .2byte 0
    .2byte 313
    .2byte 3
    .2byte 0 @ padding

    @ 8451828
    .string "SEA BASIN$", 12
    .2byte 45 @ in decimeters
    .2byte 3520 @ in hectograms
    .4byte Text2_844E07B
    .4byte Text2_844E0E5
    .2byte 0 @ unused
    .2byte 272
    .2byte 1
    .2byte 639
    .2byte 13
    .2byte 0 @ padding

    @ 845184C
    .string "CONTINENT$", 12
    .2byte 35 @ in decimeters
    .2byte 9500 @ in hectograms
    .4byte Text2_844E0E6
    .4byte Text2_844E143
    .2byte 0 @ unused
    .2byte 276
    .2byte 0
    .2byte 530
    .2byte 12
    .2byte 0 @ padding

    @ 8451870
    .string "SKY HIGH$", 12
    .2byte 70 @ in decimeters
    .2byte 2065 @ in hectograms
    .4byte Text2_844E144
    .4byte Text2_844E1AC
    .2byte 0 @ unused
    .2byte 286
    .2byte -1
    .2byte 483
    .2byte 9
    .2byte 0 @ padding

    @ 8451894
    .string "WISH$", 12
    .2byte 3 @ in decimeters
    .2byte 11 @ in hectograms
    .4byte Text2_844E1AD
    .4byte Text2_844E20D
    .2byte 0 @ unused
    .2byte 608
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding

    @ 84518B8
    .string "DNA$", 12
    .2byte 17 @ in decimeters
    .2byte 608 @ in hectograms
    .4byte Text2_844E20E
    .4byte Text2_844E26E
    .2byte 0 @ unused
    .2byte 293
    .2byte 0
    .2byte 337
    .2byte 2
    .2byte 0 @ padding

