kPokedexEntries:: @ 844E850
    @ NONE
    .string "UNKNOWN$", 12
    .2byte 0 @ in decimeters
    .2byte 0 @ in hectograms
    .4byte kPokedexDescription1_NONE
    .4byte kPokedexDescription2_NONE
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte 0
    .2byte 0 @ padding
    @ BULBASAUR
    .string "SEED$", 12
    .2byte 7 @ in decimeters
    .2byte 69 @ in hectograms
    .4byte kPokedexDescription1_BULBASAUR
    .4byte kPokedexDescription2_BULBASAUR
    .2byte 0 @ unused
    .2byte 356
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ IVYSAUR
    .string "SEED$", 12
    .2byte 10 @ in decimeters
    .2byte 130 @ in hectograms
    .4byte kPokedexDescription1_IVYSAUR
    .4byte kPokedexDescription2_IVYSAUR
    .2byte 0 @ unused
    .2byte 332
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VENUSAUR
    .string "SEED$", 12
    .2byte 20 @ in decimeters
    .2byte 1000 @ in hectograms
    .4byte kPokedexDescription1_VENUSAUR
    .4byte kPokedexDescription2_VENUSAUR
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding
    @ CHARMANDER
    .string "LIZARD$", 12
    .2byte 6 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte kPokedexDescription1_CHARMANDER
    .4byte kPokedexDescription2_CHARMANDER
    .2byte 0 @ unused
    .2byte 410
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CHARMELEON
    .string "FLAME$", 12
    .2byte 11 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte kPokedexDescription1_CHARMELEON
    .4byte kPokedexDescription2_CHARMELEON
    .2byte 0 @ unused
    .2byte 294
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CHARIZARD
    .string "FLAME$", 12
    .2byte 17 @ in decimeters
    .2byte 905 @ in hectograms
    .4byte kPokedexDescription1_CHARIZARD
    .4byte kPokedexDescription2_CHARIZARD
    .2byte 0 @ unused
    .2byte 271
    .2byte 0
    .2byte 317
    .2byte 3
    .2byte 0 @ padding
    @ SQUIRTLE
    .string "TINY TURTLE$", 12
    .2byte 5 @ in decimeters
    .2byte 90 @ in hectograms
    .4byte kPokedexDescription1_SQUIRTLE
    .4byte kPokedexDescription2_SQUIRTLE
    .2byte 0 @ unused
    .2byte 412
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WARTORTLE
    .string "TURTLE$", 12
    .2byte 10 @ in decimeters
    .2byte 225 @ in hectograms
    .4byte kPokedexDescription1_WARTORTLE
    .4byte kPokedexDescription2_WARTORTLE
    .2byte 0 @ unused
    .2byte 334
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BLASTOISE
    .string "SHELLFISH$", 12
    .2byte 16 @ in decimeters
    .2byte 855 @ in hectograms
    .4byte kPokedexDescription1_BLASTOISE
    .4byte kPokedexDescription2_BLASTOISE
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 329
    .2byte 3
    .2byte 0 @ padding
    @ CATERPIE
    .string "WORM$", 12
    .2byte 3 @ in decimeters
    .2byte 29 @ in hectograms
    .4byte kPokedexDescription1_CATERPIE
    .4byte kPokedexDescription2_CATERPIE
    .2byte 0 @ unused
    .2byte 549
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ METAPOD
    .string "COCOON$", 12
    .2byte 7 @ in decimeters
    .2byte 99 @ in hectograms
    .4byte kPokedexDescription1_METAPOD
    .4byte kPokedexDescription2_METAPOD
    .2byte 0 @ unused
    .2byte 350
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BUTTERFREE
    .string "BUTTERFLY$", 12
    .2byte 11 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte kPokedexDescription1_BUTTERFREE
    .4byte kPokedexDescription2_BUTTERFREE
    .2byte 0 @ unused
    .2byte 312
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WEEDLE
    .string "HAIRY BUG$", 12
    .2byte 3 @ in decimeters
    .2byte 32 @ in hectograms
    .4byte kPokedexDescription1_WEEDLE
    .4byte kPokedexDescription2_WEEDLE
    .2byte 0 @ unused
    .2byte 455
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KAKUNA
    .string "COCOON$", 12
    .2byte 6 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte kPokedexDescription1_KAKUNA
    .4byte kPokedexDescription2_KAKUNA
    .2byte 0 @ unused
    .2byte 424
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BEEDRILL
    .string "POISON BEE$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte kPokedexDescription1_BEEDRILL
    .4byte kPokedexDescription2_BEEDRILL
    .2byte 0 @ unused
    .2byte 366
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PIDGEY
    .string "TINY BIRD$", 12
    .2byte 3 @ in decimeters
    .2byte 18 @ in hectograms
    .4byte kPokedexDescription1_PIDGEY
    .4byte kPokedexDescription2_PIDGEY
    .2byte 0 @ unused
    .2byte 492
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PIDGEOTTO
    .string "BIRD$", 12
    .2byte 11 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte kPokedexDescription1_PIDGEOTTO
    .4byte kPokedexDescription2_PIDGEOTTO
    .2byte 0 @ unused
    .2byte 334
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PIDGEOT
    .string "BIRD$", 12
    .2byte 15 @ in decimeters
    .2byte 395 @ in hectograms
    .4byte kPokedexDescription1_PIDGEOT
    .4byte kPokedexDescription2_PIDGEOT
    .2byte 0 @ unused
    .2byte 269
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ RATTATA
    .string "MOUSE$", 12
    .2byte 3 @ in decimeters
    .2byte 35 @ in hectograms
    .4byte kPokedexDescription1_RATTATA
    .4byte kPokedexDescription2_RATTATA
    .2byte 0 @ unused
    .2byte 481
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ RATICATE
    .string "MOUSE$", 12
    .2byte 7 @ in decimeters
    .2byte 185 @ in hectograms
    .4byte kPokedexDescription1_RATICATE
    .4byte kPokedexDescription2_RATICATE
    .2byte 0 @ unused
    .2byte 401
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SPEAROW
    .string "TINY BIRD$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte kPokedexDescription1_SPEAROW
    .4byte kPokedexDescription2_SPEAROW
    .2byte 0 @ unused
    .2byte 571
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ FEAROW
    .string "BEAK$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte kPokedexDescription1_FEAROW
    .4byte kPokedexDescription2_FEAROW
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 272
    .2byte -2
    .2byte 0 @ padding
    @ EKANS
    .string "SNAKE$", 12
    .2byte 20 @ in decimeters
    .2byte 69 @ in hectograms
    .4byte kPokedexDescription1_EKANS
    .4byte kPokedexDescription2_EKANS
    .2byte 0 @ unused
    .2byte 298
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ARBOK
    .string "COBRA$", 12
    .2byte 35 @ in decimeters
    .2byte 650 @ in hectograms
    .4byte kPokedexDescription1_ARBOK
    .4byte kPokedexDescription2_ARBOK
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 296
    .2byte 1
    .2byte 0 @ padding
    @ PIKACHU
    .string "MOUSE$", 12
    .2byte 4 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte kPokedexDescription1_PIKACHU
    .4byte kPokedexDescription2_PIKACHU
    .2byte 0 @ unused
    .2byte 479
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ RAICHU
    .string "MOUSE$", 12
    .2byte 8 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte kPokedexDescription1_RAICHU
    .4byte kPokedexDescription2_RAICHU
    .2byte 0 @ unused
    .2byte 426
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SANDSHREW
    .string "MOUSE$", 12
    .2byte 6 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte kPokedexDescription1_SANDSHREW
    .4byte kPokedexDescription2_SANDSHREW
    .2byte 0 @ unused
    .2byte 370
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SANDSLASH
    .string "MOUSE$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte kPokedexDescription1_SANDSLASH
    .4byte kPokedexDescription2_SANDSLASH
    .2byte 0 @ unused
    .2byte 341
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NIDORAN_F
    .string "POISON PIN$", 12
    .2byte 4 @ in decimeters
    .2byte 70 @ in hectograms
    .4byte kPokedexDescription1_NIDORAN_F
    .4byte kPokedexDescription2_NIDORAN_F
    .2byte 0 @ unused
    .2byte 488
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NIDORINA
    .string "POISON PIN$", 12
    .2byte 8 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte kPokedexDescription1_NIDORINA
    .4byte kPokedexDescription2_NIDORINA
    .2byte 0 @ unused
    .2byte 381
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NIDOQUEEN
    .string "DRILL$", 12
    .2byte 13 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte kPokedexDescription1_NIDOQUEEN
    .4byte kPokedexDescription2_NIDOQUEEN
    .2byte 0 @ unused
    .2byte 283
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NIDORAN_M
    .string "POISON PIN$", 12
    .2byte 5 @ in decimeters
    .2byte 90 @ in hectograms
    .4byte kPokedexDescription1_NIDORAN_M
    .4byte kPokedexDescription2_NIDORAN_M
    .2byte 0 @ unused
    .2byte 480
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NIDORINO
    .string "POISON PIN$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte kPokedexDescription1_NIDORINO
    .4byte kPokedexDescription2_NIDORINO
    .2byte 0 @ unused
    .2byte 408
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NIDOKING
    .string "DRILL$", 12
    .2byte 14 @ in decimeters
    .2byte 620 @ in hectograms
    .4byte kPokedexDescription1_NIDOKING
    .4byte kPokedexDescription2_NIDOKING
    .2byte 0 @ unused
    .2byte 304
    .2byte 3
    .2byte 323
    .2byte 2
    .2byte 0 @ padding
    @ CLEFAIRY
    .string "FAIRY$", 12
    .2byte 6 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte kPokedexDescription1_CLEFAIRY
    .4byte kPokedexDescription2_CLEFAIRY
    .2byte 0 @ unused
    .2byte 425
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CLEFABLE
    .string "FAIRY$", 12
    .2byte 13 @ in decimeters
    .2byte 400 @ in hectograms
    .4byte kPokedexDescription1_CLEFABLE
    .4byte kPokedexDescription2_CLEFABLE
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 272
    .2byte -1
    .2byte 0 @ padding
    @ VULPIX
    .string "FOX$", 12
    .2byte 6 @ in decimeters
    .2byte 99 @ in hectograms
    .4byte kPokedexDescription1_VULPIX
    .4byte kPokedexDescription2_VULPIX
    .2byte 0 @ unused
    .2byte 497
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NINETALES
    .string "FOX$", 12
    .2byte 11 @ in decimeters
    .2byte 199 @ in hectograms
    .4byte kPokedexDescription1_NINETALES
    .4byte kPokedexDescription2_NINETALES
    .2byte 0 @ unused
    .2byte 339
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ JIGGLYPUFF
    .string "BALLOON$", 12
    .2byte 5 @ in decimeters
    .2byte 55 @ in hectograms
    .4byte kPokedexDescription1_JIGGLYPUFF
    .4byte kPokedexDescription2_JIGGLYPUFF
    .2byte 0 @ unused
    .2byte 419
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WIGGLYTUFF
    .string "BALLOON$", 12
    .2byte 10 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte kPokedexDescription1_WIGGLYTUFF
    .4byte kPokedexDescription2_WIGGLYTUFF
    .2byte 0 @ unused
    .2byte 328
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ZUBAT
    .string "BAT$", 12
    .2byte 8 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte kPokedexDescription1_ZUBAT
    .4byte kPokedexDescription2_ZUBAT
    .2byte 0 @ unused
    .2byte 355
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GOLBAT
    .string "BAT$", 12
    .2byte 16 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte kPokedexDescription1_GOLBAT
    .4byte kPokedexDescription2_GOLBAT
    .2byte 0 @ unused
    .2byte 291
    .2byte 0
    .2byte 296
    .2byte 2
    .2byte 0 @ padding
    @ ODDISH
    .string "WEED$", 12
    .2byte 5 @ in decimeters
    .2byte 54 @ in hectograms
    .4byte kPokedexDescription1_ODDISH
    .4byte kPokedexDescription2_ODDISH
    .2byte 0 @ unused
    .2byte 423
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GLOOM
    .string "WEED$", 12
    .2byte 8 @ in decimeters
    .2byte 86 @ in hectograms
    .4byte kPokedexDescription1_GLOOM
    .4byte kPokedexDescription2_GLOOM
    .2byte 0 @ unused
    .2byte 329
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VILEPLUME
    .string "FLOWER$", 12
    .2byte 12 @ in decimeters
    .2byte 186 @ in hectograms
    .4byte kPokedexDescription1_VILEPLUME
    .4byte kPokedexDescription2_VILEPLUME
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 272
    .2byte -2
    .2byte 0 @ padding
    @ PARAS
    .string "MUSHROOM$", 12
    .2byte 3 @ in decimeters
    .2byte 54 @ in hectograms
    .4byte kPokedexDescription1_PARAS
    .4byte kPokedexDescription2_PARAS
    .2byte 0 @ unused
    .2byte 546
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PARASECT
    .string "MUSHROOM$", 12
    .2byte 10 @ in decimeters
    .2byte 295 @ in hectograms
    .4byte kPokedexDescription1_PARASECT
    .4byte kPokedexDescription2_PARASECT
    .2byte 0 @ unused
    .2byte 307
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VENONAT
    .string "INSECT$", 12
    .2byte 10 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte kPokedexDescription1_VENONAT
    .4byte kPokedexDescription2_VENONAT
    .2byte 0 @ unused
    .2byte 360
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VENOMOTH
    .string "POISON MOTH$", 12
    .2byte 15 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte kPokedexDescription1_VENOMOTH
    .4byte kPokedexDescription2_VENOMOTH
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 293
    .2byte 1
    .2byte 0 @ padding
    @ DIGLETT
    .string "MOLE$", 12
    .2byte 2 @ in decimeters
    .2byte 8 @ in hectograms
    .4byte kPokedexDescription1_DIGLETT
    .4byte kPokedexDescription2_DIGLETT
    .2byte 0 @ unused
    .2byte 706
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DUGTRIO
    .string "MOLE$", 12
    .2byte 7 @ in decimeters
    .2byte 333 @ in hectograms
    .4byte kPokedexDescription1_DUGTRIO
    .4byte kPokedexDescription2_DUGTRIO
    .2byte 0 @ unused
    .2byte 384
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MEOWTH
    .string "SCRATCH CAT$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte kPokedexDescription1_MEOWTH
    .4byte kPokedexDescription2_MEOWTH
    .2byte 0 @ unused
    .2byte 480
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PERSIAN
    .string "CLASSY CAT$", 12
    .2byte 10 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte kPokedexDescription1_PERSIAN
    .4byte kPokedexDescription2_PERSIAN
    .2byte 0 @ unused
    .2byte 320
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PSYDUCK
    .string "DUCK$", 12
    .2byte 8 @ in decimeters
    .2byte 196 @ in hectograms
    .4byte kPokedexDescription1_PSYDUCK
    .4byte kPokedexDescription2_PSYDUCK
    .2byte 0 @ unused
    .2byte 347
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GOLDUCK
    .string "DUCK$", 12
    .2byte 17 @ in decimeters
    .2byte 766 @ in hectograms
    .4byte kPokedexDescription1_GOLDUCK
    .4byte kPokedexDescription2_GOLDUCK
    .2byte 0 @ unused
    .2byte 272
    .2byte 4
    .2byte 287
    .2byte 1
    .2byte 0 @ padding
    @ MANKEY
    .string "PIG MONKEY$", 12
    .2byte 5 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte kPokedexDescription1_MANKEY
    .4byte kPokedexDescription2_MANKEY
    .2byte 0 @ unused
    .2byte 388
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PRIMEAPE
    .string "PIG MONKEY$", 12
    .2byte 10 @ in decimeters
    .2byte 320 @ in hectograms
    .4byte kPokedexDescription1_PRIMEAPE
    .4byte kPokedexDescription2_PRIMEAPE
    .2byte 0 @ unused
    .2byte 326
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GROWLITHE
    .string "PUPPY$", 12
    .2byte 7 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte kPokedexDescription1_GROWLITHE
    .4byte kPokedexDescription2_GROWLITHE
    .2byte 0 @ unused
    .2byte 346
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ARCANINE
    .string "LEGENDARY$", 12
    .2byte 19 @ in decimeters
    .2byte 1550 @ in hectograms
    .4byte kPokedexDescription1_ARCANINE
    .4byte kPokedexDescription2_ARCANINE
    .2byte 0 @ unused
    .2byte 256
    .2byte -1
    .2byte 312
    .2byte 2
    .2byte 0 @ padding
    @ POLIWAG
    .string "TADPOLE$", 12
    .2byte 6 @ in decimeters
    .2byte 124 @ in hectograms
    .4byte kPokedexDescription1_POLIWAG
    .4byte kPokedexDescription2_POLIWAG
    .2byte 0 @ unused
    .2byte 353
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ POLIWHIRL
    .string "TADPOLE$", 12
    .2byte 10 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte kPokedexDescription1_POLIWHIRL
    .4byte kPokedexDescription2_POLIWHIRL
    .2byte 0 @ unused
    .2byte 288
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ POLIWRATH
    .string "TADPOLE$", 12
    .2byte 13 @ in decimeters
    .2byte 540 @ in hectograms
    .4byte kPokedexDescription1_POLIWRATH
    .4byte kPokedexDescription2_POLIWRATH
    .2byte 0 @ unused
    .2byte 256
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ABRA
    .string "PSI$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte kPokedexDescription1_ABRA
    .4byte kPokedexDescription2_ABRA
    .2byte 0 @ unused
    .2byte 374
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KADABRA
    .string "PSI$", 12
    .2byte 13 @ in decimeters
    .2byte 565 @ in hectograms
    .4byte kPokedexDescription1_KADABRA
    .4byte kPokedexDescription2_KADABRA
    .2byte 0 @ unused
    .2byte 272
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ALAKAZAM
    .string "PSI$", 12
    .2byte 15 @ in decimeters
    .2byte 480 @ in hectograms
    .4byte kPokedexDescription1_ALAKAZAM
    .4byte kPokedexDescription2_ALAKAZAM
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 271
    .2byte -1
    .2byte 0 @ padding
    @ MACHOP
    .string "SUPERPOWER$", 12
    .2byte 8 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte kPokedexDescription1_MACHOP
    .4byte kPokedexDescription2_MACHOP
    .2byte 0 @ unused
    .2byte 320
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MACHOKE
    .string "SUPERPOWER$", 12
    .2byte 15 @ in decimeters
    .2byte 705 @ in hectograms
    .4byte kPokedexDescription1_MACHOKE
    .4byte kPokedexDescription2_MACHOKE
    .2byte 0 @ unused
    .2byte 304
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MACHAMP
    .string "SUPERPOWER$", 12
    .2byte 16 @ in decimeters
    .2byte 1300 @ in hectograms
    .4byte kPokedexDescription1_MACHAMP
    .4byte kPokedexDescription2_MACHAMP
    .2byte 0 @ unused
    .2byte 278
    .2byte 2
    .2byte 283
    .2byte 0
    .2byte 0 @ padding
    @ BELLSPROUT
    .string "FLOWER$", 12
    .2byte 7 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte kPokedexDescription1_BELLSPROUT
    .4byte kPokedexDescription2_BELLSPROUT
    .2byte 0 @ unused
    .2byte 354
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WEEPINBELL
    .string "FLYCATCHER$", 12
    .2byte 10 @ in decimeters
    .2byte 64 @ in hectograms
    .4byte kPokedexDescription1_WEEPINBELL
    .4byte kPokedexDescription2_WEEPINBELL
    .2byte 0 @ unused
    .2byte 256
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VICTREEBEL
    .string "FLYCATCHER$", 12
    .2byte 17 @ in decimeters
    .2byte 155 @ in hectograms
    .4byte kPokedexDescription1_VICTREEBEL
    .4byte kPokedexDescription2_VICTREEBEL
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 302
    .2byte 2
    .2byte 0 @ padding
    @ TENTACOOL
    .string "JELLYFISH$", 12
    .2byte 9 @ in decimeters
    .2byte 455 @ in hectograms
    .4byte kPokedexDescription1_TENTACOOL
    .4byte kPokedexDescription2_TENTACOOL
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TENTACRUEL
    .string "JELLYFISH$", 12
    .2byte 16 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte kPokedexDescription1_TENTACRUEL
    .4byte kPokedexDescription2_TENTACRUEL
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 312
    .2byte 0
    .2byte 0 @ padding
    @ GEODUDE
    .string "ROCK$", 12
    .2byte 4 @ in decimeters
    .2byte 200 @ in hectograms
    .4byte kPokedexDescription1_GEODUDE
    .4byte kPokedexDescription2_GEODUDE
    .2byte 0 @ unused
    .2byte 330
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GRAVELER
    .string "ROCK$", 12
    .2byte 10 @ in decimeters
    .2byte 1050 @ in hectograms
    .4byte kPokedexDescription1_GRAVELER
    .4byte kPokedexDescription2_GRAVELER
    .2byte 0 @ unused
    .2byte 272
    .2byte 8
    .2byte 305
    .2byte 1
    .2byte 0 @ padding
    @ GOLEM
    .string "MEGATON$", 12
    .2byte 14 @ in decimeters
    .2byte 3000 @ in hectograms
    .4byte kPokedexDescription1_GOLEM
    .4byte kPokedexDescription2_GOLEM
    .2byte 0 @ unused
    .2byte 266
    .2byte 3
    .2byte 298
    .2byte 1
    .2byte 0 @ padding
    @ PONYTA
    .string "FIRE HORSE$", 12
    .2byte 10 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte kPokedexDescription1_PONYTA
    .4byte kPokedexDescription2_PONYTA
    .2byte 0 @ unused
    .2byte 288
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ RAPIDASH
    .string "FIRE HORSE$", 12
    .2byte 17 @ in decimeters
    .2byte 950 @ in hectograms
    .4byte kPokedexDescription1_RAPIDASH
    .4byte kPokedexDescription2_RAPIDASH
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 312
    .2byte 1
    .2byte 0 @ padding
    @ SLOWPOKE
    .string "DOPEY$", 12
    .2byte 12 @ in decimeters
    .2byte 360 @ in hectograms
    .4byte kPokedexDescription1_SLOWPOKE
    .4byte kPokedexDescription2_SLOWPOKE
    .2byte 0 @ unused
    .2byte 271
    .2byte 10
    .2byte 272
    .2byte -2
    .2byte 0 @ padding
    @ SLOWBRO
    .string "HERMIT CRAB$", 12
    .2byte 16 @ in decimeters
    .2byte 785 @ in hectograms
    .4byte kPokedexDescription1_SLOWBRO
    .4byte kPokedexDescription2_SLOWBRO
    .2byte 0 @ unused
    .2byte 257
    .2byte -2
    .2byte 312
    .2byte 0
    .2byte 0 @ padding
    @ MAGNEMITE
    .string "MAGNET$", 12
    .2byte 3 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte kPokedexDescription1_MAGNEMITE
    .4byte kPokedexDescription2_MAGNEMITE
    .2byte 0 @ unused
    .2byte 294
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MAGNETON
    .string "MAGNET$", 12
    .2byte 10 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte kPokedexDescription1_MAGNETON
    .4byte kPokedexDescription2_MAGNETON
    .2byte 0 @ unused
    .2byte 293
    .2byte -4
    .2byte 273
    .2byte -2
    .2byte 0 @ padding
    @ FARFETCHD
    .string "WILD DUCK$", 12
    .2byte 8 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte kPokedexDescription1_FARFETCHD
    .4byte kPokedexDescription2_FARFETCHD
    .2byte 0 @ unused
    .2byte 317
    .2byte -2
    .2byte 256
    .2byte -3
    .2byte 0 @ padding
    @ DODUO
    .string "TWIN BIRD$", 12
    .2byte 14 @ in decimeters
    .2byte 392 @ in hectograms
    .4byte kPokedexDescription1_DODUO
    .4byte kPokedexDescription2_DODUO
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 287
    .2byte 0
    .2byte 0 @ padding
    @ DODRIO
    .string "TRIPLE BIRD$", 12
    .2byte 18 @ in decimeters
    .2byte 852 @ in hectograms
    .4byte kPokedexDescription1_DODRIO
    .4byte kPokedexDescription2_DODRIO
    .2byte 0 @ unused
    .2byte 272
    .2byte -2
    .2byte 296
    .2byte 1
    .2byte 0 @ padding
    @ SEEL
    .string "SEA LION$", 12
    .2byte 11 @ in decimeters
    .2byte 900 @ in hectograms
    .4byte kPokedexDescription1_SEEL
    .4byte kPokedexDescription2_SEEL
    .2byte 0 @ unused
    .2byte 298
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DEWGONG
    .string "SEA LION$", 12
    .2byte 17 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte kPokedexDescription1_DEWGONG
    .4byte kPokedexDescription2_DEWGONG
    .2byte 0 @ unused
    .2byte 288
    .2byte 1
    .2byte 306
    .2byte -1
    .2byte 0 @ padding
    @ GRIMER
    .string "SLUDGE$", 12
    .2byte 9 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte kPokedexDescription1_GRIMER
    .4byte kPokedexDescription2_GRIMER
    .2byte 0 @ unused
    .2byte 258
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MUK
    .string "SLUDGE$", 12
    .2byte 12 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte kPokedexDescription1_MUK
    .4byte kPokedexDescription2_MUK
    .2byte 0 @ unused
    .2byte 288
    .2byte 7
    .2byte 288
    .2byte -1
    .2byte 0 @ padding
    @ SHELLDER
    .string "BIVALVE$", 12
    .2byte 3 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte kPokedexDescription1_SHELLDER
    .4byte kPokedexDescription2_SHELLDER
    .2byte 0 @ unused
    .2byte 643
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CLOYSTER
    .string "BIVALVE$", 12
    .2byte 15 @ in decimeters
    .2byte 1325 @ in hectograms
    .4byte kPokedexDescription1_CLOYSTER
    .4byte kPokedexDescription2_CLOYSTER
    .2byte 0 @ unused
    .2byte 264
    .2byte 0
    .2byte 288
    .2byte -1
    .2byte 0 @ padding
    @ GASTLY
    .string "GAS$", 12
    .2byte 13 @ in decimeters
    .2byte 1 @ in hectograms
    .4byte kPokedexDescription1_GASTLY
    .4byte kPokedexDescription2_GASTLY
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HAUNTER
    .string "GAS$", 12
    .2byte 16 @ in decimeters
    .2byte 1 @ in hectograms
    .4byte kPokedexDescription1_HAUNTER
    .4byte kPokedexDescription2_HAUNTER
    .2byte 0 @ unused
    .2byte 269
    .2byte 2
    .2byte 308
    .2byte 1
    .2byte 0 @ padding
    @ GENGAR
    .string "SHADOW$", 12
    .2byte 15 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte kPokedexDescription1_GENGAR
    .4byte kPokedexDescription2_GENGAR
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 317
    .2byte 1
    .2byte 0 @ padding
    @ ONIX
    .string "ROCK SNAKE$", 12
    .2byte 88 @ in decimeters
    .2byte 2100 @ in hectograms
    .4byte kPokedexDescription1_ONIX
    .4byte kPokedexDescription2_ONIX
    .2byte 0 @ unused
    .2byte 257
    .2byte 0
    .2byte 515
    .2byte 12
    .2byte 0 @ padding
    @ DROWZEE
    .string "HYPNOSIS$", 12
    .2byte 10 @ in decimeters
    .2byte 324 @ in hectograms
    .4byte kPokedexDescription1_DROWZEE
    .4byte kPokedexDescription2_DROWZEE
    .2byte 0 @ unused
    .2byte 274
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HYPNO
    .string "HYPNOSIS$", 12
    .2byte 16 @ in decimeters
    .2byte 756 @ in hectograms
    .4byte kPokedexDescription1_HYPNO
    .4byte kPokedexDescription2_HYPNO
    .2byte 0 @ unused
    .2byte 298
    .2byte 3
    .2byte 310
    .2byte 2
    .2byte 0 @ padding
    @ KRABBY
    .string "RIVER CRAB$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte kPokedexDescription1_KRABBY
    .4byte kPokedexDescription2_KRABBY
    .2byte 0 @ unused
    .2byte 469
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KINGLER
    .string "PINCER$", 12
    .2byte 13 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte kPokedexDescription1_KINGLER
    .4byte kPokedexDescription2_KINGLER
    .2byte 0 @ unused
    .2byte 287
    .2byte 3
    .2byte 308
    .2byte 1
    .2byte 0 @ padding
    @ VOLTORB
    .string "BALL$", 12
    .2byte 5 @ in decimeters
    .2byte 104 @ in hectograms
    .4byte kPokedexDescription1_VOLTORB
    .4byte kPokedexDescription2_VOLTORB
    .2byte 0 @ unused
    .2byte 364
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ELECTRODE
    .string "BALL$", 12
    .2byte 12 @ in decimeters
    .2byte 666 @ in hectograms
    .4byte kPokedexDescription1_ELECTRODE
    .4byte kPokedexDescription2_ELECTRODE
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ EXEGGCUTE
    .string "EGG$", 12
    .2byte 4 @ in decimeters
    .2byte 25 @ in hectograms
    .4byte kPokedexDescription1_EXEGGCUTE
    .4byte kPokedexDescription2_EXEGGCUTE
    .2byte 0 @ unused
    .2byte 495
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ EXEGGUTOR
    .string "COCONUT$", 12
    .2byte 20 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte kPokedexDescription1_EXEGGUTOR
    .4byte kPokedexDescription2_EXEGGUTOR
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 376
    .2byte 7
    .2byte 0 @ padding
    @ CUBONE
    .string "LONELY$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte kPokedexDescription1_CUBONE
    .4byte kPokedexDescription2_CUBONE
    .2byte 0 @ unused
    .2byte 545
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MAROWAK
    .string "BONE KEEPER$", 12
    .2byte 10 @ in decimeters
    .2byte 450 @ in hectograms
    .4byte kPokedexDescription1_MAROWAK
    .4byte kPokedexDescription2_MAROWAK
    .2byte 0 @ unused
    .2byte 293
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HITMONLEE
    .string "KICKING$", 12
    .2byte 15 @ in decimeters
    .2byte 498 @ in hectograms
    .4byte kPokedexDescription1_HITMONLEE
    .4byte kPokedexDescription2_HITMONLEE
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 273
    .2byte -2
    .2byte 0 @ padding
    @ HITMONCHAN
    .string "PUNCHING$", 12
    .2byte 14 @ in decimeters
    .2byte 502 @ in hectograms
    .4byte kPokedexDescription1_HITMONCHAN
    .4byte kPokedexDescription2_HITMONCHAN
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 264
    .2byte -2
    .2byte 0 @ padding
    @ LICKITUNG
    .string "LICKING$", 12
    .2byte 12 @ in decimeters
    .2byte 655 @ in hectograms
    .4byte kPokedexDescription1_LICKITUNG
    .4byte kPokedexDescription2_LICKITUNG
    .2byte 0 @ unused
    .2byte 272
    .2byte 3
    .2byte 272
    .2byte -3
    .2byte 0 @ padding
    @ KOFFING
    .string "POISON GAS$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte kPokedexDescription1_KOFFING
    .4byte kPokedexDescription2_KOFFING
    .2byte 0 @ unused
    .2byte 369
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WEEZING
    .string "POISON GAS$", 12
    .2byte 12 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte kPokedexDescription1_WEEZING
    .4byte kPokedexDescription2_WEEZING
    .2byte 0 @ unused
    .2byte 321
    .2byte -1
    .2byte 276
    .2byte -1
    .2byte 0 @ padding
    @ RHYHORN
    .string "SPIKES$", 12
    .2byte 10 @ in decimeters
    .2byte 1150 @ in hectograms
    .4byte kPokedexDescription1_RHYHORN
    .4byte kPokedexDescription2_RHYHORN
    .2byte 0 @ unused
    .2byte 291
    .2byte 7
    .2byte 276
    .2byte -2
    .2byte 0 @ padding
    @ RHYDON
    .string "DRILL$", 12
    .2byte 19 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte kPokedexDescription1_RHYDON
    .4byte kPokedexDescription2_RHYDON
    .2byte 0 @ unused
    .2byte 272
    .2byte -1
    .2byte 344
    .2byte 3
    .2byte 0 @ padding
    @ CHANSEY
    .string "EGG$", 12
    .2byte 11 @ in decimeters
    .2byte 346 @ in hectograms
    .4byte kPokedexDescription1_CHANSEY
    .4byte kPokedexDescription2_CHANSEY
    .2byte 0 @ unused
    .2byte 257
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TANGELA
    .string "VINE$", 12
    .2byte 10 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte kPokedexDescription1_TANGELA
    .4byte kPokedexDescription2_TANGELA
    .2byte 0 @ unused
    .2byte 320
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KANGASKHAN
    .string "PARENT$", 12
    .2byte 22 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte kPokedexDescription1_KANGASKHAN
    .4byte kPokedexDescription2_KANGASKHAN
    .2byte 0 @ unused
    .2byte 257
    .2byte -3
    .2byte 349
    .2byte 5
    .2byte 0 @ padding
    @ HORSEA
    .string "DRAGON$", 12
    .2byte 4 @ in decimeters
    .2byte 80 @ in hectograms
    .4byte kPokedexDescription1_HORSEA
    .4byte kPokedexDescription2_HORSEA
    .2byte 0 @ unused
    .2byte 399
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SEADRA
    .string "DRAGON$", 12
    .2byte 12 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte kPokedexDescription1_SEADRA
    .4byte kPokedexDescription2_SEADRA
    .2byte 0 @ unused
    .2byte 296
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GOLDEEN
    .string "GOLDFISH$", 12
    .2byte 6 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte kPokedexDescription1_GOLDEEN
    .4byte kPokedexDescription2_GOLDEEN
    .2byte 0 @ unused
    .2byte 379
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SEAKING
    .string "GOLDFISH$", 12
    .2byte 13 @ in decimeters
    .2byte 390 @ in hectograms
    .4byte kPokedexDescription1_SEAKING
    .4byte kPokedexDescription2_SEAKING
    .2byte 0 @ unused
    .2byte 304
    .2byte 1
    .2byte 288
    .2byte -2
    .2byte 0 @ padding
    @ STARYU
    .string "STAR SHAPE$", 12
    .2byte 8 @ in decimeters
    .2byte 345 @ in hectograms
    .4byte kPokedexDescription1_STARYU
    .4byte kPokedexDescription2_STARYU
    .2byte 0 @ unused
    .2byte 326
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ STARMIE
    .string "MYSTERIOUS$", 12
    .2byte 11 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte kPokedexDescription1_STARMIE
    .4byte kPokedexDescription2_STARMIE
    .2byte 0 @ unused
    .2byte 301
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MR_MIME
    .string "BARRIER$", 12
    .2byte 13 @ in decimeters
    .2byte 545 @ in hectograms
    .4byte kPokedexDescription1_MR_MIME
    .4byte kPokedexDescription2_MR_MIME
    .2byte 0 @ unused
    .2byte 258
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SCYTHER
    .string "MANTIS$", 12
    .2byte 15 @ in decimeters
    .2byte 560 @ in hectograms
    .4byte kPokedexDescription1_SCYTHER
    .4byte kPokedexDescription2_SCYTHER
    .2byte 0 @ unused
    .2byte 272
    .2byte 0
    .2byte 293
    .2byte 1
    .2byte 0 @ padding
    @ JYNX
    .string "HUMAN SHAPE$", 12
    .2byte 14 @ in decimeters
    .2byte 406 @ in hectograms
    .4byte kPokedexDescription1_JYNX
    .4byte kPokedexDescription2_JYNX
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 300
    .2byte 1
    .2byte 0 @ padding
    @ ELECTABUZZ
    .string "ELECTRIC$", 12
    .2byte 11 @ in decimeters
    .2byte 300 @ in hectograms
    .4byte kPokedexDescription1_ELECTABUZZ
    .4byte kPokedexDescription2_ELECTABUZZ
    .2byte 0 @ unused
    .2byte 330
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MAGMAR
    .string "SPITFIRE$", 12
    .2byte 13 @ in decimeters
    .2byte 445 @ in hectograms
    .4byte kPokedexDescription1_MAGMAR
    .4byte kPokedexDescription2_MAGMAR
    .2byte 0 @ unused
    .2byte 293
    .2byte 4
    .2byte 272
    .2byte -2
    .2byte 0 @ padding
    @ PINSIR
    .string "STAG BEETLE$", 12
    .2byte 15 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte kPokedexDescription1_PINSIR
    .4byte kPokedexDescription2_PINSIR
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 257
    .2byte -2
    .2byte 0 @ padding
    @ TAUROS
    .string "WILD BULL$", 12
    .2byte 14 @ in decimeters
    .2byte 884 @ in hectograms
    .4byte kPokedexDescription1_TAUROS
    .4byte kPokedexDescription2_TAUROS
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 312
    .2byte 3
    .2byte 0 @ padding
    @ MAGIKARP
    .string "FISH$", 12
    .2byte 9 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte kPokedexDescription1_MAGIKARP
    .4byte kPokedexDescription2_MAGIKARP
    .2byte 0 @ unused
    .2byte 317
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GYARADOS
    .string "ATROCIOUS$", 12
    .2byte 65 @ in decimeters
    .2byte 2350 @ in hectograms
    .4byte kPokedexDescription1_GYARADOS
    .4byte kPokedexDescription2_GYARADOS
    .2byte 0 @ unused
    .2byte 288
    .2byte -1
    .2byte 512
    .2byte 11
    .2byte 0 @ padding
    @ LAPRAS
    .string "TRANSPORT$", 12
    .2byte 25 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte kPokedexDescription1_LAPRAS
    .4byte kPokedexDescription2_LAPRAS
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 425
    .2byte 8
    .2byte 0 @ padding
    @ DITTO
    .string "TRANSFORM$", 12
    .2byte 3 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte kPokedexDescription1_DITTO
    .4byte kPokedexDescription2_DITTO
    .2byte 0 @ unused
    .2byte 602
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ EEVEE
    .string "EVOLUTION$", 12
    .2byte 3 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte kPokedexDescription1_EEVEE
    .4byte kPokedexDescription2_EEVEE
    .2byte 0 @ unused
    .2byte 476
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VAPOREON
    .string "BUBBLE JET$", 12
    .2byte 10 @ in decimeters
    .2byte 290 @ in hectograms
    .4byte kPokedexDescription1_VAPOREON
    .4byte kPokedexDescription2_VAPOREON
    .2byte 0 @ unused
    .2byte 316
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ JOLTEON
    .string "LIGHTNING$", 12
    .2byte 8 @ in decimeters
    .2byte 245 @ in hectograms
    .4byte kPokedexDescription1_JOLTEON
    .4byte kPokedexDescription2_JOLTEON
    .2byte 0 @ unused
    .2byte 283
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ FLAREON
    .string "FLAME$", 12
    .2byte 9 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte kPokedexDescription1_FLAREON
    .4byte kPokedexDescription2_FLAREON
    .2byte 0 @ unused
    .2byte 302
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PORYGON
    .string "VIRTUAL$", 12
    .2byte 8 @ in decimeters
    .2byte 365 @ in hectograms
    .4byte kPokedexDescription1_PORYGON
    .4byte kPokedexDescription2_PORYGON
    .2byte 0 @ unused
    .2byte 328
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ OMANYTE
    .string "SPIRAL$", 12
    .2byte 4 @ in decimeters
    .2byte 75 @ in hectograms
    .4byte kPokedexDescription1_OMANYTE
    .4byte kPokedexDescription2_OMANYTE
    .2byte 0 @ unused
    .2byte 521
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ OMASTAR
    .string "SPIRAL$", 12
    .2byte 10 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte kPokedexDescription1_OMASTAR
    .4byte kPokedexDescription2_OMASTAR
    .2byte 0 @ unused
    .2byte 307
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KABUTO
    .string "SHELLFISH$", 12
    .2byte 5 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte kPokedexDescription1_KABUTO
    .4byte kPokedexDescription2_KABUTO
    .2byte 0 @ unused
    .2byte 438
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KABUTOPS
    .string "SHELLFISH$", 12
    .2byte 13 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte kPokedexDescription1_KABUTOPS
    .4byte kPokedexDescription2_KABUTOPS
    .2byte 0 @ unused
    .2byte 271
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ AERODACTYL
    .string "FOSSIL$", 12
    .2byte 18 @ in decimeters
    .2byte 590 @ in hectograms
    .4byte kPokedexDescription1_AERODACTYL
    .4byte kPokedexDescription2_AERODACTYL
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 317
    .2byte 2
    .2byte 0 @ padding
    @ SNORLAX
    .string "SLEEPING$", 12
    .2byte 21 @ in decimeters
    .2byte 4600 @ in hectograms
    .4byte kPokedexDescription1_SNORLAX
    .4byte kPokedexDescription2_SNORLAX
    .2byte 0 @ unused
    .2byte 275
    .2byte 1
    .2byte 408
    .2byte 7
    .2byte 0 @ padding
    @ ARTICUNO
    .string "FREEZE$", 12
    .2byte 17 @ in decimeters
    .2byte 554 @ in hectograms
    .4byte kPokedexDescription1_ARTICUNO
    .4byte kPokedexDescription2_ARTICUNO
    .2byte 0 @ unused
    .2byte 278
    .2byte 0
    .2byte 308
    .2byte 1
    .2byte 0 @ padding
    @ ZAPDOS
    .string "ELECTRIC$", 12
    .2byte 16 @ in decimeters
    .2byte 526 @ in hectograms
    .4byte kPokedexDescription1_ZAPDOS
    .4byte kPokedexDescription2_ZAPDOS
    .2byte 0 @ unused
    .2byte 275
    .2byte 1
    .2byte 330
    .2byte 3
    .2byte 0 @ padding
    @ MOLTRES
    .string "FLAME$", 12
    .2byte 20 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte kPokedexDescription1_MOLTRES
    .4byte kPokedexDescription2_MOLTRES
    .2byte 0 @ unused
    .2byte 270
    .2byte 1
    .2byte 379
    .2byte 6
    .2byte 0 @ padding
    @ DRATINI
    .string "DRAGON$", 12
    .2byte 18 @ in decimeters
    .2byte 33 @ in hectograms
    .4byte kPokedexDescription1_DRATINI
    .4byte kPokedexDescription2_DRATINI
    .2byte 0 @ unused
    .2byte 256
    .2byte 8
    .2byte 386
    .2byte 6
    .2byte 0 @ padding
    @ DRAGONAIR
    .string "DRAGON$", 12
    .2byte 40 @ in decimeters
    .2byte 165 @ in hectograms
    .4byte kPokedexDescription1_DRAGONAIR
    .4byte kPokedexDescription2_DRAGONAIR
    .2byte 0 @ unused
    .2byte 274
    .2byte 0
    .2byte 423
    .2byte 6
    .2byte 0 @ padding
    @ DRAGONITE
    .string "DRAGON$", 12
    .2byte 22 @ in decimeters
    .2byte 2100 @ in hectograms
    .4byte kPokedexDescription1_DRAGONITE
    .4byte kPokedexDescription2_DRAGONITE
    .2byte 0 @ unused
    .2byte 283
    .2byte -1
    .2byte 342
    .2byte 4
    .2byte 0 @ padding
    @ MEWTWO
    .string "GENETIC$", 12
    .2byte 20 @ in decimeters
    .2byte 1220 @ in hectograms
    .4byte kPokedexDescription1_MEWTWO
    .4byte kPokedexDescription2_MEWTWO
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 342
    .2byte 5
    .2byte 0 @ padding
    @ MEW
    .string "NEW SPECIES$", 12
    .2byte 4 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte kPokedexDescription1_MEW
    .4byte kPokedexDescription2_MEW
    .2byte 0 @ unused
    .2byte 460
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CHIKORITA
    .string "LEAF$", 12
    .2byte 9 @ in decimeters
    .2byte 64 @ in hectograms
    .4byte kPokedexDescription1_CHIKORITA
    .4byte kPokedexDescription2_CHIKORITA
    .2byte 0 @ unused
    .2byte 512
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BAYLEEF
    .string "LEAF$", 12
    .2byte 12 @ in decimeters
    .2byte 158 @ in hectograms
    .4byte kPokedexDescription1_BAYLEEF
    .4byte kPokedexDescription2_BAYLEEF
    .2byte 0 @ unused
    .2byte 296
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MEGANIUM
    .string "HERB$", 12
    .2byte 18 @ in decimeters
    .2byte 1005 @ in hectograms
    .4byte kPokedexDescription1_MEGANIUM
    .4byte kPokedexDescription2_MEGANIUM
    .2byte 0 @ unused
    .2byte 286
    .2byte 0
    .2byte 317
    .2byte 2
    .2byte 0 @ padding
    @ CYNDAQUIL
    .string "FIRE MOUSE$", 12
    .2byte 5 @ in decimeters
    .2byte 79 @ in hectograms
    .4byte kPokedexDescription1_CYNDAQUIL
    .4byte kPokedexDescription2_CYNDAQUIL
    .2byte 0 @ unused
    .2byte 539
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ QUILAVA
    .string "VOLCANO$", 12
    .2byte 9 @ in decimeters
    .2byte 190 @ in hectograms
    .4byte kPokedexDescription1_QUILAVA
    .4byte kPokedexDescription2_QUILAVA
    .2byte 0 @ unused
    .2byte 329
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TYPHLOSION
    .string "VOLCANO$", 12
    .2byte 17 @ in decimeters
    .2byte 795 @ in hectograms
    .4byte kPokedexDescription1_TYPHLOSION
    .4byte kPokedexDescription2_TYPHLOSION
    .2byte 0 @ unused
    .2byte 284
    .2byte -1
    .2byte 287
    .2byte 0
    .2byte 0 @ padding
    @ TOTODILE
    .string "BIG JAW$", 12
    .2byte 6 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte kPokedexDescription1_TOTODILE
    .4byte kPokedexDescription2_TOTODILE
    .2byte 0 @ unused
    .2byte 487
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CROCONAW
    .string "BIG JAW$", 12
    .2byte 11 @ in decimeters
    .2byte 250 @ in hectograms
    .4byte kPokedexDescription1_CROCONAW
    .4byte kPokedexDescription2_CROCONAW
    .2byte 0 @ unused
    .2byte 378
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ FERALIGATR
    .string "BIG JAW$", 12
    .2byte 23 @ in decimeters
    .2byte 888 @ in hectograms
    .4byte kPokedexDescription1_FERALIGATR
    .4byte kPokedexDescription2_FERALIGATR
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding
    @ SENTRET
    .string "SCOUT$", 12
    .2byte 8 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte kPokedexDescription1_SENTRET
    .4byte kPokedexDescription2_SENTRET
    .2byte 0 @ unused
    .2byte 439
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ FURRET
    .string "LONG BODY$", 12
    .2byte 18 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte kPokedexDescription1_FURRET
    .4byte kPokedexDescription2_FURRET
    .2byte 0 @ unused
    .2byte 346
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HOOTHOOT
    .string "OWL$", 12
    .2byte 7 @ in decimeters
    .2byte 212 @ in hectograms
    .4byte kPokedexDescription1_HOOTHOOT
    .4byte kPokedexDescription2_HOOTHOOT
    .2byte 0 @ unused
    .2byte 380
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NOCTOWL
    .string "OWL$", 12
    .2byte 16 @ in decimeters
    .2byte 408 @ in hectograms
    .4byte kPokedexDescription1_NOCTOWL
    .4byte kPokedexDescription2_NOCTOWL
    .2byte 0 @ unused
    .2byte 278
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LEDYBA
    .string "FIVE STAR$", 12
    .2byte 10 @ in decimeters
    .2byte 108 @ in hectograms
    .4byte kPokedexDescription1_LEDYBA
    .4byte kPokedexDescription2_LEDYBA
    .2byte 0 @ unused
    .2byte 256
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LEDIAN
    .string "FIVE STAR$", 12
    .2byte 14 @ in decimeters
    .2byte 356 @ in hectograms
    .4byte kPokedexDescription1_LEDIAN
    .4byte kPokedexDescription2_LEDIAN
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SPINARAK
    .string "STRING SPIT$", 12
    .2byte 5 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte kPokedexDescription1_SPINARAK
    .4byte kPokedexDescription2_SPINARAK
    .2byte 0 @ unused
    .2byte 414
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ARIADOS
    .string "LONG LEG$", 12
    .2byte 11 @ in decimeters
    .2byte 335 @ in hectograms
    .4byte kPokedexDescription1_ARIADOS
    .4byte kPokedexDescription2_ARIADOS
    .2byte 0 @ unused
    .2byte 316
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CROBAT
    .string "BAT$", 12
    .2byte 18 @ in decimeters
    .2byte 750 @ in hectograms
    .4byte kPokedexDescription1_CROBAT
    .4byte kPokedexDescription2_CROBAT
    .2byte 0 @ unused
    .2byte 279
    .2byte -1
    .2byte 313
    .2byte 2
    .2byte 0 @ padding
    @ CHINCHOU
    .string "ANGLER$", 12
    .2byte 5 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte kPokedexDescription1_CHINCHOU
    .4byte kPokedexDescription2_CHINCHOU
    .2byte 0 @ unused
    .2byte 424
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LANTURN
    .string "LIGHT$", 12
    .2byte 12 @ in decimeters
    .2byte 225 @ in hectograms
    .4byte kPokedexDescription1_LANTURN
    .4byte kPokedexDescription2_LANTURN
    .2byte 0 @ unused
    .2byte 269
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PICHU
    .string "TINY MOUSE$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte kPokedexDescription1_PICHU
    .4byte kPokedexDescription2_PICHU
    .2byte 0 @ unused
    .2byte 508
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CLEFFA
    .string "STAR SHAPE$", 12
    .2byte 3 @ in decimeters
    .2byte 30 @ in hectograms
    .4byte kPokedexDescription1_CLEFFA
    .4byte kPokedexDescription2_CLEFFA
    .2byte 0 @ unused
    .2byte 462
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ IGGLYBUFF
    .string "BALLOON$", 12
    .2byte 3 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte kPokedexDescription1_IGGLYBUFF
    .4byte kPokedexDescription2_IGGLYBUFF
    .2byte 0 @ unused
    .2byte 457
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TOGEPI
    .string "SPIKE BALL$", 12
    .2byte 3 @ in decimeters
    .2byte 15 @ in hectograms
    .4byte kPokedexDescription1_TOGEPI
    .4byte kPokedexDescription2_TOGEPI
    .2byte 0 @ unused
    .2byte 507
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TOGETIC
    .string "HAPPINESS$", 12
    .2byte 6 @ in decimeters
    .2byte 32 @ in hectograms
    .4byte kPokedexDescription1_TOGETIC
    .4byte kPokedexDescription2_TOGETIC
    .2byte 0 @ unused
    .2byte 424
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NATU
    .string "TINY BIRD$", 12
    .2byte 2 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte kPokedexDescription1_NATU
    .4byte kPokedexDescription2_NATU
    .2byte 0 @ unused
    .2byte 610
    .2byte 23
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ XATU
    .string "MYSTIC$", 12
    .2byte 15 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte kPokedexDescription1_XATU
    .4byte kPokedexDescription2_XATU
    .2byte 0 @ unused
    .2byte 258
    .2byte 4
    .2byte 317
    .2byte 3
    .2byte 0 @ padding
    @ MAREEP
    .string "WOOL$", 12
    .2byte 6 @ in decimeters
    .2byte 78 @ in hectograms
    .4byte kPokedexDescription1_MAREEP
    .4byte kPokedexDescription2_MAREEP
    .2byte 0 @ unused
    .2byte 379
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ FLAAFFY
    .string "WOOL$", 12
    .2byte 8 @ in decimeters
    .2byte 133 @ in hectograms
    .4byte kPokedexDescription1_FLAAFFY
    .4byte kPokedexDescription2_FLAAFFY
    .2byte 0 @ unused
    .2byte 372
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ AMPHAROS
    .string "LIGHT$", 12
    .2byte 14 @ in decimeters
    .2byte 615 @ in hectograms
    .4byte kPokedexDescription1_AMPHAROS
    .4byte kPokedexDescription2_AMPHAROS
    .2byte 0 @ unused
    .2byte 275
    .2byte 2
    .2byte 283
    .2byte -1
    .2byte 0 @ padding
    @ BELLOSSOM
    .string "FLOWER$", 12
    .2byte 4 @ in decimeters
    .2byte 58 @ in hectograms
    .4byte kPokedexDescription1_BELLOSSOM
    .4byte kPokedexDescription2_BELLOSSOM
    .2byte 0 @ unused
    .2byte 472
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MARILL
    .string "AQUA MOUSE$", 12
    .2byte 4 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte kPokedexDescription1_MARILL
    .4byte kPokedexDescription2_MARILL
    .2byte 0 @ unused
    .2byte 476
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ AZUMARILL
    .string "AQUA RABBIT$", 12
    .2byte 8 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte kPokedexDescription1_AZUMARILL
    .4byte kPokedexDescription2_AZUMARILL
    .2byte 0 @ unused
    .2byte 448
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SUDOWOODO
    .string "IMITATION$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte kPokedexDescription1_SUDOWOODO
    .4byte kPokedexDescription2_SUDOWOODO
    .2byte 0 @ unused
    .2byte 305
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ POLITOED
    .string "FROG$", 12
    .2byte 11 @ in decimeters
    .2byte 339 @ in hectograms
    .4byte kPokedexDescription1_POLITOED
    .4byte kPokedexDescription2_POLITOED
    .2byte 0 @ unused
    .2byte 289
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HOPPIP
    .string "COTTONWEED$", 12
    .2byte 4 @ in decimeters
    .2byte 5 @ in hectograms
    .4byte kPokedexDescription1_HOPPIP
    .4byte kPokedexDescription2_HOPPIP
    .2byte 0 @ unused
    .2byte 562
    .2byte -7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SKIPLOOM
    .string "COTTONWEED$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte kPokedexDescription1_SKIPLOOM
    .4byte kPokedexDescription2_SKIPLOOM
    .2byte 0 @ unused
    .2byte 387
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ JUMPLUFF
    .string "COTTONWEED$", 12
    .2byte 8 @ in decimeters
    .2byte 30 @ in hectograms
    .4byte kPokedexDescription1_JUMPLUFF
    .4byte kPokedexDescription2_JUMPLUFF
    .2byte 0 @ unused
    .2byte 418
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ AIPOM
    .string "LONG TAIL$", 12
    .2byte 8 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte kPokedexDescription1_AIPOM
    .4byte kPokedexDescription2_AIPOM
    .2byte 0 @ unused
    .2byte 363
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SUNKERN
    .string "SEED$", 12
    .2byte 3 @ in decimeters
    .2byte 18 @ in hectograms
    .4byte kPokedexDescription1_SUNKERN
    .4byte kPokedexDescription2_SUNKERN
    .2byte 0 @ unused
    .2byte 541
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SUNFLORA
    .string "SUN$", 12
    .2byte 8 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte kPokedexDescription1_SUNFLORA
    .4byte kPokedexDescription2_SUNFLORA
    .2byte 0 @ unused
    .2byte 374
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ YANMA
    .string "CLEAR WING$", 12
    .2byte 12 @ in decimeters
    .2byte 380 @ in hectograms
    .4byte kPokedexDescription1_YANMA
    .4byte kPokedexDescription2_YANMA
    .2byte 0 @ unused
    .2byte 274
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WOOPER
    .string "WATER FISH$", 12
    .2byte 4 @ in decimeters
    .2byte 85 @ in hectograms
    .4byte kPokedexDescription1_WOOPER
    .4byte kPokedexDescription2_WOOPER
    .2byte 0 @ unused
    .2byte 479
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ QUAGSIRE
    .string "WATER FISH$", 12
    .2byte 14 @ in decimeters
    .2byte 750 @ in hectograms
    .4byte kPokedexDescription1_QUAGSIRE
    .4byte kPokedexDescription2_QUAGSIRE
    .2byte 0 @ unused
    .2byte 273
    .2byte 4
    .2byte 273
    .2byte -2
    .2byte 0 @ padding
    @ ESPEON
    .string "SUN$", 12
    .2byte 9 @ in decimeters
    .2byte 265 @ in hectograms
    .4byte kPokedexDescription1_ESPEON
    .4byte kPokedexDescription2_ESPEON
    .2byte 0 @ unused
    .2byte 363
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ UMBREON
    .string "MOONLIGHT$", 12
    .2byte 10 @ in decimeters
    .2byte 270 @ in hectograms
    .4byte kPokedexDescription1_UMBREON
    .4byte kPokedexDescription2_UMBREON
    .2byte 0 @ unused
    .2byte 317
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MURKROW
    .string "DARKNESS$", 12
    .2byte 5 @ in decimeters
    .2byte 21 @ in hectograms
    .4byte kPokedexDescription1_MURKROW
    .4byte kPokedexDescription2_MURKROW
    .2byte 0 @ unused
    .2byte 401
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SLOWKING
    .string "ROYAL$", 12
    .2byte 20 @ in decimeters
    .2byte 795 @ in hectograms
    .4byte kPokedexDescription1_SLOWKING
    .4byte kPokedexDescription2_SLOWKING
    .2byte 0 @ unused
    .2byte 265
    .2byte -1
    .2byte 330
    .2byte 4
    .2byte 0 @ padding
    @ MISDREAVUS
    .string "SCREECH$", 12
    .2byte 7 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte kPokedexDescription1_MISDREAVUS
    .4byte kPokedexDescription2_MISDREAVUS
    .2byte 0 @ unused
    .2byte 407
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ UNOWN
    .string "SYMBOL$", 12
    .2byte 5 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte kPokedexDescription1_UNOWN
    .4byte kPokedexDescription2_UNOWN
    .2byte 0 @ unused
    .2byte 411
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WOBBUFFET
    .string "PATIENT$", 12
    .2byte 13 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte kPokedexDescription1_WOBBUFFET
    .4byte kPokedexDescription2_WOBBUFFET
    .2byte 0 @ unused
    .2byte 274
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GIRAFARIG
    .string "LONG NECK$", 12
    .2byte 15 @ in decimeters
    .2byte 415 @ in hectograms
    .4byte kPokedexDescription1_GIRAFARIG
    .4byte kPokedexDescription2_GIRAFARIG
    .2byte 0 @ unused
    .2byte 281
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PINECO
    .string "BAGWORM$", 12
    .2byte 6 @ in decimeters
    .2byte 72 @ in hectograms
    .4byte kPokedexDescription1_PINECO
    .4byte kPokedexDescription2_PINECO
    .2byte 0 @ unused
    .2byte 445
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ FORRETRESS
    .string "BAGWORM$", 12
    .2byte 12 @ in decimeters
    .2byte 1258 @ in hectograms
    .4byte kPokedexDescription1_FORRETRESS
    .4byte kPokedexDescription2_FORRETRESS
    .2byte 0 @ unused
    .2byte 293
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DUNSPARCE
    .string "LAND SNAKE$", 12
    .2byte 15 @ in decimeters
    .2byte 140 @ in hectograms
    .4byte kPokedexDescription1_DUNSPARCE
    .4byte kPokedexDescription2_DUNSPARCE
    .2byte 0 @ unused
    .2byte 284
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GLIGAR
    .string "FLYSCORPION$", 12
    .2byte 11 @ in decimeters
    .2byte 648 @ in hectograms
    .4byte kPokedexDescription1_GLIGAR
    .4byte kPokedexDescription2_GLIGAR
    .2byte 0 @ unused
    .2byte 350
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ STEELIX
    .string "IRON SNAKE$", 12
    .2byte 92 @ in decimeters
    .2byte 4000 @ in hectograms
    .4byte kPokedexDescription1_STEELIX
    .4byte kPokedexDescription2_STEELIX
    .2byte 0 @ unused
    .2byte 278
    .2byte -1
    .2byte 557
    .2byte 13
    .2byte 0 @ padding
    @ SNUBBULL
    .string "FAIRY$", 12
    .2byte 6 @ in decimeters
    .2byte 78 @ in hectograms
    .4byte kPokedexDescription1_SNUBBULL
    .4byte kPokedexDescription2_SNUBBULL
    .2byte 0 @ unused
    .2byte 465
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GRANBULL
    .string "FAIRY$", 12
    .2byte 14 @ in decimeters
    .2byte 487 @ in hectograms
    .4byte kPokedexDescription1_GRANBULL
    .4byte kPokedexDescription2_GRANBULL
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ QWILFISH
    .string "BALLOON$", 12
    .2byte 5 @ in decimeters
    .2byte 39 @ in hectograms
    .4byte kPokedexDescription1_QWILFISH
    .4byte kPokedexDescription2_QWILFISH
    .2byte 0 @ unused
    .2byte 430
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SCIZOR
    .string "PINCER$", 12
    .2byte 18 @ in decimeters
    .2byte 1180 @ in hectograms
    .4byte kPokedexDescription1_SCIZOR
    .4byte kPokedexDescription2_SCIZOR
    .2byte 0 @ unused
    .2byte 282
    .2byte 0
    .2byte 282
    .2byte 0
    .2byte 0 @ padding
    @ SHUCKLE
    .string "MOLD$", 12
    .2byte 6 @ in decimeters
    .2byte 205 @ in hectograms
    .4byte kPokedexDescription1_SHUCKLE
    .4byte kPokedexDescription2_SHUCKLE
    .2byte 0 @ unused
    .2byte 485
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HERACROSS
    .string "SINGLE HORN$", 12
    .2byte 15 @ in decimeters
    .2byte 540 @ in hectograms
    .4byte kPokedexDescription1_HERACROSS
    .4byte kPokedexDescription2_HERACROSS
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 283
    .2byte -2
    .2byte 0 @ padding
    @ SNEASEL
    .string "SHARP CLAW$", 12
    .2byte 9 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte kPokedexDescription1_SNEASEL
    .4byte kPokedexDescription2_SNEASEL
    .2byte 0 @ unused
    .2byte 413
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TEDDIURSA
    .string "LITTLE BEAR$", 12
    .2byte 6 @ in decimeters
    .2byte 88 @ in hectograms
    .4byte kPokedexDescription1_TEDDIURSA
    .4byte kPokedexDescription2_TEDDIURSA
    .2byte 0 @ unused
    .2byte 455
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ URSARING
    .string "HIBERNATOR$", 12
    .2byte 18 @ in decimeters
    .2byte 1258 @ in hectograms
    .4byte kPokedexDescription1_URSARING
    .4byte kPokedexDescription2_URSARING
    .2byte 0 @ unused
    .2byte 275
    .2byte 0
    .2byte 280
    .2byte 0
    .2byte 0 @ padding
    @ SLUGMA
    .string "LAVA$", 12
    .2byte 7 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte kPokedexDescription1_SLUGMA
    .4byte kPokedexDescription2_SLUGMA
    .2byte 0 @ unused
    .2byte 329
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MAGCARGO
    .string "LAVA$", 12
    .2byte 8 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte kPokedexDescription1_MAGCARGO
    .4byte kPokedexDescription2_MAGCARGO
    .2byte 0 @ unused
    .2byte 332
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SWINUB
    .string "PIG$", 12
    .2byte 4 @ in decimeters
    .2byte 65 @ in hectograms
    .4byte kPokedexDescription1_SWINUB
    .4byte kPokedexDescription2_SWINUB
    .2byte 0 @ unused
    .2byte 324
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PILOSWINE
    .string "SWINE$", 12
    .2byte 11 @ in decimeters
    .2byte 558 @ in hectograms
    .4byte kPokedexDescription1_PILOSWINE
    .4byte kPokedexDescription2_PILOSWINE
    .2byte 0 @ unused
    .2byte 306
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CORSOLA
    .string "CORAL$", 12
    .2byte 6 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte kPokedexDescription1_CORSOLA
    .4byte kPokedexDescription2_CORSOLA
    .2byte 0 @ unused
    .2byte 410
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ REMORAID
    .string "JET$", 12
    .2byte 6 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte kPokedexDescription1_REMORAID
    .4byte kPokedexDescription2_REMORAID
    .2byte 0 @ unused
    .2byte 316
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ OCTILLERY
    .string "JET$", 12
    .2byte 9 @ in decimeters
    .2byte 285 @ in hectograms
    .4byte kPokedexDescription1_OCTILLERY
    .4byte kPokedexDescription2_OCTILLERY
    .2byte 0 @ unused
    .2byte 296
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DELIBIRD
    .string "DELIVERY$", 12
    .2byte 9 @ in decimeters
    .2byte 160 @ in hectograms
    .4byte kPokedexDescription1_DELIBIRD
    .4byte kPokedexDescription2_DELIBIRD
    .2byte 0 @ unused
    .2byte 293
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MANTINE
    .string "KITE$", 12
    .2byte 21 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte kPokedexDescription1_MANTINE
    .4byte kPokedexDescription2_MANTINE
    .2byte 0 @ unused
    .2byte 275
    .2byte 0
    .2byte 360
    .2byte 6
    .2byte 0 @ padding
    @ SKARMORY
    .string "ARMOR BIRD$", 12
    .2byte 17 @ in decimeters
    .2byte 505 @ in hectograms
    .4byte kPokedexDescription1_SKARMORY
    .4byte kPokedexDescription2_SKARMORY
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 276
    .2byte 0
    .2byte 0 @ padding
    @ HOUNDOUR
    .string "DARK$", 12
    .2byte 6 @ in decimeters
    .2byte 108 @ in hectograms
    .4byte kPokedexDescription1_HOUNDOUR
    .4byte kPokedexDescription2_HOUNDOUR
    .2byte 0 @ unused
    .2byte 393
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HOUNDOOM
    .string "DARK$", 12
    .2byte 14 @ in decimeters
    .2byte 350 @ in hectograms
    .4byte kPokedexDescription1_HOUNDOOM
    .4byte kPokedexDescription2_HOUNDOOM
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KINGDRA
    .string "DRAGON$", 12
    .2byte 18 @ in decimeters
    .2byte 1520 @ in hectograms
    .4byte kPokedexDescription1_KINGDRA
    .4byte kPokedexDescription2_KINGDRA
    .2byte 0 @ unused
    .2byte 257
    .2byte 1
    .2byte 293
    .2byte 1
    .2byte 0 @ padding
    @ PHANPY
    .string "LONG NOSE$", 12
    .2byte 5 @ in decimeters
    .2byte 335 @ in hectograms
    .4byte kPokedexDescription1_PHANPY
    .4byte kPokedexDescription2_PHANPY
    .2byte 0 @ unused
    .2byte 465
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DONPHAN
    .string "ARMOR$", 12
    .2byte 11 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte kPokedexDescription1_DONPHAN
    .4byte kPokedexDescription2_DONPHAN
    .2byte 0 @ unused
    .2byte 313
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PORYGON2
    .string "VIRTUAL$", 12
    .2byte 6 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte kPokedexDescription1_PORYGON2
    .4byte kPokedexDescription2_PORYGON2
    .2byte 0 @ unused
    .2byte 320
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ STANTLER
    .string "BIG HORN$", 12
    .2byte 14 @ in decimeters
    .2byte 712 @ in hectograms
    .4byte kPokedexDescription1_STANTLER
    .4byte kPokedexDescription2_STANTLER
    .2byte 0 @ unused
    .2byte 277
    .2byte -1
    .2byte 277
    .2byte 0
    .2byte 0 @ padding
    @ SMEARGLE
    .string "PAINTER$", 12
    .2byte 12 @ in decimeters
    .2byte 580 @ in hectograms
    .4byte kPokedexDescription1_SMEARGLE
    .4byte kPokedexDescription2_SMEARGLE
    .2byte 0 @ unused
    .2byte 287
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TYROGUE
    .string "SCUFFLE$", 12
    .2byte 7 @ in decimeters
    .2byte 210 @ in hectograms
    .4byte kPokedexDescription1_TYROGUE
    .4byte kPokedexDescription2_TYROGUE
    .2byte 0 @ unused
    .2byte 292
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HITMONTOP
    .string "HANDSTAND$", 12
    .2byte 14 @ in decimeters
    .2byte 480 @ in hectograms
    .4byte kPokedexDescription1_HITMONTOP
    .4byte kPokedexDescription2_HITMONTOP
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 257
    .2byte -2
    .2byte 0 @ padding
    @ SMOOCHUM
    .string "KISS$", 12
    .2byte 4 @ in decimeters
    .2byte 60 @ in hectograms
    .4byte kPokedexDescription1_SMOOCHUM
    .4byte kPokedexDescription2_SMOOCHUM
    .2byte 0 @ unused
    .2byte 440
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ELEKID
    .string "ELECTRIC$", 12
    .2byte 6 @ in decimeters
    .2byte 235 @ in hectograms
    .4byte kPokedexDescription1_ELEKID
    .4byte kPokedexDescription2_ELEKID
    .2byte 0 @ unused
    .2byte 363
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MAGBY
    .string "LIVE COAL$", 12
    .2byte 7 @ in decimeters
    .2byte 214 @ in hectograms
    .4byte kPokedexDescription1_MAGBY
    .4byte kPokedexDescription2_MAGBY
    .2byte 0 @ unused
    .2byte 284
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MILTANK
    .string "MILK COW$", 12
    .2byte 12 @ in decimeters
    .2byte 755 @ in hectograms
    .4byte kPokedexDescription1_MILTANK
    .4byte kPokedexDescription2_MILTANK
    .2byte 0 @ unused
    .2byte 280
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BLISSEY
    .string "HAPPINESS$", 12
    .2byte 15 @ in decimeters
    .2byte 468 @ in hectograms
    .4byte kPokedexDescription1_BLISSEY
    .4byte kPokedexDescription2_BLISSEY
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 310
    .2byte 3
    .2byte 0 @ padding
    @ RAIKOU
    .string "THUNDER$", 12
    .2byte 19 @ in decimeters
    .2byte 1780 @ in hectograms
    .4byte kPokedexDescription1_RAIKOU
    .4byte kPokedexDescription2_RAIKOU
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 359
    .2byte 6
    .2byte 0 @ padding
    @ ENTEI
    .string "VOLCANO$", 12
    .2byte 21 @ in decimeters
    .2byte 1980 @ in hectograms
    .4byte kPokedexDescription1_ENTEI
    .4byte kPokedexDescription2_ENTEI
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 370
    .2byte 7
    .2byte 0 @ padding
    @ SUICUNE
    .string "AURORA$", 12
    .2byte 20 @ in decimeters
    .2byte 1870 @ in hectograms
    .4byte kPokedexDescription1_SUICUNE
    .4byte kPokedexDescription2_SUICUNE
    .2byte 0 @ unused
    .2byte 286
    .2byte 0
    .2byte 371
    .2byte 7
    .2byte 0 @ padding
    @ LARVITAR
    .string "ROCK SKIN$", 12
    .2byte 6 @ in decimeters
    .2byte 720 @ in hectograms
    .4byte kPokedexDescription1_LARVITAR
    .4byte kPokedexDescription2_LARVITAR
    .2byte 0 @ unused
    .2byte 472
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PUPITAR
    .string "HARD SHELL$", 12
    .2byte 12 @ in decimeters
    .2byte 1520 @ in hectograms
    .4byte kPokedexDescription1_PUPITAR
    .4byte kPokedexDescription2_PUPITAR
    .2byte 0 @ unused
    .2byte 292
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TYRANITAR
    .string "ARMOR$", 12
    .2byte 20 @ in decimeters
    .2byte 2020 @ in hectograms
    .4byte kPokedexDescription1_TYRANITAR
    .4byte kPokedexDescription2_TYRANITAR
    .2byte 0 @ unused
    .2byte 285
    .2byte 0
    .2byte 383
    .2byte 7
    .2byte 0 @ padding
    @ LUGIA
    .string "DIVING$", 12
    .2byte 52 @ in decimeters
    .2byte 2160 @ in hectograms
    .4byte kPokedexDescription1_LUGIA
    .4byte kPokedexDescription2_LUGIA
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 742
    .2byte 18
    .2byte 0 @ padding
    @ HO_OH
    .string "RAINBOW$", 12
    .2byte 38 @ in decimeters
    .2byte 1990 @ in hectograms
    .4byte kPokedexDescription1_HO_OH
    .4byte kPokedexDescription2_HO_OH
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 620
    .2byte 16
    .2byte 0 @ padding
    @ CELEBI
    .string "TIME TRAVEL$", 12
    .2byte 6 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte kPokedexDescription1_CELEBI
    .4byte kPokedexDescription2_CELEBI
    .2byte 0 @ unused
    .2byte 393
    .2byte -10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TREECKO
    .string "WOOD GECKO$", 12
    .2byte 5 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte kPokedexDescription1_TREECKO
    .4byte kPokedexDescription2_TREECKO
    .2byte 0 @ unused
    .2byte 541
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GROVYLE
    .string "WOOD GECKO$", 12
    .2byte 9 @ in decimeters
    .2byte 216 @ in hectograms
    .4byte kPokedexDescription1_GROVYLE
    .4byte kPokedexDescription2_GROVYLE
    .2byte 0 @ unused
    .2byte 360
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SCEPTILE
    .string "FOREST$", 12
    .2byte 17 @ in decimeters
    .2byte 522 @ in hectograms
    .4byte kPokedexDescription1_SCEPTILE
    .4byte kPokedexDescription2_SCEPTILE
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 313
    .2byte 3
    .2byte 0 @ padding
    @ TORCHIC
    .string "CHICK$", 12
    .2byte 4 @ in decimeters
    .2byte 25 @ in hectograms
    .4byte kPokedexDescription1_TORCHIC
    .4byte kPokedexDescription2_TORCHIC
    .2byte 0 @ unused
    .2byte 566
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ COMBUSKEN
    .string "YOUNG FOWL$", 12
    .2byte 9 @ in decimeters
    .2byte 195 @ in hectograms
    .4byte kPokedexDescription1_COMBUSKEN
    .4byte kPokedexDescription2_COMBUSKEN
    .2byte 0 @ unused
    .2byte 343
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BLAZIKEN
    .string "BLAZE$", 12
    .2byte 19 @ in decimeters
    .2byte 520 @ in hectograms
    .4byte kPokedexDescription1_BLAZIKEN
    .4byte kPokedexDescription2_BLAZIKEN
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 314
    .2byte 3
    .2byte 0 @ padding
    @ MUDKIP
    .string "MUD FISH$", 12
    .2byte 4 @ in decimeters
    .2byte 76 @ in hectograms
    .4byte kPokedexDescription1_MUDKIP
    .4byte kPokedexDescription2_MUDKIP
    .2byte 0 @ unused
    .2byte 535
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MARSHTOMP
    .string "MUD FISH$", 12
    .2byte 7 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte kPokedexDescription1_MARSHTOMP
    .4byte kPokedexDescription2_MARSHTOMP
    .2byte 0 @ unused
    .2byte 340
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SWAMPERT
    .string "MUD FISH$", 12
    .2byte 15 @ in decimeters
    .2byte 819 @ in hectograms
    .4byte kPokedexDescription1_SWAMPERT
    .4byte kPokedexDescription2_SWAMPERT
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 282
    .2byte -2
    .2byte 0 @ padding
    @ POOCHYENA
    .string "BITE$", 12
    .2byte 5 @ in decimeters
    .2byte 136 @ in hectograms
    .4byte kPokedexDescription1_POOCHYENA
    .4byte kPokedexDescription2_POOCHYENA
    .2byte 0 @ unused
    .2byte 481
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MIGHTYENA
    .string "BITE$", 12
    .2byte 10 @ in decimeters
    .2byte 370 @ in hectograms
    .4byte kPokedexDescription1_MIGHTYENA
    .4byte kPokedexDescription2_MIGHTYENA
    .2byte 0 @ unused
    .2byte 359
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ZIGZAGOON
    .string "TINYRACCOON$", 12
    .2byte 4 @ in decimeters
    .2byte 175 @ in hectograms
    .4byte kPokedexDescription1_ZIGZAGOON
    .4byte kPokedexDescription2_ZIGZAGOON
    .2byte 0 @ unused
    .2byte 560
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LINOONE
    .string "RUSHING$", 12
    .2byte 5 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte kPokedexDescription1_LINOONE
    .4byte kPokedexDescription2_LINOONE
    .2byte 0 @ unused
    .2byte 321
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WURMPLE
    .string "WORM$", 12
    .2byte 3 @ in decimeters
    .2byte 36 @ in hectograms
    .4byte kPokedexDescription1_WURMPLE
    .4byte kPokedexDescription2_WURMPLE
    .2byte 0 @ unused
    .2byte 711
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SILCOON
    .string "COCOON$", 12
    .2byte 6 @ in decimeters
    .2byte 100 @ in hectograms
    .4byte kPokedexDescription1_SILCOON
    .4byte kPokedexDescription2_SILCOON
    .2byte 0 @ unused
    .2byte 431
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BEAUTIFLY
    .string "BUTTERFLY$", 12
    .2byte 10 @ in decimeters
    .2byte 284 @ in hectograms
    .4byte kPokedexDescription1_BEAUTIFLY
    .4byte kPokedexDescription2_BEAUTIFLY
    .2byte 0 @ unused
    .2byte 298
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CASCOON
    .string "COCOON$", 12
    .2byte 7 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte kPokedexDescription1_CASCOON
    .4byte kPokedexDescription2_CASCOON
    .2byte 0 @ unused
    .2byte 391
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DUSTOX
    .string "POISON MOTH$", 12
    .2byte 12 @ in decimeters
    .2byte 316 @ in hectograms
    .4byte kPokedexDescription1_DUSTOX
    .4byte kPokedexDescription2_DUSTOX
    .2byte 0 @ unused
    .2byte 269
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LOTAD
    .string "WATER WEED$", 12
    .2byte 5 @ in decimeters
    .2byte 26 @ in hectograms
    .4byte kPokedexDescription1_LOTAD
    .4byte kPokedexDescription2_LOTAD
    .2byte 0 @ unused
    .2byte 406
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LOMBRE
    .string "JOLLY$", 12
    .2byte 12 @ in decimeters
    .2byte 325 @ in hectograms
    .4byte kPokedexDescription1_LOMBRE
    .4byte kPokedexDescription2_LOMBRE
    .2byte 0 @ unused
    .2byte 277
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LUDICOLO
    .string "CAREFREE$", 12
    .2byte 15 @ in decimeters
    .2byte 550 @ in hectograms
    .4byte kPokedexDescription1_LUDICOLO
    .4byte kPokedexDescription2_LUDICOLO
    .2byte 0 @ unused
    .2byte 283
    .2byte 0
    .2byte 282
    .2byte 0
    .2byte 0 @ padding
    @ SEEDOT
    .string "ACORN$", 12
    .2byte 5 @ in decimeters
    .2byte 40 @ in hectograms
    .4byte kPokedexDescription1_SEEDOT
    .4byte kPokedexDescription2_SEEDOT
    .2byte 0 @ unused
    .2byte 472
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NUZLEAF
    .string "WILY$", 12
    .2byte 10 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte kPokedexDescription1_NUZLEAF
    .4byte kPokedexDescription2_NUZLEAF
    .2byte 0 @ unused
    .2byte 299
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SHIFTRY
    .string "WICKED$", 12
    .2byte 13 @ in decimeters
    .2byte 596 @ in hectograms
    .4byte kPokedexDescription1_SHIFTRY
    .4byte kPokedexDescription2_SHIFTRY
    .2byte 0 @ unused
    .2byte 290
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TAILLOW
    .string "TINYSWALLOW$", 12
    .2byte 3 @ in decimeters
    .2byte 23 @ in hectograms
    .4byte kPokedexDescription1_TAILLOW
    .4byte kPokedexDescription2_TAILLOW
    .2byte 0 @ unused
    .2byte 465
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SWELLOW
    .string "SWALLOW$", 12
    .2byte 7 @ in decimeters
    .2byte 198 @ in hectograms
    .4byte kPokedexDescription1_SWELLOW
    .4byte kPokedexDescription2_SWELLOW
    .2byte 0 @ unused
    .2byte 428
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WINGULL
    .string "SEAGULL$", 12
    .2byte 6 @ in decimeters
    .2byte 95 @ in hectograms
    .4byte kPokedexDescription1_WINGULL
    .4byte kPokedexDescription2_WINGULL
    .2byte 0 @ unused
    .2byte 295
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ PELIPPER
    .string "WATER BIRD$", 12
    .2byte 12 @ in decimeters
    .2byte 280 @ in hectograms
    .4byte kPokedexDescription1_PELIPPER
    .4byte kPokedexDescription2_PELIPPER
    .2byte 0 @ unused
    .2byte 288
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ RALTS
    .string "FEELING$", 12
    .2byte 4 @ in decimeters
    .2byte 66 @ in hectograms
    .4byte kPokedexDescription1_RALTS
    .4byte kPokedexDescription2_RALTS
    .2byte 0 @ unused
    .2byte 457
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KIRLIA
    .string "EMOTION$", 12
    .2byte 8 @ in decimeters
    .2byte 202 @ in hectograms
    .4byte kPokedexDescription1_KIRLIA
    .4byte kPokedexDescription2_KIRLIA
    .2byte 0 @ unused
    .2byte 354
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GARDEVOIR
    .string "EMBRACE$", 12
    .2byte 16 @ in decimeters
    .2byte 484 @ in hectograms
    .4byte kPokedexDescription1_GARDEVOIR
    .4byte kPokedexDescription2_GARDEVOIR
    .2byte 0 @ unused
    .2byte 277
    .2byte 0
    .2byte 276
    .2byte -1
    .2byte 0 @ padding
    @ SURSKIT
    .string "POND SKATER$", 12
    .2byte 5 @ in decimeters
    .2byte 17 @ in hectograms
    .4byte kPokedexDescription1_SURSKIT
    .4byte kPokedexDescription2_SURSKIT
    .2byte 0 @ unused
    .2byte 375
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MASQUERAIN
    .string "EYEBALL$", 12
    .2byte 8 @ in decimeters
    .2byte 36 @ in hectograms
    .4byte kPokedexDescription1_MASQUERAIN
    .4byte kPokedexDescription2_MASQUERAIN
    .2byte 0 @ unused
    .2byte 378
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SHROOMISH
    .string "MUSHROOM$", 12
    .2byte 4 @ in decimeters
    .2byte 45 @ in hectograms
    .4byte kPokedexDescription1_SHROOMISH
    .4byte kPokedexDescription2_SHROOMISH
    .2byte 0 @ unused
    .2byte 513
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BRELOOM
    .string "MUSHROOM$", 12
    .2byte 12 @ in decimeters
    .2byte 392 @ in hectograms
    .4byte kPokedexDescription1_BRELOOM
    .4byte kPokedexDescription2_BRELOOM
    .2byte 0 @ unused
    .2byte 324
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SLAKOTH
    .string "SLACKER$", 12
    .2byte 8 @ in decimeters
    .2byte 240 @ in hectograms
    .4byte kPokedexDescription1_SLAKOTH
    .4byte kPokedexDescription2_SLAKOTH
    .2byte 0 @ unused
    .2byte 291
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VIGOROTH
    .string "WILD MONKEY$", 12
    .2byte 14 @ in decimeters
    .2byte 465 @ in hectograms
    .4byte kPokedexDescription1_VIGOROTH
    .4byte kPokedexDescription2_VIGOROTH
    .2byte 0 @ unused
    .2byte 301
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SLAKING
    .string "LAZY$", 12
    .2byte 20 @ in decimeters
    .2byte 1305 @ in hectograms
    .4byte kPokedexDescription1_SLAKING
    .4byte kPokedexDescription2_SLAKING
    .2byte 0 @ unused
    .2byte 277
    .2byte 5
    .2byte 326
    .2byte 3
    .2byte 0 @ padding
    @ NINCADA
    .string "TRAINEE$", 12
    .2byte 5 @ in decimeters
    .2byte 55 @ in hectograms
    .4byte kPokedexDescription1_NINCADA
    .4byte kPokedexDescription2_NINCADA
    .2byte 0 @ unused
    .2byte 405
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NINJASK
    .string "NINJA$", 12
    .2byte 8 @ in decimeters
    .2byte 120 @ in hectograms
    .4byte kPokedexDescription1_NINJASK
    .4byte kPokedexDescription2_NINJASK
    .2byte 0 @ unused
    .2byte 383
    .2byte -9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SHEDINJA
    .string "SHED$", 12
    .2byte 8 @ in decimeters
    .2byte 12 @ in hectograms
    .4byte kPokedexDescription1_SHEDINJA
    .4byte kPokedexDescription2_SHEDINJA
    .2byte 0 @ unused
    .2byte 372
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WHISMUR
    .string "WHISPER$", 12
    .2byte 6 @ in decimeters
    .2byte 163 @ in hectograms
    .4byte kPokedexDescription1_WHISMUR
    .4byte kPokedexDescription2_WHISMUR
    .2byte 0 @ unused
    .2byte 373
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LOUDRED
    .string "BIG VOICE$", 12
    .2byte 10 @ in decimeters
    .2byte 405 @ in hectograms
    .4byte kPokedexDescription1_LOUDRED
    .4byte kPokedexDescription2_LOUDRED
    .2byte 0 @ unused
    .2byte 356
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ EXPLOUD
    .string "LOUD NOISE$", 12
    .2byte 15 @ in decimeters
    .2byte 840 @ in hectograms
    .4byte kPokedexDescription1_EXPLOUD
    .4byte kPokedexDescription2_EXPLOUD
    .2byte 0 @ unused
    .2byte 284
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MAKUHITA
    .string "GUTS$", 12
    .2byte 10 @ in decimeters
    .2byte 864 @ in hectograms
    .4byte kPokedexDescription1_MAKUHITA
    .4byte kPokedexDescription2_MAKUHITA
    .2byte 0 @ unused
    .2byte 256
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HARIYAMA
    .string "ARM THRUST$", 12
    .2byte 23 @ in decimeters
    .2byte 2538 @ in hectograms
    .4byte kPokedexDescription1_HARIYAMA
    .4byte kPokedexDescription2_HARIYAMA
    .2byte 0 @ unused
    .2byte 268
    .2byte -1
    .2byte 375
    .2byte 6
    .2byte 0 @ padding
    @ AZURILL
    .string "POLKA DOT$", 12
    .2byte 2 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte kPokedexDescription1_AZURILL
    .4byte kPokedexDescription2_AZURILL
    .2byte 0 @ unused
    .2byte 603
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ NOSEPASS
    .string "COMPASS$", 12
    .2byte 10 @ in decimeters
    .2byte 970 @ in hectograms
    .4byte kPokedexDescription1_NOSEPASS
    .4byte kPokedexDescription2_NOSEPASS
    .2byte 0 @ unused
    .2byte 256
    .2byte 9
    .2byte 289
    .2byte 1
    .2byte 0 @ padding
    @ SKITTY
    .string "KITTEN$", 12
    .2byte 6 @ in decimeters
    .2byte 110 @ in hectograms
    .4byte kPokedexDescription1_SKITTY
    .4byte kPokedexDescription2_SKITTY
    .2byte 0 @ unused
    .2byte 492
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DELCATTY
    .string "PRIM$", 12
    .2byte 11 @ in decimeters
    .2byte 326 @ in hectograms
    .4byte kPokedexDescription1_DELCATTY
    .4byte kPokedexDescription2_DELCATTY
    .2byte 0 @ unused
    .2byte 322
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SABLEYE
    .string "DARKNESS$", 12
    .2byte 5 @ in decimeters
    .2byte 110 @ in hectograms
    .4byte kPokedexDescription1_SABLEYE
    .4byte kPokedexDescription2_SABLEYE
    .2byte 0 @ unused
    .2byte 451
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MAWILE
    .string "DECEIVER$", 12
    .2byte 6 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte kPokedexDescription1_MAWILE
    .4byte kPokedexDescription2_MAWILE
    .2byte 0 @ unused
    .2byte 466
    .2byte 15
    .2byte 256
    .2byte -3
    .2byte 0 @ padding
    @ ARON
    .string "IRON ARMOR$", 12
    .2byte 4 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte kPokedexDescription1_ARON
    .4byte kPokedexDescription2_ARON
    .2byte 0 @ unused
    .2byte 419
    .2byte 21
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LAIRON
    .string "IRON ARMOR$", 12
    .2byte 9 @ in decimeters
    .2byte 1200 @ in hectograms
    .4byte kPokedexDescription1_LAIRON
    .4byte kPokedexDescription2_LAIRON
    .2byte 0 @ unused
    .2byte 275
    .2byte 11
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ AGGRON
    .string "IRON ARMOR$", 12
    .2byte 21 @ in decimeters
    .2byte 3600 @ in hectograms
    .4byte kPokedexDescription1_AGGRON
    .4byte kPokedexDescription2_AGGRON
    .2byte 0 @ unused
    .2byte 274
    .2byte -1
    .2byte 374
    .2byte 7
    .2byte 0 @ padding
    @ MEDITITE
    .string "MEDITATE$", 12
    .2byte 6 @ in decimeters
    .2byte 112 @ in hectograms
    .4byte kPokedexDescription1_MEDITITE
    .4byte kPokedexDescription2_MEDITITE
    .2byte 0 @ unused
    .2byte 465
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MEDICHAM
    .string "MEDITATE$", 12
    .2byte 13 @ in decimeters
    .2byte 315 @ in hectograms
    .4byte kPokedexDescription1_MEDICHAM
    .4byte kPokedexDescription2_MEDICHAM
    .2byte 0 @ unused
    .2byte 298
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ELECTRIKE
    .string "LIGHTNING$", 12
    .2byte 6 @ in decimeters
    .2byte 152 @ in hectograms
    .4byte kPokedexDescription1_ELECTRIKE
    .4byte kPokedexDescription2_ELECTRIKE
    .2byte 0 @ unused
    .2byte 290
    .2byte 16
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MANECTRIC
    .string "DISCHARGE$", 12
    .2byte 15 @ in decimeters
    .2byte 402 @ in hectograms
    .4byte kPokedexDescription1_MANECTRIC
    .4byte kPokedexDescription2_MANECTRIC
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 257
    .2byte -2
    .2byte 0 @ padding
    @ PLUSLE
    .string "CHEERING$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte kPokedexDescription1_PLUSLE
    .4byte kPokedexDescription2_PLUSLE
    .2byte 0 @ unused
    .2byte 515
    .2byte -9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MINUN
    .string "CHEERING$", 12
    .2byte 4 @ in decimeters
    .2byte 42 @ in hectograms
    .4byte kPokedexDescription1_MINUN
    .4byte kPokedexDescription2_MINUN
    .2byte 0 @ unused
    .2byte 512
    .2byte -7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VOLBEAT
    .string "FIREFLY$", 12
    .2byte 7 @ in decimeters
    .2byte 177 @ in hectograms
    .4byte kPokedexDescription1_VOLBEAT
    .4byte kPokedexDescription2_VOLBEAT
    .2byte 0 @ unused
    .2byte 442
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ILLUMISE
    .string "FIREFLY$", 12
    .2byte 6 @ in decimeters
    .2byte 177 @ in hectograms
    .4byte kPokedexDescription1_ILLUMISE
    .4byte kPokedexDescription2_ILLUMISE
    .2byte 0 @ unused
    .2byte 572
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ROSELIA
    .string "THORN$", 12
    .2byte 3 @ in decimeters
    .2byte 20 @ in hectograms
    .4byte kPokedexDescription1_ROSELIA
    .4byte kPokedexDescription2_ROSELIA
    .2byte 0 @ unused
    .2byte 677
    .2byte 20
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GULPIN
    .string "STOMACH$", 12
    .2byte 4 @ in decimeters
    .2byte 103 @ in hectograms
    .4byte kPokedexDescription1_GULPIN
    .4byte kPokedexDescription2_GULPIN
    .2byte 0 @ unused
    .2byte 593
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SWALOT
    .string "POISON BAG$", 12
    .2byte 17 @ in decimeters
    .2byte 800 @ in hectograms
    .4byte kPokedexDescription1_SWALOT
    .4byte kPokedexDescription2_SWALOT
    .2byte 0 @ unused
    .2byte 256
    .2byte 5
    .2byte 345
    .2byte 4
    .2byte 0 @ padding
    @ CARVANHA
    .string "SAVAGE$", 12
    .2byte 8 @ in decimeters
    .2byte 208 @ in hectograms
    .4byte kPokedexDescription1_CARVANHA
    .4byte kPokedexDescription2_CARVANHA
    .2byte 0 @ unused
    .2byte 362
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SHARPEDO
    .string "BRUTAL$", 12
    .2byte 18 @ in decimeters
    .2byte 888 @ in hectograms
    .4byte kPokedexDescription1_SHARPEDO
    .4byte kPokedexDescription2_SHARPEDO
    .2byte 0 @ unused
    .2byte 265
    .2byte 0
    .2byte 342
    .2byte 4
    .2byte 0 @ padding
    @ WAILMER
    .string "BALL WHALE$", 12
    .2byte 20 @ in decimeters
    .2byte 1300 @ in hectograms
    .4byte kPokedexDescription1_WAILMER
    .4byte kPokedexDescription2_WAILMER
    .2byte 0 @ unused
    .2byte 256
    .2byte 10
    .2byte 493
    .2byte 10
    .2byte 0 @ padding
    @ WAILORD
    .string "FLOAT WHALE$", 12
    .2byte 145 @ in decimeters
    .2byte 3980 @ in hectograms
    .4byte kPokedexDescription1_WAILORD
    .4byte kPokedexDescription2_WAILORD
    .2byte 0 @ unused
    .2byte 276
    .2byte -1
    .2byte 1428
    .2byte 20
    .2byte 0 @ padding
    @ NUMEL
    .string "NUMB$", 12
    .2byte 7 @ in decimeters
    .2byte 240 @ in hectograms
    .4byte kPokedexDescription1_NUMEL
    .4byte kPokedexDescription2_NUMEL
    .2byte 0 @ unused
    .2byte 310
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CAMERUPT
    .string "ERUPTION$", 12
    .2byte 19 @ in decimeters
    .2byte 2200 @ in hectograms
    .4byte kPokedexDescription1_CAMERUPT
    .4byte kPokedexDescription2_CAMERUPT
    .2byte 0 @ unused
    .2byte 256
    .2byte 6
    .2byte 345
    .2byte 4
    .2byte 0 @ padding
    @ TORKOAL
    .string "COAL$", 12
    .2byte 5 @ in decimeters
    .2byte 804 @ in hectograms
    .4byte kPokedexDescription1_TORKOAL
    .4byte kPokedexDescription2_TORKOAL
    .2byte 0 @ unused
    .2byte 392
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SPOINK
    .string "BOUNCE$", 12
    .2byte 7 @ in decimeters
    .2byte 306 @ in hectograms
    .4byte kPokedexDescription1_SPOINK
    .4byte kPokedexDescription2_SPOINK
    .2byte 0 @ unused
    .2byte 423
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GRUMPIG
    .string "MANIPULATE$", 12
    .2byte 9 @ in decimeters
    .2byte 715 @ in hectograms
    .4byte kPokedexDescription1_GRUMPIG
    .4byte kPokedexDescription2_GRUMPIG
    .2byte 0 @ unused
    .2byte 358
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SPINDA
    .string "SPOT PANDA$", 12
    .2byte 11 @ in decimeters
    .2byte 50 @ in hectograms
    .4byte kPokedexDescription1_SPINDA
    .4byte kPokedexDescription2_SPINDA
    .2byte 0 @ unused
    .2byte 321
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ TRAPINCH
    .string "ANT PIT$", 12
    .2byte 7 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte kPokedexDescription1_TRAPINCH
    .4byte kPokedexDescription2_TRAPINCH
    .2byte 0 @ unused
    .2byte 298
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ VIBRAVA
    .string "VIBRATION$", 12
    .2byte 11 @ in decimeters
    .2byte 153 @ in hectograms
    .4byte kPokedexDescription1_VIBRAVA
    .4byte kPokedexDescription2_VIBRAVA
    .2byte 0 @ unused
    .2byte 370
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ FLYGON
    .string "MYSTIC$", 12
    .2byte 20 @ in decimeters
    .2byte 820 @ in hectograms
    .4byte kPokedexDescription1_FLYGON
    .4byte kPokedexDescription2_FLYGON
    .2byte 0 @ unused
    .2byte 280
    .2byte 0
    .2byte 299
    .2byte 2
    .2byte 0 @ padding
    @ CACNEA
    .string "CACTUS$", 12
    .2byte 4 @ in decimeters
    .2byte 513 @ in hectograms
    .4byte kPokedexDescription1_CACNEA
    .4byte kPokedexDescription2_CACNEA
    .2byte 0 @ unused
    .2byte 455
    .2byte 19
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CACTURNE
    .string "SCARECROW$", 12
    .2byte 13 @ in decimeters
    .2byte 774 @ in hectograms
    .4byte kPokedexDescription1_CACTURNE
    .4byte kPokedexDescription2_CACTURNE
    .2byte 0 @ unused
    .2byte 327
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SWABLU
    .string "COTTON BIRD$", 12
    .2byte 4 @ in decimeters
    .2byte 12 @ in hectograms
    .4byte kPokedexDescription1_SWABLU
    .4byte kPokedexDescription2_SWABLU
    .2byte 0 @ unused
    .2byte 422
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ALTARIA
    .string "HUMMING$", 12
    .2byte 11 @ in decimeters
    .2byte 206 @ in hectograms
    .4byte kPokedexDescription1_ALTARIA
    .4byte kPokedexDescription2_ALTARIA
    .2byte 0 @ unused
    .2byte 327
    .2byte 0
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ZANGOOSE
    .string "CAT FERRET$", 12
    .2byte 13 @ in decimeters
    .2byte 403 @ in hectograms
    .4byte kPokedexDescription1_ZANGOOSE
    .4byte kPokedexDescription2_ZANGOOSE
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SEVIPER
    .string "FANG SNAKE$", 12
    .2byte 27 @ in decimeters
    .2byte 525 @ in hectograms
    .4byte kPokedexDescription1_SEVIPER
    .4byte kPokedexDescription2_SEVIPER
    .2byte 0 @ unused
    .2byte 275
    .2byte 6
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LUNATONE
    .string "METEORITE$", 12
    .2byte 10 @ in decimeters
    .2byte 1680 @ in hectograms
    .4byte kPokedexDescription1_LUNATONE
    .4byte kPokedexDescription2_LUNATONE
    .2byte 0 @ unused
    .2byte 300
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SOLROCK
    .string "METEORITE$", 12
    .2byte 12 @ in decimeters
    .2byte 1540 @ in hectograms
    .4byte kPokedexDescription1_SOLROCK
    .4byte kPokedexDescription2_SOLROCK
    .2byte 0 @ unused
    .2byte 328
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BARBOACH
    .string "WHISKERS$", 12
    .2byte 4 @ in decimeters
    .2byte 19 @ in hectograms
    .4byte kPokedexDescription1_BARBOACH
    .4byte kPokedexDescription2_BARBOACH
    .2byte 0 @ unused
    .2byte 581
    .2byte -2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WHISCASH
    .string "WHISKERS$", 12
    .2byte 9 @ in decimeters
    .2byte 236 @ in hectograms
    .4byte kPokedexDescription1_WHISCASH
    .4byte kPokedexDescription2_WHISCASH
    .2byte 0 @ unused
    .2byte 317
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CORPHISH
    .string "RUFFIAN$", 12
    .2byte 6 @ in decimeters
    .2byte 115 @ in hectograms
    .4byte kPokedexDescription1_CORPHISH
    .4byte kPokedexDescription2_CORPHISH
    .2byte 0 @ unused
    .2byte 484
    .2byte 18
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CRAWDAUNT
    .string "ROGUE$", 12
    .2byte 11 @ in decimeters
    .2byte 328 @ in hectograms
    .4byte kPokedexDescription1_CRAWDAUNT
    .4byte kPokedexDescription2_CRAWDAUNT
    .2byte 0 @ unused
    .2byte 365
    .2byte 7
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BALTOY
    .string "CLAY DOLL$", 12
    .2byte 5 @ in decimeters
    .2byte 215 @ in hectograms
    .4byte kPokedexDescription1_BALTOY
    .4byte kPokedexDescription2_BALTOY
    .2byte 0 @ unused
    .2byte 384
    .2byte 18
    .2byte 256
    .2byte -3
    .2byte 0 @ padding
    @ CLAYDOL
    .string "CLAY DOLL$", 12
    .2byte 15 @ in decimeters
    .2byte 1080 @ in hectograms
    .4byte kPokedexDescription1_CLAYDOL
    .4byte kPokedexDescription2_CLAYDOL
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 280
    .2byte 0
    .2byte 0 @ padding
    @ LILEEP
    .string "SEA LILY$", 12
    .2byte 10 @ in decimeters
    .2byte 238 @ in hectograms
    .4byte kPokedexDescription1_LILEEP
    .4byte kPokedexDescription2_LILEEP
    .2byte 0 @ unused
    .2byte 305
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ CRADILY
    .string "BARNACLE$", 12
    .2byte 15 @ in decimeters
    .2byte 604 @ in hectograms
    .4byte kPokedexDescription1_CRADILY
    .4byte kPokedexDescription2_CRADILY
    .2byte 0 @ unused
    .2byte 275
    .2byte -1
    .2byte 269
    .2byte -1
    .2byte 0 @ padding
    @ ANORITH
    .string "OLD SHRIMP$", 12
    .2byte 7 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte kPokedexDescription1_ANORITH
    .4byte kPokedexDescription2_ANORITH
    .2byte 0 @ unused
    .2byte 296
    .2byte 4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ARMALDO
    .string "PLATE$", 12
    .2byte 15 @ in decimeters
    .2byte 682 @ in hectograms
    .4byte kPokedexDescription1_ARMALDO
    .4byte kPokedexDescription2_ARMALDO
    .2byte 0 @ unused
    .2byte 312
    .2byte 2
    .2byte 271
    .2byte -1
    .2byte 0 @ padding
    @ FEEBAS
    .string "FISH$", 12
    .2byte 6 @ in decimeters
    .2byte 74 @ in hectograms
    .4byte kPokedexDescription1_FEEBAS
    .4byte kPokedexDescription2_FEEBAS
    .2byte 0 @ unused
    .2byte 423
    .2byte 3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ MILOTIC
    .string "TENDER$", 12
    .2byte 62 @ in decimeters
    .2byte 1620 @ in hectograms
    .4byte kPokedexDescription1_MILOTIC
    .4byte kPokedexDescription2_MILOTIC
    .2byte 0 @ unused
    .2byte 282
    .2byte -1
    .2byte 382
    .2byte 7
    .2byte 0 @ padding
    @ CASTFORM
    .string "WEATHER$", 12
    .2byte 3 @ in decimeters
    .2byte 8 @ in hectograms
    .4byte kPokedexDescription1_CASTFORM
    .4byte kPokedexDescription2_CASTFORM
    .2byte 0 @ unused
    .2byte 435
    .2byte -5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ KECLEON
    .string "COLOR SWAP$", 12
    .2byte 10 @ in decimeters
    .2byte 220 @ in hectograms
    .4byte kPokedexDescription1_KECLEON
    .4byte kPokedexDescription2_KECLEON
    .2byte 0 @ unused
    .2byte 316
    .2byte 8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SHUPPET
    .string "PUPPET$", 12
    .2byte 6 @ in decimeters
    .2byte 23 @ in hectograms
    .4byte kPokedexDescription1_SHUPPET
    .4byte kPokedexDescription2_SHUPPET
    .2byte 0 @ unused
    .2byte 440
    .2byte -3
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BANETTE
    .string "MARIONETTE$", 12
    .2byte 11 @ in decimeters
    .2byte 125 @ in hectograms
    .4byte kPokedexDescription1_BANETTE
    .4byte kPokedexDescription2_BANETTE
    .2byte 0 @ unused
    .2byte 262
    .2byte 9
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DUSKULL
    .string "REQUIEM$", 12
    .2byte 8 @ in decimeters
    .2byte 150 @ in hectograms
    .4byte kPokedexDescription1_DUSKULL
    .4byte kPokedexDescription2_DUSKULL
    .2byte 0 @ unused
    .2byte 376
    .2byte 13
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DUSCLOPS
    .string "BECKON$", 12
    .2byte 16 @ in decimeters
    .2byte 306 @ in hectograms
    .4byte kPokedexDescription1_DUSCLOPS
    .4byte kPokedexDescription2_DUSCLOPS
    .2byte 0 @ unused
    .2byte 256
    .2byte 2
    .2byte 299
    .2byte 2
    .2byte 0 @ padding
    @ TROPIUS
    .string "FRUIT$", 12
    .2byte 20 @ in decimeters
    .2byte 1000 @ in hectograms
    .4byte kPokedexDescription1_TROPIUS
    .4byte kPokedexDescription2_TROPIUS
    .2byte 0 @ unused
    .2byte 283
    .2byte -1
    .2byte 371
    .2byte 6
    .2byte 0 @ padding
    @ CHIMECHO
    .string "WIND CHIME$", 12
    .2byte 6 @ in decimeters
    .2byte 10 @ in hectograms
    .4byte kPokedexDescription1_CHIMECHO
    .4byte kPokedexDescription2_CHIMECHO
    .2byte 0 @ unused
    .2byte 505
    .2byte -4
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ ABSOL
    .string "DISASTER$", 12
    .2byte 12 @ in decimeters
    .2byte 470 @ in hectograms
    .4byte kPokedexDescription1_ABSOL
    .4byte kPokedexDescription2_ABSOL
    .2byte 0 @ unused
    .2byte 301
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WYNAUT
    .string "BRIGHT$", 12
    .2byte 6 @ in decimeters
    .2byte 140 @ in hectograms
    .4byte kPokedexDescription1_WYNAUT
    .4byte kPokedexDescription2_WYNAUT
    .2byte 0 @ unused
    .2byte 453
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SNORUNT
    .string "SNOW HAT$", 12
    .2byte 7 @ in decimeters
    .2byte 168 @ in hectograms
    .4byte kPokedexDescription1_SNORUNT
    .4byte kPokedexDescription2_SNORUNT
    .2byte 0 @ unused
    .2byte 380
    .2byte 14
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GLALIE
    .string "FACE$", 12
    .2byte 15 @ in decimeters
    .2byte 2565 @ in hectograms
    .4byte kPokedexDescription1_GLALIE
    .4byte kPokedexDescription2_GLALIE
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 344
    .2byte 2
    .2byte 0 @ padding
    @ SPHEAL
    .string "CLAP$", 12
    .2byte 8 @ in decimeters
    .2byte 395 @ in hectograms
    .4byte kPokedexDescription1_SPHEAL
    .4byte kPokedexDescription2_SPHEAL
    .2byte 0 @ unused
    .2byte 315
    .2byte 15
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SEALEO
    .string "BALL ROLL$", 12
    .2byte 11 @ in decimeters
    .2byte 876 @ in hectograms
    .4byte kPokedexDescription1_SEALEO
    .4byte kPokedexDescription2_SEALEO
    .2byte 0 @ unused
    .2byte 338
    .2byte 12
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ WALREIN
    .string "ICE BREAK$", 12
    .2byte 14 @ in decimeters
    .2byte 1506 @ in hectograms
    .4byte kPokedexDescription1_WALREIN
    .4byte kPokedexDescription2_WALREIN
    .2byte 0 @ unused
    .2byte 305
    .2byte 2
    .2byte 277
    .2byte 0
    .2byte 0 @ padding
    @ CLAMPERL
    .string "BIVALVE$", 12
    .2byte 4 @ in decimeters
    .2byte 525 @ in hectograms
    .4byte kPokedexDescription1_CLAMPERL
    .4byte kPokedexDescription2_CLAMPERL
    .2byte 0 @ unused
    .2byte 691
    .2byte 22
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ HUNTAIL
    .string "DEEP SEA$", 12
    .2byte 17 @ in decimeters
    .2byte 270 @ in hectograms
    .4byte kPokedexDescription1_HUNTAIL
    .4byte kPokedexDescription2_HUNTAIL
    .2byte 0 @ unused
    .2byte 307
    .2byte 1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ GOREBYSS
    .string "SOUTH SEA$", 12
    .2byte 18 @ in decimeters
    .2byte 226 @ in hectograms
    .4byte kPokedexDescription1_GOREBYSS
    .4byte kPokedexDescription2_GOREBYSS
    .2byte 0 @ unused
    .2byte 278
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ RELICANTH
    .string "LONGEVITY$", 12
    .2byte 10 @ in decimeters
    .2byte 234 @ in hectograms
    .4byte kPokedexDescription1_RELICANTH
    .4byte kPokedexDescription2_RELICANTH
    .2byte 0 @ unused
    .2byte 316
    .2byte 5
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LUVDISC
    .string "RENDEZVOUS$", 12
    .2byte 6 @ in decimeters
    .2byte 87 @ in hectograms
    .4byte kPokedexDescription1_LUVDISC
    .4byte kPokedexDescription2_LUVDISC
    .2byte 0 @ unused
    .2byte 371
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ BAGON
    .string "ROCK HEAD$", 12
    .2byte 6 @ in decimeters
    .2byte 421 @ in hectograms
    .4byte kPokedexDescription1_BAGON
    .4byte kPokedexDescription2_BAGON
    .2byte 0 @ unused
    .2byte 448
    .2byte 17
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SHELGON
    .string "ENDURANCE$", 12
    .2byte 11 @ in decimeters
    .2byte 1105 @ in hectograms
    .4byte kPokedexDescription1_SHELGON
    .4byte kPokedexDescription2_SHELGON
    .2byte 0 @ unused
    .2byte 311
    .2byte 10
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ SALAMENCE
    .string "DRAGON$", 12
    .2byte 15 @ in decimeters
    .2byte 1026 @ in hectograms
    .4byte kPokedexDescription1_SALAMENCE
    .4byte kPokedexDescription2_SALAMENCE
    .2byte 0 @ unused
    .2byte 272
    .2byte 2
    .2byte 307
    .2byte 0
    .2byte 0 @ padding
    @ BELDUM
    .string "IRON BALL$", 12
    .2byte 6 @ in decimeters
    .2byte 952 @ in hectograms
    .4byte kPokedexDescription1_BELDUM
    .4byte kPokedexDescription2_BELDUM
    .2byte 0 @ unused
    .2byte 414
    .2byte -1
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ METANG
    .string "IRON CLAW$", 12
    .2byte 12 @ in decimeters
    .2byte 2025 @ in hectograms
    .4byte kPokedexDescription1_METANG
    .4byte kPokedexDescription2_METANG
    .2byte 0 @ unused
    .2byte 256
    .2byte 3
    .2byte 272
    .2byte -2
    .2byte 0 @ padding
    @ METAGROSS
    .string "IRON LEG$", 12
    .2byte 16 @ in decimeters
    .2byte 5500 @ in hectograms
    .4byte kPokedexDescription1_METAGROSS
    .4byte kPokedexDescription2_METAGROSS
    .2byte 0 @ unused
    .2byte 272
    .2byte 3
    .2byte 461
    .2byte 4
    .2byte 0 @ padding
    @ REGIROCK
    .string "ROCK PEAK$", 12
    .2byte 17 @ in decimeters
    .2byte 2300 @ in hectograms
    .4byte kPokedexDescription1_REGIROCK
    .4byte kPokedexDescription2_REGIROCK
    .2byte 0 @ unused
    .2byte 256
    .2byte 1
    .2byte 309
    .2byte 1
    .2byte 0 @ padding
    @ REGICE
    .string "ICEBERG$", 12
    .2byte 18 @ in decimeters
    .2byte 1750 @ in hectograms
    .4byte kPokedexDescription1_REGICE
    .4byte kPokedexDescription2_REGICE
    .2byte 0 @ unused
    .2byte 265
    .2byte 0
    .2byte 317
    .2byte 3
    .2byte 0 @ padding
    @ REGISTEEL
    .string "IRON$", 12
    .2byte 19 @ in decimeters
    .2byte 2050 @ in hectograms
    .4byte kPokedexDescription1_REGISTEEL
    .4byte kPokedexDescription2_REGISTEEL
    .2byte 0 @ unused
    .2byte 256
    .2byte 0
    .2byte 359
    .2byte 6
    .2byte 0 @ padding
    @ LATIAS
    .string "EON$", 12
    .2byte 14 @ in decimeters
    .2byte 400 @ in hectograms
    .4byte kPokedexDescription1_LATIAS
    .4byte kPokedexDescription2_LATIAS
    .2byte 0 @ unused
    .2byte 291
    .2byte 2
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ LATIOS
    .string "EON$", 12
    .2byte 20 @ in decimeters
    .2byte 600 @ in hectograms
    .4byte kPokedexDescription1_LATIOS
    .4byte kPokedexDescription2_LATIOS
    .2byte 0 @ unused
    .2byte 273
    .2byte 0
    .2byte 313
    .2byte 3
    .2byte 0 @ padding
    @ KYOGRE
    .string "SEA BASIN$", 12
    .2byte 45 @ in decimeters
    .2byte 3520 @ in hectograms
    .4byte kPokedexDescription1_KYOGRE
    .4byte kPokedexDescription2_KYOGRE
    .2byte 0 @ unused
    .2byte 272
    .2byte 1
    .2byte 639
    .2byte 13
    .2byte 0 @ padding
    @ GROUDON
    .string "CONTINENT$", 12
    .2byte 35 @ in decimeters
    .2byte 9500 @ in hectograms
    .4byte kPokedexDescription1_GROUDON
    .4byte kPokedexDescription2_GROUDON
    .2byte 0 @ unused
    .2byte 276
    .2byte 0
    .2byte 530
    .2byte 12
    .2byte 0 @ padding
    @ RAYQUAZA
    .string "SKY HIGH$", 12
    .2byte 70 @ in decimeters
    .2byte 2065 @ in hectograms
    .4byte kPokedexDescription1_RAYQUAZA
    .4byte kPokedexDescription2_RAYQUAZA
    .2byte 0 @ unused
    .2byte 286
    .2byte -1
    .2byte 483
    .2byte 9
    .2byte 0 @ padding
    @ JIRACHI
    .string "WISH$", 12
    .2byte 3 @ in decimeters
    .2byte 11 @ in hectograms
    .4byte kPokedexDescription1_JIRACHI
    .4byte kPokedexDescription2_JIRACHI
    .2byte 0 @ unused
    .2byte 608
    .2byte -8
    .2byte 256
    .2byte -2
    .2byte 0 @ padding
    @ DEOXYS
    .string "DNA$", 12
    .2byte 17 @ in decimeters
    .2byte 608 @ in hectograms
    .4byte kPokedexDescription1_DEOXYS
    .4byte kPokedexDescription2_DEOXYS
    .2byte 0 @ unused
    .2byte 293
    .2byte 0
    .2byte 337
    .2byte 2
    .2byte 0 @ padding
